### ISSUE TITLE
Signal calls not connecting

### ISSUE THREAD

**Issue by sakshamb21** [nextdns/metadata#1001]
I use nextdns android app on old samsung device(galaxy a9 pro) and it is causing issues in signal app. Whenever someone tries to call me, app gives a notification of connecting call, but it doesn't get connected. I turn off nextdns, and it connects the call.
I also use the private dns feature of my newer device(a galaxy s21), and there are no problems there.
I use only the official nextdns block list and steven black hosts file.
What to do?

**Comment by sakshamb21** [comment]
> Have you checked the NextDNS logs to see if anything is being blocked?

Yes i checked, nothing is getting blocked.

**Comment by sakshamb21** [comment]
> Have you checked the NextDNS logs to see if anything is being blocked?

![20220607_221459](https://user-images.githubusercontent.com/106823003/172437526-9c2446dd-0049-4075-9d90-e91214c3faa1.jpg)

See this for example

**Comment by SleepingPanda** [comment]
Why was this issue closed? Did you find a solution? I'm also having this issue.
