### ISSUE TITLE
The Pirate Bay domains for your Piracy list

### ISSUE THREAD

**Issue by Sduibek** [nextdns/metadata#1002]
I noticed these domains aren't blocked by the Piracy setting within Parental Controls, so I wanted to let you know in case it wasn't already on your radar.

As of this writing, these aren't currently blocked by enabling the Piracy block:

```
bayproxy.top

bayspirateproxy.com

piratebay.ink

piratebayproxy.click

pirateproxy.party

pirateproxy.pm

pirateproxytpb.com

sites.google.com/site/tbpunblock/

the-pirate-bay.online

thepirate-bay3.org

thepirate-proxylist.com

thepiratebay.ae

thepiratebay.gg

thepiratebay.gl

thepiratebay.in

thepiratebay.ind.in

thepiratebays1.com

thepiratebays3.com

thepirates-bay.org

theproxypiratebay.com

tpbay.link

tpbpiratebayproxy.com
```

**Comment by romaincointepas** [comment]
@Sduibek good catch! Do you feel like creating a PR for https://github.com/nextdns/piracy-blocklists/blob/master/torrent-websites?

**Comment by Sduibek** [comment]
Sure thing! Will do soon.

**Comment by Sduibek** [comment]
All set: 
https://github.com/nextdns/piracy-blocklists/pull/29
@romaincointepas
