### ISSUE TITLE
False positive: api.townsq.io

### ISSUE THREAD

**Issue by zwangzw-zw** [nextdns/metadata#1006]
api.townsq.io is a false positive blocked by NextDNS Ads & Trackers Blocklist

The domain is used for login of a property management portal (can be directly accessed from https://www.townsq.io/)

**Comment by quantumpacket** [comment]
It's being blocked by a lot more lists.

![Screenshot_2022-06-10_09-51-01](https://user-images.githubusercontent.com/8516784/173080415-3d0907b5-b4f3-4fd5-8a6f-7c12b3c7831a.png)

**Comment by romaincointepas** [comment]
Please report `api-gateway.us-west-2.elasticbeanstalk.com` as false positive to https://github.com/StevenBlack/hosts.
