### ISSUE TITLE
Filter Lists

### ISSUE THREAD

**Issue by kptechnologyservices** [nextdns/metadata#102]
Can you possibly Add filters for Proxies/Annonimysers, Hacking,Drugs, Tobacco, Alcohol, and anything illegal?

**Comment by romaincointepas** [comment]
Proxies/anonymizers are (or should be) in the *Parental Control -> Block Bypass Methods* feature, feel free to improve that list.

Regarding the categories you mentioned, we may add them in the future, we need some good blocklists for those.
