### ISSUE TITLE
False Positive Mintos.com

### ISSUE THREAD

**Issue by Moonstone3010** [nextdns/metadata#1020]
Mintos.com is blocked by Threat Information Sources (first checkbox on the security tab). It is a secure investment portal that has been in operation for several years.

**Comment by lyrad87** [comment]
Must have been fixed upstream because I can access this website with TI Feeds enabled.

**Comment by u3hv1smup** [comment]
I found the actual source here:
https://dsi.ut-capitole.fr/blacklists/index_en.php

I have sent a message to the author so it remains to wait for him to respond.

**Comment by romaincointepas** [comment]
Thanks @Moonstone3010, closing.
