### ISSUE TITLE
Partial content missing on NZZ.ch

### ISSUE THREAD

**Issue by maXity** [nextdns/metadata#1027]
NextDNS default filters are a bit too aggressive on NZZ.ch newspaper. See this example: https://www.nzz.ch/technologie/-ld.1693543

Normally the text should be truncated after the first paragraph and lead into a paywall login, as in picture below:

![image](https://user-images.githubusercontent.com/23332112/179162684-1da38912-4d95-41c7-aad3-fa3132de0c83.png)

However that part is mistakenly blocked when using NextDNS, with no option to log-in and see the content behind paywall:

![image](https://user-images.githubusercontent.com/23332112/179162813-6be55be6-7e99-477f-9c34-d47d92d6c6ce.png)

Thank you for looking into this!

**Comment by romaincointepas** [comment]
We will check this out.

**Comment by maXity** [comment]
Thank you, Romain, for looking into this--however I'm afraid the issue still persists, The login page to get past the paywall is still truncated. Can you have another look please? Thank you!

**Comment by hagezi** [comment]
Whitelist

track.nzz.ch
ens.nzz.ch

**Comment by maXity** [comment]
> Whitelist
> 
> track.nzz.ch ens.nzz.ch

That works :) Thank you for your help!
