### ISSUE TITLE
(whitelist) nordvpn.com

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#103]
https://nordvpn.com/download/linux/

is blocked, need to whitelist

![image](https://user-images.githubusercontent.com/19517680/78027034-daaffd00-7386-11ea-85c1-ca081b44acc5.png)

**Comment by agottardo** [comment]
You can open the query logs in your dashboard and see which list is blocking this hostname. Additionally, you can whitelist the domain yourself from the dashboard.

**Comment by 3xploiton3** [comment]
> You can open the query logs in your dashboard and see which list is blocking this hostname. Additionally, you can whitelist the domain yourself from the dashboard.

okay thx

**Comment by scafroglia93** [comment]
> You can open the query logs in your dashboard and see which list is blocking this hostname. Additionally, you can whitelist the domain yourself from the dashboard.

maybe is blocked under bypass features

**Comment by romaincointepas** [comment]
It's (only) blocked by the *Parental Control -> Block Bypass Methods* feature, closing.
