### ISSUE TITLE
NextDNS Ads & Trackers Blocklist breaks CBS News streaming

### ISSUE THREAD

**Issue by yokoffing** [nextdns/metadata#1030]
**Description:** `production-cmp.isgprivacy.cbsi.com` is a filter in `NextDNS Ads & Trackers Blocklist`. It breaks streaming on `https://www.cbsnews.com/live/#x`. We tried to isolate the breakage last year (#574); and after multiple months of testing, I appear to have found the culprit.

Here's my setup: https://github.com/yokoffing/NextDNS-Config. As long as I allowlist `production-cmp.isgprivacy.cbsi.com`, it works.

**Related:** #285

**Comment by romaincointepas** [comment]
Could you please report this to https://github.com/StevenBlack/hosts?
