### ISSUE TITLE
[False Positive - TIF] pastebin.pl

### ISSUE THREAD

**Issue by ClusterByte-x** [nextdns/metadata#1032]
<img width="706" alt="Zrzut ekranu 2022-07-28 o 16 08 34" src="https://user-images.githubusercontent.com/76107417/181526024-b07a2190-17cd-45e6-9e3e-bdf9305888ba.png">

**Comment by lyrad87** [comment]
This is blocked by [urlhaus.abuse.ch](https://urlhaus.abuse.ch/host/pastebin.pl/) so I suggest you mention it upstream.

**Comment by romaincointepas** [comment]
Fixed
