### ISSUE TITLE
Issue with background start with iOS Shortcuts

### ISSUE THREAD

**Issue by GhostR111der** [nextdns/metadata#1034]
Hello to the nextdns team. I am constantly using adguard vpn and nextdns with automations created in iOS Shortcuts. When I create scripts using adguard vpn there is an option to enable and disable vpn in the background, without activating the app, which is very convenient. When working with nextdns this option also exists, but it launches the nextdns app to enable or disable the service. Could you add in one of the next app updates an option to enable and disable nextdns service in the background, without activating the app, like Adblock vpn, it would give a huge advantage to your product.

**Comment by romaincointepas** [comment]
We will check this out.
