### ISSUE TITLE
[REQUEST] A central website for categorisation of websites

### ISSUE THREAD

**Issue by ghost** [nextdns/metadata#1036]
I'm not sure if the infrastructure for this is in place, but it would be cool to have a website where people could report false positives or report sites. For example,

- https://cleanbrowsing.org/2021/11/categorify-a-cleanbrowsing-categorization-engine/
- https://categorify.org/
- https://categorify.org/recategorize

This might also allow for a filtering system that is independent of third-party lists.

**Comment by romaincointepas** [comment]
We will work on this at some point.
