### ISSUE TITLE
False Positive mega.nz [PIRACY]

### ISSUE THREAD

**Issue by Box-boi** [nextdns/metadata#1038]
![image](https://user-images.githubusercontent.com/65017137/182648007-5176f6d1-f27e-422c-a392-686494c3553f.png)

The domain mega.nz is being falsely flagged as piracy. It's the equivalent of blocking google-drive and onedrive for piracy.

**Comment by Oakwas** [comment]
You can report and remove pirated content with Google Drive and OneDrive. I am not sure if mega.nz does that.

**Comment by NyeUsr** [comment]
> You can report and remove pirated content with Google Drive and OneDrive. I am not sure if mega.nz does that.

You can report copyrighted content to Mega and have it taken down similar to Google Drive and/or OneDrive. Mega has done this for some time now. See `https://torrentfreak.com/mega-has-now-terminated-95000-users-for-repeat-copyright-infringement-201203/`

**Comment by romaincointepas** [comment]
Feel free to add it to your Allowlist, the piracy category is aggressive on purpose and `mega.nz` made the cut (still heavily used for piracy, even if not only).
