### ISSUE TITLE
False Positive? Android Youtube history is not working

### ISSUE THREAD

**Issue by Mwyann** [nextdns/metadata#1043]
Domain: s.youtube.com
List: Steven Black

I don't know what this domain is supposed to provide, but at least on Android, if this domain is blocked, then every time I watch a video on my phone, it doesn't appear in my Youtube history. This is a problem because then Youtube keeps suggesting me videos that I've already watched. On my computer, it works fine because it doesn't makes use of this domain.

**Comment by romaincointepas** [comment]
Please report this to https://github.com/StevenBlack/hosts.
