### ISSUE TITLE
pop.com is being blocked

### ISSUE THREAD

**Issue by Jeremy-Walton** [nextdns/metadata#1049]
https://pop.com/ which is a screen sharing / collaboration tool is currently being blocked by Threat Intelligence Feeds. It was not being blocked as of 3 days ago.

<img width="378" alt="Screen Shot 2022-08-08 at 1 21 38 PM" src="https://user-images.githubusercontent.com/5957102/183480916-865bfc5b-f457-4221-947f-9e1761ea0e18.png">

I looked through the feeds list https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json and cannot find which list is blocking it. I was not able to look through https://data.phishtank.com/data/{{PHISHTANK_APP_KEY}}/online-valid.csv as it requires a key.

According to a developer of pop.com, when they purchased the domain, it did have an issue of being on some blocked lists due to the previous owners, though they indicated those issues have been resolved for a while.

Could one of these lists be blocking it again incorrectly?

**Comment by hagezi** [comment]
pop.com is blocked by https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

**Comment by Jeremy-Walton** [comment]
I've let the pop team know and they should be reaching out to that company. Thanks!

**Comment by Jeremy-Walton** [comment]
https://www.stopforumspam.com/downloads/toxic_domains_whole.txt has removed `pop.com` from their list.
