### ISSUE TITLE
pornaway out of date & many false positive

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#105]
https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt

**Comment by romaincointepas** [comment]
Could you extract a few false positives from that list?

**Comment by lyrad87** [comment]
openmultipleurl.com
cliqz.com
zaobao.com.sg
pladform.ru
admitad.com

Some of the above were issues here before that were addressed (like #98 or #77) while others will be fixed when/if #145 is implemented.
