### ISSUE TITLE
wd.adcolony.com blocked by porn

### ISSUE THREAD

**Issue by travisboss** [nextdns/metadata#1054]
Confirmed this is being blocked by porn (and oisd which is good) and not sure why porn would have to do with a ad service?

**Comment by hagezi** [comment]
It's blocked by [mhxion's pornaway](https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt)

ping @mhxion

Cheers,
Gerd - [DNS Blocklists - For a better internet!](https://github.com/hagezi/dns-blocklists)

**Comment by romaincointepas** [comment]
Fixed
