### ISSUE TITLE
Add entering more than one white list domain at once

### ISSUE THREAD

**Issue by Delkaloop** [nextdns/metadata#1055]
Hey, 

Entering a white list domain one by one is so exhausting, add an option to enter them at once.

**Comment by hagezi** [comment]
@Delkaloop
Use [NXEnhanced(https://github.com/hjk789/NXEnhanced) by @hjk789 as a browser extension, besides adding multiple domains to the allow or denylist the extension can do much more and makes it easier to configure NextDNS.

Cheers,
Gerd - [DNS Blocklists - For a better internet!](https://github.com/hagezi/dns-blocklists)
