### ISSUE TITLE
Proposal: Make powershell script to setup and enable DoH encrypted only on Windows 11

### ISSUE THREAD

**Issue by SHJordan** [nextdns/metadata#1059]
By default Windows 11 only give support to 3 providers: Cloudflare, Google and Quad9 .  This can be checked running

`Get-DNSClientDohServerAddress` on powershell

if one wants to use the provided ips and DoH functionallity natively from Windows it would need to run 4 commands:

`Add-DnsClientDohServerAddress -ServerAddress 'YOUR_IP_4_1' -DohTemplate 'https://dns.nextdns.io/YOUR_CONFIG_ID' -AllowFallbackToUdp $False -AutoUpgrade $True`

`Add-DnsClientDohServerAddress -ServerAddress 'YOUR_IP_4_2' -DohTemplate 'https://dns.nextdns.io/YOUR_CONFIG_ID' -AllowFallbackToUdp $False -AutoUpgrade $True`

`Add-DnsClientDohServerAddress -ServerAddress 'YOUR_IP_6_1' -DohTemplate 'https://dns.nextdns.io/YOUR_CONFIG_ID' -AllowFallbackToUdp $False -AutoUpgrade $True`

`Add-DnsClientDohServerAddress -ServerAddress 'YOUR_IP_6_2' -DohTemplate 'https://dns.nextdns.io/YOUR_CONFIG_ID' -AllowFallbackToUdp $False -AutoUpgrade $True`

And then proceed to set them to the interface you want to NextDNS take care of. More info about this can be found here: https://docs.microsoft.com/pt-br/windows-server/networking/dns/doh-client-support

Since i lack the knowledge to make it myself it would be nice if someone automate it so i could deploy on the machines i have faster.

Thank for your attention and I hope you have a nice week.

EDIT: just realized i might have proposed it on the wrong repository, if so, please let me know and i will redo it on the proper one.

**Comment by FadeMind** [comment]
@SHJordan  See https://www.reddit.com/r/nextdns/comments/i56ao2/comment/g0ow0sp/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by SHJordan** [comment]
By my understanding we should avoid assigning ipvr dns then?

**Comment by romaincointepas** [comment]
Windows 11 now supports manually inputing the DoH endpoint (much easier way than this), we will update our Setup Guide in the coming days.
