### ISSUE TITLE
Possible Whitelist Candidates - Amazon Video

### ISSUE THREAD

**Issue by jondagle** [nextdns/metadata#1061]
Today I couldn't stream The Rings of Power on Amazon Video, even though it worked Friday without any changes on my end. 
These domains are being blocked by NextDNS Blocklist and seem to interfere with video, starting tonight. They didn't show in my logs before this.
- s3.ll.videorolls.row.aiv-cdn.net    # new, but not necessary to stream
- s3-iad-ww.cf.videorolls.row.aiv-cdn.net   # new, can't stream unless whitelisted.

**Comment by hagezi** [comment]
Blocked by @jaws101 (AdAway) @stevenblack (Hosts) @bongochong

Regards,
Gerd - https://github.com/hagezi/dns-blocklists

**Comment by jondagle** [comment]
Danke schön! I would expect this to be a problem for many NextDNS list users....

**Comment by bongochong** [comment]
Thank you for the heads up @hagezi ! Much appreciated. Added to my whitelists / exclusion patterns.

**Comment by romaincointepas** [comment]
Should be reported to the blocklists maintainers themselves.
