### ISSUE TITLE
False positive: refinery29.com (Porn)

### ISSUE THREAD

**Issue by mingaldrichgan** [nextdns/metadata#1062]
refinery29.com is blocked by the Porn filter. I have added it to my allowlist, but I would like to propose that it be excluded from the blocklist as it does not contain porn AFAIK.

EDIT: It is listed in both the `pornaway` and `Sinfonietta` lists. The `pornaway` list, in particular, hasn't been updated in 2 years so I humbly suggest adding this to the `exclusions` list in `porn.json`.

EDIT 2: Apparently there are "softcore porn and descriptions of hardcore sex acts" at https://www.refinery29.com/en-us/porn (see: https://github.com/Sinfonietta/hostfiles/issues/213). Feel free to close this issue if you see fit.

**Comment by romaincointepas** [comment]
Fixed
