### ISSUE TITLE
Apple tv  profile does not work

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#1068]
i tried to download a apple dns config profile at apple.nextdns.io](http://apple.nextdns.io/ but it doesn't work since a month now

i dont know what the issue is, only know the error code what the apple tv gives 

 
the profile (-1004) cant be installed check the url and try it again
https://help.nextdns.io/t/h7hnakp/the-apple-config-dns-profile-generator-doesnt-work

**Comment by rs** [comment]
Closing as this is not a metadata related issue.
