### ISSUE TITLE
False Positive: episode.wtf in Porn parental control filtering

### ISSUE THREAD

**Issue by instanttim** [nextdns/metadata#1069]
The very popular framed.wtf daily game has branched out and now has a tv show variant hosted at episode.wtf, which is currently blocked by the Porn Parental Control of NextDNS. Perhaps the previous owner was using it for porn, but it’s clean now, it should be removed.

**Comment by romaincointepas** [comment]
We have moved to our internal Porn AI, this should be fixed soon.
