### ISSUE TITLE
YouTube Ad Blocklist

### ISSUE THREAD

**Issue by ducktapeonmydesk** [nextdns/metadata#1075]
Please add the blocklist below; it blocks YouTube ads.

https://github.com/Ewpratten/youtube_ad_blocklist

**Comment by bbossola** [comment]
Bump!

**Comment by hagezi** [comment]
You cannot block YT advertising at the DNS level. By blocking the advertising domains, some videos no longer start or the playback is stopped in the middle and further problems occur. Use a browser content blocker like uBlock to block ads on YT and co.

**Comment by romaincointepas** [comment]
What @hagezi said.
