### ISSUE TITLE
Please add Goodbye Ads blocklist

### ISSUE THREAD

**Issue by yatmund** [nextdns/metadata#1076]
Can be found here : https://github.com/jerryn70/GoodbyeAds

Alternatively, it would be great if there was a way to bulk upload domains to the denylist.

**Comment by romaincointepas** [comment]
Already available.

**Comment by yatmundcera** [comment]
Ah Awesome! Thanks for this!

**Comment by yatmund** [comment]
Ah Awesome! Thanks for this!
