### ISSUE TITLE
False Positive: gigya.com on the corsair site from the NextDNS Blocklist.

### ISSUE THREAD

**Issue by H1rrakon** [nextdns/metadata#1078]
I don't know when it started but recently the corsair store (www.corsair.com) site stopped functioning properly and it seems the NextDNS Ads & Trackers Blocklist is the culprit as it blocks gigya.com which is apparently required for the corsair site to work.

When gigya.com is blocked, corsair.com loads up but when clicking on merch the page is missing elements and doesn't function fully.

**Comment by romaincointepas** [comment]
Fixed
