### ISSUE TITLE
Dating sites not being blocked by any filter

### ISSUE THREAD

**Issue by blackstone250** [nextdns/metadata#1080]
https://www.flirt.com/
https://friendfinder-x.com/
https://lesbianpersonals.com
https://www.bdsmdatingonly.com/
https://www.match.com
https://www.bdsmdatingsites.co.uk/
https://www.wiccadating.com/
https://www.dateawiccan.com/
https://www.wiccanpersonals.com/
https://www.wiccandatingsite.com/
https://www.flirt.com/
https://bdsmdatingchat.com/
https://bondagepal.com/
https://bdsmdate.com/
https://www.mybdsmhookups.com/
https://ar.bdsmu.com/
https://www.fetster.com/
https://www.bondagedating.com/
https://kinkd-kink-dating-app.es.aptoide.com/app
https://perfect.is

**Comment by romaincointepas** [comment]
Could you please directly report those as false negative to https://dsi.ut-capitole.fr/blacklists/index_en.php (dating category)?
