### ISSUE TITLE
NextDNS Trackers & Ads Blocklist preventing iRobot login

### ISSUE THREAD

**Issue by absane** [nextdns/metadata#1086]
The domains below are preventing the iRobot app from logging in to control the devices:

- socialize.us1.gigya.com
- accounts.us1.gigya.com

They are in the "NextDNS Trackers & Ads Blocklist" list.

I don't know if these were recently added, but the iRobot app stopped working for at least a week. After I placed them on my allowlist, the iRobot app works now.

**Comment by romaincointepas** [comment]
Fixed
