### ISSUE TITLE
Block ads sites for Smart TV LG

### ISSUE THREAD

**Issue by wuniversales** [nextdns/metadata#109]
*.lgsmartad.com

**Comment by scafroglia93** [comment]
you can block with "dbloisdnl"

you can close this issue

**Comment by romaincointepas** [comment]
Agree, we like to keep our recommended list safe and some blocklists decided to not block that domain, so blocking it could be breaking stuff in some cases. Thanks for the report though!

**Comment by vinhtruyen92** [comment]
> *.lgsmartad.com

Hi bro. How can i block this? Is it right if I block this domain from router huawei like this video?
https://www.youtube.com/watch?v=a7WgYRZi87k
Thanks

**Comment by vinhtruyen92** [comment]
> I just tested it on my smart tv by manually blocking the domain "* .lgsmartad.com". And the TV works correctly, I have no problems in the update downloads or in the store downloads, LG uses that specific domain for its ads on the Smart TV.
> 
> The only thing that does not load are the ads that appear on the smart TV menus.

Hi bro. How can i block this? Is it right if I block this domain from router huawei like this video?
https://www.youtube.com/watch?v=a7WgYRZi87k
Thanks
