### ISSUE TITLE
Redirection blocking

### ISSUE THREAD

**Issue by blackstone250** [nextdns/metadata#1093]
URL:
https://www.morphi.net/linkcartas/manolo.php
http://churrosmanolo.serveftp.net:3055/churros/

Note: no external privacy filter is blocking the website. Is a native Nextdns function.

**Comment by hagezi** [comment]
Blocked by DynDNS security feature. Disable it or whitelist the domain.

**Comment by blackstone250** [comment]
@hagezi Excellent answer! Tks!

Solved!
