### ISSUE TITLE
False positive: jordemort.dev blocked for porn

### ISSUE THREAD

**Issue by jordemort** [nextdns/metadata#1094]
Hi, one of the readers of my blog says that NextDNS is blocking it for porn.

I dug around in this repository and couldn't figure out where the block is coming from, my domain doesn't seem to appear here or in any of the lists referenced here.

jordemort.dev is a pretty boring technical blog. There is no porn there. It is hosted at GitHub Pages, so I'm pretty sure I wouldn't even be allowed to host porn there, even if I wanted to, which I don't.

stats.jordemort.dev is an instance of [Plausible Analytics](https://plausible.io/). It is also definitely not porn.

I would appreciate it if you would unblock my site. I would appreciate it even more if you could tell me why you blocked my site to begin with.

![image](https://user-images.githubusercontent.com/1467022/193459896-8eeea0fb-3153-4a60-b928-0301c428d03b.png)

**Comment by romaincointepas** [comment]
Fixed
