### ISSUE TITLE
False Positive : nexusrules.officeapps.live.com

### ISSUE THREAD

**Issue by anxiouslelimo** [nextdns/metadata#1103]
<img width="480" alt="Untitled" src="https://user-images.githubusercontent.com/115996455/196198366-79ff9bb6-d884-4178-b097-f21da2f91d7b.png">

Request to whitelist **nexusrules.officeapps.live.com.**
The following endpoints are used to connect to the Microsoft 365 admin center's shared infrastructure, including Office in a browser. For more info, see Office 365 URLs and IP address ranges. You can turn this off by removing all Microsoft Office apps and the Mail and Calendar apps. **If you turn off traffic for these endpoints, users won't be able to save documents to the cloud or see their recently used documents.**

**Comment by lyrad87** [comment]
You should report it upstream. NextDNS‘s blocklist includes Steven Black as well.

**Comment by anxiouslelimo** [comment]
Oh. Okay. Already done and it is sorted in Steven Black's. Closing.
