### ISSUE TITLE
SECURITY RISK: domain obvladovanje-tveganj.si is NRD but not blocked

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#1105]
The domain in question is not problematic as it is, but Block NRD not working is a security risk.

Domain `obvladovanje-tveganj.si` is not NRD blocked despite the "Block Newly Registered Domains (NRDs)" is enabled.
Domain was registered 10.10.2022 (that is 10 days ago).

Cheers

**Comment by romaincointepas** [comment]
Without access to the TLD zone files, our NRD features may miss some domains (that's the case for `.si`), we are working on improving this.
