### ISSUE TITLE
Porn: reporting two false positives

### ISSUE THREAD

**Issue by mflint** [nextdns/metadata#1106]
These two domains are being blocked, somehow, by the "porn" category, but I can't find where they are in the blocklists:

* www.lincstrust.org.uk
* www.nottinghamshirewildlife.org

**Comment by lyrad87** [comment]
@romaincointepas could you please remove "https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts" from the porn.json. I think it's the culprit of many tickets regarding false positives. You would solve a handful of tickets most likely by just removing it or replacing it via [porn-records](https://mypdns.org/my-privacy-dns/porn-records).

**Comment by romaincointepas** [comment]
We have now switched to our internal Porn AI, and those 2 domains are not blocked anymore.
