### ISSUE TITLE
False positive: http://post.spmailtechno.com

### ISSUE THREAD

**Issue by essereio** [nextdns/metadata#1110]
http://post.spmailtechno.com/

**Comment by hagezi** [comment]
Blocked by the following lists: @stevenblack, @notracking, @bongochong, Peter Lowe and NextDNS Ads&Tracking

Allowed by NextDNS "Allow Affiliate & Tracking Links" function if enabled.

Regards,
Gerd - https://github.com/hagezi/dns-blocklists

**Comment by macbugs** [comment]
This is a bulk email provider that likely provides click/link tracking ;
at this moment both servers are not responding.

**Comment by romaincointepas** [comment]
What @hagezi said.

**Comment by macbugs** [comment]
all filters & blocklists were disabled -- the servers were really offline (and it happens frequently with that service)
