### ISSUE TITLE
Oisd list not updated

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#1112]
Oisd list not updated,
Last update 2 days ago

**Comment by hagezi** [comment]
Last modified: 2022-10-24T00:13:40+0200 on Upstream: https://dblw.oisd.nl

So seems to be a NextDNS problem. @romaincointepas @rs 

Ping @sjhgvr

**Comment by ghost** [comment]
> Last modified: 2022-10-24T00:13:40+0200 on Upstream: https://dblw.oisd.nl
> 
> So seems to be a NextDNS problem. @romaincointepas @rs Bug Report: https://help.nextdns.io/t/y4h79dq
> 
> Ping @sjhgvr

The maintainer already knows it

**Comment by hagezi** [comment]
From NextDNS Support:

"_There seems to be a HTTP conditional request bug on their server (returning "not modified" when it shouldn't), we have reached out to @sjhgvr._"

**Comment by ghost** [comment]
Issue has been fixed, closing issue now
