### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by missdeer** [nextdns/metadata#1113]
Hi,

What license does this project use? Can I use the data from this repository in my own project?

Regards,
Fan

**Comment by lyrad87** [comment]
If you are talking about the metadata aspect, they haven't specified a license. If you are talking about the windows and CLI client, it's licensed under the MIT License.

**Comment by missdeer** [comment]
> If you are talking about the metadata aspect, they haven't specified a license. If you are talking about the windows and CLI client, it's licensed under the MIT License.

I'm talking about the metadata, I want to use these data in my own project, I hope there will be a clear and definite license for the metadata.

**Comment by romaincointepas** [comment]
We have split this mono repo, and each new repo will have its own license.
