### ISSUE TITLE
False positive: netbank.takarekbank.hu

### ISSUE THREAD

**Issue by zsoltsandor** [nextdns/metadata#1114]
The URL is a legitimate Netbank in Hungary, but got blocked by the Threat Intelligence Feeds. Idk if it can be queried anywhere, but I would appreciate if you could help me locating it, and give any heads up on it.

More details: it was fine on the 17th October, blocked on the 25th October.

**Comment by lyrad87** [comment]
I did a quick check and it's included in the [phishing.army blocklist](https://phishing.army/download/phishing_army_blocklist.txt). Report it upstream and they may remove it.

**Comment by lyrad87** [comment]
It’s also blocked by the notracking blocklist.

**Comment by romaincointepas** [comment]
Seems to be fixed.
