### ISSUE TITLE
Add DNS rewrite lists (RiiConnect24 - RC24)

### ISSUE THREAD

**Issue by wuniversales** [nextdns/metadata#1120]
As the title mentions, it would be nice to allow DNS rewrites on some lists.
For example, Nintendo Wii shut down their online service a while ago, but it can be activated again by doing a DNS rewrite.
The RiiConnect24 list can be found at this link:
https://github.com/RiiConnect24/DNS-Server
Currently I have manually set everything, but I think it would be much better if rewrites could be triggered by automatically importing from github.
Doing something similar to blocklists.
It would be nice to add "rewrite lists".

**Comment by romaincointepas** [comment]
Feels a bit too niche, but we will keep this in mind.
