### ISSUE TITLE
False positive: Kutt.it

### ISSUE THREAD

**Issue by fabianski7** [nextdns/metadata#1135]
![20221111-142238](https://user-images.githubusercontent.com/47755037/201395111-a1934cff-5a71-46f7-9ede-f138e20fe6c4.png)
![20221111-142255](https://user-images.githubusercontent.com/47755037/201395139-e602d402-ebc7-4337-81b8-c592928f08a8.png)

**Comment by lyrad87** [comment]
It seems like this was fixed upstream as I have TIFs enabled and can access this website just fine.

**Comment by lyrad87** [comment]
Added to their allowlist.
https://github.com/notracking/hosts-blocklists/issues/819#issuecomment-1331780178

This issue can be closed, imo.
