### ISSUE TITLE
Mastodon server 'ioc.exchange' blocked by AI / TIF

### ISSUE THREAD

**Issue by macbugs** [nextdns/metadata#1137]
[ioc.exchange](https://ioc.exchange) is a public  discussion server on the [official Mastodon server list](https://joinmastodon.org/servers).

( blocked by `Threat Intelligence Feeds` and `AI-Driven Threat Detection` )

I seriously doubt that this Mastodon server represents a security threat: it is more likely that the AI made a mistake in classification because security threats are discussed on the forum.  How can I determine the blacklisting criteria and assist in training the AI (if necessary) ?

**Comment by lyrad87** [comment]
I have both enabled and can access `ioc.exchange` just fine so I guess the AI may have learned and it was fixed upstream for the TIFs.
