### ISSUE TITLE
Bug with block page

### ISSUE THREAD

**Issue by chizhang9135** [nextdns/metadata#1138]
After enable block page, the website can be blocked.
<img width="1792" alt="Screenshot 2022-11-13 at 10 30 12 PM" src="https://user-images.githubusercontent.com/42708131/201590586-577095b6-9fa0-40c4-9857-77f157874835.png">

However, the third-party ads in other websites as banner will not block. 
<img width="1792" alt="Screenshot 2022-11-13 at 10 30 01 PM" src="https://user-images.githubusercontent.com/42708131/201590606-492fe70d-4620-4327-992c-61c0d8de261e.png">

But if you click the ads, it will show the block page

**Comment by romaincointepas** [comment]
The ad must be loaded from another domain.
