### ISSUE TITLE
x-diesel.com and codecguide.com marked as porn

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#114]
Hello,
these is false positives - mistakenly marked as porn category:
x-diesel.com - Unreal Commander official page
codecguide.com - K-Lite Codec Pack official page

Please, remove it!

Cheers!

**Comment by romaincointepas** [comment]
`codecguide.com` doesn't seem to be blocked by Porn anymore, probably fixed upstream.

`x-diesel.com` however is also blocked by a TON of popular blocklists, do you know why?

**Comment by ammnt** [comment]
> `x-diesel.com` however is also blocked by a TON of popular blocklists, do you know why?

I have no idea.

**Comment by romaincointepas** [comment]
Ok, well, I've whitelisted `x-diesel.com` (only) from the Porn category.
