### ISSUE TITLE
nextdns being blocked by Energized Ultimate??

### ISSUE THREAD

**Issue by botthebestplayerintheworld** [nextdns/metadata#1145]
![Screenshot (58)](https://user-images.githubusercontent.com/96731476/203907135-464953fc-8913-45cf-aa84-3ad89c516442.png)
![image](https://user-images.githubusercontent.com/96731476/203907167-ba8e0d96-ec17-49ab-a2c8-fba4b1d75878.png)
https://github.com/EnergizedProtection/block/issues/971
https://github.com/EnergizedProtection/block/issues/972
https://github.com/EnergizedProtection/block/issues/973
https://github.com/EnergizedProtection/block/issues/974
https://github.com/EnergizedProtection/block/issues/975
https://github.com/EnergizedProtection/block/issues/976
https://help.nextdns.io/t/m1hs207/energized-ultimate-lists-blocking-nextdns
https://help.nextdns.io/t/q6hs204/nextdns-io-addresses-added-to-a-blocklist-internet-goes-down
https://github.com/EnergizedProtection/block/issues/977
https://help.nextdns.io/t/83hsb6l/energized-ultimate-have-0-entries

**Comment by botthebestplayerintheworld** [comment]
1385 entries 🤔

**Comment by botthebestplayerintheworld** [comment]
https://help.nextdns.io/t/m1hs207/energized-ultimate-lists-blocking-nextdns found this

**Comment by correabuscar** [comment]
`*.io` is all blocked

**Comment by botthebestplayerintheworld** [comment]
thanks

**Comment by botthebestplayerintheworld** [comment]
`paper.io` works

**Comment by quantumpacket** [comment]
This is precisely why I had opened up https://github.com/nextdns/metadata/issues/528, but it was closed by NextDNS. Any upstream blocklist could lock people out of the dashboard inadvertently.

**Comment by botthebestplayerintheworld** [comment]
well a parent might want to block nextdns.io just in case the children find out

**Comment by quantumpacket** [comment]
> well a parent might want to block nextdns.io just in case the children find out and change the configuration or delete the account

I would hope a parent is not sharing their NextDNS login info with their children. :eyes:

**Comment by botthebestplayerintheworld** [comment]
the kids can always use the device that their parents use

**Comment by botthebestplayerintheworld** [comment]
they could allow nextdns.io unless it is being blocked by denylist

**Comment by quantumpacket** [comment]
> the kids can always use the device that their parents use

It's a terrible security practice to give access to a device logged into a service's admin dashboard to the very same people who are being restricted by said service.

**Comment by botthebestplayerintheworld** [comment]
agreed

**Comment by botthebestplayerintheworld** [comment]
closing because the problem is now fixed
so i just tried to get a pic of the entries but well
![image](https://user-images.githubusercontent.com/96731476/204066656-6eb2b5a4-63dc-4f54-ac68-4fa8afae4fec.png)

**Comment by botthebestplayerintheworld** [comment]
https://github.com/nextdns/metadata/issues/1145
https://github.com/EnergizedProtection/block/issues/971
https://github.com/EnergizedProtection/block/issues/972
https://github.com/EnergizedProtection/block/issues/973
https://github.com/EnergizedProtection/block/issues/974
https://github.com/EnergizedProtection/block/issues/975
https://github.com/EnergizedProtection/block/issues/976
https://help.nextdns.io/t/m1hs207/energized-ultimate-lists-blocking-nextdns
https://help.nextdns.io/t/q6hs204/nextdns-io-addresses-added-to-a-blocklist-internet-goes-down
https://github.com/EnergizedProtection/block/issues/977

**Comment by botthebestplayerintheworld** [comment]
problem with energized https://block.energized.pro/ultimate/formats/domains.txt

**Comment by quantumpacket** [comment]
Seems it's not just the Energized Ultimate list, but others as well.

![Screenshot_2022-11-25_20-28-06](https://user-images.githubusercontent.com/8516784/204067295-411cd1e9-7a03-4598-9f18-4b40409506e1.png)

**Comment by botthebestplayerintheworld** [comment]
not a problem with nextdns

**Comment by Quorum75** [comment]
Simple solution. All Energized lists have been removed and are now blacklisted.

NextDNS official response to this issue.

![image](https://user-images.githubusercontent.com/49731083/204089581-2f014656-251c-40c0-b8b1-aff485155641.jpeg)
