### ISSUE TITLE
damro.lk is blocked by Threat Intelligence Feeds

### ISSUE THREAD

**Issue by nishaddesilva** [nextdns/metadata#1147]
This is a legit website. Please unblock.

URL: damro.lk

**Comment by lyrad87** [comment]
It is also included in `oisd` and `notracking`. I reported it upstream for you.

**Comment by lyrad87** [comment]
https://threatfox.abuse.ch/ioc/954526/ mentions that the site is compromised and may host other malware.

You could report it as a false positive (via the Actions button) and they may remove it upon further investigation. It also included in `oisd` and `notracking`. If it's removed from threatfox, it will likely be removed by `oisd` and `notracking` as well.

**Comment by nishaddesilva** [comment]
Thanks!

**Comment by nishaddesilva** [comment]
damro.lk is blocked again.
Please fix.
