### ISSUE TITLE
AI Feed is blocking formspree.io

### ISSUE THREAD

**Issue by travisboss** [nextdns/metadata#1149]
This is a form service, that is legitimate and is being blocked by Threat Intelligence Feed.
<img width="304" alt="Screenshot 2022-11-28 at 11 22 24 AM" src="https://user-images.githubusercontent.com/16948721/204341388-e733f45f-35e4-45c9-a299-30b805542bb0.png">

**Comment by romaincointepas** [comment]
Fixed (added to https://github.com/nextdns/bin-domains)
