### ISSUE TITLE
List of domains that are no longer in use

### ISSUE THREAD

**Issue by S8D** [nextdns/metadata#1150]
I used the tool and checked the list of domains and found that some domains were no longer in use. Hope Dev also remove it from the list of domains please!
  Thank you!
Below is a list of domains that are no longer in use:

zacebookpk.com
https://browserleaks.com/ip/zacebookpk.com

youtubefreeproxy.net
https://browserleaks.com/ip/youtubefreeproxy.net

youtubebyclick.com
https://browserleaks.com/ip/youtubebyclick.com

webunblocker.xyz
https://browserleaks.com/ip/webunblocker.xyz

vectroproxy.com
https://browserleaks.com/ip/vectroproxy.com

unblockandsurf.com
https://browserleaks.com/ip/unblockandsurf.com

tomatoproxy.eu
https://browserleaks.com/ip/tomatoproxy.eu

spanproxy.com
https://browserleaks.com/ip/spanproxy.com

serverfriend.altervista.org
https://browserleaks.com/ip/serverfriend.altervista.org

radmin-vpn.org
https://browserleaks.com/ip/radmin-vpn.org

proxyunblock.club
https://browserleaks.com/ip/proxyunblock.club

proxythis.info
https://browserleaks.com/ip/proxythis.info

proxysite.fr
https://browserleaks.com/ip/proxysite.fr

proxyserverfree.net
https://browserleaks.com/ip/proxyserverfree.net

proxyone.net
https://browserleaks.com/ip/proxyone.net

proxyisp.com
https://browserleaks.com/ip/proxyisp.com

proxy.toolur.com
https://browserleaks.com/ip/proxy.toolur.com

pollproxy.info
https://browserleaks.com/ip/pollproxy.info

opera-proxy.net
https://browserleaks.com/ip/opera-proxy.net

onion.sh
https://browserleaks.com/ip/onion.sh

onion.pet
https://browserleaks.com/ip/onion.pet

onion.direct
https://browserleaks.com/ip/onion.direct

leo.paulmihaipavel.com
https://browserleaks.com/ip/leo.paulmihaipavel.com

ipredia.org
https://browserleaks.com/ip/ipredia.org

i.233py.com.a.bdydns.com
https://browserleaks.com/ip/i.233py.com.a.bdydns.com

hidingyour.info
https://browserleaks.com/ip/hidingyour.info

helloworld.cx
https://browserleaks.com/ip/helloworld.cx

guardian-vpn.com
https://browserleaks.com/ip/guardian-vpn.com

freedom.cx
https://browserleaks.com/ip/freedom.cx

franceproxy.pw
https://browserleaks.com/ip/franceproxy.pw

fixproxy.com
https://browserleaks.com/ip/fixproxy.com

fi.doh.dns.snopyta.org
https://browserleaks.com/ip/fi.doh.dns.snopyta.org

fi.dot.dns.snopyta.org
https://browserleaks.com/ip/fi.dot.dns.snopyta.org

example.doh.blockerdns.com
https://browserleaks.com/ip/example.doh.blockerdns.com

evyy.net
https://browserleaks.com/ip/evyy.net

doyouremember.love
https://browserleaks.com/ip/doyouremember.love

doh.westeu.pi-dns.com
https://browserleaks.com/ip/doh.westeu.pi-dns.com

doh.gslb2.xfinity.com
https://browserleaks.com/ip/doh.gslb2.xfinity.com

doh.blahdns.com
https://browserleaks.com/ip/doh.blahdns.com

doh.armadillodns.net
https://browserleaks.com/ip/doh.armadillodns.net

dns2.developer.li
https://browserleaks.com/ip/dns2.developer.li

dns2.alekberg.net
https://browserleaks.com/ip/dns2.alekberg.net

dns.pumplex.com
https://browserleaks.com/ip/dns.pumplex.com

dns.developer.li
https://browserleaks.com/ip/dns.developer.li

dns.containerpi.com
https://browserleaks.com/ip/dns.containerpi.com

dns.containerpi.co
https://browserleaks.com/ip/dns.containerpi.co

dns.alekberg.net
https://browserleaks.com/ip/dns.alekberg.net

dns.aaflalo.me
https://browserleaks.com/ip/dns.aaflalo.me

dns.233py.com.cdn.cloudflare.net
https://browserleaks.com/ip/dns.233py.com.cdn.cloudflare.net

darknet.to
https://browserleaks.com/ip/darknet.to

cloudflare-gateway.com
https://browserleaks.com/ip/cloudflare-gateway.com

cg‑dialup.net
https://browserleaks.com/ip/cg‑dialup.net

canadianshield.cira.ca
https://browserleaks.com/ip/canadianshield.cira.ca

bumblebee.site
https://browserleaks.com/ip/bumblebee.site

bogbone.com
https://browserleaks.com/ip/bogbone.com

blocka.net
https://browserleaks.com/ip/blocka.net

blackvpn.com
https://browserleaks.com/ip/blackvpn.com

avira-vpn.com
https://browserleaks.com/ip/avira-vpn.com

atoproxy.com
https://browserleaks.com/ip/atoproxy.com

anonymizer.nntime.com
https://browserleaks.com/ip/anonymizer.nntime.com

adguard.io
https://browserleaks.com/ip/adguard.io

adblock.mydns.network
https://browserleaks.com/ip/adblock.mydns.network

**Comment by romaincointepas** [comment]
We are working on our own automated script for this (coming soon), but thanks!
