### ISSUE TITLE
Maintainer of 'lightswitch05' block list alleges incorrect deployment by NextDNS

### ISSUE THREAD

**Issue by macbugs** [nextdns/metadata#1155]
[**_"NextDNS is doing wildcard blocking of my list --
 ...which isn't how the list is meant to be used and is completely out of my control."_**](https://github.com/lightswitch05/hosts/issues/301#issuecomment-1336326768)

**Comment by romaincointepas** [comment]
I commented there: https://github.com/lightswitch05/hosts/issues/301#issuecomment-1345642038.
