### ISSUE TITLE
Threat Intelligence blocking static.vanta.com

### ISSUE THREAD

**Issue by mahtd** [nextdns/metadata#1156]
static.vanta.com's CNAME is vanta-prod.pages.dev, which is the domain that seems to get blocked

static.vanta.com is used by https://app.vanta.com/login, and is completely legitimate as far as I know.

I tried looking through the lists in threat-intelligence-feeds.json, but couldn't find one that was blocking either of those 2 domains

**Comment by romaincointepas** [comment]
It's only blocked by our AI Threat Detection at the moment, should be fixed in the coming days.
