### ISSUE TITLE
o0.pages.dev blocked by AI-Driven Threat Detection

### ISSUE THREAD

**Issue by unknown4849** [nextdns/metadata#1157]
![image](https://user-images.githubusercontent.com/74445408/206125397-fcf5c577-65ea-4b9d-b5aa-04304d7c27d6.png)

1host filter site

**Comment by botthebestplayerintheworld** [comment]
https://help.nextdns.io/t/h7hs0dn/o0-pages-dev-blocked-by-ai-driven-threat-detection
yes

**Comment by romaincointepas** [comment]
Should be fixed in the coming days, thanks for reporting.
