### ISSUE TITLE
[Add BlockList] s

### ISSUE THREAD

**Issue by git6578** [nextdns/metadata#1159]
I want to be able to add own blocklists similar to ublock, like other customers lining up here: https://help.nextdns.io/t/q6hmva4/custom-blocklist-support

Blocklists like in this folder: https://github.com/RPiList/specials/tree/master/Blocklisten

**Comment by kalle07** [comment]
Hello,

same suggestion !
some of the build in blocklist are older than a year !
some options from me:
https://github.com/hagezi/dns-blocklists
https://github.com/lightswitch05/hosts
https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist

PLEASE   ;)
