### ISSUE TITLE
One of your porn lists is 404

### ISSUE THREAD

**Issue by travisboss** [nextdns/metadata#1161]
https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts

This list no longer resolves.

**Comment by romaincointepas** [comment]
We have internalized our Porn category.

**Comment by travisboss** [comment]
>We have internalized our Porn category.

I just wanted to ask what this means exactly, are you guys now using your AI to handle this?  I am only asking out of curiousity.

**Comment by travisboss** [comment]
> We have internalized our Porn category.

I just wanted to ask what this means exactly, are you guys now using your AI to handle this?  I am only asking out of curiousity.
