### ISSUE TITLE
Polish CERT custom blocklist support

### ISSUE THREAD

**Issue by Kucharskov** [nextdns/metadata#1165]
Hello!

Im amazend with NextDNS. Only thing what is missing for me is support for custom DNS. The most common used in poland is polish CERT domains block list which consist all of polish (and others too) campaings used by threat actors in phishings, mostly banking but not only.

The full list is updated there: http://hole.cert.pl/domains/ (as csv, json, txt, xml, adblock list).
I think it would be very good to implement that.

Regards and nice x-mas time 🎁 🎄

**Comment by scafroglia93** [comment]
I confirm that the filter is already present in the threat intelligence section

**Comment by Kucharskov** [comment]
Youre right! I confirmed it after creating a issue. I got blank page instead of "this website was blocked" due uBlock Origin chrome addon. I dont know why website blocked by uBlock&NextDNS shows only blank page.
Anyways i can close that issue. Big thanks, good job!
