### ISSUE TITLE
[Threat Intelligence] False positives

### ISSUE THREAD

**Issue by JaehaerysNL** [nextdns/metadata#1167]
**Good evening, I wish to report four false positives, blocked by the Threat Intelligence Feeds and AI Driven Threat Detection.**

- Issue type: _False positive_
- Affected domains: _"bio.link", "paypal-opwaarderen.nl", "paypal-opladen.be" and "paypal-topup.be"_
- Blocked by: _Threat Intelligence Feeds and AI Driven Threat Detection_
- System: _Windows 10 22H2_
- Protocol: _DNS-over-HTTP/3_
- Client: _Mozilla Firefox 108.0.1_
- Description (1): _https://bio.link is an alternative service to https://linktr.ee (Linktree), operated by those who set up https://www.buymeacoffee.com_
- Description (2) _The three latter links are legitimate PayPal top-up sites using iDeal for NL and BanContact for BE, you can verify my claim by checking https://www.onlinebetaalplatform.nl/ and https://onlinepaymentplatform.com/ of which both are referenced by the top-up websites, Online Payment Platform is officially registered in the Netherlands as Online Payments Platform B.V. under Chamber of Commerce (KvK/CoC) no. 50124498, whose entry you can find at https://www.kvk.nl/orderstraat/product-kiezen/?kvknummer=501244980000 (Dutch Chamber of Commerce Registry)_

If you have any comments and/or questions, feel free to mention me.

Kind regards,
Jaehaerys

**Comment by romaincointepas** [comment]
`bio.link` [fixed](https://github.com/nextdns/bin-domains/commit/e826d5c644259867e9a5a1d373c088c065a2db0e), we will have a look for the other 3.
