### ISSUE TITLE
Remove coronazaehler.de from threat-intelligence-feeds

### ISSUE THREAD

**Issue by lyrad87** [nextdns/metadata#117]
Please remove (or whitelist) [coronazaehler.de](https://www.coronazaehler.de/) from your threat-intelligence-feeds. It's a website that shows current Corona infections and deaths in Germany, and is used by many people to keep up to date about the spread of the virus. Thanks in advance!

**Comment by romaincointepas** [comment]
Could you report this directly to https://dsi.ut-capitole.fr/blacklists/index_en.php? Their "malware" blocklist contains this domain.

@scafroglia93 maybe you can help?

**Comment by lyrad87** [comment]
Thanks for the heads up. I've reported it but scafroglia93 can certainly do his thing if he wants to and message them a different way.

**Comment by scafroglia93** [comment]
For False Positive Issue  ->

- fabrice.prigent@ut-capitole.fr
- https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi

**Comment by lyrad87** [comment]
The owner of the website has removed the domain from his malware blocklist, so I can close this issue. :) Thanks for the heads up again!
