### ISSUE TITLE
ajax.googleapis.com should not be blocked

### ISSUE THREAD

**Issue by controversial** [nextdns/metadata#1171]
This morning nextdns started blocking ajax.googleapis.com, which hosts versions of popular libraries (jquery etc) for a lot of major sites on the internet, at urls like https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js. 

Having this domain blocked breaks a lot of popular sites (for example, I couldn’t access stackoverflow this morning).

<img width="894" alt="Screenshot 2022-12-29 at 2 44 42 PM" src="https://user-images.githubusercontent.com/10377391/210004560-3532337d-cae5-4e3a-b115-d9264dc9d858.png">

**Comment by hagezi** [comment]
Blocked by @stevenblack. No explanation why this ended up on the blocklist.

**Comment by StevenBlack** [comment]
Sorry folks. This is fixed in release 3.11.47, just now.

**Comment by controversial** [comment]
Fixed by @StevenBlack ❤️
