### ISSUE TITLE
Zenmate VPN not blocked.

### ISSUE THREAD

**Issue by ghost** [nextdns/metadata#1173]
https://microsoftedge.microsoft.com/addons/detail/zenmate-free-vpn-%E2%80%93-best-v/kepdippgcikacmcdaijnponnfgljfbea

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/dns-bypass-methods/commit/58c57dbc42970c759c7b0744f5fd3ceb01519dc6.
