### ISSUE TITLE
Add `mask-api.icloud.com` to `bypass-methods` list

### ISSUE THREAD

**Issue by user8446** [nextdns/metadata#1185]
I found the `mask-api.icloud.com` domain on my network coming from an iPhone 14 for the apple private relay feature. Others have seen this domain as well: https://gfw.report/blog/private_relay_censorship/en/

This should be added in addition to the two already in the list: `mask.icloud.com` and `mask-h2.icloud.com`

I didn't see any info that this list is from another list maintainer so if it is I can report there as well.

**Comment by romaincointepas** [comment]
This domain doesn't need to be blocked to stop private relay from working.
