### ISSUE TITLE
Add my Threat Intelligence Feeds?

### ISSUE THREAD

**Issue by hagezi** [nextdns/metadata#1195]
Hi @romaincointepas,

any chance of adding my threat intelligence feeds list to your TIFs?

See: https://github.com/hagezi/dns-blocklists#tif

Thanks,
Gerd

**Comment by iJorgen** [comment]
This would be so great in addition to the privacy-focused lists already added (NORMAL, PRO, PRO++, ULTIMATE etc.)

**Comment by romaincointepas** [comment]
@hagezi for TI feeds we only use original sources

**Comment by hagezi** [comment]
Ok, thanks.
