### ISSUE TITLE
Cannot whitelist the domain

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#120]
Hello,

I can 't add **pagead.l.doubleclick.net** to the whitelist - when I type the domain and press enter, nothing happens. Please, help!

Cheets.

**Comment by lyrad87** [comment]
Try adding just "doubleclick.net"

**Comment by romaincointepas** [comment]
@ammnt Weird bug, could you talk to us via the chat on our website so we can debug this privately?
