### ISSUE TITLE
hopp.to is blocked by Threat Intelligence Feeds

### ISSUE THREAD

**Issue by shaulgo** [nextdns/metadata#1209]
Hey,
Hopp.to is blocked by `Threat Intelligence Feeds`.
It is a link shortener and link-in-bio product by wix.com. 
Can you whitelist the domain? 
Like any link shortener, subdomains should be blocked individually. 
Thanks

**Comment by romaincointepas** [comment]
Could you please suggest it directly to https://github.com/PeterDaveHello/url-shorteners?

**Comment by shaulgo** [comment]
Thanks, I will do that :)

**Comment by shaulgo** [comment]
I had a long conversation with @PeterDaveHello (https://github.com/PeterDaveHello/url-shorteners/pull/23). 
Unfortunately we are not a good fit for his list. His list is only for services that allow to change the path. Where we also change the subdomain.

Hopp.to is a legitimate link shortener and link-in-bio (owned by wix.com). 

The url structure of the services is provided like so:
1. [username].hopp.to/[custom]
2. hopp.to/[username]

So the parent domain should be handled separately from subdomains and paths.
Could you please whitelist us? Also, are you using a blocklist? I connected all the lists I could find and they all removed us from their blocklist and added us to their white list (if they have one). 

Thanks,
Shaul

**Comment by PeterDaveHello** [comment]
One approach in https://github.com/PeterDaveHello/url-shorteners may be to list those parent domains for the use cases like hopp.to, but still need NextDNS to make sure their subdomains will be whitelisted. I would be curious about the priority when there are parent domains and different subdomains in both blacklist and whitelist, who has the highest priority to be applied?

**Comment by shaulgo** [comment]
@romaincointepas do you know why hopp.to is still blocked? This is very frustrating. It's been removed from every block list and service I can find. 

Except 1 one that is marked in Phishtank. Phishtank doesn't have a way to contact them. While the path has been deleted a long time ago.
