### ISSUE TITLE
Suggested Idea

### ISSUE THREAD

**Issue by sbpir92i** [nextdns/metadata#122]
hello
 
Hello would be possible to add the following function.
from the logs, blocker or unlock one or more domains directly.
You can block this domain or block similar domains . Whitelisting a domain or Blacklisting a domain. 

in IOS apps the  fonction log to. 
For the IOS Apps included the log with the same feature mentioned above.  Currently must switch to safari. and it's manipulation between Blacklisting a domain, Whitelisting a domain and logs.

sorry for english
best regards

**Comment by scafroglia93** [comment]
For new features write inside nextdns reddit

you can close this issue

**Comment by romaincointepas** [comment]
@sbpir92i First feature will come soon. Second one no plan for it yet.

Like @scafroglia93 said, our subreddit /r/nextdns is a better place for feature suggestions!
