### ISSUE TITLE
Please Add a Blocklist for tiktok

### ISSUE THREAD

**Issue by D4RKW1NT3R** [nextdns/metadata#1228]
Please add a Blocklist for TikTok ads/trackers one I've found is here https://gist.github.com/RupGautam/e6953b6e0a68ece63e6721309135190f

**Comment by hagezi** [comment]
Tiktok Fingerprinting is blocked in my Blocklists Pro to Ultimate.

My native list: https://github.com/hagezi/dns-blocklists#native

**Comment by hagezi** [comment]
https://github.com/nextdns/native-tracking-domains/pull/12

**Comment by HRGSEC** [comment]
I found this TikTok block list
https://blocklistproject.github.io/Lists/tiktok.txt
