### ISSUE TITLE
[Urgent] Remove get.massive.app from blocklist | Major business impact

### ISSUE THREAD

**Issue by masvmajed** [nextdns/metadata#1238]
Your service flags one of our SaaS business domains ([get.massive.app](http://get.massive.app/)) citing "Blocked by threat intelligence feeds". This is negatively impacting our customers and our business, as our customers can't use our services when our domain is blocked by your DNS. We have reports from multiple customers who use Amazon Eero which is seemingly using your service for DNS filtering as well.

Background: MASV (https://massive.io/) is a fast file transfer SaaS, targeting the media & entertainment industry. We have customers around the globe and offer a free limited-time trial to drive adoption and growth for our business.

**Comment by hagezi** [comment]
@masvmajed FYI: Blocked because flagged as phishing in https://gitlab.com/malware-filter/phishing-filter

![grafik](https://user-images.githubusercontent.com/104343908/234124766-a3d42fc2-24fa-47b6-b707-2d6415ea4a3f.png)

**Comment by masvmajed** [comment]
Thanks @hagezi, this is very helpful. Our website was removed from PhishTank yesterday, and consequently phishing-filter and NextDNS as well (confirmed with a few tests this morning)

Closing this issue. Will follow up with the phishing-filter team as our TLD is on top 1m sites, but they apparently don't whitelist based on TLD
