### ISSUE TITLE
threat intelligence feeds : additional list

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#124]
1- 
Source -> https://www.threatcrowd.org/
Feeds IoC -> https://www.threatcrowd.org/feeds/domains.txt

2-
Source -> https://azorult-tracker.net/
Feeds IoC -> https://azorult-tracker.net/api/list/domain?format=plain

3-
https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt

**Comment by romaincointepas** [comment]
Added, thanks!
