### ISSUE TITLE
[untracked porn site] lisinha.com

### ISSUE THREAD

**Issue by mabequinho** [nextdns/metadata#1249]
Website from a epic meme. Also, is this the correct place to make such report? 

![image](https://github.com/nextdns/metadata/assets/46428150/d2c6dc29-e140-435c-8849-7a81803a8af1)

**Comment by williamd1k0** [comment]
It seems to work well.

![image](https://github.com/nextdns/metadata/assets/10428035/02d4d757-25b8-40f6-a1fb-69c486c90334)

**Comment by mabequinho** [comment]
Working.
