### ISSUE TITLE
Issues with Instagram and the "NextDNS Recommended Ads & Trackers Blocklist"

### ISSUE THREAD

**Issue by MitchellCash** [nextdns/metadata#125]
Since I started using the "NextDNS Recommended Ads & Trackers Blocklist" Instagram has had many issues, especially with loading Instagram Stories.

I captured the network traffic from my iOS device and ran some tests and it relates to the blocking of `graph.instagram.com` from the Steven Black hosts file (which "NextDNS Recommended Ads & Trackers Blocklist" uses).

I am following this up upstream and a similar issue has recently been created by another person here https://github.com/StevenBlack/hosts/issues/1206. It looks like `graph.instagram.com` should probably exist in a social block list, not the adware + malware blocklist.

**Workaround**
As a (hopefully just temporary) workaround, inside NextDNS you can add `graph.instagram.com` to the Whitelist.

This issue is more of an FYI for anyone else having the same problem while the issue hopefully gets resolved upstream.

**Comment by romaincointepas** [comment]
Thanks. Let's wait a few days see if gets fixed upstream, otherwise we will whitelist it ourselves.
