### ISSUE TITLE
False positive - cyberplace.social listed in Threat Intelligence feed

### ISSUE THREAD

**Issue by rgbartlett** [nextdns/metadata#1270]
cyberplace.social (Kevin Beaumont's Mastodon instance) is blocked under Threat Intelligence feed. Apparently a vendor linked one of his Mastodon threads in a write up and NextDNS categorised it as a C2 server. Could you remove please?

**Comment by hagezi** [comment]
ping @stamparm @MikhailKasimov, included in maltrail.

**Comment by MikhailKasimov** [comment]
Hello!

Fixed in https://github.com/stamparm/maltrail/commit/f4bc33c5458689cf8af837f73c4da617e517742d
Whitelisted in https://github.com/stamparm/maltrail/commit/a2f37182f7b1f61685e5670269daf0962e6cce9f

Sorry for FP!

**Comment by rgbartlett** [comment]
That’s great, thanks!  It’s still coming up as blocked on mine (when I disable the whitelisted entry) still as threat intelligence feed. Is there a lag on updating in live?

**Comment by MikhailKasimov** [comment]
Hello!

I have re-checked ```/maltrail-malware-domains.txt``` list, which in use of NextDNS --> record ```cyberplace.social``` is absent. Hence, everything should be OK for the moment of typing this message.

Basicly, as fa as I remember, ```/maltrail-malware-domains.txt``` gets uptated 1 time per day, so yes, could be a lag on updating in live.

**Comment by rgbartlett** [comment]
All working now, thank you.  Issue closed.
