### ISSUE TITLE
149677182.v2.pressablecdn.com

### ISSUE THREAD

**Issue by anxiouslelimo** [nextdns/metadata#1272]
149677182.v2.pressablecdn.com blocked by threat intelligence feeds cause issues in omglinux.com

**Comment by quantumpacket** [comment]
This appears to be a legitimate threat domain.

https://www.virustotal.com/gui/url/3dff320c294445cc3fa87861d9f9e56a7e0e0c77f4a76851d623fb04c1e3d731

> Activity related to SOCGHOLISH - according to source Cluster25 -
This DOMAIN is used by SOCGHOLISH 

https://redcanary.com/threat-detection-report/threats/socgholish/

**Comment by hagezi** [comment]
Was blocked by URLhaus because of a JPG: https://urlhaus.abuse.ch/url/2704828/
Is now offline.

I have reported it to URLhaus.

**Comment by anxiouslelimo** [comment]
According to a comment by Joey in the following link it's a false positive. Joey is well reputed in the foss/linux community. https://www.omglinux.com/kde-plasma-makes-double-click-default/
