### ISSUE TITLE
new domains not getting blocked even if block new domains switch in ON

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#1274]
https://positivedistantstale.com/
is a new domain that didn't get blocked

**Comment by rs** [comment]
I can’t repro, it’s present in the nrd db.

**Comment by SohanRay** [comment]
> I can’t repro, it’s present in the nrd db.

Well its blocking now, but it wasn't blocking when I created this issue. When I tried to access the link, it didn't block but directed me to google.com. And the same happened with zero.dns0.eu also....
BTW could you check https://github.com/nextdns/metadata/issues/1273 , also ?
