### ISSUE TITLE
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#128]
The https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist list is a very good one.

I recommend adding it

**Edit:**
The file name has now changed to a better one:
[TOP_EU_US_Ads_Trackers_HOST](https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_HOST)

**Comment by romaincointepas** [comment]
Cool idea, but doesn't seem very popular (and probably risky and/or highly redundant).

Letting this open, would love to hear what others think.

**Comment by beerisgood** [comment]
This list is from a very known member from MalwareTips.com user.
It's not important that the list is known or not. But I guess with your help if would be get more attention ;)

Also it's highly maintained and dev is fast with fixes. I also use it and can only recommend it ;)

**Comment by scafroglia93** [comment]
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/Top500#L429

**Comment by beerisgood** [comment]
> https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/master/Top500#L429

Any problem with that? if so, you can create a issue

**Comment by scafroglia93** [comment]
yep this is AWS (amazon)

**Comment by Kees1958** [comment]
Nope, beer is good on Eastern in the backyard with the sun shining




On Sun, Apr 12, 2020 at 2:09 PM +0200, "Lorenzo Ori" <notifications@github.com> wrote:















yep this is AWS (amazon)

**Comment by beerisgood** [comment]
More info:

> This blocklist is based on surveys of most used advertising and tracking technology (e.g. surveys of W3C, W3Tech and the on-line marketing community itself). These tech surveys are held once a year. This is the reason of the low update frequency (365 days and ad hoc corrections to correct website breakage). The surveys are oriented on Europe and North America, this is the reason this blocklist contains mostly EU and US based advertising and tracking networks.

**Comment by LennyFox** [comment]
I use it to, no false positives, as effective as uBlockOrigin with 300.000 rules

**Comment by crssi** [comment]
I had one breakage recently, which brings me today to this line in the source:
https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist/blob/b7eaf76d3bbb404bf6511f6dc51c56473d72fa7b/Top500#L10

So OP (@beerisgood  😸) should change the suggested URL perhaps to [EU US most commen ads & trackers HOST format](https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU%20US%20most%20commen%20ads%20%26%20trackers%20HOST%20format), that is `https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU%20US%20most%20commen%20ads%20%26%20trackers%20HOST%20format`?

**Comment by beerisgood** [comment]
Yes @crssi you're right. The new hosts file is the successor of my beer is good list and also even better for projects like NextDNS 👍

**Comment by beerisgood** [comment]
The file name has now changed to a better one:
[TOP_EU_US_Ads_Trackers_HOST](https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/TOP_EU_US_Ads_Trackers_HOST)

**Comment by beerisgood** [comment]
I compare latest TOP_EU_US_Ads_Trackers_HOST with NextDNS default list and 1340 entries are missed at NextDNS side.
So please add this list.

@Kees1958 (ping to inform you about that comparison 🍺)
