### ISSUE TITLE
benkow.cc

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#129]
it's blocked by ->  threat-intelligence-feeds.

was whitelisted in previous ticket

**Comment by romaincointepas** [comment]
Included in https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt, can you check with them?

**Comment by scafroglia93** [comment]
https://github.com/HorusTeknoloji/TR-PhishingList/pull/6

**Comment by scafroglia93** [comment]
https://github.com/HorusTeknoloji/TR-PhishingList/pull/6
