### ISSUE TITLE
nsupdate.info

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#130]
blocked by -> threat-intelligence-feeds

List -> https://phishing.army/download/phishing_army_blocklist_extended.txt

**Comment by lyrad87** [comment]
Maybe contact the guy behind it to report it so that he can take it out of his blocklist.
Email --> [drego85@draghetti.it](mailto:drego85@draghetti.it)

**Comment by scafroglia93** [comment]
done

Il giorno sab 11 apr 2020 alle ore 10:31 lyrad87 <notifications@github.com>
ha scritto:

**Comment by scafroglia93** [comment]
@ drego85
UP

**Comment by scafroglia93** [comment]
@drego85 UP

**Comment by scafroglia93** [comment]
Was fixed by change of the list in the past day

**Comment by drego85** [comment]
Sorry guys for delay, I spent intense weeks (covid-19 problems and a degree to write/discuss). 

The domain will be whitelisted next week.

**Comment by lyrad87** [comment]
@romaincointepas this has been fixed upstream and can be closed
