### ISSUE TITLE
(filter porn category) block.energized.pro/porn/formats/domains.txt

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#131]
https://block.energized.pro/porn/formats/domains.txt

They have 388,570 entries & active maintain

**Comment by scafroglia93** [comment]
@romaincointepas 
Don't add this it's full of False Positive

**Comment by 3xploiton3** [comment]
> Don't add this it's full of False Positive

i agree, still needed to unblock (whitelist) 
https://github.com/EnergizedProtection/unblock/raw/master/basic/formats/domains.txt

**Comment by sbpir92i** [comment]
Hello add filter list here https://github.com/spirillen/pornhosts

**Comment by scafroglia93** [comment]
@sbpir92i 
https://github.com/Sinfonietta/hostfiles 
https://github.com/Clefspeare13/pornhosts
https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts"

They have already been entered

Before asking for the insertion, I advise you to look if they are not already present within nextdns

**Comment by romaincointepas** [comment]
@scafroglia93 what are the false positives from https://block.energized.pro/porn/formats/domains.txt?

**Comment by scafroglia93** [comment]
The maintainer is not very present, I invite you to view the part related to the issues
https://github.com/EnergizedProtection/block/issues

**Comment by romaincointepas** [comment]
Some inactivity is okay for (popular) blocklists, but this would be too risky to put in a category.

@scafroglia93 I would love to know which domains are false positives specifically for that porn list though?

**Comment by scafroglia93** [comment]
The false positives that I mean are those present in the list.
I used it for a week and web navigation was a disaster

Flickr blocked by a bad conversion from adb to host

And much more

Thi is my opinion guys

**Comment by spirillen** [comment]
> Hello add filter list here https://github.com/spirillen/pornhosts
> 
> porno hosts https://github.com/Sinfonietta/hostfiles https://github.com/Clefspeare13/pornhosts porno jap https://github.com/tiuxo/hosts/

Thanks for this thought of my effort, the urls you suggest however have become rather outdated, thanks to Github deletion of several Porn Blacklisting repositories. This mean the main project is now and for good moved to https://mypdns.org/my-privacy-dns/porn-records (no hosts files) The host file extraction of that project however is still to be found as usual in https://mypdns.org/clefspeare13/pornhosts

**Comment by romaincointepas** [comment]
We have moved to our internal Porn AI, closing.
