### ISSUE TITLE
false positive - naymee.com

### ISSUE THREAD

**Issue by drewwilson** [nextdns/metadata#1315]
Hi!
I recently launched a new app called Naymee. And it's somehow on your block list. Folks are unable to reach my website because of this. Can you please remove Naymee.com from your lists?

Example (with screenshot) of someone being blocked by nextdns: https://twitter.com/levifig/status/1751732005581062156

Thanks!

**Comment by hagezi** [comment]
This domain is flagged by some security services and therefore blocked by some Secure DNS like Quad9 and can be found on some lists like Phishing Army and CERT PL.

https://www.virustotal.com/gui/domain/naymee.com/summary

![image](https://github.com/nextdns/metadata/assets/104343908/984d47de-93df-49bb-bf29-00e7f26a66d3)

**Comment by drewwilson** [comment]
wow, super helpful! Thank you! I'm reaching out to all of them now 👍

still would be great to be whitelisted on NextDNS tho :)

**Comment by krystian3w** [comment]
Based on your e-mail, I don't see blockade in files:

https://raw.githubusercontent.com/FiltersHeroes/KAD/master/KAD.txt

https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhosts.txt
https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADhole.txt
https://raw.githubusercontent.com/FiltersHeroes/KADhosts/master/KADdnsmasq.txt

In the change history, I don't see people logging in what could have removed between January 28 to 31 this domain from the files (rather, no one hacked into our repositories with the change history obliterated).

> [!Note]
>
> Those willing can try using git in the console to trace the files.
>
> https://stackoverflow.com/questions/2928584/how-to-grep-search-through-committed-code-in-the-git-history

**Comment by drewwilson** [comment]
Thanks!
I forgot to come back and close the issue. I ended up finding out about the source blocklists that nextdns uses, and asked those Mainers to remove my domain, and they did :) so it's no longer an issue in nextdns.. but still is in other places. I'm sending lots of emails :)thanks!
