### ISSUE TITLE
Threatcrowd KO (Threat Intelligence)

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#136]
https://www.threatcrowd.org/feeds/domains.txt (not more update)
My apologize
@romaincointepas

**Comment by romaincointepas** [comment]
How do you know they are not updating it anymore?

**Comment by scafroglia93** [comment]
Source ->https://threatcrowd.blogspot.com/
https://threatcrowd.blogspot.com/2016/02/crowdsourced-feeds-from-threatcrowd.html

Better to remove (pardon)

**Comment by romaincointepas** [comment]
Removed.
