### ISSUE TITLE
https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#137]
Source -> http://vxvault.net
- http://vxvault.net/URL_List.php

- https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE

**Comment by romaincointepas** [comment]
URL feeds won't work for DNS blocking.

The second, looks pretty redondant and not very popular. Am I missing something?

**Comment by scafroglia93** [comment]
The second is from italian cyber security community called "cybersayan"
Source -> https://www.cybersaiyan.it/

**Comment by scafroglia93** [comment]
@gmellini UP

**Comment by gmellini** [comment]
@scafroglia93 tks for the mention. 
We fill the PI-HOLE feed https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE with domains provided by community trusted sources; this is a verified content.
Domains in the feed are a subset of the IoC we publish in STIX/TAXII2 format (as well HTTP/JSON/CSV) in our Info Sharing platform.
More info (italian sorry) here: https://github.com/CyberSaiyanIT/InfoSharing

**Comment by scafroglia93** [comment]
Tested for 4 months, no issue
+1

**Comment by scafroglia93** [comment]
Any news for this request ?

**Comment by scafroglia93** [comment]
@romaincointepas 
Any news about this request =?
