### ISSUE TITLE
More Lists

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#139]
Malware ->
- https://gitlab.com/quidsup/notrack-blocklists/-/blob/master/notrack-malware.txt

ADS ->
- https://threatcenter.crdf.fr/public/urls/domains_ads-tracking.txt

We could consider adding some inside TI
Cheers :)

**Comment by sbpir92i** [comment]
Hello

I have already submitted it.
suggest --> https://filtri-dns.ga/filtri.txt

for scam __> https://www.stopforumspam.com/downloads

no compatible https://malsilo.gitlab.io/feeds/dumps/domain_list.txt for nextdns ...

**Comment by scafroglia93** [comment]
Cleaned

**Comment by scafroglia93** [comment]
-1 https://www.stopforumspam.com/downloads/toxic_domains_whole.txt

**Comment by romaincointepas** [comment]
Could you open one issue per list, so it's easier to discuss/keep track?

**Comment by scafroglia93** [comment]
sure
