### ISSUE TITLE
Simply.com tracking info & delist

### ISSUE THREAD

**Issue by emilstahl** [nextdns/metadata#140]
Hi

We acquired Simply.com, Simply.net and other domains, see https://domaininvesting.com/unoeuro-announces-rebrand-to-simply-com/

The name is now used for a web hosting brand, and not an affiliate or ad company. The domain has some history as tracking/ads serving, but it does not have anything to do with advertising or tracking anymore.

I can't find any info for Simply.com at whotrack.me or in their GitHub repo, can you remove this info in your end?
![image](https://user-images.githubusercontent.com/3885790/79229979-32a93200-7e64-11ea-9488-774d90f9db98.png)

Can you whitelist the domain in your end? As we have problems getting in touch with all the authors of the block lists you are using to get the domain delisted. The only listing left seems to be Energized, which I have both mailed - and created this [issue](https://github.com/EnergizedProtection/block/issues/400) 

Thanks!

**Comment by romaincointepas** [comment]
Seems to be only blocked by Energized Regional extension (out of all the blocklists we support). We don't touch third-party blocklists so we will have to wait on them.

Regarding whotracks.me, if they removed it, it will be updated as soon as we sync with them in a week or 2.

**Comment by emilstahl** [comment]
@romaincointepas I can't find Simply.com in whotracks.me GitHub source or on their website. I checked 1-2 months ago. Can you please check where NextDNS got that data from?
