### ISSUE TITLE
Appropriate identification name for adult material

### ISSUE THREAD

**Issue by eoopx** [nextdns/metadata#143]
Currently NextDNS has categorized adult materials as following,

- Block Child Sexual Abuse Material
- Porn
- Dating

Can you put that three categories into single entity with suitable name for every age users? Eg, Kids protection, Child Safety smth like that?

@romaincointepas Is it possible to PR?

**Comment by romaincointepas** [comment]
**Child Sexual Abuse Material** is not adult material, it's illegal material (see https://projectarachnid.ca).

If I understand correctly, you would like some sort of single toggle "PG-13" that would automatically set all the different settings for you to protect kids?

**Comment by eoopx** [comment]
> **Child Sexual Abuse Material** is not adult material, it's illegal material (see https://projectarachnid.ca).

No. I mean can you please avoid use words similar 'sexual', 'porn', 'dating', 'pornhub', 'escort sites' in NextDNS UI? so far age from 9-10 use this service

> If I understand correctly, you would like some sort of single toggle "PG-13" that would automatically set all the different settings for you to protect kids?

Yes and possible to add explanation below the identifier however no special benefit from categorize adult content like that

**Comment by fire-dotcom** [comment]
+1 Please update that.

**Comment by romaincointepas** [comment]
We may replace Porn by Adult content, not sure about the rest though.
