### ISSUE TITLE
app.adjust.com is required to set up 2FA for MS Live

### ISSUE THREAD

**Issue by MagerValp** [nextdns/metadata#144]
I tried to enable two step verification on my Microsoft Live account, but the process couldn't be completed until I added a whitelist entry for `app.adjust.com`.

<img width="322" alt="app adjust com" src="https://user-images.githubusercontent.com/404393/79631955-91b8c080-815c-11ea-99b9-4c84bf17a7f0.png">

**Comment by teohhanhui** [comment]
app.adjust.com is used for many "launch or install app" (deep)links anyway. I don't think we can block it without breaking many things.

**Comment by romaincointepas** [comment]
It's currently blocked by all those blocklists:

```
1hosts-complete
1hosts-mini
1hosts-pro
abpvn-list
adaway
adguard-base-filter
adguard-simplified
anudeep-blacklist
bkrucarci-turk-adlist
certyficateit
chef-koch-spotify
easylist
energized-basic
energized-blu
energized-blu-go
energized-regional-extension
energized-spark
energized-ultimate
energized-xtreme-extension
goodbye-ads
goodbye-ads-ultra
hostsvn
lightswitch05-ads-tracking
nextdns-recommended
notrack-tracker-blocklist
notracking
shallas-blacklists-tracker
steven-black
wally3k-personal
```

Wondering if we should whitelist it from nextdns-recommended, or just affiliate/tracking. Thoughts?

**Comment by badmojr** [comment]
I don’t think **app.adjust.com** fits into the “affiliate/tracking” description, which states: “Those usually only get called after manually clicking on a link“.

**Comment by teohhanhui** [comment]
@badmojr Actually it *is* exactly what you've described. There are many app.adjust.com tracking / redirect links as I've explained above.

**Comment by badmojr** [comment]
@teohhanhui Take Spotify for instance.
https://open.spotify.com/artist/0QHgL1lAIqAw0HtD7YldmP

It also uses the above domain to track installs/conversions.
But, the domain will continually keep on tracking the user long after s/he installed the app.

It not a one-time-track-install & be done “app installs tracker” like **app.link** (used by Reddit).

**Comment by badmojr** [comment]
> Wondering if we should whitelist it from nextdns-recommended, or just affiliate/tracking. Thoughts?

In my humble opinion, whitelist it from nextdns-recommended only.

**Comment by crssi** [comment]
Here I have a lot of denies to `app.adjust.com` and nothing is broken.
I think that `app.adjust.com` is abused by many and if someone has problems with it (I would guess that is a minority) it should be manually whitelisted.

IMHO the `app.adjust.com` should not be part of [affiliate-tracking-domains ](https://github.com/nextdns/metadata/blob/master/privacy/affiliate-tracking-domains) and secondly, we (as a customers) need exact definition for `affiliate-tracking-domains`, since ATM it looks like all sort of things are thrown into it, without real explanation.
