### ISSUE TITLE
Whitelist analytics.twitter.com

### ISSUE THREAD

**Issue by teohhanhui** [nextdns/metadata#146]
Blocking this breaks any external URLs from the Twitter app.

Example link: https://analytics.twitter.com/mob_idsync_click?slug=VZKWeYY6e3&idb=AAAAEIAgMsreFR1-HgruiLeN3gnHwb5f46UtGH5JgwO9J0EEzBhDGYUzWg8qdyePsIH-SDPqRqqdeBIbM26Kyyo-FNdcxLKL4DBNB06okB3TkIZ0TmocRNXr8AcBGy9dy9lrBPxukr4O7vtArEAi9d60LfbkFuTZ&tailored_ads=true&ad_tracking=true

At least this must be whitelisted when "Allow Affiliate & Tracking Links" is selected.

**Comment by emilstahl** [comment]
+1 as it breaks all links via Twitter apps _and twitter.com._

**Comment by romaincointepas** [comment]
Twitter switch between `t.co` and `analytics.twitter.com` for redirects to third-parties, not sure what's their logic behind this.

Added to Allow Affiliate & Tracking Links.
