### ISSUE TITLE
Separate ad and tracker lists

### ISSUE THREAD

**Issue by teohhanhui** [nextdns/metadata#147]
As a user, personally I don't care about being tracked, and indeed as a programmer I'd hate to cause things like telemetry / monitoring / analytics to be blocked.

Also, blocking trackers breaks too many things, see for example #144 and #146.

**Comment by romaincointepas** [comment]
Most popular blocklists combine the 2 so it would be hard to divide it that way.

Ideally, the NextDNS blocklist and a few popular others considered safe should not blocked anything that breaks things.
