### ISSUE TITLE
Threat Intelligence -> New List

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#148]
https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt

Compared to the one already present (which is to be kept) this list contains all the domains that have passed through urlhaus

**Comment by romaincointepas** [comment]
Do you know the difference between the list you're suggesting and the official https://urlhaus.abuse.ch/downloads/hostfile?

**Comment by scafroglia93** [comment]
Original contain the top domain inside 48 hours

The new one is a fork with all the domain transit from urlabuse

We have more coverage

**Comment by romaincointepas** [comment]
Got it, sorry I misread your initial post where you explained that.

It's already included in TI feeds, closing.
