### ISSUE TITLE
joyreactor.cc and fastpic.ru - false positives

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#150]
Hello,

**joyreactor.cc** is blocked for cryptojacking, but there no cryptjacking anymore. This is russian Reddit analog - please, unblock it.

**fastpic.ru** is blocked in porn category, but this is russian imageshack analog. Please, confirm it and unblock too.

Cheers!

**Comment by romaincointepas** [comment]
`fastpic.ru` doesn't seem to be blocked by porn anymore, probably fixed upstream.
