### ISSUE TITLE
EnergizedProtection - Whitelist

### ISSUE THREAD

**Issue by emilstahl** [nextdns/metadata#155]
Implement
https://raw.githubusercontent.com/EnergizedProtection/unblock/master/basic/formats/domains.txt (mentioned in #131)

This will fix the blocking part of #140.

**Comment by romaincointepas** [comment]
Isn't this whitelist automatically applied to all their blocklists?

**Comment by emilstahl** [comment]
@romaincointepas Does not seems like it, since Simply.com is being blocked by NextDNS, because it is the EnergizedProtection Regional list? (#140)
 
Simply.com is in the linked unblock file (and the adguard whitelist, #145)

**Comment by scafroglia93** [comment]
@emilstahl 
At the moment energized is not maintained properly, I tried it but there were more false positives than sites blocked for malware and other malicious operations

**Comment by scafroglia93** [comment]
eenrgized is dead atm and it's bad mantained

**Comment by michaelb-ae** [comment]
> eenrgized is dead atm and it's bad mantained

yes and no, on github it's dead on their website energized.pro, the list is updated every day it seems the bot don't update github and 1 they don't have seen it, 2 they don't care
