### ISSUE TITLE
[Chinese] https://github.com/privacy-protection-tools/anti-AD

### ISSUE THREAD

**Issue by dorawei** [nextdns/metadata#157]
https://github.com/privacy-protection-tools/anti-AD
It says it's the most accurate list for Chinese community

**Comment by whatdafoxsay** [comment]
i actually find this list better than the other 2 Chinese list, i have been using it in adguard home with nextdns DOH.

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/3d2a01a3c4a7c47d28c6f9bed2c14d78e93ec5e7, thanks!
