### ISSUE TITLE
new list -> threat intelligence -> quidsup notrackak-malware

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#160]
malware ->
https://gitlab.com/quidsup/notrack-blocklists/-/blob/master/notrack-malware.txt

**Comment by romaincointepas** [comment]
Already there.

**Comment by beerisgood** [comment]
Just a info:

This list is already added in https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json but use the following URL:
https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
instead of the URL with a extra "-" in this issue.

**Comment by scafroglia93** [comment]
this was my issue
