### ISSUE TITLE
Add direct links to the raw filter lists to user interface

### ISSUE THREAD

**Issue by 894-572** [nextdns/metadata#165]
I prefer inspecting the lists before installing. The linked homepages (`https://my.nextdns.io/id/privacy`) such as unchecky.com don't necessarily display the respective list anywhere (I didn't find from the entire Unchecky website) and for NextDNS you must browse this repository.

![Screenshot_2020-04-23 Privacy - My First Configuration - NextDNS](https://user-images.githubusercontent.com/44001490/80136932-f7101580-8591-11ea-9488-a05ce2cf04ea.png)

**Comment by romaincointepas** [comment]
We may add this later. Closing as it's not related to this repo (https://reddit.com/r/nextdns is better for feature suggestions like this).
