### ISSUE TITLE
new list -> threath intelligence -> dga feeds

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#166]
https://osint.bambenekconsulting.com/feeds/dga-feed.txt

**Comment by emilstahl** [comment]
NextDNS already uses his C2 list. I agree this should be added too 👍🏻

**Comment by romaincointepas** [comment]
Already used by `Security -> Domain Generation Algorithms (DGAs) Protection`.

**Comment by beerisgood** [comment]
> Already used by `Security -> Domain Generation Algorithms (DGAs) Protection`.

Can't find this list in https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json

**Comment by lyrad87** [comment]
@romaincointepas can you maybe reopen this issue? You use [https://osint.bambenekconsulting.com/feeds/c2-dommasterlist-high.txt](https://osint.bambenekconsulting.com/feeds/c2-dommasterlist-high.txt) but you should also include the list mentioned above: [https://osint.bambenekconsulting.com/feeds/dga-feed.txt](https://osint.bambenekconsulting.com/feeds/dga-feed.txt). They are not the same and both should be included.
