### ISSUE TITLE
Add Switzerland and Scumware filter lists

### ISSUE THREAD

**Issue by deletescape** [nextdns/metadata#168]
Add my two original lists, one for [Switzerland](https://raw.githubusercontent.com/deletescape/noads/master/lists/add-switzerland.txt), and the other one for ["Scumware"](https://raw.githubusercontent.com/deletescape/noads/master/lists/fo-scumware.txt) (this one completely breaks android apps by various very shady entities)

**Comment by scafroglia93** [comment]
can it cause malfunctions to apps ?

**Comment by romaincointepas** [comment]
I'm seeing `photogrid.org` in Scumware, not reassuring. Also, aside from a few exceptions, we like to stick to domains or hosts file format.

**Comment by deletescape** [comment]
Photogrid was bought up by Cheetah Mobile quite some time ago, but understandable that this might not be entirely fitting for this project :)

**Comment by scafroglia93** [comment]
@romaincointepas 
Couldn't you put it the same way as No Google?

No Google prevents all Google-related services from functioning
