### ISSUE TITLE
Able to import domains in Whitelist/Blacklist tab

### ISSUE THREAD

**Issue by cbuijs** [nextdns/metadata#17]
Import domains with an upload-file feature.

See also #12

**Comment by DaBomby** [comment]
I would add that the abilit to export my blacklist and whitelist would be great too!

**Comment by romaincointepas** [comment]
Are we talking about importing a manually built private blacklist/whitelist over the years or a public list that is not (yet) available in Lists?

If it's the former, how many domains are we talking about approximately?

**Comment by cbuijs** [comment]
@romaincointepas 
Both, but uploading personal curatted/personal lists as a first pick if needed to prioritize. I would say be able to upload up to 10.000 domains in total? Not sure what the maximum is of the blacklist/whitelist tab is today?

**Comment by romaincointepas** [comment]
Importing a massive amount of domains (like a custom blocklist, or a blocklist that's not available) will probably never be possible for technical/performance/costs reasons.

Migrating a few dozens domains quickly would make sense though, so that's something that we could add soon.
