### ISSUE TITLE
[Feature Request] Block Disqus

### ISSUE THREAD

**Issue by specter78** [nextdns/metadata#177]
The "Websites, Apps & Games" category can provide blocking of Disqus and other similar comment plug-ins (another example https://vuukle.com). These plug-ins are privacy nightmare, collecting as much data as possible.

**Comment by romaincointepas** [comment]
Ideally, we should have a separate feature under Privacy, something like "Block social buttons and comments plugins".

**Comment by specter78** [comment]
That would be a lot better.

**Comment by specter78** [comment]
> Ideally, we should have a separate feature under Privacy, something like "Block social buttons and comments plugins".

@romaincointepas When will this feature be implemented?
