### ISSUE TITLE
Tracking - https://github.com/theerhan/fck_telemetry

### ISSUE THREAD

**Issue by theerhan** [nextdns/metadata#178]
Hello! Can add this list to BlockList?
https://github.com/theerhan/fck_telemetry

**Comment by vtsft** [comment]
so what do you want?

**Comment by vtsft** [comment]
cool list

**Comment by beerisgood** [comment]
I'm strongly against this list.
It has a lot of false positives and looks like the dev doesn't know what he do

**Comment by theerhan** [comment]
> 
> 
> I'm strongly against this list.
> It has a lot of false positives and looks like the dev doesn't know what he do

Is there something wrong? Only domains with trackers are listed

**Comment by amdruzen3600** [comment]
Hmm,good list!

**Comment by beerisgood** [comment]
> Is there something wrong? Only domains with trackers are listed
>
No. A lot of non-trackers are listed which even are needed for some services. Also you name that list a "anti-telemetry" list but even that is incorrect for these examples and others.

Examples:
go.microsoft.com
samsung.com
safebrowsing.googleapis.com

**Comment by theerhan** [comment]
> 
> 
> > Is there something wrong? Only domains with trackers are listed
> 
> No. A lot of non-trackers are listed which even are needed for some services. Also you name that list a "anti-telemetry" list but even that is incorrect for these examples and others.
> 
> Examples:
> go.microsoft.com
> samsung.com
> safebrowsing.googleapis.com

samsung devices sends telemetry to samsung.com
 with safebrowsing.googleapis.com google tracks to which sites you go
go.microsoft.com - sometimes windows connects to this domain

**Comment by beerisgood** [comment]
You don't know what you're talking about.

Go.microsoft.com is a redirection service.
It doesn't matter if windows connect to that or not as it's legit.

Safebrowsing: you can disable it if you don't care about security. It's not tracking nor telemetry. It's how such service works

**Comment by scafroglia93** [comment]
I'm with @beerisgood

**Comment by romaincointepas** [comment]
Closing, looking too much like an amateur blocklist. Open to discuss this again if/when it gains popularity.
