### ISSUE TITLE
(gambling site) https://www.casino.org/gambling/

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#179]
need block

**Comment by scafroglia93** [comment]
open an issue inside one of gambling list

**Comment by romaincointepas** [comment]
Can you open an issue at https://github.com/Sinfonietta/hostfiles/blob/master/gambling-hosts ?

**Comment by lyrad87** [comment]
Done, see https://github.com/Sinfonietta/hostfiles/issues/108
