### ISSUE TITLE
grainconnect.com

### ISSUE THREAD

**Issue by maghuro** [nextdns/metadata#181]
I think it's a false positive on thread intelligence feeds.
It was called directly from my router (not from a client) when performing a legit speedtest through speedtest.net

**Comment by scafroglia93** [comment]
uk fiber operator

**Comment by romaincointepas** [comment]
Appears in https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt

@scafroglia93 can you help?

**Comment by lyrad87** [comment]
I contacted the person behind the blocklist, so hopefully, it should be solved upstream soon. You don't need to do anything anymore, @scafroglia93 ;)

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/domain/grainconnect.com/relations

**Comment by scafroglia93** [comment]
fixed

**Comment by scafroglia93** [comment]
@maghuro 
it's ok
https://github.com/HorusTeknoloji/TR-PhishingList/pull/8

**Comment by maghuro** [comment]
Thank you very much!! Closing now
