### ISSUE TITLE
new list -> threat intelligence -> stamparm

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#183]
@stamparm is one of the best with regards to malicious domains.
It would be really useful to have his support within the TI lists

https://github.com/stamparm/maltrail/tree/master/trails/static ->
there are 3 sub section

Cheers

**Comment by stamparm** [comment]
Created a new malware-domains "blacklist", which will be updated on a daily basis:

https://raw.githubusercontent.com/stamparm/aux/master/maltrail-malware-domains.txt

Basically, all malware domains from Maltrail's `static/malware` will be pushed there. Anybody that is following the Maltrail development knows that each domain is hand picked and has a reference to report(s).

p.s. I wouldn't use Maltrail's `malicious` and `suspicious` domains for any kind of "blacklisting" as those domains are intended more for threat-analyst tracking purposes than for "blocking"

**Comment by scafroglia93** [comment]
WoW that's insane

You chane my day

**Comment by scafroglia93** [comment]
@romaincointepas add this right now :)

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/a1550d747def5e19a2821fbf529e707f7a8ec7e3, thanks @stamparm for the combined list.
