### ISSUE TITLE
cdn.adc.eamobile.com blocked false positive

### ISSUE THREAD

**Issue by farmerchris** [nextdns/metadata#184]
cdn.adc.eamobile.com Was blocked today by the nextdns-recommenced list. This domain is required to successfully log in to Simpsons Tapped Out mobile game.

**Comment by scafroglia93** [comment]
https://raw.githubusercontent.com/vokins/yhosts/master/hosts

**Comment by scafroglia93** [comment]
fixed

**Comment by romaincointepas** [comment]
@scafroglia93 thanks for helping out
