### ISSUE TITLE
whitelist domains

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#186]
this are good domains, 

.referrer.disqus.com

*.realtime.services.disqus.com

*.c.evidon.com

*.static.ziffdavis.com

*.cdn.ziffstatic.com

please whitelist

**Comment by scafroglia93** [comment]
what liste are you using ?

**Comment by romaincointepas** [comment]
Those are all blocked by MANY popular blocklists, there must be a reason.

What does blocking them break exactly?

**Comment by ghost** [comment]
on downdetector and the dutch version the comment section of disqus

**Comment by romaincointepas** [comment]
Can you report those to the popular blocklists blocking them? We don't alter third party blocklists.
