### ISSUE TITLE
Bypass-methods don't include popular web proxys

### ISSUE THREAD

**Issue by mark4409** [nextdns/metadata#187]
I understand that there are countless numbers of these, but an attempt should at least be made to block the more popular ones that regularly appear on the first few pages of a quick google search. I have compiled my own list for now which hopefully you can make use off - at the moment, I'm using it with DNSCrypt. I haven't included www variants as DNSCrypt automatically blocks subdomains. My WIP list is at https://github.com/mark4409/Web-Proxy-VPN-DNS-Blocklists/blob/master/proxy-vpn-domains-raw.txt and also includes free VPNs and other proxy websites. I have compiled it by trawling through the first 10 pages of a few search engines, and also including domains listed in top x web proxy lists.

**Comment by scafroglia93** [comment]
fetch metadata -> make a diff with the actually list the go with PR

**Comment by mark4409** [comment]
I can have a go at doing that for sure... might take me a while to go through and seperate into VPN and Web Proxies.

There's a much bigger list I've just found over at https://blocklist.site/app/dl/proxy - are you allowed to use those blocklists? or are there licensing issues?

**Comment by mark4409** [comment]
I see a couple of pull requests already for this list  - mine has some overlap with those changes so am I better off waiting for those to go through first? Apologies if that's a silly question - I'm new to this.

**Comment by mark4409** [comment]
Alternatively, as I'm hoping to update my list regularly, I could split them into different files on my own repository and you could include them maybe? I've added another 30 sites to my list since submitting the PR.

**Comment by romaincointepas** [comment]
@mark4409 a bit late, but feel free to contribute to https://github.com/nextdns/dns-bypass-methods directly (we are splitting this monorepo).
