### ISSUE TITLE
Exclude from Recommended List

### ISSUE THREAD

**Issue by sacca97** [nextdns/metadata#188]
The domain **get3.adobe.com** is legit from adobe.

See: https://community.adobe.com/t5/flash-player/quot-get3-adobe-com-quot/td-p/5621354?page=1

**Comment by sacca97** [comment]
I saw the answer of the list mantainer but I can't understand, it's the **specific** adobe flash player update page you get redirected to from the updater:
https://get3.adobe.com/it/flashplayer/update/plugin/
I can't see the point in blocking that domain.

@romaincointepas can you whitelist it from nextDNS recommended?

**Comment by romaincointepas** [comment]
Done, thanks
