### ISSUE TITLE
Third-party domains shouldn't be blocked (by default)

### ISSUE THREAD

**Issue by dimqua** [nextdns/metadata#19]
I've noticed that the service blocks third-party domains such as `||ozon.ru^$third-party` in EasyList, as a result these websites couldn't be visited. This is a dangerous practice, IMHO.

**Comment by pe0mot** [comment]
Please explain why it's dangerous.

**Comment by dimqua** [comment]
Many popular lists are not intended to use with DNS-based adblockers, they focus on blocking ads in web browsers, that why they use more advanced adblock+ syntax, which supports many types of network rules. Those with `$third-party` modifier, block all third-party requests to specified domain. A third-party request is a request from different domain. For example, a request to `ozon.ru`, from `google.com` is a third-party request. But for a DNS server it's not possible to distinguish third-party requests from others. That's why there's always a chance to completely block certain domains (and subdomains), when there is no need.

Ideally, users should decide for themselves how the service should process different types of rules.

**Comment by bdougherty** [comment]
It's also dangerous because it requires adding domains to the whitelist, where there is no option but to allow _all_ subdomains (which could include tracking subdomains).

**Comment by romaincointepas** [comment]
We have the ability to exclude domains from lists (the exclusions folder on this repo).

So considering that most ABP-format lists use $third-party as default/lowest level, we either let a lot of stuff pass through, or we don't ignore `$third-party` and we manually exclude the few domains where there is value in not blocking the site itself.

@dimqua @bdougherty in your experience, do you think this affects a lot of domains?

**Comment by dimqua** [comment]
It depends on how many ABP-lists a person uses, I guess. Potentially, there's a lot of such rules (~25%, in my case), of course not all of them are valuable.

I don't use many lists in general, that's why in my case, it should be possible to go with a whitelist, but at the moment it's not possible to use your own whitelist, see: #17.

**Comment by dimqua** [comment]
> we either let a lot of stuff pass through, or we don't ignore $third-party

There's an another option, users can decide on per-list basis, if they also want to block third-party domains.

**Comment by romaincointepas** [comment]
We only keep the following for ABP lists:

```
||example.org^
||example.org^$third-party
||example.org^$popup
```

Or a combination of the last 2.

And if needed, we can whitelist.

We will add a visual warning on my.nextdns.io for ABP lists, and will prefer lists in hosts/domains format whenever available.

**Comment by krystian3w** [comment]
Last two is bad #https://github.com/nextdns/metadata/issues/459

**Comment by skapytek** [comment]
The last 2 options are nonsense.
for example https://github.com/nextdns/metadata/issues/459

shortpixel.ai^$popup is on easylist. Cause nextdns blocks them the whole domain is blocked and i cant access cdn.shortpixel.ai which is a cdn for wordpress optimised images.
Whitelisting is a very bad idea cause you need to whitelist every possible subdomain (who should report and whitelist all this domains?)

**Comment by skapytek** [comment]
I have also wrote you an email over a week ago and i still dont got an answer.
Very unsatisifed as a paying customer.

**Comment by skapytek** [comment]
> 
> 
> We only keep the following for ABP lists:
> 
> ```
> ||example.org^
> ||example.org^$third-party
> ||example.org^$popup
> ```
> 
> Or a combination of the last 2.
> 
> And if needed, we can whitelist.
> 
> We will add a visual warning on my.nextdns.io for ABP lists, and will prefer lists in hosts/domains format whenever available.

theres still not a warning

**Comment by S-a-l-a-d** [comment]
I was gonna create a new issue but have seen this one.
```
netdna-ssl.com
```
in **Liste FR**, used by Microsoft => https://blogs.windows.com
