### ISSUE TITLE
Piracy blocklist only includes torrent sites

### ISSUE THREAD

**Issue by mark4409** [nextdns/metadata#190]
The piracy blocklist only includes torrent websites at the moment. Are you open to expanding that with a more generic piracy list? If so, I'm happy to start working on something.

**Comment by romaincointepas** [comment]
Yep definitely, it's something we have been wanting to do!

**Comment by mark4409** [comment]
I made a start on a collection of lists that are growing rapidly and I'm actively maintaining. I'm utilising various directories and maintained lists on reddit as well as plain old search engine searches and the top million websites lists (not many legitimate sites with the word 'warez' in them). It's a bit laborious at the moment but I'm currently working on a series of scraper scripts so I can keep them up to date in a more automated way. I've tried to split them up as much as possible so people can pick and choose what they include. 

So how do you want to do this? You can either include my lists directly (they can be found at https://github.com/mark4409/DNS-Blocklists/tree/master/categories) or I can regularly put through PRs here to update one of your own lists?

**Comment by romaincointepas** [comment]
We've expanded/renamed our torrent-only repo:
https://github.com/nextdns/piracy-blocklists

It is and will stay MIT, we would love if you could contribute!

**Comment by mark4409** [comment]
Will do - I've had to take a little break away from this for a few weeks due to personal issues brought about by the pandemic. I've had barely a minutes free time. I'll hopefully be back on the case shortly though... I've finished a collection of scraper scripts to do the work for me - I just need to put it all together and then the whole thing should be automated (or at least semi-automated!)
