### ISSUE TITLE
New Blocklist suggestion : https://sebsauvage.net/hosts/hosts

### ISSUE THREAD

**Issue by amidj** [nextdns/metadata#191]
Hello,

Thanks for your amazing service.
Please add this weel maintained list from
https://sebsauvage.net/hosts/hosts

**Comment by scafroglia93** [comment]
most of this list are inside notracking and we have notracking inside of nextdns

**Comment by romaincointepas** [comment]
We avoid adding combined blocklists, except when they are very popular/reputable.
