### ISSUE TITLE
new lists -> malware -> fruxlabs TI

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#193]
Seeing the site I noticed that there are these two lists that could be inserted ->

- https://rescure.fruxlabs.com/maze.txt (maze ransomware)
- https://rescure.fruxlabs.com/rescure_domain_blacklist.txt (malicious domain)

good job

**Comment by romaincointepas** [comment]
Added

**Comment by beerisgood** [comment]
"https://rescure.fruxlabs.com/rescure_domain_blacklist.txt"

include the following false positive:
www.youtube.com

I already wrote them. Let's see how fast they fix that

@scafroglia93 
@romaincointepas
