### ISSUE TITLE
new lists -> suspicious -> suspiciois parking

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#194]
Source -> Palo Alto

Lists ->
https://raw.githubusercontent.com/pan-unit42/iocs/master/COVID-19%20IOCs/Proactive%20Registrations%20of%20Suspicious%20Parked%20Pages

**Comment by romaincointepas** [comment]
Probably redundant, and definitely risky (parked domains with covid in their name is not always malicious). Closing for now.
