### ISSUE TITLE
new lists -> kristintel -> malware (TI) ?

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#195]
lists ->

https://kriskintel.com/ktip_maze.txt
https://kriskintel.com/ktip_domain_blacklist.txt

Cheers

**Comment by romaincointepas** [comment]
Added.

**Comment by beerisgood** [comment]
Anyone know how we can contact them? Their [contact](https://kriskintel.com/#connect) is defect.

I ask because the "https://kriskintel.com/ktip_domain_blacklist.txt" use now more then 1 week the following invalid (for PiHole) domain:
`  шляхтен.рф`

@scafroglia93 
@romaincointepas
