### ISSUE TITLE
social tool blocked

### ISSUE THREAD

**Issue by td7902** [nextdns/metadata#196]
Meltwater.com is blocked by the Porn filter. This is a legit social tool site.

**Comment by scafroglia93** [comment]
If you have problems with a site you should check for the presence of the site in the lists you are using and, if it is present, open an issue to proceed with the removal

**Comment by td7902** [comment]
I cannot see which sites are in the porn category, but it was mentioned when trying to reach the site.
Is this the wrong place to open issues?

**Comment by scafroglia93** [comment]
https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/porn.json

**Comment by scafroglia93** [comment]
@romaincointepas 
https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt

latest commit was made in September 2018; maybe we remove them ?

**Comment by td7902** [comment]
So I can just add the site to the exclusions list in your first link?
(sorry, newbie on github :) )

**Comment by romaincointepas** [comment]
Added.

@scafroglia93 old blocklists are okay for porn, most complete each others. Let's just whitelist for now.
