### ISSUE TITLE
Blocklists for 26,000 COVID-19 threats

### ISSUE THREAD

**Issue by speckz** [nextdns/metadata#197]
Hi,

I was wondering if you would consider adding [https://www.cyberthreatcoalition.org/blocklist](https://www.cyberthreatcoalition.org/blocklist).

Thank you

**Comment by lyrad87** [comment]
This is already included in the Threat Intelligence Feeds: [https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json](https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json)

**Comment by speckz** [comment]
Great, how do I ensure that the Threat Intelligence Feed is enabled?

**Comment by speckz** [comment]
Derp! Nevermind, it's the first item on the Security tab.
