### ISSUE TITLE
Cyber volunteers release blocklists for 26,000 COVID-19 threats

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#198]
The COVID-19 Cyber Threat Coalition has released a block list of known URLs and domain names associated with Coronavirus-themed scams, phishing attacks, and malware threats.

The coalition is a volunteer organization created towards the end of March 2020 to disseminate information about new threats trying to take advantage of the Coronavirus pandemic.

This COVID-19 Cyber Threat Coalition consists of members from the cybersecurity community, large companies, cyber intelligence firms, and antivirus vendors who use the collected information to protect businesses, consumers, government, and healthcare organizations from online attacks.

please add the lists : https://www.bleepingcomputer.com/news/security/cyber-volunteers-release-blocklists-for-26-000-covid-19-threats/

https://blocklist.cyberthreatcoalition.org/vetted/url.txt
https://blocklist.cyberthreatcoalition.org/vetted/domain.txt

**Comment by romaincointepas** [comment]
This has been included in the Threat Intelligence Feeds for a month now, among many other reputable COVID-related blocklists :)
