### ISSUE TITLE
Allow Affiliate Tracking Links

### ISSUE THREAD

**Issue by BevanC** [nextdns/metadata#199]
I have 'Allow Affiliate Tracking Links" switched to on, but some still dont work eg https://www.pepperjamnetwork.com/tracking/cookie.php?data=UFFPUlNYWVJQT09WWFVXUE9ZV1dWVllRTFJRUU9UVA&tarurl=https%3A%2F%2Fwww.senreve.com%2F%3Futm_source%3Dpepperjam%26utm_medium%3Daffiliate%26utm_campaign%3D120349%26clickId%3D3100796810&tracking=Dynamic - is there a way to allow these links too?
--

**Comment by romaincointepas** [comment]
Added
