### ISSUE TITLE
Intelligence threads feeds false positive

### ISSUE THREAD

**Issue by maghuro** [nextdns/metadata#201]
pdesaa.cimaa.pt (local company sub website)

**Comment by romaincointepas** [comment]
Blocked by https://gitlab.com/curben/urlhaus-filter/-/raw/master/urlhaus-filter-domains.txt, can you check with them?

@scafroglia93

**Comment by lyrad87** [comment]
I created a ticket for it, see [https://gitlab.com/curben/urlhaus-filter/-/issues/13](https://gitlab.com/curben/urlhaus-filter/-/issues/13). You don't need to do it anymore, @scafroglia93 :)

**Comment by curbengh** [comment]
Maintainer of https://gitlab.com/curben/urlhaus-filter here

I've added to exclusion list. Blocklist will be updated in 8 hours.

The website is added by https://urlhaus.abuse.ch/url/452/ and it shows the malware URLs are already offline. Offline URLs are excluded in "urlhaus-filter-domains-online.txt"; this blocklist has fewer false positive (compared to "urlhaus-filter-domains.txt"), but online/offline status is not 100% reliable and may lead to false negative.
