### ISSUE TITLE
shengen.ru and eurodir.ru

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#208]
Hello,

I found two false positives in your threat intelligence list:
- shengen.ru - this is not malicious site anymore. This domain looks good and provides legal support for obtaining Schengen visa
- eurodir.ru - this is the technical domain of the hosting provider Eurobyte:
https://eurobyte.ru

Please, confirm that.

Thank you.

**Comment by lyrad87** [comment]
The 2nd domain doesn't seem to be blocked. The first one is also blocked via the dbl.oisd.nl blocklist.

**Comment by scafroglia93** [comment]
@ammnt 
https://www.virustotal.com/gui/domain/shengen.ru/relations

"this is not malicious site anymore" -> any documents for proving this ?

**Comment by ammnt** [comment]
@lyrad87
> The 2nd domain doesn't seem to be blocked. The first one is also blocked via the dbl.oisd.nl blocklist.

Its blocked by drp. My bad, sorry.

@scafroglia93
> "this is not malicious site anymore" -> any documents for proving this ?

I don 't answer stupid questions. We 're not in court🤦🏻‍♂️

@romaincointepas, who this guy? Is he a member of your team or a support officer? I 'm asking you now as your client. Thank you.

**Comment by scafroglia93** [comment]
@ammnt 

Before creating unnecessary confusion, would you be able to answer my question?

Why should you unblock a site that is still reported?

PS:
I'm a customers and contributor

**Comment by ammnt** [comment]
@scafroglia93

I 'm not saying you should unblock it. I asked you to check this information. What documents do you expect from me and on the basis of what? I 'm not a lawyer or a judge.

If the team decides to keep this domain blocked based on the VirusTotal report - I'm OK with that. But demanding documents for each domain from third parties makes no sense, I think. Don't you?

**Comment by romaincointepas** [comment]
There is an history for `make-money.shengen.ru`, `only-valium.shengen.ru` and similar, funky to say the least, especially when the allegedly new owners have some sort of catch-all in place.

`shengen.ru` is blocked by https://gitlab.com/curben/urlhaus-filter/-/raw/master/urlhaus-filter-domains.txt, can you see directly with them? @scafroglia93 can help, he has some experience with dealing with issues in upstream blocklists.

`eurodir.ru` is not blocked by TI feeds anymore.

**Comment by scafroglia93** [comment]
@lyrad87 can you check it (i don't have gitlab account)

**Comment by lyrad87** [comment]
Done, see https://gitlab.com/curben/urlhaus-filter/-/issues/14

**Comment by lyrad87** [comment]
Update: `shengen.ru`has been excluded from [ https://gitlab.com/curben/urlhaus-filter/-/raw/master/urlhaus-filter-domains.txt]( https://gitlab.com/curben/urlhaus-filter/-/raw/master/urlhaus-filter-domains.txt) but currently remains blocked by `dbl.oisd.nl`.

**Comment by lyrad87** [comment]
Update 2: also been whitelisted by `dbl.oisd.nl` now

**Comment by ammnt** [comment]
Thanks for the help everyone! 😘
