### ISSUE TITLE
Santander phishing website

### ISSUE THREAD

**Issue by CyanoTex** [nextdns/metadata#209]
https://netbanco-particulares.pt.nets-dk.co/v/PLZ/#

**Comment by scafroglia93** [comment]
hi, it's already block by google protection

**Comment by CyanoTex** [comment]
> hi, it's already block by google protection 

Oh, looks like the robots over there are quick to pick up on that stuff.

**Comment by romaincointepas** [comment]
We try to avoid maintaining a manual blocklist for TI Feeds, could you reach out to any of the public feed we include?

See https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json
