### ISSUE TITLE
whitelist from porn category

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#214]
freenom.link

![image](https://user-images.githubusercontent.com/19517680/81605708-17e2c280-93fc-11ea-919f-b305a302146a.png)

**Comment by scafroglia93** [comment]
have you check the list ?

**Comment by lyrad87** [comment]
It's included in [https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt](https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt). @3xploiton3, can you please see with them so that they can fix it on their side?

**Comment by lyrad87** [comment]
@romaincointepas Same issue as #239 The last update for that list was done 2018 so I wouldn't hold my breath that it gets excluded from the list. Maybe you can whitelist it instead?
