### ISSUE TITLE
false positive mywot.com

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#215]
![image](https://user-images.githubusercontent.com/19517680/81608899-30091080-9401-11ea-8ca8-810809eee0c6.png)

**Comment by scafroglia93** [comment]
have you check the list ?

**Comment by lyrad87** [comment]
It's also blocked by [https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts). @3xploiton3, can you please check with them so that it's fixed upstream?

**Comment by FadeMind** [comment]
Web Of Trust developers selling collected data:
http://thehackernews.com/2016/11/web-of-trust-addon.html
http://www.ghacks.net/2016/11/01/browsing-history-sold/
If you don't care about your privacy - whitelist this. 🤷‍♀️

**Comment by lyrad87** [comment]
Thank you for your insight! :) Not going to whitelist it personally but maybe that's the best action forward, @3xploiton3

**Comment by romaincointepas** [comment]
We're going to follow Steven Black on that one.
