### ISSUE TITLE
.AE WHOIS server is blocked by DGA

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#217]
Hello, @romaincointepas 

**whois.aeda.net.ae**

this WHOIS server of .AE top level domain is blocked by DGA Protection. Looks like a bug. Please, take a look:
https://www.iana.org/domains/root/db/ae.html

Thank you.

**Comment by ammnt** [comment]
The same thing for **whois.dot.cf** host😟

**Comment by lyrad87** [comment]
#211 is another false positive blocked by DGA

**Comment by ammnt** [comment]
Works fine now!
