### ISSUE TITLE
new lists -> scam -> Threat Intelligence -> Silverterrier

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#220]
Source ->
https://unit42.paloaltonetworks.com/silverterrier-2019-update/

List ->
https://raw.githubusercontent.com/pan-unit42/iocs/master/silverterrier/domains19.csv

(pull request was made for fix ", issue") ->
https://github.com/pan-unit42/iocs/pull/8

**Comment by beerisgood** [comment]
Sadly this list isn't PiHole compatible

**Comment by scafroglia93** [comment]
i can create a txt without problems

**Comment by scafroglia93** [comment]
added inside my blocklist
