### ISSUE TITLE
Matrix servers being blocked

### ISSUE THREAD

**Issue by Tuinslak** [nextdns/metadata#221]
Running a matrix.org server, I noticed quite a few (but not all) nodes being blocked by `threat-intelligence-feeds`. 

Not sure if it's a coincidence or if these nodes are involved in other dodgy stuff. 

For example:
```
fws.fr
matrix.fws.fr
winterfell.homeunix.com
matrix.wisellama.rocks
``` 
and several others (but these are most common).

Are Matrix servers being labeled as botnets?

**Comment by lyrad87** [comment]
Fwiw,
* `fws.fr`, `matrix.fws.fr` and `winterfell.homeunix.com` are being blocked by `threat-intelligence-feeds`, `dbloisdnl ` and `notracking`
* `winterfell.homeunix.com` is being blocked by just `threat-intelligence-feeds`

**Comment by romaincointepas** [comment]
We don't alter third-party blocklists, so feel free to open an issue with them directly.

For TI Feeds:
- `*.fws.fr` blocked by https://www.stopforumspam.com/downloads/toxic_domains_whole.txt
- `*.homeunix.com` blocked by https://raw.githubusercontent.com/cbuijs/shallalist/master/spyware/domains
- `*.wisellama.rocks ` blocked by https://raw.githubusercontent.com/HorusTeknoloji/TR-PhishingList/master/url-lists.txt

**Comment by Tuinslak** [comment]
oki thanks
