### ISSUE TITLE
new list: AttackVectors-Domain-List

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#222]
This list is designed to block phishing sites and other fake local journals domains.
These domains are also blocked by third party security extensions, such as Bitdefender Trafficlight but for those that do not want to install these extensions, this list can be used instead.

Found on WaLLy3K/wally3k.github.io#103

**Comment by romaincointepas** [comment]
Not super convinced about that one, it's just paid advertising looking like news, not a nice thing to do, but not a threat or privacy intrusion.
