### ISSUE TITLE
sahte pdf siteleri engelleyici - hosts listesi (fake [malicious/selling Public Domain lit/profiting from ads] pdf site blocker)

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#223]
Not a general ad-blocking list; however this hosts file is (100%) unique. It served one purpose: "**reklam amaçlı ve sahte içerikli pdf sitelerini engelle**". It essentially translates into '**block pdf sites with advertising and counterfeit content**' in English.

`https://gitlab.com/anarcho-copy/block-fake-pdf-sites.git`

`https://gitlab.com/anarcho-copy/block-fake-pdf-sites/-/raw/master/hosts`

**Comment by romaincointepas** [comment]
I don't think this fits TI Feeds, and not popular enough (0 stars) to make it as a Blocklist. Closing for now, we can revisit later.
