### ISSUE TITLE
Add more Energized lists once their hosting transition is complete

### ISSUE THREAD

**Issue by RacerDuke** [nextdns/metadata#233]
Hi there, I wanted to chime in regarding Energized. According to their Telegram group, they are in transition to a new host due to Github limitations. The Telegram group can be found here https://t.me/EnergizedProtection with all the relevant updates/info. 

Anyway, once they get the new host up and running, I suggest their remaining lists be added as long as there are no issues doing so. Thank you for your time!

**Comment by scafroglia93** [comment]
@romaincointepas 

For information only ->
These blocklists are the same ones that accused me of working for nextdns by sponsoring the service for a fee

All of this is truly ridiculous; they come to ask to change the pointing to their service

**Comment by romaincointepas** [comment]
Done in https://github.com/nextdns/metadata/commit/1b54cd635ef678da9e8f7565a605f82bd3c2551d
