### ISSUE TITLE
yhosts: new mantainer 

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#236]
old ->
https://github.com/vokins/yhosts

new ->
https://github.com/VeleSila/yhosts

old url ->
https://raw.githubusercontent.com/vokins/yhosts/master/hosts

new url ->
https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts.txt

**Comment by romaincointepas** [comment]
Fixed in https://github.com/nextdns/metadata/commit/4658cd04ba5a0452cc4d3db691f94e67d9d83172
