### ISSUE TITLE
only adblock lists

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#237]
https://v.firebog.net/hosts/AdguardDNS.txt
https://adaway.org/hosts.txt
https://v.firebog.net/hosts/AdguardDNS.txt
https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
https://v.firebog.net/hosts/Easylist.txt
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts

are these added?

**Comment by lyrad87** [comment]
Some of them are directly available via the blocklist list on the page (like Disconnect, Anudeep, Adaway, Unchecky). Just cross-check the urls [here](https://github.com/nextdns/metadata/tree/master/privacy/blocklists). Others are included via other blocklists.
