### ISSUE TITLE
Exclude dickssportinggoods.com from porn list

### ISSUE THREAD

**Issue by rsyring** [nextdns/metadata#239]

**Comment by lyrad87** [comment]
@rsyring It's blocked by https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt. Can you contact them, so that they can fix it?

**Comment by lyrad87** [comment]
A ticket has already been created, see https://github.com/mhxion/pornaway/issues/7
The last update was done 2018 though so I wouldn't hold my breath that it gets excluded from the list. @romaincointepas maybe you can whitelist it instead?
