### ISSUE TITLE
Messaging apps blocked by "Social Networks" category

### ISSUE THREAD

**Issue by matrixik** [nextdns/metadata#242]
"Social Networks" category have this description: 

> Blocks all social networks sites and apps (facebook, instagram, tiktok, reddit, etc.). **Does not block messaging apps**.

But this list is blocking web version of Messenger.
I went to https://github.com/olbat/ut1-blacklists/blob/master/blacklists/social_networks/domains and it's blocking `fbcdn.net` and I understand why it's on this list but then this description is wrong.

For web version of Messenger to work only `xx.fbcdn.net` need to be whitelisted (so no whole `fbcdn.net`).

**Comment by matrixik** [comment]
Android version of Messenger also needed whitelisting `edge-mqtt.facebook.com` or it would be showing all the time "Waiting for connection" (take into account that I'm from Poland and don't know if this subdomain will be different in different countries).

**Comment by matrixik** [comment]
I said it too early, looks like for Android Messenger to work also `graph.facebook.com` needs to be whitelisted.

**Comment by matrixik** [comment]
Web version of WhatsApp also blocked: `web.whatsapp.com` by "Social Networks" category

**Comment by matrixik** [comment]
`telegram.org` is also banned with this list (so `web.telegram.org` is not working). But looks like Android app is working without whitelisting it and and don't see any logs from it on nextdns.io (maybe it's using some IP for all connections?).

**Comment by romaincointepas** [comment]
Thanks for the investigation, I excluded those domains (this category is indeed not supposed to break any messaging app).

**Comment by matrixik** [comment]
Thank you.

**Comment by Sidharth-Darwin** [comment]
LinkedIn is a social network platform, but isn't it necessary for most people? Maybe the list is for blocking social networks regardless of what they are used for, in which case its okay ig.
