### ISSUE TITLE
WindowsSpyBlocker (Spy) and / or UncheckyAds Windows installers ads sources. "breaks not for real" windows 10 network connection.

### ISSUE THREAD

**Issue by cocoflan** [nextdns/metadata#243]
One of this lists or both make windows believe there is no internet connection. 

There still is an internet connection if you look the old way via ipconfig or old control panel network settings.

It's the windows connection interface and network logo from windows 10 interface how is thinking there is no connection.

So i hope that it can be fixed in the lists.

Greetings

**Comment by romaincointepas** [comment]
We do not alter third-party blocklists, please report this to them directly!
