### ISSUE TITLE
List: "KAD - przekręty" + "KADFake"

### ISSUE THREAD

**Issue by MajsterMechazod** [nextdns/metadata#244]
`KAD list`: https://github.com/PolishFiltersTeam/KAD/blob/master/KAD.txt
`KADFake list`: https://github.com/PolishFiltersTeam/KAD/blob/master/KADfake.txt 
`GitHub`: https://github.com/PolishFiltersTeam/KAD

_KAD are Polish filters protecting against various types of scams and frauds, such as SMS subscriptions, viruses and fake shops._

**Comment by romaincointepas** [comment]
We already include https://github.com/PolishFiltersTeam/KADhosts/blob/master/KADhosts_without_controversies.txt in our TI feeds.
