### ISSUE TITLE
Phonearena.com blocked 

### ISSUE THREAD

**Issue by Laurisade** [nextdns/metadata#246]
Hello!

Seems that the whole domain is blocked. Please correct:)

www.phonearena.com
Blocked by blocklist:nextdns-recommended.

**Comment by lyrad87** [comment]
Blocked by [https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts](https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts) (`ads.phonearena.com`) and [https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt](https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt). I suggest you create a ticket in both repositories in order to get it unblocked, @Laurisade .

**Comment by romaincointepas** [comment]
Closing, we don't alter third party blocklists, feel free to open an issue like @lyrad87 said.

**Comment by carlylemiii** [comment]
Seems like an odd response. It's a list with your name/branding on it...if you're pulling from other sources why not take it out of your own list or work to get it removed from those other lists rather than putting the onus on users?

**Comment by carlylemiii** [comment]
What is the repo for the second list mentioned

**Comment by Laurisade** [comment]
Are you using https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt ?

**Disconnect response:**
Thank you for reaching out to us about this. The list you referenced was used in our legacy products, it is not maintained, has not been updated, and is not currently licensed by us. You can check our active main tracker list (linked below) which is used by partners such as Firefox.
https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json

So perhaps you'd need to update.

**Comment by Laurisade** [comment]
@romaincointepas could you please have a look at this?
I believe the NDNS recommended list contains old Disconnect's list :)

**Comment by romaincointepas** [comment]
We've removed those disconnect.me legacy blocklists from the recommended list.

Weird thing is, even if those lists are now deprecated, they were carefully built/maintained by disconnect and at some point and `phonearena.com` was consciously added.
