### ISSUE TITLE
cameleon list deprecated

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#247]
source ->
- https://github.com/WaLLy3K/wally3k.github.io/commit/7d8ec4c0e2a58b30bdc70a5559685153477a5c8b

- https://github.com/collinbarrett/FilterLists/issues/1626

**Comment by romaincointepas** [comment]
We will keep extremely popular (but deprecated) blocklists for a bit, and add a *deprecated* warning for them.
