### ISSUE TITLE
Economist.com login is getting blocked

### ISSUE THREAD

**Issue by lminer** [nextdns/metadata#255]
No matter what I do, I can't seem to login to the economist with nextdns enabled. I just keep getting the paywall. I've tried whitelisting economist.com and tinypass.com but it doesn't seem to help. Nothing else is showing up as blocked in the logs so not sure what else to do.

**Comment by lyrad87** [comment]
I can load the website just fine. Maybe it got fixed upstream by a blocklist you have added.

**Comment by lminer** [comment]
Oddly it seems to be working now. Maybe it was fixed.
