### ISSUE TITLE
Hide iOS status bar VPN icon 

### ISSUE THREAD

**Issue by bradenglund** [nextdns/metadata#256]
Please add a toggle to the iOS app to provide an option to hide the VPN icon in iOS status. It is possible to disable the VPN icon for NextDNS and reserve it for a "personal vpn" per the iOS settings.

DNSCloak has a switch as seen here:
- https://github.com/s-s/dnscloak/blob/35c5aaee139ba13442933633c016b1970b144c81/src/partials/dnssettings/general.html#L32-L54
- https://github.com/s-s/dnscloak/blob/35c5aaee139ba13442933633c016b1970b144c81/src/js/dnssettings.js#L21-L30
- https://github.com/s-s/dnscloak/blob/9c9b5dbcede69756aa946944bdd96fe66fd1d43f/platforms/ios/DNSCryptAppExt/PacketTunnelProvider.m#L278-L290

**Comment by romaincointepas** [comment]
This is a less than ideal way of doing it (listening on 127.0.0.1), and would be less battery efficient. We are keeping this in mind though.
