### ISSUE TITLE
blazepizza.com login area blocked by list.

### ISSUE THREAD

**Issue by luisv5z** [nextdns/metadata#260]
To reproduce, enable NextDNS Recommended Ads & Trackers Blocklist then visit [blazepizza.com](https://blazepizza.com), click the login button.

**Comment by lyrad87** [comment]
I can't reproduce and I have it enabled. Maybe it got fixed upstream already.

**Comment by luisv5z** [comment]
Weird. I still can reproduce. Try using this link, [https://www.blazepizza.com/account/login](https://www.blazepizza.com/account/login)

**Comment by lyrad87** [comment]
You are right. It works for me at first but it throws an SSL error and once I click on "Continue", it shows that `api.punchh.com` is being blocked (in my case) by` Steven Black`, `notracking` and `NextDNS Recommended Ads & Trackers Blocklist`.

**Comment by romaincointepas** [comment]
@luisv5z Could you open an issue at https://github.com/StevenBlack/hosts for `api.punchh.com`?
