### ISSUE TITLE
Feature Requests for paid accounts.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#265]
Currently users have the choice to display a NextDNS block page instead of a standard, and oft annoying, `NXDOMAIN` loading (& loading). It's a nice feature, one that may be utilized to a further extent if a self-hosted (e.g. right here on GitHub or over @ GitLab) page could be used in place of the standard block page displayed by NextDNS.

Thank-you.

**Comment by romaincointepas** [comment]
If you don't turn on Block Page, we return `0.0.0.0` or `::`, not `NXDOMAIN`.

Custom block pages is in our todo.
