### ISSUE TITLE
Incorrectly flagged as malicious

### ISSUE THREAD

**Issue by medakk** [nextdns/metadata#267]
Hello, I run https://karthikkaranth.me and a user just reported that my website is listed as "flagged by an aggregated threat intelligence feed" on NextDNS. How can I get this status revoked? I can't think of anything malicious on my domain. I use Netlify for the hosting

**Comment by lyrad87** [comment]
You probably have to contact one of the list creators from [here](https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json) in order to get it fixed.

**Comment by medakk** [comment]
I found on the [TR Phishing List](https://github.com/HorusTeknoloji/TR-PhishingList) and have raised an issue there.

If anyone else has this issue, here's a script to figure out which list contains your domain: 
https://gist.github.com/medakk/665f96b6d70adc7a25381670eb04cb72

In any case, I think @nextdns should be providing a better way for domain owners to figure out why their domain is being flagged.

**Comment by romaincointepas** [comment]
We've decided to remove that list from TI feeds (way too many false positives).
