### ISSUE TITLE
[User Defined] Custom Websites, Apps & Games

### ISSUE THREAD

**Issue by valaria247** [nextdns/metadata#268]
**Problem Description**

Currently users only able to block services provided by nextdns otherwise need to request or PR to this repository. Some unpopular services may even get promoted due wide use of nextdns platform.

**Proposed Solution**

Let users to add custom websites, apps & games.

- Tap > Add new service
- Add service name (First capital letter use as service logo)
- Add domains belong to particular service per row
- Done

![Screenshot_1](https://user-images.githubusercontent.com/64679174/84006447-f0e6c480-a998-11ea-9c42-5d0c1db1bdd0.png)

**Comment by romaincointepas** [comment]
We have no plans for this right now, using the Blacklist feature should work very well for this though.

Can I ask which Websites, Apps or Games are missing in your case?

**Comment by valaria247** [comment]
> We have no plans for this right now, using the Blacklist feature should work very well for this though.

I dont see that, blacklist feature suitable for block single or several domains but it doesn't help for preseve and maintain certain domains list belong to particular company or service.
You can bring "Websites, Apps & Games" component to seperate page with a tab name similar 'Block services' and let users to add their own. Above UI sample explain how it needs to be implemented and the rest, users able to edit or remove etc within web interface.

> We have no plans for this right now

If seems that kind of perfect then you can reopen the issue however this might be next level work compared to pihole etc rather than letting to add custom lists through remote url. 

> Can I ask which Websites, Apps or Games are missing in your case?

Well, those're not suitable for add into global nextdns webapp.

**Comment by valaria247** [comment]
If nextdns implement that, Eg: this will help us to add custom games, video stream services. next we can ask for an additional enhancement related parental control to restrict access for services based on time range.
