### ISSUE TITLE
PhoneArena should not be in default blocklist

### ISSUE THREAD

**Issue by carlylemiii** [nextdns/metadata#269]
www.phonearena.com should not be in NextDNS Recommended Ads & Trackers Blocklist. This is just a normal site.

**Comment by lyrad87** [comment]
Please their response in #246 re phonearena.

**Comment by r-a-y** [comment]
I'd strongly recommend removing the legacy Disconnect lists and using their newer JSON source as per https://github.com/nextdns/metadata/issues/246#issuecomment-640651163.
