### ISSUE TITLE
[Block Bypass Methods] some doh and dot not blocked

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#272]
hello, 
i was configuring an DOH app for an older android and i have see in my nextdns log, some doh/dot isn't blocked by the block bypass methods can you add it to the list : 

unicast.uncensoreddns.org
doh.asecdns.com
doh.appliedprivacy.net
uncensored-dot.dnswarden.com
adult-filter-dot.dnswarden.com
ecs-doh.dnswarden.com
dns.keweon.center
adblock-dot.dnswarden.com

**Comment by romaincointepas** [comment]
Thanks!

Note: dnswarden.com is dead (those endpoints NXDOMAIN), so not added.
