### ISSUE TITLE
Change Disconnect list url in TI

### ISSUE THREAD

**Issue by lyrad87** [nextdns/metadata#273]
You are still using the legacy list `https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt` in your threat-intelligence-feeds which isn't maintained and hasn't been updated for a while.

The new links are 
`https://github.com/disconnectme/disconnect-tracking-protection/blob/master/entities.json` and `https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json`

**Comment by romaincointepas** [comment]
We are keeping the list (for now) because it contains `malware-check.disconnect.me`, which is checked by some systems.

The new links you mentioned are not security-related.

**Comment by lyrad87** [comment]
@romaincointepas Alright, while they may not be security-related and there's no need for you to change it for the TI, you should still change the URLs in the blocklist section though. If the old list is giving a false positive, it won't be fixed upstream anymore since the maintainer deprecated the list.
