### ISSUE TITLE
Remove TLS 1.0 and 1.1 for my.nextdns.io

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#274]
TLS 1.2 exist now for **12 years** and your server's even support TLS 1.3 so i don't see any reason to keep the old and insecure ones. If a random browser or client doesn't support that, it shouldn't connect to internet anyway.

Also because of that, all server got only a "B" ranking, instead of (without this problem) A+
https://www.ssllabs.com/ssltest/analyze.html?d=my.nextdns.io

**Comment by rs** [comment]
Fixed

**Comment by beerisgood** [comment]
Thanks!

your server now get "A+" ranking
Good work
