### ISSUE TITLE
Provide Two-Factor Authentication for my.nextdns.io

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#275]
With [WebAuthn](https://webauthn.io/) your site would be a lot safer.

User's can add normal 2FA or even use FIDO2 keys as password-less login.
Highly recommend

**Comment by aelisya** [comment]
i have emailed them recently and they have responded it in development process (for the two-auth at least), but i confirm i want it too (DNS is a very sensitive information so the security of our account must be as high as possible)

**Comment by romaincointepas** [comment]
Currently being worked on!

**Comment by beerisgood** [comment]
@romaincointepas after soon 1year, any update?
