### ISSUE TITLE
Improve DNS Anti-Spoofing

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#276]
With the [DNS Nameserver Spoofability Test](https://www.grc.com/dns/dns.htm) i test "*.dns.nextdns.io" and got the following:
![GRSecurity](https://user-images.githubusercontent.com/9625159/84594698-6d274f00-ae54-11ea-9b9a-6091e22139bc.jpg)

As you can see, under DNS Nameserver Access Details:
Alphabetic Case is "all lower". Better value is: "mixed" like in this result:

<img width="612" alt="better" src="https://user-images.githubusercontent.com/9625159/84594759-bf687000-ae54-11ea-9caa-ae955925f54e.png">

I don't know if it helps, but in Unbound this can be solved with that config:
```
sudoedit /etc/unbound/unbound.conf.d/pi-hole.conf

use-caps-for-id: yes
```

**Comment by rs** [comment]
This can create incompatibilities with some auth DNS.

**Comment by beerisgood** [comment]
Maybe it can then be added as opt-in ? So it's disabled by default but user can activate it.

**Comment by aelisya** [comment]
i must say i'm pretty with @beerisgood in this case, add this as a facultative opt-in under Security section must be an ideal solution.
Like that the user have the choice to use it or not.

**Comment by romaincointepas** [comment]
We will keep this in mind. Closing this, feel free to post on https://www.reddit.com/r/nextdns for feature requests.
