### ISSUE TITLE
Social networks does not block facebook mobile when it contain facebook.com domain

### ISSUE THREAD

**Issue by matrixik** [nextdns/metadata#277]
Looks like social networks list does not blocks mobile version of facebook even that it contain facebook.com domain. But when I enable facebook block in parental control it's blocked.

You can check it by enabling social networks list and NOT enabling facebook page parental control then opening in private windows or on mobile in browser https://m.facebook.com

**Comment by Voltairine-de-Cleyre** [comment]
> Looks like social networks list does not blocks mobile version of facebook even that it contain facebook.com domain. But when I enable facebook block in parental control it's blocked.
> 
> You can check it by enabling social networks list and NOT enabling facebook page parental control then opening in private windows or on mobile in browser https://m.facebook.com

**Blocking `star-mini.c10r.facebook.com` will block both `m.facebook.com` & `www.facebook.com` without clashing with the exclusions listed in the Social Networks category.**

**Comment by romaincointepas** [comment]
We use https://dsi.ut-capitole.fr/blacklists/index_en.php behind the Social Networks category, could you report that directly to them so it benefits everyone?

**Comment by Voltairine-de-Cleyre** [comment]
Shouldn't that be NextDNS' job?

**Comment by romaincointepas** [comment]
@matrixik I misread the original issue, we were actually excluding some subdomains of `facebook.com`, automatically removing any parent domains from that list. I manually added some facebook domains that should block only Facebook itself, tell me if that's better.
