### ISSUE TITLE
[Feature Request] Pre-configured Whitelist

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#278]
The idea is to create whitelist to activate (with the help of us of course).

Some list with minimum domain, for exemple a list of minimum domain needed to use YouTube with an accounts and another without, so like that if we enable no google we can use YouTube, for that i recommend to go to the list used in umatrix (they have list like YouTube with account, YouTube without account (for umatix mais convert them in whitelist must be feasible).

I have used YouTube exemple because YouTube is very difficult to replace.

**Comment by romaincointepas** [comment]
That feels to much of an edge case IMO, but feel free to discuss this with the community on our subreddit at https://www.reddit.com/r/nextdns.
