### ISSUE TITLE
Add remaining blacklists from Steven Black

### ISSUE THREAD

**Issue by paupin2** [nextdns/metadata#280]
You already have Steven Black's "Unified hosts" list, so I would say it qualifies as a "public and well maintained list".

It would be helpful to include the remaining lists from the same repository: [fakenews](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts), [gambling](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts), [porn](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts) and [social](https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts).

**Comment by romaincointepas** [comment]
We have our parental control tabs for things like that, Privacy -> Blocklists is only privacy/ads related.
