### ISSUE TITLE
[Feature Request] Provide one-click whitelisting

### ISSUE THREAD

**Issue by crsssl** [nextdns/metadata#283]
While NextDNS is running, I often have websites I want to navigate to, but cannot. I would need to

1. temporarily disable NextDNS, navigate to the site, and subsequently reenable NextDNS; or
2. go to my NextDNS Settings Panel to add the domain to the whitelist, and then navigate to the site.

Either way, this is cumbersome.

There should be a pop-up or a page+link provided within the browser to automatically add the domain to my whitelist. That, or provide a browse extension that lets me do this.

**Comment by romaincointepas** [comment]
We will be adding this feature to our blockpage soon.
