### ISSUE TITLE
false positive from threat-intelligence kasteelcoevorden.nl 

### ISSUE THREAD

**Issue by pilovali** [nextdns/metadata#284]
It looks like kasteelcoevorden.nl is being blocked by the threat intelligence.
The website is a normal website. I don't know why the threat intelligence gets triggered.

**Comment by lyrad87** [comment]
Blocked by https://raw.githubusercontent.com/mitchellkrogza/Phishing.Database/master/phishing-domains-ACTIVE.txt. You may want to contact them to get it fixed upstream.

**Comment by pilovali** [comment]
Alright, thx.

**Comment by romaincointepas** [comment]
Closing, as this should/will be fixed upstream.
