### ISSUE TITLE
cbsnews.com not playing video on Chrome

### ISSUE THREAD

**Issue by Mezito80** [nextdns/metadata#285]
I've noticed on cbsnews.com that all videos and the livestream news will not play.

Also on cbs.com, I am a subscriber, it says that adblocking software will not allow the video to load, but I don't use an adblocker program, just NextDNS.

**Comment by romaincointepas** [comment]
Could you post on our subreddit https://www.reddit.com/r/nextdns so the community can chime in? Also, check your NextDNS logs, one of the blocklists you're using could be too aggressive.
