### ISSUE TITLE
False positive: Social Networks

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#288]
**`zillow.com`** is a real estate site; it has nothing to do with social networks.

**Comment by romaincointepas** [comment]
It's blocked by the `social_networks` list from https://dsi.ut-capitole.fr/blacklists/index_en.php, could you reach out directly to them?

@scafroglia93 Can you help?

**Comment by Voltairine-de-Cleyre** [comment]
Yes, I will reach out to them directly. I apologize for my absence.
