### ISSUE TITLE
Update Spamhaus Top 10 List

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#289]
**The Spamhaus Top 10 is, from one to ten, as of 14-06-2020:**
```
.rest
.tk
.gq
.fit
.ml
.work
.cf
.ga
.cn
.asia
```
- The list prior had `.cn` at `#10` & did not include `.asia`. 
- Which leads me to what would likely be more appropriately posted as a separate issue. https://github.com/nextdns/metadata/issues/290#issue-643418291
- Nevertheless, the Spamhaus Top 10 has undergone *at least* one other change between the current list & the list included with NextDNS)

**Comment by Voltairine-de-Cleyre** [comment]
`29062020`
**The 10 Most Abused Top Level Domains**
As of 29 June 2020 the TLDs with the worst reputations for spam operations are:
```
1 | .tk | Badness Index: 4.99 | Domains seen: 21,109 Bad domains: 11,290 (53.5%)
2 | .rest | Badness Index: 4.37 | Domains seen: 2,656 Bad domains: 1,575 (59.3%)
3 | .fit | Badness Index: 4.17 | Domains seen: 18,023 Bad domains: 8,330 (46.2%)
4 | .gq | Badness Index: 3.89 | Domains seen: 5,678Bad domains: 2,782 (49.0%)
5 | .work | Badness Index: 3.62 | Domains seen: 45,557 Bad domains: 16,936 (37.2%)
6 | .ml | Badness Index: 3.43 | Domains seen: 9,185 Bad domains: 3,823 (41.6%)
7 | .ga | Badness Index: 3.40 | Domains seen: 8,543Bad domains: 3,551 (41.6%)
8 | .cf | Badness Index: 3.23 | Domains seen: 9,822 Bad domains: 3,843 (39.1%)
9 | .wang | Badness Index: 2.59 | Domains seen: 76,422 Bad domains: 19,970 (26.1%)
10 | .host | Badness Index: 2.25 | Domains seen: 4,914 Bad domains: 1,513 (30.8%)
```
```
cn = 20.2% bad (score 2.21) (2x abuse level of .us)
us = 12.0% bad (score 1.02) (2x the abuse level of .ir & 3x that of .ru)
ir = 6.1% bad (score 0.41)
ru = 4.1% bad (score 0.36)
```

**Comment by scafroglia93** [comment]
it would be better to remove it as it is constantly changing

**Comment by CyanoTex** [comment]
> it would be better to remove it as it is constantly changing

Is it theoretically possible to have the TLD Block function automagically update which TLDs are currently at the top?

**Comment by Voltairine-de-Cleyre** [comment]
> > it would be better to remove it as it is constantly changing
> 
> Is it theoretically possible to have the TLD Block function automagically update which TLDs are currently at the top?

Theoretically if NextDNS pays for Spamhaus' commercial service.

Even changing it weekly would be a welcomed addition. At the very least placing China Iran & Russia in alphabetical order with the rest of the TLDs is, I think, necessary for security reasons. How many people see them at the top & "flip the switch" to block, thinking that since they're at the top they must be dangerous? It would be interesting to find out.

**Comment by romaincointepas** [comment]
Updated, and we will try to keep this up to date as much as possible.

**Comment by Voltairine-de-Cleyre** [comment]
Thank-you. I'll be glad to help by posting updates from Spamhaus on a weekly / bi-weekly basis.

**Comment by jurriaan** [comment]
Seems like the current list is not up to date anymore, See https://www.spamhaus.org/statistics/tlds/
