### ISSUE TITLE
Place the TLDs .ru .cn & .ir where they actually belong.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#290]
In the Security section of NextDNS, above the Spamhaus Top 10 list are the TLDs for Russia, Iran & China. Perhaps they'd be better placed where they would be if not for the apparent lens of xenophobia. Now, as was mentioned in #289 , **`.cn`** is actually now ranked at 9, so it should be listed as such. However, neither `.ru` or `.ir` is even near achieving the statistics necessary for being listed in that top 10. In fact, if data were to be used instead of (???), `.us` is a (far more) abused TLD per Spamhaus' ratings compared to `.ru`:

- **.us = 10.3% bad (score 0.86)**
- **.ru = 3.8% bad (score 0.32)**
The United States TLD is nearly 3x more abused than Russia's TLD.

Continuing to use factors other than facts is not only promoting xenophobia to NextDNS users but is also promoting **insecurity** to NextDNS users.

**EDIT 29 June 2020:**
- `cn = 20.2% bad (score 2.21)` (no longer in top 10)
- `us = 12.0% bad (score 1.02)` (2x the abuse level of `.ir` & 3x that of `.ru`)
- `ir = 6.1% bad (score 0.41)`
- `ru = 4.1% bad (score 0.36)`

**Comment by scafroglia93** [comment]
+1

**Comment by romaincointepas** [comment]
Very valid point, and fixed.

We started with those as those were the most blacklisted TLDs (before we introduced that specific TLD feature)

**Comment by Voltairine-de-Cleyre** [comment]
Thank-you.
