### ISSUE TITLE
[New list] Youtube-ADS

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#292]
i propose to add this list to the sources : https://github.com/kboghdady/youTube_ads_4_pi-hole/blob/master/black.list
on github they said it can block youtube ads without break youtube and it's update daily).
So i propose to test it to see if its true.

and if it's true adding it to your list (or a new list only for youtube).

**Comment by romaincointepas** [comment]
We tested it, it doesn't work without breaking Youtube.
