### ISSUE TITLE
[Threat Intelligence Feeds] New list: CERT Poland

### ISSUE THREAD

**Issue by MajsterMechazod** [nextdns/metadata#294]
This is the official list of the Polish CERT team, which is updated every 5 minutes. Contains pages with any scams, e.g. fear of coronavirus (not fake-news), fake payment links. It is used by the largest Polish telecommunications operators such as Play, Plus, Orange, and T-Mobile -https://www.cert.pl/ostrzezenia_phishing/

`Text format:` https://hole.cert.pl/domains/domains.txt
`TSV format`: https://hole.cert.pl/domains/domains.csv
`JSON format`: https://hole.cert.pl/domains/domains.json
`XML format`: https://hole.cert.pl/domains/domains.xml

**Comment by scafroglia93** [comment]
@romaincointepas maybe inside TI section ?

**Comment by romaincointepas** [comment]
Thanks!
