### ISSUE TITLE
Missing domains from "Piracy" list

### ISSUE THREAD

**Issue by Refalm** [nextdns/metadata#297]
While testing the "Piracy" list, I noticed a few popular piracy sites missing:
https://katcr.co/
https://www.torlock2.com/
https://www.torrentfunk.com/
https://ettvtorrents.com/
https://btdig.com/
https://idope.se/
http://www.toorgle.com/
https://dirtytorrents.com/

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/bittorrent-blocklist/commit/76cc89a4ba6f6a41bf601d45e2bdaad558d7e9ae
