### ISSUE TITLE
[Native-Huawei] i catch something suspicious in huawei phone

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#298]
my huawei phone always connecting to this domain, it is safe?

    grs.dbankcloud.eu.home

    grs.dbankcloud.eu

    grs.dbankcloud.com

    cloudres-dra.dbankcdn.com

    grs.dbankcloud.cn

    openapi5.dbank.com

    appoptimize-dra.dbankcdn.com.home

    appdl2.dbankcdn.com

**Comment by romaincointepas** [comment]
Please ask this question on our subreddit https://www.reddit.com/r/nextdns so the community can chime in.
