### ISSUE TITLE
[request] how to block all domain

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#299]
i try block all keyword domain `dbankcloud.*` but didn't work

![image](https://user-images.githubusercontent.com/19517680/85910329-5a474e00-b848-11ea-97f3-ba6642baaec9.png)

**Comment by romaincointepas** [comment]
We don't support wildcards, you will have to enter all TLDs

**Comment by Voltairine-de-Cleyre** [comment]
> We don't support wildcards, you will have to enter all TLDs

A related question: how does the TLD `google` integrate with the (stated as necessary format) FQDNs within any combination of settings/lists? Wildcard support would be a good tool to have.
