### ISSUE TITLE
Games list is empty?

### ISSUE THREAD

**Issue by zzymurgy** [nextdns/metadata#3]
Are there any sites in the Games list? I can't see any in the code. Is this something that will be done in the near future, or will it be removed?
I would be happy to try to help.

**Comment by romaincointepas** [comment]
We couldn't find a reliable and complete blocklist for this. Not even sure it's possible to do it correctly to be honest (as this is way harder than simply categorizing websites).

**Comment by PoorPocketsMcNewHold** [comment]
There that one https://github.com/DandelionSprout/adfilt/blob/master/GameConsoleAdblockList.txt
And also that one, https://github.com/SweetSophia/androidappspihole if we talk mainly of blocking ads/trackers in games or games platform only.

**Comment by romaincointepas** [comment]
@PoorPocketsMcNewHold I think @zzymurgy was talking about the ability to block games themselves as a whole.

We will figure this out soon, and if we can't find anything good out there we will start our own list.

**Comment by PoorPocketsMcNewHold** [comment]
Because, There's that one, which is pretty extensive. Contains Video Games services (Steam, Origin, etc...) and game themselves.
https://gitlab.com/CHEF-KOCH/cks-filterlist/blob/master/hosts/Game.txt

**Comment by crssi** [comment]
Leave staff from CF alone and better find the source, which is more up-to-date.

https://github.com/ghacksuserjs/ghacks-user.js/issues/323

Cheers

**Comment by PoorPocketsMcNewHold** [comment]
> Leave staff from CF alone and better find the source, which is more up-to-date.
> 
> [ghacksuserjs/ghacks-user.js#323](https://github.com/ghacksuserjs/ghacks-user.js/issues/323)
> 
> Cheers

But first, You need to found the source, if it the case for that one.
Either you get no protection with the Games List, or you do get some, based of probably stolen scraping work.

**Comment by crssi** [comment]
Using lists from people as upper is highly irresponsible, since such can easily get modified by those personal agendas.
