### ISSUE TITLE
Re-opening issue re: Importing a massive amount of domains (like a custom blocklist, or a blocklist that's not available) will probably never be possible for technical/performance/costs reasons.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#306]
>  Importing a massive amount of domains (like a custom blocklist, or a blocklist that's not available) will probably never be possible for technical/performance/costs reasons.
  Migrating a few dozens domains quickly would make sense though, so that's something that we could add soon.

_Originally posted by @romaincointepas in https://github.com/nextdns/metadata/issues/17#issuecomment-584078898_

*If you'd allow me the honor of re/opening an issue* related to, or rather nearly exactly the same as, the issue that was closed due to the above stated reasons, I'd appreciate it. First of all, forgive me my ignorance of NextDNS's business income, and understand that any statements regarding (the reason of) cost given above, that I make are made from said place of ignorance. However, I sincerely hope (and would think) that people are actually paying the monthly or have already paid for year's plan and hope said revenue to expense ratio is positive.

That said:

- [x] Technical reasons: Allowing (at least) those of us who do have a paid plan to subscribe to `filter list x` or `filter list y` shouldn't be technically difficult unless we all share the same account (we don't) & appearance is all that differs (it's not). As it stands, this would *decrease* operating costs as it would reduce the amount of time spent looking at all the lists suggested by all of us for consideration to be included into the available list of lists from which to choose. It would also increase revenue since it is a feature that other services such as the above mentioned Pi-Hole, which is self created and maintained, yes, but still, and to use a comparable service, AdGuard (iOS, Android, Mac, Windows & AdGuard Home for those of us who prefer Linux). In fact, and as a workaround to not being able to subscribe to this list or that, I would highly suggest that people use a third party app such as AdGuard, AdGuard Pro or DNSCloak to connect to NextDNS via DoH or DNSCrypt (all three apps) or DoT (AdGuard & AdGuard Pro) depending on one's preference / mood (I'd use DoT but already use that in my router so I cannot use it on my devices, so I use DNSCrypt). Doing so allows you to use any filter subscription/s with the added functionality of NextDNS {my iPhone SE easily handles a combination of lists {(2 of my own, 1 of AdGuard's & a Greek 'ad block' list) that totals over 200 thousand distinct rules + (242017 ATM))}. If NextDNS focused on cleaning up the offered lists, changing the criteria initially used in choosing the offered lists (popularity via stars is one that I know of; quality has unfortunately been excluded unintentionally in the choice of ~25% of the available lists as popularity does not equal quality) & allowed for customization beyond what NextDNS currently allows - such as being able to subscribe to filter lists of (actual) choice as is opened in this issue - NextDNS would be a one stop shop, as goes the saying. Take that to your board. 😁
- [x] Reasons of cost: see the latter part of my argument made against the technical limitations. As I said in the beginning I cannot know your BI & thus cannot truly make a fact based argument re: cost. But ... but I know that if I pay for a service and additionally help contribute to it, I'd like to think the money spent was well spent and that I can reasonably expect that functionality that would be welcomed by the community is incorporated into the product. 👍🏼
- [x] Performance reasons: Really? We already have the ability to use millions of rules through a combination of the offered lists without any noticeable impact on performance. Allowing us to use a choice of any combination of pre-offered lists and others we want to use that aren't available in those pre-offered would reduce the number of total rules used per person (at least for the reasonable among us) as we'd have exactly what we need for our individual use cases. This would then, I would think, increase performance. All it is is a GET per list chosen and an update per list directions and a cache between updates. You'd even begin to see the bigger picture as to what people actually want to choose as opposed to what people have to want to choose. Given time, you'd be able to use that data to offset the data used in choosing the lists you currently offer & throw off dead weight while continuing to offer actively developed / maintained filter lists from which to choose for people using NextDNS. 🙂

Thank-you.

**Comment by scafroglia93** [comment]
I believe that the best solution is to rely on a list present in order to share information with the community.

Why on earth should I create my own list when I can share it with anyone through the present lists?

**Comment by Voltairine-de-Cleyre** [comment]
> Why on earth should I create my own list when I can share it with anyone through the present lists?

I'm not suggesting that you create your own list/s. The only reason two of those I use happen to be my own is that I've been maintaining both of them for over three years, close to four years actually. They each also have a loyal community of users from around the world, the highest concentrations of which are in the U.S. & Taiwan (going by communication I receive + visitors to my websites I use to host them, one of which acts as a mirror for my main site). I apologize for the lack of clarity in my comment that led to thinking otherwise.

Additionally, there are, e.g., an entire community of list maintainers over at https://filterlists.com as well as, obviously, the lists the site presents to people to choose & subscribe to.

Simply stated, what I am suggesting is a hybrid solution: a preselected offering of filter lists from NextDNS just like is currently present with the ability granted to users of/subscribers to NextDNS to choose from among the enormous variety of filter lists. If someone wants to subscribe to a list not present within the preselected offering of lists from NextDNS, why tell them they cannot? Moreover, I'm fairly certain that adding NextDNS's "icon" to lists that NextDNS is able to take advantage of, just like is currently done for uBlock Origin, AdGuard & several other formats of lists (hosts files, plain domains, etc.) would be a welcomed addition to FilterLists (specifically it's founder & main contributor: @collinbarrett & @DandelionSprout; both of whom I'm notifying for input on this specific part of the matter) and a great addition to the available formats. This would, additionally, have the end benefit of promoting NextDNS to a very large number of people who would otherwise not even know NextDNS exists.

**Comment by DandelionSprout** [comment]
Long story short: To add a software icon and sorting-category to FilterListsCOM, it's mandatory to support adding custom entries, and preferably even custom lists. This is also the reason why Brave Browser does not have an icon there either.

**Comment by romaincointepas** [comment]
Like mentioned many times before, we probably won't ever support this.

However, could you tell us more about:
- the current blocklists that you feel shouldn't be there (and why)
- the blocklists that are not currently available on NextDNS and why they should be

**Comment by Voltairine-de-Cleyre** [comment]
Energized, 1hosts, all of the unmaintained lists. False positives way too high in energized & not well maintained. 1hosts complete is the culprit, not the others. Again, too many false positives. I'm not going to go through each list to tell you, the developers of a network security product, what lists are appropriate & which are not.

**Comment by badmojr** [comment]
> Energized, 1hosts, all of the unmaintained lists. False positives way too high in energized & not well maintained. 1hosts complete is the culprit, not the others. Again, too many false positives. I'm not going to go through each list to tell you, the developers of a network security product, what lists are appropriate & which are not.

:()
The source code used to create all **1Hosts** filter/block lists is open source.
Feel free to fork it & create your own lists, with less false positives..

**Comment by Voltairine-de-Cleyre** [comment]
1. I meant the "Pro" version, this gives me the opportunity to state that. As this was in answer to a question regarding NextDNS, it relates to integration with NextDNS. If the NextDNS devs were to look through the sources for the "Pro" version, they'd see, among the dozens of sources (including unmaintained & archived sources) is in fact NextDNS's CNAME section of hosts. So, they are essentially reimporting their own source material.2. The "source code" used to crate 1hosts? What source code? Its a hodgepodge of other lists, as is stated in the commenting. Calling a filter list source code is misleading. Perhaps you meant to reference software you use to tie all the lists together? 3. I do maintain lists, however, as kind as the offer was, I'll refrain from "forking" 1hosts.I regret even answering the question; I thought Energized may be offended, not you.Moreover, I suspect that's the reason I was asked in the first place. Sent from ProtonMail Mobile On Sat, Jul 4, 2020 at 16:43, badmojr <notifications@github.com> wrote:  

Energized, 1hosts, all of the unmaintained lists. False positives way too high in energized & not well maintained. 1hosts complete is the culprit, not the others. Again, too many false positives. I'm not going to go through each list to tell you, the developers of a network security product, what lists are appropriate & which are not.

:()
The source code used to create all 1Hosts filter/block lists is open source.
Feel free to fork it & create your own lists, with less false positives..

**Comment by badmojr** [comment]
> 1. I meant the "Pro" version, this gives me the opportunity to state that. As this was in answer to a question regarding NextDNS, it relates to integration with NextDNS.
If the NextDNS devs were to look through the sources for the "Pro" version, they'd see, **among the dozens of sources (including unmaintained & archived sources) is in fact NextDNS's CNAME section of hosts**. So, they are essentially reimporting their own source material.

I don’t remember receiving a removal request, so they seem fine with me doing that.
If not, the team can simply stop including 1Hosts.
0 Fs given!

> 2. The "source code" used to crate 1hosts? What source code? Its a hodgepodge of other lists, as is stated in the commenting. Calling a filter list source code is misleading.  **Perhaps you meant to reference software you use to tie all the lists together?**

https://github.com/badmojr/code41Hosts

> 3. I do maintain lists, however, as kind as the offer was, **I'll refrain from "forking" 1hosts.**
I regret even answering the question; I thought Energized may be offended, not you.Moreover, I suspect that's the reason I was asked in the first place.

Be my guest!

**Comment by scafroglia93** [comment]
It is not entirely wrong, energized is just a script that assimilates all the lists without knowledge

**Comment by badmojr** [comment]
> It is not entirely wrong, energized is just a script that assimilates all the lists without knowledge

I’m not so sure about that..., but it’s really popular.
What do you suggest as an alternative?

**Comment by scafroglia93** [comment]
> > It is not entirely wrong, energized is just a script that assimilates all the lists without knowledge
> 
> I’m not so sure about that..., but it’s really popular.
> What do you suggest as an alternative?

https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

**Comment by badmojr** [comment]
> > > It is not entirely wrong, energized is just a script that assimilates all the lists without knowledge
> > 
> > 
> > I’m not so sure about that..., but it’s really popular.
> > What do you suggest as an alternative?
> 
> https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

Good for you!

**Comment by romaincointepas** [comment]
Closing this now.

@Voltairine-de-Cleyre Thanks for taking the time to argue your case, but as you probably guessed, making a great service is saying yes as much as sometimes saying no, and in that case, this is a no-go for many reasons.

Our approach for now is trying to make the most *popular* blocklists available at the click of a button, and offering denylist/allowlist for small adjustements. If you maintain your own blocklist that is not popular and absolutely need to use it, NextDNS is probably not for you. And if you feel we're missing a great blocklist, you can open an issue and we will consider adding it.

**Comment by scafroglia93** [comment]
Keeping a personal blocklist doesn't make sense, better to share it or to rely on some list like I did

**Comment by Voltairine-de-Cleyre** [comment]
> Closing this now.
> 
> @Voltairine-de-Cleyre Thanks for taking the time to argue your case, but as you probably guessed, making a great service is saying yes as much as sometimes saying no, and in that case, this is a no-go for many reasons.
> 
> Our approach for now is trying to make the most _popular_ blocklists available at the click of a button, and offering denylist/allowlist for small adjustements. If you maintain your own blocklist that is not popular and absolutely need to use it, NextDNS is probably not for you. And if you feel we're missing a great blocklist, you can open an issue and we will consider adding it.

Popularity =~ uniqueness; it's also a matter of GitHub v GitLab, as well as publicity (in the case of the No Facebook list, the maintainer wrote to Peter Lowe regarding it & as is well known, Peter Lowe's list & site are both very popular, thus the 2000+ stars on GitHub.

Regardless, it's not like I cannot use a third-party app & include other lists (not only my own, which despite a lack of stars, are popular & have been in development first on GitHub pre-Microsoft days & on GitLab after that sellout totaling ~4years) - in the case of `iVOID.hosts` & `DomainVoider`, the latter of which would require NextDNS to prune a subset of rules in much the same way it does any of the included AdGuard lists - that are not included due to being "unpopular". 

And, perhaps most importantly, I paid for a year's subscription in advance the day after it came out of beta. I liked the product & (wrongly) assumed development would continue in a direction desired by the user base as well as the NextDNS team.

**Comment by rs** [comment]
The development continues. Maintaining a service involve tasks that aren’t always visible to the users. It’s not because the feature you want is not released right away that the development stopped.

**Comment by Voltairine-de-Cleyre** [comment]
I will take that as a statement that the probability is non-nil that the feature will be released. Sent from ProtonMail Mobile On Wed, Jul 8, 2020 at 08:48, Olivier Poitrey <notifications@github.com> wrote:  
The development continues. Maintaining a service involve tasks that aren’t always visible to the users. It’s not because the feature you want is not released right away that the development stopped.
