### ISSUE TITLE
New profile copy from ...

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#308]
Since i'm using multiple profile, i have a function, it would be awesome for administrator. create a copy of another profile.

New -> we enter the name, and a new box whom profile we want to copy.

Like that the new profile have the same whitelist, blacklist, privacy, and security profile out of the box, all we have to do is add the change we want from this.

Thanks

**Comment by scafroglia93** [comment]
+1

**Comment by romaincointepas** [comment]
We may add this in the future (Duplicate configuration button in the Settings).
