### ISSUE TITLE
Add denylist from Warden 

### ISSUE THREAD

**Issue by ghost** [nextdns/metadata#309]
Hello, 

I read this beatiful artilce [https://forum.xda-developers.com/android/apps-games/warden-app-manager-t4122227](article) on XDA. 

Can you add their list, you can find it  [https://gitlab.com/AuroraOSS/AppWarden/-/blob/master/app/src/main/assets/trackers.json](here) or in the previous link, in order to protect our smartphone from trackers? 

Thanks for all!

**Comment by scafroglia93** [comment]
Nextdns cannot proceed with the block, you must send this request within one of the many lists present so that the maintainer can proceed by analyzing the request in order to avoid blocking the applications, making the phone unstable

**Comment by snowdenjohnch** [comment]
Ok, i see that links does not work so now I upload the list that i suggested:  https://send.firefox.com/download/2d10064b197b304b/#WydxB9-2SmZLtfpfT2PnBw

**Comment by scafroglia93** [comment]
Open a Pull Request inside this ->

https://github.com/notracking/hosts-blocklists
https://github.com/StevenBlack/hosts
https://github.com/anudeepND/blacklist

**Comment by snowdenjohnch** [comment]
I do it now, I hope in a correct way, I'm new on Github.

**Comment by romaincointepas** [comment]
Closing, thanks @scafroglia93 for assisting.
