### ISSUE TITLE
new list -> osint.digitalside.it

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#310]
url ->
https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt

**Comment by beerisgood** [comment]
Also listed on https://firebog.net/ and listed as "are least likely to interfere with browsing"

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/7b56796cad78a15357b7525708db9e6f234b5dea
