### ISSUE TITLE
Adding two ads sites

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#312]
```
https://runative-syndicate.com/

https://www.protectmobiletechieai.club/
```

Both are open annoying windows/ popups on a streaming site

**Comment by romaincointepas** [comment]
Could you recommend those to https://github.com/StevenBlack/hosts?

**Comment by beerisgood** [comment]
@romaincointepas done: https://github.com/StevenBlack/hosts/commit/ddafbadaf6d6fd0f34aa4ae8aa5668fa6601e94c
