### ISSUE TITLE
Add blocklist against (Google) Accelerated Mobile Pages (AMP) 

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#313]
_Block AMP pages with this list. Since I use DuckDuckGo, this list is pretty sparse and suggestions are welcome!_

From https://github.com/lightswitch05/hosts
`https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt`

**Comment by romaincointepas** [comment]
This feels too aggressive for us and doesn't really match our approach of not breaking things.

NextDNS automatically block subdomains, so blacklisting the following should be enough:
```
amp.cloudflare.com
ampproject.net
ampproject.org
```
