### ISSUE TITLE
Android Native Tracking Protection

### ISSUE THREAD

**Issue by 4oo4** [nextdns/metadata#315]
Wasn't sure if this was in the works or not, but it would be really nice to have the Native Tracking Protection feature for Android. To get an idea of what an Android phone is reaching out to, I turned on DNS logging on my stock Pixel phone, and came up with this. This is just a raw list from my phone with a few obvious ones removed (google.com, mail.google.com, etc.), but hopefully this is a good starting point for identifying which ones are used for tracking.

https://gist.github.com/4oo4/0cf0ba1d466cea5526606c0e90edcaa7

**Comment by beerisgood** [comment]
Your list isn't a tracking list. You should research the domains before publish it as "protection"

**Comment by romaincointepas** [comment]
As far as we know, there is no tracking/telemetry domain that can be blocked without breaking anything on unforked-Android. 

Closing, happy to reopen if that's the case.

**Comment by 4oo4** [comment]
@beerisgood I was upfront that it was a raw list of google domains I noticed and made no guarantee of protection. The only purpose was to start a conversation about it.

@romaincointepas Sad, but good to know.
