### ISSUE TITLE
Suggestion when using AdGuard Filters

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#316]
Knowing the limitations of NextDNS, rather than using the `.../extension/chromium/...` lists, using the
https://filters.adtidy.org/ios/filters/13_optimized.txt
(in the case of the Turkish Filter) or
https://filters.adtidy.org/ios/filters/15_optimized.txt
(in the case of the DNS filter)
would ease integration into NextDNS due to the optimized iOS lists lacking less (if not all) of AdGuard's advanced JavaScript functions.

https://github.com/nextdns/metadata/issues/304#issue-648414530

**Comment by Voltairine-de-Cleyre** [comment]
Whomever downvoted this does not understand the fact that NextDNS cannot handle AdGuard's JavaScript engine.

**Comment by romaincointepas** [comment]
Good point. It wouldn't really change much though, as we ignore DOM rules, whatever ends up being used *post NextDNS compilation* will be the same.

It does absolutely has to do with browser extensions vs. DNS-level blocking though.

**Comment by Voltairine-de-Cleyre** [comment]
> as we ignore DOM rules

Having just reread this thread when looking through posted issues, I noticed this phrasing. Ignoring DOM rules implies ignoring "strict blocking" of sites. Ignoring _all but DOM rules_ is the actual, technical case. 🙂
