### ISSUE TITLE
Netlab DGA

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#319]
URL ->

https://data.netlab.360.com/feeds/dga/dga.txt

https://data.netlab.360.com/feeds/dga/bamital.txt
https://data.netlab.360.com/feeds/dga/banjori.txt
https://data.netlab.360.com/feeds/dga/blackhole.txt
https://data.netlab.360.com/feeds/dga/ccleaner.txt
https://data.netlab.360.com/feeds/dga/chinad.txt
https://data.netlab.360.com/feeds/dga/conficker.txt
https://data.netlab.360.com/feeds/dga/cryptolocker.txt
https://data.netlab.360.com/feeds/dga/dircrypt.txt
https://data.netlab.360.com/feeds/dga/dyre.txt
https://data.netlab.360.com/feeds/dga/emotet.txt
https://data.netlab.360.com/feeds/dga/enviserv.txt
https://data.netlab.360.com/feeds/dga/feodo.txt
https://data.netlab.360.com/feeds/dga/fobber.txt
https://data.netlab.360.com/feeds/dga/gameover.txt
https://data.netlab.360.com/feeds/dga/gspy.txt
https://data.netlab.360.com/feeds/dga/locky.txt
https://data.netlab.360.com/feeds/dga/madmax.txt
https://data.netlab.360.com/feeds/dga/matsnu.txt
https://data.netlab.360.com/feeds/dga/murofet.txt
https://data.netlab.360.com/feeds/dga/mydoom.txt
https://data.netlab.360.com/feeds/dga/necurs.txt
https://data.netlab.360.com/feeds/dga/nymaim.txt
https://data.netlab.360.com/feeds/dga/omexo.txt
https://data.netlab.360.com/feeds/dga/padcrypt.txt
https://data.netlab.360.com/feeds/dga/proslikefan.txt
https://data.netlab.360.com/feeds/dga/pykspa.txt
https://data.netlab.360.com/feeds/dga/qadars.txt
https://data.netlab.360.com/feeds/dga/ramnit.txt
https://data.netlab.360.com/feeds/dga/ranbyus.txt
https://data.netlab.360.com/feeds/dga/rovnix.txt
https://data.netlab.360.com/feeds/dga/shifu.txt
https://data.netlab.360.com/feeds/dga/shiotob.txt
https://data.netlab.360.com/feeds/dga/simda.txt
https://data.netlab.360.com/feeds/dga/suppobox.txt
https://data.netlab.360.com/feeds/dga/symmi.txt
https://data.netlab.360.com/feeds/dga/tempedreve.txt
https://data.netlab.360.com/feeds/dga/tinba.txt
https://data.netlab.360.com/feeds/dga/tinynuke.txt
https://data.netlab.360.com/feeds/dga/tofsee.txt
https://data.netlab.360.com/feeds/dga/vawtrak.txt
https://data.netlab.360.com/feeds/dga/vidro.txt
https://data.netlab.360.com/feeds/dga/virut.txt
https://data.netlab.360.com/feeds/dga/xshellghost.txt

**Comment by romaincointepas** [comment]
Already in use (among other things) for our **Security -> Domain Generation Algorithms (DGAs) Protection** feature (we don't yet disclose publicly how we do that one though).
