### ISSUE TITLE
Suggestion: "Most Abused TLDs" as one button instead of many

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#321]
Currently this is the overview from "Security" - > "Block Top-Level Domains (TLDs)":
<img width="839" alt="default" src="https://user-images.githubusercontent.com/9625159/86963267-87f39780-c164-11ea-86ea-0e1aa23d93ed.png">

My suggestion is changing this to:
<img width="839" alt="change" src="https://user-images.githubusercontent.com/9625159/86963784-56c79700-c165-11ea-8edf-b69eb3772c3b.png">

This would be much more easier for user and less work for you guys as top domain's change over time. So a list which include these is less maintenance.

**Comment by romaincointepas** [comment]
Thanks for the suggestion, we have to improve this TLD selection window with search, ranking, etc.

Closing, could you keep feature suggestions for https://www.reddit.com/r/nextdns?
