### ISSUE TITLE
Found one strange TLD on a Google domain

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#324]
Hello,
Yesterday i was rapidly checking my history and a have found a very strange TLD on a Google domain i was ".getcacheddhcpresultsforcurrentconfig", i have immediately add it to the blacklist so i want to know if it's only me or if anyone already have seen it (if it's the case maybe add it to "security" tab with other TLD).

**Comment by quantumpacket** [comment]
From what I can gather this is something generated by older versions of Android?

Thread: https://lists.dns-oarc.net/pipermail/dns-operations/2018-December/018210.html

**Comment by aelisya** [comment]
maybe, i have spoted it on a profile where they only have windows 10 and android 10 (and 9), so, just in case i let it in my blacklist but maybe add it in tld under a 3rd name "not confirmed" or "unofficial" tld.

**Comment by romaincointepas** [comment]
This is not a valid TLD, it will never resolve except locally.
