### ISSUE TITLE
Remove some sources from threat-intelligence-feeds.json

### ISSUE THREAD

**Issue by sr093906** [nextdns/metadata#326]
Hi, some of the sources in the threat-intelligence-feeds.json hasn't been updated for more than three months and even suspended. Is it possible to remove them?

https://www.malwaredomainlist.com/hostslist/hosts.txt (Last updated: Wed, 22 Jan 20 12:15:23 +0000)
https://isc.sans.edu/feeds/suspiciousdomains_High.txt (SERVICE SUSPENDED)
https://malc0de.com/bl/ZONES (Last updated 2019-12-16)
https://github.com/Dawsey21/Lists/blob/master/main-blacklist.txt (Latest commit f1974f8 on Apr 15, 2018
)

**Comment by romaincointepas** [comment]
https://www.malwaredomainlist.com/hostslist/hosts.txt
For solid security feeds with a good reputation, we like to wait a few more months before deprecating them (there is no negative impact of keeping it).

https://isc.sans.edu/feeds/suspiciousdomains_High.txt
Temporarily suspended, from their website: "The lists will be empty until we find a way to resume this service."

https://malc0de.com/bl/ZONES
We could, as it's probably redundant anyway.

https://github.com/Dawsey21/Lists/blob/master/main-blacklist.txt
We found at least one malicious domain that was only caught by that list a few months ago. We will keep it until we can further investigate.

Side note, redundancies in feeds have no performance impact at all.
