### ISSUE TITLE
Replace Dawsey21's Spam404 Blocklist 

### ISSUE THREAD

**Issue by sr093906** [nextdns/metadata#327]
Thanks for your quick reply to my issue #326.

Could you explain why you choose to use an older version of Spam404 list at

https://github.com/Dawsey21/Lists/raw/master/main-blacklist.txt

not the newer one at 

https://github.com/Spam404/lists/raw/master/main-blacklist.txt

**Comment by romaincointepas** [comment]
For some reasons we had both, I removed the old version in https://github.com/nextdns/metadata/commit/f802c0df5bcd8999cc01523cf34408d689291391.
