### ISSUE TITLE
threat-intelligence-feeds is blocking google.com

### ISSUE THREAD

**Issue by lgrn** [nextdns/metadata#329]
I just noticed that google.com is being blocked for me. Inspecting the "logs" tab on my.nextdns.io shows that the lookup was blocked by "threat-intelligence-feeds". Without knowing much of how this works, I'm guessing one of the lists here include it and the whitelist needs to be expanded perhaps? https://github.com/nextdns/metadata/blob/3e33dcd5c4213ba30865210f84ec501300d89dda/security/threat-intelligence-feeds.json

**Comment by lgrn** [comment]
There was a change done recently, could this be caused by something like this being removed?

```
  "excludeTopFQDNs": true,	
  "excludeTopRootDomains": true,
```

Commit: https://github.com/nextdns/metadata/commit/3e33dcd5c4213ba30865210f84ec501300d89dda @romaincointepas

**Comment by LagSeeN** [comment]
same google block by threat-intelligence-feeds

**Comment by Veldkornet** [comment]
Same here, also for play.google.com

**Comment by lyrad87** [comment]
I've checked both `google.com` and `play.google.com` and don't seem to have any issues. I don't know if you use the official app but maybe try disabling and enabling it again, similar on your mobile device.

**Comment by lgrn** [comment]
@lyrad87 the issue should already be resolved, I got a response from @romaincointepas via Intercom about 40 min ago.

**Comment by lyrad87** [comment]
Great, then I guess this issue can be closed. =)

**Comment by lgrn** [comment]
I thought I'd leave it open for @romaincointepas to close with some kind of summary of what happened.

**Comment by romaincointepas** [comment]
Sorry about this guys, we fixed it immediately.

Long story short, whitelisting highly queried domains (top 1M alexa or similar) is far from an ideal approach, even if (too) many are doing it. We worked on getting away from this and a small bug found its way through.

We've added safeguards that test for critical domains like `www.google.com` so this doesn't happen again.
