### ISSUE TITLE
[Feature Request] Bypass warning + Paid plan new functionality.

### ISSUE THREAD

**Issue by aelisya** [nextdns/metadata#330]
It would be nice some day (when other services more useful will be done), 

It's to have a way to redirect them to a different warning page like, you have made an illegal request and warn the administrator when they try to use a bypass method (tor, other dns, etc...).
And send a message to the admin like "ip/computer have tried to bypass the dns", 
So like that if a company use your services they will have a way to collect who does what event without connecting themself often to the web-interfaces.

And on to that two function for paid account like : 

1. Error page customisation (css & html),
2. A software to install on the admin post, like that the information ip/computer is sended to the admin with a notification immediately.

**Comment by romaincointepas** [comment]
We will work on blockpage customization soon.

Regarding the other stuff, not in our short-term todo and doesn't really fit our current product strategy, but noted, thanks!
