### ISSUE TITLE
Videobox.com not blocked by porn filter

### ISSUE THREAD

**Issue by pinuk77** [nextdns/metadata#331]
Videobox.com is not blocked by your porn filter. Am surprised this one slipped through, can it be added please?

Thanks.

**Comment by romaincointepas** [comment]
It's blocked (and was when the issue was created), could you double-check?

**Comment by pinuk77** [comment]
I checked when I posted and have just checked on my mobile and it is still available.

**Comment by pinuk77** [comment]
If I try pornhub.com or xnxx.com they are blocked by category porn but videobox.com isn't. There is something wrong here!
