### ISSUE TITLE
[Native:windows] Suggestion to add

### ISSUE THREAD

**Issue by Thuijoss** [nextdns/metadata#334]
_Hello! What do you think about adding the following domains for native blocking?_

- `v10.events.data.microsoft.com` -> Lightswitch05 - Ads & Tracking
- `uhf.microsoft.com` -> Lightswitch05 - Ads & Tracking
- `activity.windows.com` -> Lightswitch05 - Ads & Tracking
- `ris.api.iris.microsoft.com` -> notracking
- `client.wns.windows.com` -> notracking
- `prodxnews1blob.blob.core.windows.net` -> notracking, NextDNS Recommended

**Comment by beerisgood** [comment]
You already can enable Windows tracking if you don't care about a fully usable Windows.
Adding this non-tracking domains to default, break a lot of Windows functions

**Comment by crssi** [comment]
The first 3 on the upper list, that is `v10.events.data.microsoft.com`,  `uhf.microsoft.comI`  and `activity.windows.com` I am blocking from the start over `Lightswitch05 - Ads & Tracking` and have no breakages, that is 0 problems with Windows.

@beerisgood  can you point us more specific to wich Windows functions?

I also do not see the reason that `v10.events.data.microsoft.com` in in the `https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json` exclusion?

**Comment by ammnt** [comment]
> The first 3 on the upper list, that is `v10.events.data.microsoft.com`, `uhf.microsoft.comI` and `activity.windows.com` I am blocking from the start over `Lightswitch05 - Ads & Tracking` and have no breakages, that is 0 problems with Windows.
> 
> @beerisgood can you point us more specific to wich Windows functions?
> 
> I also do not see the reason that `v10.events.data.microsoft.com` in in the `https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json` exclusion?

if you block this host, you'll break Xbox live functions:

```
mobile.pipe.aria.microsoft.com
v10.vortex-win.data.microsoft.com
v20.vortex-win.data.microsoft.com
settings-win.data.microsoft.com
v10.events.data.microsoft.com
v20.events.data.microsoft.com
```

More information here:
https://www.reddit.com/r/pihole/comments/9ztxdx/psa_pihole_seems_to_be_blocking_xbox_achievements/
http://kamilslab.com/2017/01/02/fix-xbox-live-achievements-not-popping-up-when-using-pi-hole/

**Comment by crssi** [comment]
@ammnt None of the links asked for are not even mentioned on those the articles.

Are you sure you have fully read my question?

Cheers

**Comment by ammnt** [comment]
> @ammnt None of the links asked for are not even mentioned on those the articles.
> 
> Are you sure you have fully read my question?
> 
> Cheers

Yeah, I'm sure. I've had Xbox for 13 years and I know exactly what hosts are responsible for. You're not alone here and it's not just about Windows. If you want to block individual hosts, do it. You do not need to violate the network integrity of other users for this.

**Comment by crssi** [comment]
@ammnt  thank you, but @beerisgood mentioned `break a lot of Windows functions` and I was asking for Windows not Xbox. 😉

**Comment by ammnt** [comment]
> @ammnt thank you, but @beerisgood mentioned `break a lot of Windows functions` and I was asking for Windows not Xbox. 😉

Thanks to you too. Xbox Live is part of Windows 10 :(

**Comment by beerisgood** [comment]
> @beerisgood can you point us more specific to wich Windows functions?
> 
> I also do not see the reason that `v10.events.data.microsoft.com` in in the `https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nextdns-recommended.json` exclusion?
>
You break Windows features which keep your system stable if errors are founded:
https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-2004-non-enterprise-editions
https://docs.microsoft.com/en-us/windows/privacy/configure-windows-diagnostic-data-in-your-organization

And no, telemetry doesn't mean that your private data are transmitted. Telemetry are needed for reporting error's and keep your system stable. If you block that, this isn't possible.
Don't try to block things you don't understand. Also read Microsoft privacy policy

**Comment by crssi** [comment]
@beerisgood 
I know what telemetry means and I do not like to block real telemetry, since it should be used for improving product... for example I never block Firefox telemetry.
Unfortunately not all telemetry is a telemetry... but that is another topic which is nor OP nor my question. :wink:

Your first link... that is `https://docs.microsoft.com/en-us/windows/privacy/windows-endpoints-2004-non-enterprise-editions` is 👍 

Thank you
Cheers
