### ISSUE TITLE
False positive for slashdot.org when using Fanboy's Annoyance List

### ISSUE THREAD

**Issue by agoralski** [nextdns/metadata#335]
When using Fanboy's Annoyance List in nextdns I have slashdot.org blocked completely, it resolves to 0.0.0.0.

When I disable it, slashdot.org opens fine. But that's not a problem with the list itself, because when using the same list with uBlock extension for example, slashdot.org opens just fine. So maybe there's a bug on how nextdns is processing this list?

**Comment by Voltairine-de-Cleyre** [comment]
@agoralski -

> So maybe there's a bug on how nextdns is processing this list?

It's that NextDNS does not consume the included white lists in any respective "adblock-style" formatted list. It indeed causes issues such as the one you've encountered.

**Comment by Sduibek** [comment]
So this was reported 2 years ago and is still happening today.

Seems a pretty basic and important issue to resolve - you know, to have the service actually support the lists it uses. 

NextDNS is just never gonna fix it i guess, or...?

**Comment by breadtk** [comment]
Still an issue as of today.

![image](https://user-images.githubusercontent.com/1126756/191392381-dae03a57-15f8-4c1f-81e7-df7bcb46bec1.png)

**Comment by rajscode** [comment]
Still an issue.  NextDNS isn't processing Fanboy's Annoyance List properly.   Shows slashdot.org amongst others being blocked again currently.

**Comment by hagezi** [comment]
@rs @romaincointepas 

Do not extract rules with the `$third-party` modifier from adblock filters for using in DNS lists

`||slashdot.org^$third-party`

**Comment by joshuataylor** [comment]
How would it be empty? Am I misunderstanding something?

`$third-party` rules are used for adblockers to block requests to third-party, so if you're on slashdot.org, everything else will be blocked by your adblocker. This has been the case since it was implemented in 2008 by Adblock Plus, it's also used by uBlock.

Let's take a look at https://secure.fanboy.co.nz/fanboy-annoyance.txt for example (their uBlock list is similar).

It has 57,760 results.

If we search for `^$third-party`, this shows 698 results.

So it should be fine?

Alternatively, you could skip everything from:
```
!-------------------------Third-party blocking rules--------------------------!
```
to
```
!--------------------------Specific blocking filters--------------------------!
```

**Comment by hagezi** [comment]
> Without accepting `$third-party` and/or `$popup` those ABP lists would be empty. We will add a warning in the UI for those lists.

Parse Adblock lists for DNS as follows:

```
# Valid domain regex
regex="(?=^.{4,253}$)(^(?:[a-zA-Z0-9](?:(?:[a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$)"

url="https://secure.fanboy.co.nz/fanboy-annoyance.txt"

curl -sL "$url" | sed -e 's/^[[:space:]]*//' | grep ^\|\|.* | sed 's/[\|^]//g' |
    sed 's/$important,all//' |
    sed 's/$important//' |
    sed 's/$all//' |
    sed 's/$document//' |
    sed 's/$doc//' |
    sed 's/$1p//' |
    grep -P "$regex"
```
With this fanboy list you get 172 valid domains for DNS. Everything else leads to false positive domains. Adblock lists are not made for DNS but for content blockers.
