### ISSUE TITLE
add to porn category xnxx-cdn.com

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#336]
xnxx-cdn.com

![image](https://user-images.githubusercontent.com/19517680/87974467-524f9680-caf4-11ea-9853-70445d744db7.png)

**Comment by romaincointepas** [comment]
Could you suggest those at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi? It's one of the list we source for porn and they are pretty responsive.

**Comment by 3xploiton3** [comment]
> Could you suggest those at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi? It's one of the list we source for porn and they are pretty responsive.

database list integrate to nextdns? what the name?
