### ISSUE TITLE
Adding QuidsUp to the Blocklists choices

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#339]
Please, consider adding QuidsUp to the Blocklists choices in the privacy section.

That is https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt located at https://quidsup.net/notrack/blocklist.php.

Thank you and cheers

**Comment by romaincointepas** [comment]
Already there: https://github.com/nextdns/metadata/blob/master/privacy/blocklists/notrack-tracker-blocklist.json.

**Comment by crssi** [comment]
Doh... how i didn't notice. sorry for spam
