### ISSUE TITLE
Apple hosts blocked by Google Safebrowsing

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#341]
Hello,

FYI: something wrong happen with Google Safebrowsing today. These hosts was blocked:

```
configuration.apple.com.akadns.net
gsa.apple.com.akadns.net
ocsp-lb.apple.com.akadns.net
swscan-cdn.apple.com.akadns.net
```

Keep in mind!☝️

Thank you.

Cheers!

**Comment by ammnt** [comment]
https://transparencyreport.google.com/safe-browsing/search?url=swscan-cdn.apple.com.akadns.net
https://transparencyreport.google.com/safe-browsing/search?url=gsa.apple.com.akadns.net
https://transparencyreport.google.com/safe-browsing/search?url=ocsp-lb.apple.com.akadns.net
https://transparencyreport.google.com/safe-browsing/search?url=swscan-cdn.apple.com.akadns.net
🤦‍♂️

**Comment by romaincointepas** [comment]
They are flagging the whole `*.apple.com.akadns.net`. Reported to them, hopping they fix this quickly.

**Comment by ammnt** [comment]
Looks like they`re fixed this. Thanks!✌️

**Comment by ammnt** [comment]
Guys, its blocked again!

**Comment by Thuijoss** [comment]
![](https://files.tinypic.pl/i/01012/oiwvlgcndks4.jpeg)
@romaincointepas - can this be added somehow to the exceptions?

**Comment by ammnt** [comment]
@Thuijoss, just add this host to allowlist:
`apple.com.akadns.net`

**Comment by romaincointepas** [comment]
Fixed (manually on our side, unfortunately). Please reopen if you're still havint the issue.
