### ISSUE TITLE
"Applicaster" blocked by recommended blocklist, leads to broken TV network apps

### ISSUE THREAD

**Issue by smiley** [nextdns/metadata#342]
[Applicaster](https://www.applicaster.com/) powers the app for Israel's public broadcast channel, [Kan](https://play.google.com/store/apps/details?id=com.applicaster.il.ch1) (and [a few more](https://www.applicaster.com/case-studies)) It's currently blocked by "NextDNS Recommended Ads & Trackers Blocklist" and prevents the app from loading. Whitelisting `*.applicaster.com` makes it work again.

At a quick glance it doesn't seem like the usual bunch of analytics companies on the blocklist. I suggest removing it from the recommended list or, if possible, somehow exclude it from accounts created in Israel (there's also "EasyList Hebrew" but not everyone checks and enables that).

**Comment by romaincointepas** [comment]
Did you figure out which specific subdomain is breaking the app?

**Comment by smiley** [comment]
I didn't dig deeper but because the app was developed by Applicaster I think it doesn't matter that much (and could randomly break someday when they change it).
