### ISSUE TITLE
Allow DNS query on a particular website.

### ISSUE THREAD

**Issue by 92VV3M42d3v8** [nextdns/metadata#345]
Suppose you have enabled some blocklists. But there is a particular website which doesn't work when we block trackers from it, and these trackers are on most of the lists. So we can do two things-
1. Disabling blocklists or 
2. Whitelisting these common trackers which are also common on other sites ( it is denying the whole purpose of using NextDNS)

But if a option is there which can allow these on only that particular website. we can benefit from using nextdns always and also those trackers will not be passing from other websites.

**Comment by crssi** [comment]
NextDNS cannot know source website and thus cannot use rules `source->destination/target` similarly as uBO. 😢

**Comment by romaincointepas** [comment]
Can't be done at the DNS level unfortunately.
