### ISSUE TITLE
[Suggestion] "Login manager autofill abuse for tracking" list

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#346]
_The following is the list of sites from Alexa top 1 million which embed scripts that extract email addresses from the browsers' built-in login (password) managers._

https://webtransparency.cs.princeton.edu/no_boundaries/autofill_sites.html

**Comment by romaincointepas** [comment]
This is an 3.5 years old study, is it still happening?

**Comment by crssi** [comment]
It might if script is used but not at those URLs anymore.
I do not believe that NextDNS can do some useful magic here.
This should be mitigated in the browser itself by disabling non-interactive password form auto-fill.

**Comment by romaincointepas** [comment]
Agree, closing.
