### ISSUE TITLE
oisd light

### ISSUE THREAD

**Issue by timkgh** [nextdns/metadata#347]
Please add an option for the **_light_** version of osid
https://oisd.nl/?p=faq#light
https://oisd.nl/?p=dl

I like it better as the single list to use because it is less aggressive than the main list.

**Comment by crssi** [comment]
It is actually more aggressive than `main` list.
`Light` in this case doesn't mean less aggressive, but means less specific.

For example, if you have the `main` list like:
```
sub1.example.com
sub2.example.com
sub9.example.com
```

Then the light version would be:
```
example.com
```

Now using the `light` version when navigating to `sub5.example.com` will be blocked when using the `main` list would NOT be blocked.

So, at the end, you would really more like to use `main` list and never actually the `light` one.

**Comment by romaincointepas** [comment]
Agreeing with @crssi here.

Side note, gigantic blocklists have no performance impact with NextDNS.

**Comment by timkgh** [comment]
I see. For NextDNS the explanation makes sense if a domain on the list implies subdomains too. For a hosts file (as in `/etc/hosts`) which is how I've been using the light list so far, subdomains are not implied, there's no wildcarding, if you want to block a subdomain, it must be explicit in the file.
