### ISSUE TITLE
douyincdn.com

### ISSUE THREAD

**Issue by bestpika** [nextdns/metadata#348]
The `douyincdn.com` is part of TikTok's domain.
Please add it to the denylist.

**Comment by CyanoTex** [comment]
@romaincointepas , perhaps add this to the TikTok parental control thing?

**Comment by bestpika** [comment]
I found `ixigua.com` and `pstatp.com` use the same API.
So the two domain is also part of TikTok's domain.

**Comment by romaincointepas** [comment]
Our approach to the *Parental Control -> Services* feature is to block the service using the minimal amount of domains.

For *evil* services, we use *Privacy -> Blocklists* (we have No Facebook, No Google). I don't think TikTok should be there as they are not present outside their own app/website.

Except if those domains are absolutely required to stop TikTok from working, we would rather not add them.
