### ISSUE TITLE
Recommended list blocks a Firefox link

### ISSUE THREAD

**Issue by carlylemiii** [nextdns/metadata#351]
https://relay.firefox.com/?utm_source=blog.mozilla.org&utm_campaign=firefox_frontier&utm_medium=referral

![CleanShot 2020-07-31 at 17 01 54@2x](https://user-images.githubusercontent.com/29067983/89080907-c806fe00-d34f-11ea-8170-9784ecde523d.png)

`bhqf.adj.st` in the recommended list blocks this. this might be an affiliate link that needs to be let through? (i have that option turned so as to not break sites like the wirecutter, but this link is still broken from Firefox: https://bhqf.adj.st/?adjust_t=6tteyjo&adj_deeplink=lockwise%3A%2F%2F&adj_fallback=https%3A%2F%2Fwww.mozilla.org%2Fen-US%2Ffirefox%2Flockwise)

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/1568da34b9cf966c9725d86f6be3c00bed2649d8, thanks!

**Comment by carlylemiii** [comment]
Similarly, the Pocket link is blocked.

https://app.adjust.com/hr2n0yz?engagement_type=fallback_click&fallback=https%3A%2F%2Fgetpocket.com%2Ffirefox_learnmore%3Fsrc%3Dff_bento&fallback_lp=https%3A%2F%2Fapps.apple.com%2Fapp%2Fpocket-save-read-grow%2Fid309601447

**Comment by romaincointepas** [comment]
Fixed in https://github.com/nextdns/metadata/commit/1f4337f28da56883c05d259054cd1827c96d5324
