### ISSUE TITLE
Amazon subdomains on recommended list completely break Amazon app

### ISSUE THREAD

**Issue by carlylemiii** [nextdns/metadata#354]
Finally narrowed it down on which subdomains can be blocked and which can't. Functionality is restored with these allowed, so they should not be blocked by default IMO, or allowing affiliate links should at least fix this.

aan.amazon.com

aax-us-iad.amazon.com

fls-na.amazon.com

**Comment by romaincointepas** [comment]
Those are breaking the Amazon app on which platform(s)?

**Comment by carlylemiii** [comment]
It was on Android, but inexplicably things are fine now, even with those turned off in the allowlist. 🤷‍♂️
