### ISSUE TITLE
app.link and adservice.google.com at "Allow Affiliate & Tracking Links"

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#357]
Should...
```
app.link
adservice.google.com
```
...really be part of [Allow Affiliate & Tracking Links](https://github.com/nextdns/metadata/blob/master/privacy/affiliate-tracking-domains)?

I really do not see a reason for that.

Cheers

**Comment by romaincointepas** [comment]
They are tracking domains or domains that, when blocked, ends up breaking things that are manually clicked by users.

Our goal is to make that option an easy switch for maximum blocking with nothing breaking.

**Comment by crssi** [comment]
That I understand... but In my case `app.link` from the Revolut `lu5or.app.link` is neer being invoked by a user click.
Its merely the Revolut app being installed on iOS.
I can see no breakages blocking `app.link`.

The same goes with `adservice.google.com`.

Those two should no be the part of Allow Affiliate & Tracking Links.

Cheers
