### ISSUE TITLE
mercadolivre.com.br

### ISSUE THREAD

**Issue by Sucuarana** [nextdns/metadata#362]
Domain: mercadolivre.com.br

Strange that searching Google Safe Browsing, it is not blocked:

https://transparencyreport.google.com/safe-browsing/search?url=mercadolivre.com.br

This is the site of a large marketplace in Brazil, so it is a false positive.

![Captura de Tela 2020-08-05 às 10 11 55](https://user-images.githubusercontent.com/3794278/89417822-97371800-d705-11ea-8e58-03412b199091.png)

**Comment by romaincointepas** [comment]
It's CNAME'ing to `d39fbvvvia7i6z.cloudfront.net`, which is (wrongly?) flagged by Google Safe Browsing:

https://transparencyreport.google.com/safe-browsing/search?url=d39fbvvvia7i6z.cloudfront.net

I've submitted a false positive report to Google.

Also, there is currently a bug on our side where the little tooltip should show the CNAME that matched but doesn't.

**Comment by Gusta-BH** [comment]
I hadn't noticed it could be a CNAME ...

I visited `d39fbvvvia7i6z.cloudfront.net` through a VPN and a poorly aligned page is displayed, but it is legitimate. It may be a bad configuration of the site by the administrator ... I will try to contact them.

Thanks a lot for the help.
