### ISSUE TITLE
scam, please handle fast

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#365]
Hi there please block this https://twitter.com/danielverlaan/status/1291357406681849857?s=19

Its a dutch tech journalist with retweeted from foxit security company

<translated to english>
Attention: lately there has been an increase in phishing via PostNL packages.

You will receive an SMS / message that a package is on its way to you, but before you can accept it you have to pay the shipping costs.

That leads to a phishing site that steals your bank details. Warning sign Red exclamation mark

-------------------------------------------------------------------------------------------------------------------

There are many domain names (possibly) related to this scam, including some really smart ones:

your-postnl [.] me
my-postnl [.] net
package tracking [.] live
my-entry payment [.] viz
ing-ideal [.] ga
tikkie payments [.] me

https://pastebin.com/raw/AJtQ11fW

h / t
@Mike_stokkel
  from
@foxit
---------------------------------------------------------------------------------------------
pastebin text

beveilgdeomgeving[.]site
betaalonline-verzoek[.]com
mijn-postnl[.]net
pakket-bezorgservice[.]info
ingparticulier[.]eu
sorteer-centrum[.]live
online-betaling-verificatie[.]net
betaling-platform[.]website
ibetalingsplatform[.]nl
live-betalen[.]nl
bunqbetaalverzoek[.]xyz
postnlbezorging[.]info
ing-particulier-betaalverzoek[.]nl
ing-ideal-app[.]nl
ing-safepay[.]nl
handelsplatform-online[.]nl
www[.]betaal-verzoeken[.]club
bankbetaalverzoeken[.]com
abn[.]bankbetaalverzoeken[.]com
ing[.]bankbetaalverzoeken[.]com
martkplaats-verificatie[.]nl
veilig-betalingsysteem[.]online
volguwpakket-nlpostdienstservice[.]site
idealverificatie[.]online
online-afhandelzaken[.]site
tikkie-betalingen[.]me
rabobetaalverzoek[.]nl
live-betaal[.]nl
marktplaats-verificatiebetaling[.]eu
mijn-tele2[.]me
lng-verzoeken[.]ga
sorteercentrum-pakketdienst[.]online
ingideal[.]nl
omgeving-idealadministrative[.]xyz
ideal-betaaldirect[.]com
verificatie-digid[.]nl
betaalmeting[.]me
systeemverificatie[.]com
marktplaats-verificatie[.]cyou
onlinebetaalmethode[.]nl
ingrequest[.]nl
ing-particulierverzoekje[.]nl
opstuur-pakket[.]live
veiligezone[.]network
mijning[.]app
directbetalenideal[.]nl
lngbank-veilig-online[.]nl
ing-idealbetaling[.]nl
betalings-verzoeken[.]online
betaalproces[.]online
marktplaats-identificeren[.]online
betaalsupport-verzoek[.]live
jouw-postnl[.]net
inq-betaalverzoekjes[.]site
ing-betaalverzoek-app[.]nl
idealbetaalverzoek[.]me
wereldpas-online[.]com
afhandelen-onlinebetaling[.]site
betalen-nl[.]me
betaalverzoekbetalingen[.]nl
doorgestuurd-marktplaatsomgeving[.]live
idealbetalingverzoek[.]xyz
verzenden-via-postnl[.]nl
mijn-ingbetaalverzoekjes[.]com
betaalprocess[.]site
marktplaats-iban[.]nl
idealbetaling[.]me
betaalkenmerken[.]nl
marktplaats-idealcontrole[.]nl
vodafone-verificatiesysteem[.]nl
betaalverzoek-verifieren[.]ml
ingbankieren-betalen[.]com
rabobetaalverzoek[.]com
verzoekje-marktplaats[.]nl
verificatie-online-betaling[.]net
postnl-via-marktplaats[.]nl
lng-betaling[.]nl
ing-verzoekjes[.]nl
bankieren-ideal[.]me
mp-verifieren[.]nl
postnl-pakketontvangen[.]tech
pakketzending[.]me
onlinebetaalplatformsite[.]nl
idealverificatie[.]site
beveiligde-betaling[.]nl
ing-ideal[.]ga
nld1[.]veiligbetaalportaal-group[.]com
verificatie-handelsplatform[.]nl
gelijkoversteken-betaalverzoek[.]nl
iban-verificatieproces[.]xyz
pakket-volgen[.]live
direct-betaald[.]info
online-betaalsysteem[.]nl
marktplaats-verzendlabel[.]nl
vodafone-verificatie[.]nl
network-betaalverzoek[.]nl
mijn-ingbetaling[.]nl
rab0betaalverzoek[.]xyz
marktplaats-onlineverificatie[.]nl
online-betaalplatformen[.]nl
betalingverificatie[.]nl
sorteercentrum-pakketdienst[.]nl
veilig-betaalsysteem[.]online
betalingssystemen[.]online
rabo-betaalverzoekjes[.]nl
bunq-payme[.]nl
marktplaats-onlineverificaties[.]nl
betaalplatfrom-online[.]online
afhandelen-veiligonline[.]site
betalen[.]live 
betaalverzoak[.]digital
betaalverzoek-ing[.]ga
mijnrabo[.]xyz
marktplaats-autorisatie[.]nl
betaling-online-verificatie[.]net
bevestiging-handelsplatform[.]site
ibetalingsmethode[.]nl
jouw-postnl[.]me
ldealbetaalsite[.]nl
bunqverzoek[.]club
postpakket-dienstnl[.]tech
idealverzoek[.]com
bevestig-rekening[.]nl
betaling-nl[.]info
betaalverzoekje-pay[.]online
fitforfree-payment[.]nl
raboverzoek[.]com
lngbetaallink[.]com
betalingbunq[.]com
bunqverzoek[.]com
pakket-sorteercentrum[.]live
verificatiecontrole[.]info
autorisatie-betaalverzoek[.]nl
tikkie-betaalplatform[.]ga
ldeal-platform[.]nl
betalingsverzoeken[.]eu
nlpostdienst-verzendingid[.]online
postsorteercentrum[.]nl
ing-app-ideal[.]nl 
ideal-ing[.]ga

**Comment by romaincointepas** [comment]
Please report to any of the threat intelligence feeds we use:
https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json

**Comment by crssi** [comment]
Whichever I have tested from upper list is already dealt with google safebrowsing service, which most decent browsers already support natively.

Safebrowsing report page: `https://safebrowsing.google.com/safebrowsing/report_phish/`
You can check domain being on the SB list here: `https://transparencyreport.google.com/safe-browsing/search`

Cheers
