### ISSUE TITLE
Suggestion: Email Trackers List

### ISSUE THREAD

**Issue by specter78** [nextdns/metadata#367]
https://github.com/leavemealone-app/email-trackers

Not all rules would work, but many would.

Update: There's also this list https://github.com/trockerapp/trocker/blob/master/chrome/lists.js, though I do not know whether that can also be added.

**Comment by beerisgood** [comment]
The app "[FairEmail](https://github.com/M66B/FairEmail)" use ([since 20 days now](https://github.com/M66B/FairEmail/releases/tag/1.1260)) the [Disconnect's tracker protection lists](https://disconnect.me/trackerprotection)

But maybe both are useful?
@M66B

**Comment by specter78** [comment]
It would be better if there's a separate category of `block email trackers` within privacy section just like disguised trackers and native tracking.

**Comment by romaincointepas** [comment]
Blocklists already handle those as far as we know, and the most of the rules in the list you linked can't work at the DNS level.
