### ISSUE TITLE
[False Positives] login.gremimedia.pl

### ISSUE THREAD

**Issue by ghost** [nextdns/metadata#374]
Unable to access the page: `rp.pl`. On the way, the domain is blocked `login.gremimedia.pl`.
The list that blocks this is the `NextDNS Recommended Ads & Trackers Blocklist`. 
I think it was added by mistake. 🤔

**Comment by krystian3w** [comment]
https://github.com/piterzspam/qq/blob/8a9c482b945dfc8c6603bd9bf6b8b14af8a09216/Wiadomosci_mobilne.txt#L53

**Comment by krystian3w** [comment]
https://github.com/EnergizedProtection/mirror/blob/f750b880ee4662686efc32d13019b59f2ac8989a/active/filter/someonewhocares.org.txt#L3790

**Comment by krystian3w** [comment]
https://github.com/EnergizedProtection/mirror/blob/f750b880ee4662686efc32d13019b59f2ac8989a/active/filter/someonewhocares.org.txt#L6069

**Comment by romaincointepas** [comment]
`gremimedia.pl` is blocked by Steven Black (we use that blocklist among others to build our recommended blocklist).

Could you please report this false positive directly to https://github.com/StevenBlack/hosts?

**Comment by krystian3w** [comment]
@ghost - can't report here @romaincointepas  (He deleted account).

.Besides, it is better not to report anything to the mirror author `SteventBlack` if he does not double-check who is banning himself, and he also takes a few other smaller projects.
