### ISSUE TITLE
answers.sap.com blocked by nextdns-recommended

### ISSUE THREAD

**Issue by giukanis** [nextdns/metadata#377]
it is used for sap support/knowledge base. 

e.g. https://answers.sap.com/questions/7552089/how-to-use-mesearchsourceofsupply.html

**Comment by crssi** [comment]
actually its the CNAME for `sap.cloud.answerhub.com`, and the `answerhub.com` is listed under https://github.com/StevenBlack/hosts, and it gets there from https://someonewhocares.org/hosts/zero/hosts... and Dan is AWOL.

**Comment by romaincointepas** [comment]
Fixed in https://github.com/nextdns/metadata/commit/59ba31fddd058eadfe00e25b94f3ce1278330858. For Steven Black, the change has to come from there, we don't alter third-party blocklists.
