### ISSUE TITLE
false positive worldweather.wmo.int

### ISSUE THREAD

**Issue by tsekityam** [nextdns/metadata#380]
It is blocked by `liste-fr`, but I couldn't find it's GitHub repo. 

Does anyone know who should I report it to?

**Comment by romaincointepas** [comment]
They are blocking a public CDN suffix, which is pretty aggressive. Because we apply those rules to CNAMEs as well, this ends up generating a lot of false positives. Ideally, they should be more specific in their blocking (at least one subdomain below the public suffix).
