### ISSUE TITLE
my.nextdns.io is blocked by CNAME flattening.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#383]
However you've implemented CNAME flattening is blocking the NextDNS login page. I've determined that it has to be the only setting, including any 3rd party apps/blocklists/cookies/JavaScript etc... through an extensive elimination process.

**Comment by beerisgood** [comment]
Can't confirm

**Comment by Voltairine-de-Cleyre** [comment]
Create two profiles. One with CNAME flattening. One without. That's all it takes.

**Comment by beerisgood** [comment]
> Create two profiles. One with CNAME flattening. One without. That's all it takes.

No needed as I use CNAME flattering in my main profile.
No problems

**Comment by Mikaela** [comment]
I was hit by this yesterday using Unbound (1.11.0-1?) on two Debian Testings with dnssec-triggerd (0.17+repack-4). One Debian had no issues, but the other was unable to access some sites including my.nextdns.io until I disabled CNAME flattening. I think both had the same configuration, but there must be a difference somewhere that I didn't notice.

Are you also using Unbound or which clients and versions?

**Comment by Voltairine-de-Cleyre** [comment]
> > Create two profiles. One with CNAME flattening. One without. That's all it takes.
> 
> Not needed as I use CNAME flattering in my main profile.
> No problems

@beerisgood First of all, I want to apologize for initially dismissing your obvious help in this issue. So, thank-you. Your testing of it is most appreciated. In fact, after I hastily dismissed your comment, I went back to testing it myself. And, you are absolutely correct. In certain setups, there is no problem whatsoever. So, you are right. In the setups you've tested, CNAME flattening has no effect on the loading of `my.nextdns.io`.

***

@Mikaela You, too, are absolutely correct. In specific setups, CNAME flattening does in fact prohibit `my.nextdns.io` from loading. Insofar as the initial setups I was using when stumbling upon this issue, one was using NextDNS's DNSCrypt server via AdGuard Pro on iOS. I turned off all local filtering as well as all filtering through NextDNS to ensure it was in fact CNAME flattening that was causing the issue. It was: however, since originally posting the issue, NextDNS's implementation of CNAME flattening now has no effect on loading `my.nextdns.io` using the same setup. I should note that even using DoH had the same initial negative effect as well as using DoT in my router which runs Merlin's firmware for the Asus RT-AX58U. Now that too works fine with CNAME flattening, however, I use the built in DoT client, so I cannot speak for the NextDNS client for that firmware. On my workstation, I use the NextDNS client for Debian, although I use SysV instead of SystemD for my init script. I've also experimented with, and successfully used, NextDNS's DNSCrypt server via the built in Linux client as well as an Unbound setup as you've mentioned. Both were implemented in the past before NextDNS used CNAME flattening, so I cannot speak to whether or not they would have a negative effect. I can easily test DNSCrypt, though I'd prefer not bothering with another Unbound setup. I'm sure you can understand why 😂. I've seen a request for a Runit compatible NextDNS client, which I'd love as I run AntiX with runit for its init for non-work purposes. It's a wonderful Debian implementation from Greece. When you've the time, I highly recommend you check it out via USB. It'll run from RAM. It has a SysV client as well, though I personally find its Runit implementation better than any others I've tried (ArtiX - Arch is nice, but I've used Debian since Sarge but stopped using in favor of MX due to the problems Debian's use of SystemD introduced in Jessie; Void - I just don't find it usable as a stable Workstaton). Regardless, when using the native NextDNS client for Debian, I encountered the same issue as with iOS & my router. I've just logged in to my Workstation to test if it's still affected by this issue. I wil edit this momentarily after testing it. Thank-you.

**Comment by Voltairine-de-Cleyre** [comment]
This is a general reply, essentially, not specifically regarding your post, Milaela. Except for the fact that I am now being hit with this issue again, though now **only** via DoT setup within my router. DoT, DoH & DNSCrypt run through any third-party client such as AdGuard/Pro iOS functions well insofar as this particular issue is concerned. Not that the screenshots attached prove anything at all, but they do at least add visual information for the 'understand more effectively when it's presented visually' people among us if my word is to be at least mostly trusted on this issue. Thank-you. Sent from ProtonMail Mobile On Wed, Aug 26, 2020 at 4:30 AM, Mikaela Suomalainen <notifications@github.com> wrote:  
I was hit by this yesterday using Unbound (1.11.0-1?) on two Debian Testings with dnssec-triggerd (0.17+repack-4). One Debian had no issues, but the other was unable to access some sites including my.nextdns.io until I disabled CNAME flattening. I think both had the same configuration, but there must be a difference somewhere that I didn't notice.
Are you also using Unbound or which clients and versions?

**Comment by romaincointepas** [comment]
This is due to local DNSSEC validation. We validate DNSSEC on our side, so you must disable it to use that feature. We will try to make that more obvious.
