### ISSUE TITLE
Add support for Rakuten Cash Back "block"list

### ISSUE THREAD

**Issue by vladzaharia** [nextdns/metadata#385]
Rakuten hosts an exclusionary blocklist (I guess allowlist) for their cash back feature. This isn't technically a blocklist, but might be useful for those that want to use the feature.

It's a bit controversial to have in a DNS system that is meant to block these things in the first place, so I could totally see it rejected.

https://www.rakuten.com/whitelist/ebates-cash-back-shopping.txt

**Comment by romaincointepas** [comment]
Ideally, those should be added to https://github.com/nextdns/metadata/blob/master/privacy/affiliate-tracking-domains.

The link doesn't work on my side, any idea why?

**Comment by goodness-from-me** [comment]
The links works for me.

**Comment by romaincointepas** [comment]
@vladzaharia @goodness-from-me definitely not working for me (redirecting to homepage). Could you share the file on a gist/pastebin or paste it here?

**Comment by goodness-from-me** [comment]
Here it is: https://gist.github.com/goodness-from-me/f9194c770dd811a361880a432f292168

**Comment by romaincointepas** [comment]
I don't get it, why do they have `www.timewarnercable.com` or `facebook.com` in there? What is this list for?

**Comment by vladzaharia** [comment]
So as I mentioned in the original issue, this is more of an allowlist than a blocklist (which is why I figured this was controversial anyway). Basically, Rakuten has an affiliate program where they give you cashback for using their affiliate links to buy things, and this allow list specifically allows their affiliate domains, which include TWC, Facebook, and other controversial domains.

Totally fine not including it, or including it with a disclaimer or something, but would be nice to have the ability to use NextDNS with it turned on/off as needed (and not turning the entire blocking off)

**Comment by llacb47** [comment]
It's a bit of a stupid list IMO, plus they don't even know how to write filters properly.

**Comment by romaincointepas** [comment]
@vladzaharia It's not that it's controversial, it's that this list doesn't really make any sense. They added major websites because someone may post an affiliate link there? That's not how our Affiliate & Tracking links feature works either, so it doesn't really have a place anywhere on NextDNS at the moment.
