### ISSUE TITLE
Two Lists are Down

### ISSUE THREAD

**Issue by sr093906** [nextdns/metadata#387]
https://github.com/nextdns/metadata/blob/a4419a952c6a1b9b6039bee3ad79c2e63d47088a/privacy/blocklists/chef-koch-spotify.json

https://github.com/nextdns/metadata/blob/a4419a952c6a1b9b6039bee3ad79c2e63d47088a/privacy/blocklists/nsa-blocklist.json

Github account 'CHEF-KOCH' disappeared (again?)

https://www.reddit.com/r/pihole/comments/9p9d3p/chef_koch_github_account_deleted/

**Comment by beerisgood** [comment]
We should finally delete his (code stealing) lists

**Comment by sr093906** [comment]
No offense, 'CHEF-KOCH' did do something shameful, but as I can see not all of his/her repositories are stole from others without giving credits, at least not the case for the 'NSA Blocklists'. Quoted from the [cached Gihub page](https://webcache.googleusercontent.com/search?q=cache:x-FsV5K8BoEJ:https://github.com/CHEF-KOCH/NSABlocklist+&cd=1&hl=en&ct=clnk&gl=sg) "My list is original based on 2007 published Wikileaks + Cryptome documents and includes my own modifications from 2008, 2012, 2014, 2015, 2019 & 2020."

Also, the user has some other repositories which I believe he/she made a lot of efforts like [regtweaks](https://webcache.googleusercontent.com/search?q=cache:iYXdjnHqPaoJ:https://github.com/CHEF-KOCH/regtweaks+&cd=1&hl=en&ct=clnk&gl=sg), [Warez](https://webcache.googleusercontent.com/search?q=cache:rLTchSEy5OYJ:https://github.com/CHEF-KOCH/Warez+&cd=1&hl=en&ct=clnk&gl=sg), which also give some credits,
and[ Chromium-hardening](https://webcache.googleusercontent.com/search?q=cache:5x4drI6TyM8J:https://github.com/CHEF-KOCH/Chromium-hardening+&cd=1&hl=en&ct=clnk&gl=sg).

I feel sorry for the deletion of the account and wish him/her all the best.

**Comment by Atavic** [comment]
Not the funniest guy on the internet, but not bad overall, let us know where art thou gone, CHEF

**Comment by romaincointepas** [comment]
One is fixed, we're trying to get NSABlocklist back up. Not really getting any update though obviously, so you're still theoritically getting the *latest version*.

**Comment by beerisgood** [comment]
Did one also really think that a DNS list can block NSA access? That's ridiculous and block at best their official websites... wow!

**Comment by romaincointepas** [comment]
@beerisgood we include popular blocklists, we are a custom resolver and people can decide from themselves :)

**Comment by beerisgood** [comment]
see https://github.com/nextdns/metadata/issues/340#issuecomment-730620498
