### ISSUE TITLE
False Positive: portal.cfahome.com

### ISSUE THREAD

**Issue by fleetfoot15** [nextdns/metadata#390]
As of yesterday morning I'm seeing blocks for portal.cfahome.com being attributed to the EasyPrivacy subscription. However, I don't see anything in the EasyPrivacy list that should be blocking portal.cfahome.com. I believe this may be a bug? I manually whitelisted for the time being, and that resolved the issue.
<img width="912" alt="portalBlock" src="https://user-images.githubusercontent.com/15930066/91987951-b2914500-ecfc-11ea-9dab-99cfbff338fd.PNG">

**Comment by crssi** [comment]
`portal.cfahome.com` is hiding with `CNAME` method behind `portal.cfahome.com.dxcloud.episerver.net`.
`episerver.net` is listed on `EasyPrivacy` and that is why the asked domain is being blocked.

Cheers

**Comment by fleetfoot15** [comment]
What's odd is that I use EasyPrivacy on AdblockPlus in my browser and it doesn't block portal.cfahome.com. Any idea why there would be different results from using EasyPrivacy list on NextDNS?

**Comment by fleetfoot15** [comment]
FWIW episerver.net is a widely used content management platform used by many companies. Blocking the entire domain seems excessively broad? I'm currently waiting to get access to the EasyList forum so I can propose removing episerver.net

**Comment by crssi** [comment]
> What's odd is that I use EasyPrivacy on AdblockPlus in my browser and it doesn't block portal.cfahome.com. Any idea why there would be different results from using EasyPrivacy list on NextDNS?

I do not know/use AdblockPlus (but I do use uBlock Origin - uBO), which looks like it does not support the latest (anti)tracking technique over `cname`.

> FWIW episerver.net is a widely used content management platform used by many companies. Blocking the entire domain seems excessively broad? I'm currently waiting to get access to the EasyList forum so I can propose removing episerver.net

I also do not use EasyPrivacy over NextDNS, but you could add `episerver.net` to `Allowlist`, at least until your persuade EasyList maintainers to remove it.

**Comment by fleetfoot15** [comment]
Yeah I whitelisted it for now, and that solved the problem for me but I want to make sure other users don't run into the same problem down the road.
