### ISSUE TITLE
possbile fp

### ISSUE THREAD

**Issue by ijuliank** [nextdns/metadata#391]
it was blocking dns.google, dns.google.com, mail-google.com and yahoo mail, while enabled Threat Intelligence Feeds

**Comment by crssi** [comment]
Are you sure? I have enabled `Threat Intelligence Feeds` and I still can visit those domains.

**Comment by lyrad87** [comment]
Same, works fine. Must be something else.

**Comment by romaincointepas** [comment]
Disable the "Block bypass methods" feature.
