### ISSUE TITLE
anudeepND strange result

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#393]
I have `anudeepND` list under privacy.
The list has entry `a-msedge.net`, but if I query this URL, it does not get blocked.

Why is that so?

Thank you and cheers

**Comment by romaincointepas** [comment]
When migrated to treating NAMEs and CNAMEs, a-msedge.net broke a lot of stuff (it's a CNAME of many legit domains).

Aside from a few other domains (like `cloudfront.net`), we are also temporarily excluding `a-msedge.net` until we can make sure it's clean from most blocklists.

**Comment by crssi** [comment]
Could you mark with some special icon in the logs that kind of exceptions, so we don't puzzle and bang the head onto desk too long. 😉 

thank you

**Comment by romaincointepas** [comment]
That's the only one "debatable", the rest are all public suffixes.
