### ISSUE TITLE
netguard.me is incorrectly blocked.

### ISSUE THREAD

**Issue by nihalanand697** [nextdns/metadata#394]
www.netguard.me is blocked by Threat Intelligence Feed but is a genuine site of the famous Firewall for android named Netguard.
Kindly look into it.
:D

**Comment by beerisgood** [comment]
Confirm.

The official GitHub is also https://github.com/M66B/NetGuard

**Comment by romaincointepas** [comment]
Blocked by https://github.com/stamparm/aux/blob/master/maltrail-malware-domains.txt, could you open an issue with them?
