### ISSUE TITLE
www.teslarati.com is incorrectly blocked

### ISSUE THREAD

**Issue by tas50** [nextdns/metadata#396]
It's just a Tesla fanboy site.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/1015200/92881213-9f007100-f3c3-11ea-97ea-a431d7ace89b.png">

**Comment by lyrad87** [comment]
<img width="604" alt="Screenshot 2020-09-11 at 10 22 49" src="https://user-images.githubusercontent.com/7974733/92892127-c59cc700-f418-11ea-8811-97af110e594f.png">
Seems to be blocked by other blocklists as well.
The Steven Black blocklist is part of the NextDNS-Recommended blocklist and it blocks "s.ntv.io". You should ask in their repo if they can whitelist it but chances are they won't remove it. It may be easier to just add it to the Allowlist instead.

**Comment by crssi** [comment]
The culprit is actually `ntv.io` entry from Peter Lowe's list `https://pgl.yoyo.org/adservers/` which is used by StevenBlack and then by NextDNS.

**Comment by romaincointepas** [comment]
Should be fixed for our recommended blocklist. Please see directly with the list maintainers for the other blocklists.
