### ISSUE TITLE
whitehat.ro false positive

### ISSUE THREAD

**Issue by happyhater** [nextdns/metadata#398]
Hello,

One of our client reported that incident,
whitehat.ro is being blocked by threat-intelligence-feeds and category:porn.

Please fix it,
Thank you.

**Comment by scafroglia93** [comment]
nextdns has no fault, you have to try to understand which is the list that has entered the site incorrectly

for the moment put it in the allowlist

**Comment by romaincointepas** [comment]
Excluded from the Porn category, and submitted the false positive to http://www.shallalist.de/submissions.html.
