### ISSUE TITLE
livesoccertv.com false positive on Piracy filter/category

### ISSUE THREAD

**Issue by timkgh** [nextdns/metadata#399]
I don't think it's a piracy site, it has official mobile apps in the play stores, lists TV schedule with links to legit sites AFAICT

Seems to come from this list
https://raw.githubusercontent.com/nextdns/piracy-blocklists/master/streaming-video

**Comment by scafroglia93** [comment]
+1 no streaming, just info for satellite channel

**Comment by romaincointepas** [comment]
Removed in https://github.com/nextdns/piracy-blocklists/commit/f7653468b91ec265ca1eb8a72d0b39b1e4749746
