### ISSUE TITLE
3 domains to add to adult blocklist

### ISSUE THREAD

**Issue by lif0920** [nextdns/metadata#400]
Hi, could you please consider adding the following to the adult/porn category?

szjt188.com
waterdamagesandiego.org
fitnudegirls.com

thankyou!

**Comment by scafroglia93** [comment]
Nextdns does not manage the lists, try to open a pull request to one of the maintainers of the adult lists

**Comment by romaincointepas** [comment]
Could you suggest them at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi? That's one of our sources.

**Comment by lif0920** [comment]
OK, thankyou.
