### ISSUE TITLE
pubnub.com blocked as porn

### ISSUE THREAD

**Issue by emeryray2002** [nextdns/metadata#403]
pubnub.com is being blocked by the built-in porn list. It is a widely used pubsub service for messaging and IoT applications. 

https://en.wikipedia.org/wiki/PubNub

**Comment by lyrad87** [comment]
Works here and I have the "Porn" category under Parental Control enabled. So it must have been fixed upstream already.

**Comment by timkgh** [comment]
Broken again?

**Comment by emeryray2002** [comment]
Yes, it is being blocked again by the Porn filter.

**Comment by crssi** [comment]
Guys, this was all my mistake and I just  want to apologize. 

https://github.com/Sinfonietta/hostfiles/issues/122#issuecomment-703004926

Sorry and cheers

**Comment by crssi** [comment]
Blocking by `porn` is not correct, but what would be the reason to not block it anyway?

I had blocked it for months and didn't encounter any problems, also why would someone want to IoTs would share my using info to 3rd parties?

Just brainstorming... cheers
