### ISSUE TITLE
Add support for EasyList Cookie List

### ISSUE THREAD

**Issue by faheempatel** [nextdns/metadata#404]
Would be nice to have this in addition to the other EasyLists that are already supported. 

Link to list: https://easylist-downloads.adblockplus.org/easylist-cookie.txt

**Comment by crssi** [comment]
There are lists that make sense in DNS world and there are list that doesn't.

The suggested is the second and it is suitable for active content filtering and not connection filtering.

IMO this list can be used in uBO or similar, but not DNS.

Cheers

**Comment by faheempatel** [comment]
Gotcha, makes sense. I'll close 👍
