### ISSUE TITLE
learn.cisecurity.org incorrectly blocked

### ISSUE THREAD

**Issue by oskapt** [nextdns/metadata#405]
This is the download page for CIS Benchmarks from the Center for Internet Security. While it does require that people submit a form to access the content, neither the content nor the domain are adware/malware.

<img width="1165" alt="Screen Shot 2020-09-16 at 17 45 30" src="https://user-images.githubusercontent.com/171292/93390753-976a1d80-f844-11ea-8192-dc8bf4a70f29.png">

**Comment by lyrad87** [comment]
https://github.com/nextdns/metadata/issues/397#issuecomment-691933254

**Comment by romaincointepas** [comment]
I'm not seeing `pi.pardot.com` as CNAME anymore, and the current CNAME `go.pardot.com` is not blocked by our recommended blocklist. Closing for now, @oskapt can you reopen if that's not what you're seeing on your side?
