### ISSUE TITLE
Add DuckDuckGo Tracker Radar

### ISSUE THREAD

**Issue by sr093906** [nextdns/metadata#407]
https://spreadprivacy.com/duckduckgo-tracker-radar/

https://community.blokada.org/t/introducing-duckduckgo-tracker-radar-to-blokada/469/4

Hosts File:

https://github.com/blokadaorg/blokadaorg.github.io/blob/ddf0231c73e2ea4fc97abf0c52ee510f2b6527d0/blocklists/ddgtrackerradar/standard/hosts.txt

**Comment by beerisgood** [comment]
https://github.com/nextdns/metadata/issues?q=DuckDuckGo

**Comment by crssi** [comment]
@beerisgood is trying to say that this is a duplicate issue and you may close this one. 😉 

Cheers

**Comment by romaincointepas** [comment]
Too risky for DNS-level blocking, and as far as we know no one has converted that correctly without leaving tons of false positives? Closing for now.
