### ISSUE TITLE
NextDNS Blocking Zen Pinball 2 Downloads

### ISSUE THREAD

**Issue by jputting** [nextdns/metadata#409]
Hi,

I have the NextDNS app for macOS Catalina 10.15.6

I have installed the Zen Pinball 2 game from the Apple App Store and when I try to download a new pinball table I get an error message stating "You must go online to continue".

This only happens when NextDNS is active, when I quit NextDNS everything works normally and I can download pinball tables.

I have tried removing all the filter lists,

I have also deactivated all the privacy and security options that I can find in my NextDNS configuration.

I have checked my NextDNS logs for the 10th time today after trying to download a pinball table.

My logs for "Blocked Queries" are blank because every security option and filter list is disabled and yet NextDNS app for macOS still will not let me download a pinball table.

I have also added *.zenstudios.com to my "Allow List".

I have tried deleting my existing NextDNS configuration and using a different one.

But nothing I have tried solves this issue and NextDNS continues to block my Zen Pinball 2 from downloading pinball tables.

The quitting of the NextDNS app for macOS fixes this issue and when it has quit Zen Pinball 2 works normally and pinball tables can be downloaded.

NextDNS is blocking the type of connection that Zen Pinball 2 needs to establish and this refusal to allow Zen Pinball to establish the needed network connection is causing the Zen Pinball 2 to believe its offline and then gives me the message that "You must go online to continue".

I really would appreciate some help to solve this.

I have reached out to NextDNS via their Chat on their website and have been waiting and waiting and waiting and waiting for over 12 hours and still no response.

The chat on the NextDNS website stated that replies are being made in less than 5 hours.

I have waited for that amount of time, it has now been well over twice the amount of waiting time and still no technical support at all.

Their technical support is extremely poor or almost non existent.

**Comment by crssi** [comment]
Why did you close the issue?
Did you find the culprit in the mean time?
If so... what are your findings?

**Comment by jputting** [comment]
Hi,

I have closed this because I believe NextDNS app for macOS poses unacceptable security issues.

NextDNS functions with a dummy VPN.

This dummy VPN seems to be responsible for interfering or blocking the game trying to establish a network connection and causing it to believe it is offline.

This why I was getting an error  message stating "Please go online to continue" when attempting to download pinball tables.

This should not be happening at all, the fact is it has happened with a simple mac pinball game.

I have now lost many hours of sleep worrying about how many macOS apps have not been updated or received urgent security patches due to this NextDNS dummy VPN.

I am uninstalling NextDNS as this has quite serious implications for macOS security and the risks are far too great to allow this situation to occur again.

NextDNS has been uninstalled  and won't be reinstalled because of the potential for the dummy VPN to cause mac apps to believe they are offline as is the case with Zen Pinball 2.

**Comment by rs** [comment]
This is the first case of an app on macOS to behave this way. This is not a security issue and it is most probably a bug in the game’s network handling.

As I told you in the other ticket, you can try to use the [cli client](https://github.com/nextdns/nextdns) or the link IP feature which won’t use a dummy VPN to see if this is the reason for your game misbehavior.
