### ISSUE TITLE
This website is Taiwan News, not pornography. But classified by porn

### ISSUE THREAD

**Issue by onec526** [nextdns/metadata#416]
This website is Taiwan News, not pornography. But classified by porn

news.ebc.net.tw

**Comment by lyrad87** [comment]
It's blocked by [https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt](https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt). I'd suggest contacting the list maintainer directly to have it fixed upstream.
