### ISSUE TITLE
mercadolivre.com.br blocked by NextDNS recommeded blocklist

### ISSUE THREAD

**Issue by semente** [nextdns/metadata#421]
d39fbvvvia7i6z.cloudfront.net is being blocked by the NextDNS blocklist and It is preventing the access to https://www.mercadolivre.com.br, which is a popular Brazilian ecommerce.

**Comment by lyrad87** [comment]
Just FYI --> https://github.com/nextdns/metadata/issues/362#issuecomment-669207536

**Comment by romaincointepas** [comment]
It's only blocked by Google Safe Browsing, not our blocklist. See @lyrad87 comment, and feel free to report it to them at https://safebrowsing.google.com/safebrowsing/report_error/. We never alter Google Safe Browsing.
