### ISSUE TITLE
NextDNS does not resolve lol.secure.dyn.riotcdn.net

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#422]
NextDNS does not resolve `lol.secure.dyn.riotcdn.net`

But other DNS services resolves fine.

What is the culprit?

Thank you

**Comment by romaincointepas** [comment]
Seems like it's not a global issue (see https://dns.nextdns.io/?name=lol.secure.dyn.riotcdn.net). Can you talk to us via the chat on our website?

**Comment by crssi** [comment]
^^ Just say when... I am waiting now already one hour for your response on a website.
