### ISSUE TITLE
Strange domains in my log for my router

### ISSUE THREAD

**Issue by mrxoom1274** [nextdns/metadata#424]
I found strange domains in my log. Connection over my router. Do you have a idea how I could find out what this is. See screenshot. 

![image](https://user-images.githubusercontent.com/70346648/95013917-bdb0fb00-0643-11eb-83fd-421b995bc9b6.jpeg)

**Comment by Voltairine-de-Cleyre** [comment]
Use an online service such as virustotal. If it's suddenly appearing after never appearing, block the entire domain. It's suspicious looking as it is.

**Comment by romaincointepas** [comment]
This doesn't really have a place here, feel free to start a discussion on our subreddit at reddit.com/r/nextdns.
