### ISSUE TITLE
"Allow Affiliate & Tracking Links" inconsistency

### ISSUE THREAD

**Issue by cjfloss** [nextdns/metadata#430]
It allows www.googleadservice.com but not googleadservice.com, without the 'www'

**Comment by crssi** [comment]
Why do you think that the whole `googleadservice.com` should be allowed?
Do you have any working sample?
Did you found in your connections/logs any other needed than the `www` only?

**Comment by romaincointepas** [comment]
What @crssi said, we didn't find any case where anything beside `www.` should be allowed.
