### ISSUE TITLE
www.bet365.com wrongly blocked

### ISSUE THREAD

**Issue by maddler** [nextdns/metadata#437]
www.bet365.com is being reported in the Ads & Trackers blocklist. That's a betting site.
On the other hand bet365.com (without www) is allowed.

**Comment by crssi** [comment]
You should report it at source.
This came from https://someonewhocares.org/hosts/ over StevenBlack and for the reporting they use email hosts@someonewhocares.org

Cheers

**Comment by romaincointepas** [comment]
It's blocked by all of those, if anyone has the courage to report this false positive down the line.

<img width="285" alt="Screen Shot 2020-10-27 at 1 31 45 PM" src="https://user-images.githubusercontent.com/797899/97302024-c8cd0480-1858-11eb-8308-fb1f51960263.png">
