### ISSUE TITLE
Feature Request for iOS 14 users.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#438]
Now that Hardened Privacy Mode has been depreciated for iOS 14+ every dns query made is logged by U.S. based servers. I don't mean the logs to turn off & on from the dashboard I'm referring to the service providers' TOS. Any U.S. based server will log everything it can. I also doubt that since the servers are U.S. based that NextDNS is allowed to discuss any requests made by the government. May an option to choose where I want my DNS servers located - U.S., Switzerland, Iceland, Sweden, etc. - be integrated into the web UI as it's no longer a choice we have (anyone using iOS 14+)?

**Comment by rs** [comment]
If you use an encrypted protocol like DoH or DoT, queries are encrypted from your network to the DNS server and then logs are sent over encrypted channel from the DNS server to the log servers and then stored in a cyphered database. Neither your ISP nor the provider of the server will be able to log or see anything for your DNS traffic.

**Comment by romaincointepas** [comment]
Closing this, feel free to discuss this and other suggestions on our subreddit https://www.reddit.com/r/nextdns.
