### ISSUE TITLE
Messenger.com domains not resolving when Facebook is blocked in Parental Control

### ISSUE THREAD

**Issue by radupotop** [nextdns/metadata#440]
Steps to reproduce:

1. In NextDNS, go to the Parental Control tab > Websites, Apps & Games > block Facebook only
2. Open https://messenger.com/ in the browser 
3. In the NextDNS log observe that some messenger.com domains that resolve to facebook.com behind the scenes are now also being blocked.  
These domains are `edge-chat.facebook.com` and `star.facebook.com`. Whitelisting them solves the problem.

In the past I used to block `www.facebook.com`, `m.facebook.com` and `connect.facebook.net` in the Denylist section. I found it works well enough. This is a slightly more conservative approach than blocking all the facebook.com domains.

Ccreenshot here: https://i.imgur.com/USlRY8L.jpg 

Thanks

**Comment by romaincointepas** [comment]
I've moved things around for facebook/messenger (https://github.com/nextdns/metadata/commit/8045388dee9493311c7f0e5817ce97a68613d16e).

Can I ask you to remove (or just disable) all FB/Messenger domains from your denylist/allowlist, test this out and report back?

**Comment by radupotop** [comment]
Thanks, that seems to work now. 

I noticed that Facebook on Android "phones home" quite often using the domains `mqtt-mini.facebook.com` and `connect.facebook.net`, might be worth blocking those too. Thanks.

**Comment by romaincointepas** [comment]
`graph.facebook.com` is used in many other places so it's a no-go. And let's wait on the other one until it's absolutely needed.
