### ISSUE TITLE
false alarm dns rebinding

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#443]
![image](https://user-images.githubusercontent.com/19517680/97024656-42c36c00-1581-11eb-8bb7-98d0540b22cb.png)

tracker.piratepublic.com
tracker.cloudfactory.org
12.rarbg.me
public.popcorn-tracker.org

**Comment by rs** [comment]
How so? Those domains resolve to 127.0.0.1, which is exactly what DNS Rebinding protection is blocking.
