### ISSUE TITLE
pls update links in Threat Intelligence.json

### ISSUE THREAD

**Issue by arun81** [nextdns/metadata#444]
Hello Team

Please update the link in threat intelligence as existing ones are dead . Thanks
==============================================
https://kriskintel.com/feeds/ktip_malicious_Ips.txt

https://kriskintel.com/feeds/ktip_covid_domains.txt

https://kriskintel.com/feeds/ktip_malicious_domains.txt

https://kriskintel.com/feeds/ktip_malware_hashes.txt
=================================================

Thanks
https://kriskintel.com/feeds/ktip_ransomware_feeds.txt

**Comment by aelisya** [comment]
i see lot a comment without '#' on some of these link, so i'm not really fan of them for an automated download script

**Comment by romaincointepas** [comment]
Updated in https://github.com/nextdns/metadata/commit/952bbbf5212339381affeb9a7e7a392ad0ac181e.

@michaelb-ae Not sure what you meant, can you provide an example of this?
