### ISSUE TITLE
Request: xbox live as parental control service

### ISSUE THREAD

**Issue by vbap** [nextdns/metadata#445]
I currently block xbox gaming by denylist for *.xboxlive.com and *.microsoft.com (note, I use a conditional configuration just for the console on my network, so *.microsoft.com probably not a good idea to include)

Not sure if there are others related to xbox but xboxlive.com seems effective enough.

**Comment by romaincointepas** [comment]
Can you confirm that blocking ONLY `*.xboxlive.com` is enough?

**Comment by vbap** [comment]
For my use case yes. It renders Xbox live unplayable

**Comment by vbap** [comment]
HI Folks,

Any chance someone is working on this? Or, alternatively, allow recreation time for the "Denylist" entries...

**Comment by MikeyTadd** [comment]
*.xbox.com
*.xboxlive.com
Happy renders Xbox live unusable. Microsoft.com doesn't add anything additional for Xbox Live, think its analytics more than anything
