### ISSUE TITLE
Link from newsletter blocked (nzz.ch)

### ISSUE THREAD

**Issue by maXity** [nextdns/metadata#446]
Hi! I noticed that NextDNS is blocking the following (legitimate) link from a newsletter in my inbox:

http://view.email.nzz.ch/?qs=2250b75463c4ee0419f0dc4b4d4785e5ca935d9e8535a9d641c8d3b353c6a20e2c958b036e497dccba5350ba0435319d0e6f7b87928ebbebf31acfd7fad6759e5313e03cbc8d598a2173b002207acf60

Thank you for looking into this!

**Comment by CyanoTex** [comment]
Have you checked which list is doing the blocking?

**Comment by maXity** [comment]
Yes, log says "blocked by NextDNS ads & trackers blocklist"

**Comment by crssi** [comment]
@maXity 

This post https://github.com/nextdns/metadata/issues/397#issuecomment-691933254 should help you out.

Cheers
