### ISSUE TITLE
Porn pages

### ISSUE THREAD

**Issue by Mevoxel** [nextdns/metadata#448]
Recently I found that some porn pages wasn't blocked, one was bongacams7.com  and I found several pages principally from .pl domains. I suggest to add a feature to have as nextdns their own list and the option to validate if specific pages must be blocked or must be to be included. As a reference you could try with open DNS (opendns.com), they have a section and you can check if the page will be blocked or put the page to evaluate by the community if should be blocked or not and the classification like porn, games, etc. Im using the service to protect kids and teens, I trust that I can continuing doing our best to protect them with your prompt support. Thank you.

**Comment by haiderim** [comment]
You can already add domains manually to a whitelist/blacklist(Allowlist/Denylist) that overrides all lists. I do agree that there should be an interface to validate domains whether they're blocked, by which blocklist  and under which category.

**Comment by romaincointepas** [comment]
We will probably work on something like this soon. Until then, please report those to https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi (subsection: porn).

**Comment by smith558** [comment]
> We will probably work on something like this soon. Until then, please report those to https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi (subsection: porn).

Hi! Is this still a valid way to add domains?
