### ISSUE TITLE
Domain blacklist request

### ISSUE THREAD

**Issue by obeho** [nextdns/metadata#449]
`api.zhuti.intl.xiaomi.com`
`global.market.xiaomi.com`
`idmb.app.chat.global.xiaomi.net`
`resolver.msg.global.xiaomi.net`
`idmb.app.chat.global.xiaomi.net`
`mb.milink.g.mi.com`
`connect-milink.g.mi.com`

Please add these to native tracking Xiaomi list. 

And `idmb-app-chat-global-xiaomi03new-123456789.tn-north-1.elb.amazonaws.com` what does this do? Is it tracking domain? or just a cdn?

**Comment by beerisgood** [comment]
Doesn't already a Xiaomi list exist ?
Did you use it?

**Comment by obeho** [comment]
Yup, these things aren't blocked by the list.

**Comment by beerisgood** [comment]
Then you should contact the maintainer of the list

**Comment by obeho** [comment]
@romaincointepas ?

**Comment by romaincointepas** [comment]
It feels that blocking those domains would break some features of Xiaomi? This is a no-go for the Native Tracking Protection feature.
