### ISSUE TITLE
affiliate-tracking-domains

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#450]
@romaincointepas 

I do not use the `affiliate-tracking-domains`, but I would like to to avoid some breakages.

But there are domains that really bothers me on this list and makes me not use it.

Can you explain how the domain gets into this list (what are the rules) and why are those specific domain on this list?

```
ad.doubleclick.net
adservice.google.com
amazon-adsystem.com
www.googleadservices.com
analytics.twitter.com
app.adjust.com
bs.serving-sys.com
s.click.aliexpress.com
```

especially I think those are big NO to be allowed:
```
ad.doubleclick.net
adservice.google.com
amazon-adsystem.com
www.googleadservices.com
```

I have a lot of denies here for those and never find the real reason to allow those, the only real for those is to be blocked... IMHO.

Thank you and cheers

**Comment by romaincointepas** [comment]
Anything that will break manually clicked links will be added to that list. For example, `www.googleadservices.com` is the domain used when clicking on *ads* at the top of Google search results.

Note that while some of those domains belong to some known root domains that serve trackers/ads (or just *looks* like it could be), most of the time it's still a completely different subdomain. `www.googleadservices.com` is a good example of that, as far as we know it's only used after manual clicks mentioned above.

**Comment by crssi** [comment]
Thank you... will go through a list, domain by domain.

Lets start with `adservice.google.com`.
If I only open `https://www.google.com` without any additional interaction with the page, the `adservice.google.com` get contacted. So, in this case, no manual click.
From user perspective, everything works OK and nothing seem to brake even when I deny `adservice.google.com`.

So, I really do not understand allowing this domain. Is there any post that says denying breaks something?

Fast research of `www.googleadservices.com`  it shows excessive contacting this domain from mobile devices for no apparent reason. Blocking it, doesn't change user experience... but let me some time to research more for this one. Other will follow.

Thank you and cheers

**Comment by crssi** [comment]
I haven't touched my iPhone and it made a contact to `app.adjust.com` which is allowed by `affiliate-tracking-domains` and which should be allowed only by user action.

@romaincointepas Why is that?

**Comment by romaincointepas** [comment]
> Anything that will break manually clicked links will be added to that list.

It doesn't matter if a domain is used somewhere else for other purposes, only the condition above has to be satisfied. This feature is an **automatic fix for all breakages**. As far as we know, it's very rarely the case, but it can happen, and that's fine for that specific feature.

**Comment by crssi** [comment]
Actually I am not satisfied with the answer.

I can't stand that for example `www.googleadservices.com` would get whitelisted without explanation where the breakage was reported and what actually was the breakage.
If I rely to `affiliate-tracking-domains` I will need to trust it, and ATM I am not.

Where can I find documentation of those with the reason to be whitelisted?

Cheers

**Comment by romaincointepas** [comment]
I think you want a different kind of feature that NextDNS doesn't offer. In your case, I recommend you add domains to your denylist instead.

Regarding explanations, we may add more in the future, but right now most domains are self-explanatory.

**Comment by crssi** [comment]
> I think you want a different kind of feature that NextDNS doesn't offer.

Not true. But when something is allowlisted to my network devices I would like to know why.

**Comment by crssi** [comment]
@romaincointepas 
OK. Now I see that users using google as a search engine, do have breakages if those are not allowed.

Sorry for "ranting".

Cheers

**Comment by crssi** [comment]
About `adservice.google.com`...  all other TLDs should also be added like:
```
adservice.google.si
adservice.google.de
adservice.google.it
adservice.google.co.uk
...
...
```

for a completeness, since `adservice.google.com` covers only en-us "locations".

Cheers

**Comment by ignoramous** [comment]
> I think you want a different kind of feature that NextDNS doesn't offer. In your case, I recommend you add domains to your denylist instead.
> 
> Regarding explanations, we may add more in the future, but right now most domains are self-explanatory.

Please consider an option to let users opt out of NextDNS maintained allowlists from the web frontend?
