### ISSUE TITLE
Add link.sylikes.com to affiliate links

### ISSUE THREAD

**Issue by carlylemiii** [nextdns/metadata#451]
If you visit https://www.theverge.com/good-deals/2020/10/27/21535954/airpods-pro-samsung-galaxy-s20-fe-5g-ipad-air-2020-deals-sale

and click here

![CleanShot 2020-10-28 at 04 26 10@2x](https://user-images.githubusercontent.com/29067983/97417473-bd6bee80-18d5-11eb-9f1d-338de52a0c82.png)

That link can't be opened with the recommend block list and affiliate links allowed

**Comment by crssi** [comment]
> That link can't be opened with the recommend block list and affiliate links allowed

Are you sure? It opens here just fine.
But surely the `deeplink-bh.datafeedfile.com` is denied by at least `1Hosts (Lite)` and `oisd`

**Comment by carlylemiii** [comment]
Well, http://link.sylikes.com/?publisherId=615112&afCampaignId=66960X1514734X46a9ef04eb74c8c075ca7801d471fe6d&afPlacementId=1514734&url=https%3A%2F%2Fwww.bhphotovideo.com%2Fc%2Fproduct%2F1594485-REG%2Fapple_myfn2ll_a_10_9_ipad_air_wi_fi.html is what Safari stops on for me:

<img width="666" alt="CleanShot 2020-10-28 at 06 02 41@2x" src="https://user-images.githubusercontent.com/29067983/97427900-3887d180-18e3-11eb-845b-243c8cef1f2c.png">

and I see this in my logs:

<img width="361" alt="CleanShot 2020-10-28 at 06 02 00@2x" src="https://user-images.githubusercontent.com/29067983/97427870-2dcd3c80-18e3-11eb-9f6c-0b2c8c173fcc.png">

**Comment by crssi** [comment]
The behavior is different here.
Seems that it behave differently on your Safari.
Here on Firefox and Edge Chromium, Windows, it doesn't try to go over this domain.
Tried also Safari on iPhone 8+, iOS 14... it also passes well.

**Comment by carlylemiii** [comment]
Does seem there's some browser differences, as I'm not seeing it in all other browsers — but at the end of the day, I'm landing on this URL, and it's blocked by NextDNS.

**Comment by romaincointepas** [comment]
@carlylemiii it was actually one of the CNAMEs, `rd.bizrate.com`. Just added it to the affiliate/tracking domains list, thanks for the report!
