### ISSUE TITLE
Scam domain

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#453]
https://aevgsegrtrytkuy5i6u.org/myaccount/?key=8ebd01c390d64cc654dc49e6e17fb72f3e561c44

![](https://i.imgur.com/LDXFzQT.jpg)

**Comment by beerisgood** [comment]
You should report that to https://github.com/StevenBlack/hosts

**Comment by romaincointepas** [comment]
Seems to be down now, usually one of our Security feature should block it early.
