### ISSUE TITLE
BUG wrong translating easylist blocklist

### ISSUE THREAD

**Issue by skapytek** [nextdns/metadata#459]
Hello,
im using nextdns and the easylist and the adguard base filter and nextdns is blocking cdn.shortpixel.ai but its a false positive.
Website is a image cdn especially for wordpress.
https://github.com/AdguardTeam/AdguardFilters/issues/66846 and https://github.com/easylist/easylist/issues/6340#issuecomment-721016974
I think you are interpreting the lists wrong.
shortpixel.ai^$popup shouldnt block cdn.shortpixel.ai
![2020-11-02_21h26_48](https://user-images.githubusercontent.com/11317488/98029078-48d20c00-1e0f-11eb-9bd2-cb2595b5f59f.png)

**Comment by crssi** [comment]
Maybe instead of Adguard directly try the `oisd` filter.
These are the lists included in `oisd`: https://oisd.nl/?p=inc

**Comment by krystian3w** [comment]
https://oisd.nl/?p=dl - no look good, needed use own hardware/software where in NextDNS possible use DNS configuration:
- on router
- on system ("normal" / DoT)
- on browser (DoH)

Also NextDNS no support import lists for newbie on `my.nextdns.io`?

**Comment by skapytek** [comment]
Will there be any answer for any one of the devs?
Seems nobody cares at nextdns

**Comment by romaincointepas** [comment]
Closing, answered [here](https://github.com/nextdns/metadata/issues/479#issuecomment-734526577).
