### ISSUE TITLE
false positive: consent.cookiebot.com

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#461]
On e.g. https://www.nuclearblast.de/ i can't use their cookie management because of this blocked domain.
Looks also like CNAME:
![image](https://user-images.githubusercontent.com/9625159/98299298-c9337100-1fb7-11eb-81fb-04bcb6007cc2.png)

**Comment by krystian3w** [comment]
#19

**Comment by romaincointepas** [comment]
Please report this to Steven Black (one of our upstreams) at https://github.com/StevenBlack/hosts.

It seems they are blocking `consent.cookiebot.com.edgekey.net` but not `consent.cookiebot.com`, which is weird.

**Comment by krystian3w** [comment]
But this is blocked by `adaway.org`:

https://github.com/StevenBlack/hosts/blob/aa377ddd142852ae5453730a1db053bb34141e82/data/adaway.org/hosts

**Comment by crssi** [comment]
`consent.cookiebot.com` was removed due to intervention at https://github.com/anudeepND/blacklist/issues/132#issuecomment-731605007

@krystian3w 
> But this is blocked by `adaway.org`:
> 
> https://github.com/StevenBlack/hosts/blob/aa377ddd142852ae5453730a1db053bb34141e82/data/adaway.org/hosts

Obviously, I have done half of your work by getting it removed from `anudeepND`.
Why don't you do the other half and engage at https://github.com/AdAway/AdAway/issues for getting it removed from `adaway.org`?

**Comment by krystian3w** [comment]
Because someone report first to mirror repo?

**Comment by beerisgood** [comment]
> Please report this to Steven Black (one of our upstreams) at https://github.com/StevenBlack/hosts.
> 
> It seems they are blocking `consent.cookiebot.com.edgekey.net` but not `consent.cookiebot.com`, which is weird as `consent.cookiebot.com.edgekey.net` is only ever a CNAME of `consent.cookiebot.com`.

I told him but he does not want to fix it because of "too much work/ a domain is not worth it"

In my opinion, such a list is no longer usable as hardly any user report 25 domains at once - because that is what he wants from now on

See https://github.com/StevenBlack/hosts/issues/1472

**Comment by crssi** [comment]
I have reported it now https://github.com/anudeepND/blacklist/issues/132#issuecomment-735157030

I, for sure agree with @beerisgood about StevenBlack. He has sometimes "strage" approach.

There is always arguing with Steven and see the upper link... Anudeep resolved it swiftly, even before I could finish this post. I just love him/her for the passion.

Cheers

**Comment by crssi** [comment]
**OFF TOPIC (or not?)**

IMHO there is nothing significant that would not be covered in `NextDNS Ads & Trackers Blocklist` with those lists:
```
1Hosts (Lite) https://github.com/badmojr/1Hosts/blob/master/assets.txt
Anudeep's Blacklist
oisd https://oisd.nl/?p=inc
```
And those maintainers are fast responsive, they do a thorough background check and make a valid, documented/traceable, decisions.

Actually, there might be nothing else that someone would really need beside those.


And, IMHO, until the `Allow Affiliate & Tracking Links` includes the following hosts/domains, it is a privacy/tracking trap.
```
ad.doubleclick.net
adservice.google.com
amazon-adsystem.com
app.adjust.com
www.googleadservices.com
```

**Comment by beerisgood** [comment]
Problem still exists.
@romaincointepas 

I wonder how long you will use Steven's list with all the known false positives

**Comment by beerisgood** [comment]
Problem still exists.
@romaincointepas 

I wonder how long you will use Steven's list with all the known false positives.
Blocking the cookie banner doesn't make any sense but make privacy worse as all cookies would be allowed in worst case. So, user have no choice because blockage.

**Comment by crssi** [comment]
I gave up with Steven long ago.
A few sources he is using are off, but he persists those are OK, so I have stopped "arguing", but we all can see that as way too many complaints here goes directly to those.
The best results I get with my template you can find here https://github.com/crssi/NextDNS-Config and actually this is also what I am using daily.

@badmojr, Stephan (OISD) and @anudeepND  are really **GREAT**.
I would just wish that @anudeepND  would come around more frequently.

Cheers
