### ISSUE TITLE
False positive: sportscenter.api.espn.com

### ISSUE THREAD

**Issue by owine** [nextdns/metadata#464]
False positive for sportscenter.api.espn.com on NextDNS Ads & Trackers Blocklist

**Comment by crssi** [comment]
It looks like it is already removed two days ago, see https://github.com/AdAway/adaway.github.io/commit/2a01faacbf943026aaeb63315451aa4da92d94c2

But we need to wait for @StevenBlack to update.

**Comment by StevenBlack** [comment]
Hi!  @crssi and @owine I've just updated hosts to [release 3.1.5](https://github.com/StevenBlack/hosts/releases/tag/3.1.5).

**Comment by owine** [comment]
Validated fixed. Thanks.

**Comment by crssi** [comment]
Thank you @StevenBlack, 👍 
Cheers
