### ISSUE TITLE
ad.doubleclick.net in affiliate-tracking-domains?

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#466]
Can someone point me to an issue (that is documented) that was the reason for `ad.doubleclick.net` to land into `affiliate-tracking-domains`.

I have many denies here to `ad.doubleclick.net` (manully added to denylist) and:
1. nothing is broken.
2. its never caused by the reason of my manual click to some link... actually it happens without me being aware of.

Thank you and cheers

**Comment by romaincointepas** [comment]
Sometimes called in the redirect chain of those sponsored results on google.com.
