### ISSUE TITLE
False positive: www.bbt.mobi.edgekey.net & myfi.bbt.mobi

### ISSUE THREAD

**Issue by iwilliamsj** [nextdns/metadata#467]
False positive for www.bbt.mobi.edgekey.net and myfi.bbt.mobi on NextDNS Ads & Trackers Blocklist and Steven Black. This is BBT.COM Bank so is a legitimate institution which my bank!
![59E1DD3C-6A30-4656-8EBC-F104B858E165](https://user-images.githubusercontent.com/25371730/98892799-0f347d00-246f-11eb-8e3c-aa31b3c7bf4e.png)

**Comment by iwilliamsj** [comment]
@StevenBlack

**Comment by StevenBlack** [comment]
Hi @iwilliamsj thank you for the heads-up.  

I just checked and we don't block either of those domains.  Nothing matching `.bbt.` even.

The domain `mobi.edgekey.net` is listed by us, but hosts files don't support wildcards so `www.bbt.mobi.edgekey.net` would pass.

Am I missing something?

**Comment by iwilliamsj** [comment]
Hello StevenBlack,I really don't know what is going on either if I allow list myfi.bbt.mobi then the mobile App works, this is broken with the iOS app only, the Desktop site works as intended.

**Comment by romaincointepas** [comment]
@StevenBlack NextDNS wildcard-blocks, so `mobi.edgekey.net` is catching subdomains as well.

We've rarely seen a case when a parent domain should be blocked but not one of its subdomains. Could you share the reason why you're blocking `mobi.edgekey.net` specifically?

**Comment by StevenBlack** [comment]
@romaincointepas the domain `mobi.edgekey.net` cones to us via AdAway.  @jawz101 can you please have a look?  Thank you as always!

**Comment by jawz101** [comment]
removing

**Comment by iwilliamsj** [comment]
It looks like this is issue has been resolved. Will close now. Thanks for all the help everyone!
