### ISSUE TITLE
Amazon app is block by Next DNS list

### ISSUE THREAD

**Issue by Mevoxel** [nextdns/metadata#469]
I found using my mobile phone and with the amazon application installed, even the app open correctly when the NextDNS Ads & Trackers Blocklist, Steven Black and Lightswitch05 - Ads & Tracking are added I cant surf on Amazon app to buy something but if I open using a browser in my mobile and open my amazon account I have no issues to surf and buy is just only using the application.
Here are the urls I found blocked for the amazon application:
Thursday, November 12, 2020 10:32 AM
unagi.amazon.ca

Thursday, November 12, 2020 10:31 AM
fls-na.amazon.com.mx

Thursday, November 12, 2020 10:31 AM
unagi.amazon.com.mx

Thursday, November 12, 2020 10:31 AM
aan.amazon.com

Thursday, November 12, 2020 10:31 AM
aax-us-east.amazon-adsystem.com

Thursday, November 12, 2020 10:31 AM
device-metrics-us.amazon.com

Thursday, November 12, 2020 10:31 AM
device-metrics-us-2.amazon.com

Thursday, November 12, 2020 10:31 AM
unagi-na.amazon.com

Thursday, November 12, 2020 10:30 AM
unagi.amazon.ca

Thursday, November 12, 2020 10:27 AM
aan.amazon.com

**Comment by romaincointepas** [comment]
Could you please report this directly to Steven Black at https://github.com/StevenBlack/hosts? The NextDNS blocklist uses it (among a few others) as upstreams.

**Comment by securingmom** [comment]
none of these are breaking

the  FLS server is need for the endless scrolling feature

unagi is occasionally needed for licensed media in an interweb browser

metrics ought never be allowed
