### ISSUE TITLE
mobileiosapi.punchh.com

### ISSUE THREAD

**Issue by bradenglund** [nextdns/metadata#473]
NextDNS Ads & Trackers Blocklist is blocking mobileiosapi.punchh.com as seen here:
![image](https://user-images.githubusercontent.com/28195153/99805612-b59a1580-2b34-11eb-99ce-5024795900c9.png)

This breaks this app.
https://apps.apple.com/us/app/the-halal-guys/id1462764941
I am unable to verify the rewards balance in the app without manually whitelisting this site.

**Comment by crssi** [comment]
Hi,
this comes from AdAway blocklist, which is upstream on StevenBlack, which is upstream of NextDNS Ads&Trackers.

I would suggest you to place an issue here: https://github.com/AdAway/adaway.github.io

Cheers

**Comment by CyanoTex** [comment]
> Hi,
> this comes from AdAway blocklist, which is upstream on StevenBlack, which is upstream of NextDNS Ads&Trackers.
> 
> I would suggest you to place an issue here: https://github.com/AdAway/adaway.github.io
> 
> Cheers

https://github.com/AdAway/AdAway

Correct repo BTW.

**Comment by crssi** [comment]
^^ Uh, my bad. Thanks @CyanoTex

**Comment by romaincointepas** [comment]
@bradenglund @crssi is right, please report this to the upstream blocklist (https://github.com/AdAway/AdAway) if you think this is a false positive.
