### ISSUE TITLE
instabio.cc

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#474]
![image](https://user-images.githubusercontent.com/19517680/99867958-c4de9900-2bf0-11eb-8b4c-05ac461b2b18.png)

instabio.cc
wrong detection, should be whitelist

**Comment by crssi** [comment]
It comes from https://github.com/nextdns/metadata/blob/1c8c5d05136c128c72693704f395c31ed853e618/security/threat-intelligence-feeds.json#L104
which is strange. AFAICT this list is getting info from `phishtank.com` and this listing is simply not there.
In that case I don't see a reason to have `http://phishing.mailscanner.info/phishing.bad.sites.conf` defined in `threat-intelligence-feeds` when phishtank is also part of  `threat-intelligence-feeds` https://github.com/nextdns/metadata/blob/1c8c5d05136c128c72693704f395c31ed853e618/security/threat-intelligence-feeds.json#L188

**Comment by romaincointepas** [comment]
@crssi where does it say that `http://phishing.mailscanner.info/phishing.bad.sites.conf` uses phishtank only as source? If that's the case we should definitely remove it.

**Comment by crssi** [comment]
Visit main domain, that is http://phishing.mailscanner.info/ of `http://phishing.mailscanner.info/phishing.bad.sites.conf`.

Read:
> **Phishing Bad Sites**
The phishing bad sites is updated using data from www.phishtank.com once per day. The domains included are known to be fraudulent and generally dangerous.

😉
