### ISSUE TITLE
Replace the current No Facebook list with the one by Lightswitch05

### ISSUE THREAD

**Issue by drewblasphemepatchwork** [nextdns/metadata#476]
The current No Facebook list has lot of stuff that should be blocked, for example all giphy.com related and some instagram domains: https://imgur.com/a/aXMQB4s

This is the list i suggest: https://www.github.developerdan.com/hosts/lists/facebook-extended.txt

**Comment by romaincointepas** [comment]
Ideally, this list is to block Facebook Inc. (it's a privacy blocklist). If you only want to block the Facebook app, you should use the Parental Control feature.
