### ISSUE TITLE
[BUG] www.amazonforum.com blocked by Google Safe Browsing

### ISSUE THREAD

**Issue by timkgh** [nextdns/metadata#477]
```
;; ANSWER SECTION:
www.amazonforum.com.	209	IN	CNAME	www.amazonforum.com.00d4p000000go4puaq.live.siteforce.com.
www.amazonforum.com.00d4p000000go4puaq.live.siteforce.com. 209 IN CNAME	d1bd3wxsyuz0t7.cloudfront.net.
d1bd3wxsyuz0t7.cloudfront.net. 209 IN	A	0.0.0.0
```
But www.amazonforum.com itself is not really on the Google Safe Browsing list:
https://transparencyreport.google.com/safe-browsing/search?url=www.amazonforum.com&hl=en

However, `d1bd3wxsyuz0t7.cloudfront.net` is on the list:
https://transparencyreport.google.com/safe-browsing/search?url=d1bd3wxsyuz0t7.cloudfront.net&hl=en

I suspect it's because CloudFront is a CDN for many sites some of which may have questionable content.

As a side note, having "CNAME Flattening" enabled makes troubleshooting these issues tricky.

**Comment by timkgh** [comment]
This may point to a more general issue with other domains that resolve to this or other CDNs and that should not be blocked.

**Comment by romaincointepas** [comment]
We've reported `d1bd3wxsyuz0t7.cloudfront.net` as false positive to them, it may take a few days for them to unflag it (as it's obviously not a malicious domain).
