### ISSUE TITLE
Problematic list.

### ISSUE THREAD

**Issue by usernamaewa** [nextdns/metadata#481]
Hi, it seems the block list in nextdns is very different with the actual block list, for example www.teslarati.com got blocked in nextdns with these block list: Easylist, Peter Lowe, Adguard Base Filter.

But, those block list actually is not blocking the website, when I actually test with nextdns off, just browser + ublock origin with the same list. Or browser + Adguard app. www.teslarati.com is not blocked.

As it is currently nextdns is unuseable. How?

**Comment by beerisgood** [comment]
The site works here with default NextDNS list.
If you get problems with external lists, you need to contact the maintainer

**Comment by usernamaewa** [comment]
Yes, what I mean is that that 3 external list I mention has no problem with the website I mention, I test it in ublock origin and adguard app, with nextdns off.

The problem is nextdns implementation of that 3 external lsit blocking the website.

**Comment by crssi** [comment]
Actually none of those lists are designed for DNS filtering.
That is why AdGuard have a special list designed just for DNS filtering named `AdGuard DNS filter`.

**Comment by usernamaewa** [comment]
Then what should I or other user do, only enable Adguard DNS filter on the privacy tabs? Or are there any other save to enable filter list?

Thanks.

**Comment by crssi** [comment]
I must take back what I have wrote, since I was not correct and I have jumped to conclusion too fast... Sorry. 😢 
You can or allowlist `ntv.io` or report upstream for corrections about `ntv.io`.
Or Romain can decide some other solution.

**Comment by beerisgood** [comment]
> Then what should I or other user do

Stay with default list which use a lot of sources already.

**Comment by usernamaewa** [comment]
Ok, I will stay at default list for now, but this is still an issue right? It's still open or should be closed because not an issue?

**Comment by crssi** [comment]
@usernamaewa see this https://github.com/nextdns/metadata/issues/461#issuecomment-735228550

**Comment by usernamaewa** [comment]
Okay, thanks man, I add this list, right now I'm browsing while looking at logs and compare to ublock origin and adguard app, and just removing problematic list.

**Comment by markangus2b** [comment]
I am also experiencing this same issue, very frustrating.  I use the Oisd blocklist and have noticed countless URLs being blocked in my NextDNS logs that aren't actually on the Oisd list.  I initially posted this issue on reddit.

https://www.reddit.com/r/nextdns/comments/k6su9s/blocklists_bug/?utm_medium=android_app&utm_source=share

**Comment by romaincointepas** [comment]
This is due to the blocking of CNAME (`ntv.io` in the case of teslarati).

@markangus2b same thing in your case. In the logs, after hovering the little red info icon on blocked domains, look out for **→ example.com**, this means one of the CNAME was blocked.
