### ISSUE TITLE
Qualtrics survey blocked

### ISSUE THREAD

**Issue by maXity** [nextdns/metadata#484]
I received an invitation to a survey from a travel agency with this link:

https://bcdtravel.iad1.qualtrics.com/jfe/form/SV_cI1RctlA8nQr2Xr?Q_DL=Mx3SFBZAXQ5iR1g_cI1RctlA8nQr2Xr_CGC_pVEksAEj3m5m8Mm&Q_CHL=email

Although the survey itself is a legitimate business website, the qualtrics domain is blocked by NextDNS:

![image](https://user-images.githubusercontent.com/23332112/100693631-5a6eeb00-339e-11eb-9ffe-cb38e2c820bc.png)

**Comment by romaincointepas** [comment]
`bcdtravel.iad1.qualtrics.com` doesn't seem to be blocked by our list anymore (even if blocked by so many others). Tell me if that's not the case on your side and I will reopen.
