### ISSUE TITLE
Tubi False Positive

### ISSUE THREAD

**Issue by zamarax** [nextdns/metadata#488]
Seems like Tubi is being included in the block list, it's a false positive as it crashes the app, I had to whitelist

`*.production-public.tubi.io`

In order to get it to load without crashing the app, this app crash happens on all platforms.

**Comment by romaincointepas** [comment]
<img width="305" alt="Screen Shot 2020-12-12 at 9 04 02 AM" src="https://user-images.githubusercontent.com/797899/101978912-05ae5880-3c59-11eb-9dbe-1a00e044af0b.png">

This is being blocked by a lot of blocklists. Ideally, could you report this to at least Steven Black?).
