### ISSUE TITLE
Xda-Forums New App being blocked

### ISSUE THREAD

**Issue by sbcrumb** [nextdns/metadata#490]
Recently Xda Forums went through a upgrade to a new platform and a new android app was released. And NextDNS is causing issues, if I use other DNS providers no issues. Or if I turn off all block lists and all security features no issues.
Now I see nothing in the log for the device that suggests what list of action is causing the block to happen. But attached is the error.

![Screenshot_20201208-093647_XDA_Developers (1)](https://user-images.githubusercontent.com/5639759/101508512-c379d400-3945-11eb-94f1-53add229788e.png)

**Comment by beerisgood** [comment]
This looks more like a issue with showing a custom warning site for blocked HTTPS site.
Disable that in account settings and test again.

**Comment by sbcrumb** [comment]
Wow you are right I turned that off( don't recall turning it on.) and it seems to be as it should be.. Thank you.
