### ISSUE TITLE
mail.tutanota.io

### ISSUE THREAD

**Issue by Snaxeko** [nextdns/metadata#491]
I wanted to check my mails on mail.tutanota.com (the right site), but instead I typed **"mail.tutanota.io",** which is a malware domain that redirects many times and then open a website that blocks your browser (through print window.open, hiding mouse...) or open a scam webpage fake news etc.
It could be a common mistake because Tutanota mails can take this form : XX@tuta.io

It's not about phishing, but a highly unwanted domain. Maybe it could be added to the typosquatting list.

**Comment by romaincointepas** [comment]
Could you suggest this to https://phishing.army?
