### ISSUE TITLE
Liste FR misinterpreted

### ISSUE THREAD

**Issue by Snaxeko** [nextdns/metadata#492]
NextDNS interprets wrongly this rule`||1873083787.rsc.cdn77.org^` , using this rule to block `1978974432.rsc.cdn77.org` (CNAME of DxoMark's CDN, ie `cdn.dxomark.com`).

NextDNS indicates that [ListeFR](https://easylist-downloads.adblockplus.org/liste_fr.txt) is blocking this domain. I tried to add`||1873083787.rsc.cdn77.org^` in uBO filters and Dxomark worked perfectly.

**Comment by romaincointepas** [comment]
Liste FR contains `||cdn77.org^$popup,third-party` as well, and we accept both `$popup` and/or `$third-party`. (and use exclusions when necessary).

I don't see the point in blocking an entire CDN root domain like `cdn77.org`, could you report this to them directly?

**Comment by Snaxeko** [comment]
I didn't mentioned this rule as it doesn't break DxoMark with Ublock origin (in Firefox & Chromium)... 
`||cdn77.org^$popup,third-party` won't do anything with `https://1978974432.rsc.cdn77.org/`. This rule only avoid cdn77 to open a popup when cdn77 is a third-party. What would break DxoMark would be the rule `||cdn77.org^$third-party`. 
The bug seems to be effectively related to NextDNS, which doesn't read well these adblock rules.

> we accept both $popup and/or $third-party

What does "accept" means ? How NextDNS translates this ? If this rule is causing an issue, then maybe NextDNS ignores adblock rules options and only see `cdn77.org`, so the DNS rule is actually something like `cdn77.org 0.0.0.0` ?

AFAIK, `||cdn77.org^$popup,third-party` only blocks popups **_if_** `cdn77.org` is a third-party. 
It **doesn't** block this domain as a third-party _and_ popups from this domain.
That's why setting 2 rules `||cdn77.org^$third-party` + `||cdn77.org^$popup` breaks Dxomark, but not the previous rule alone.

I can't report this to them as this rule doesn't break anything if used through uBO... This list just cannot be used properly with NextDNS.
