### ISSUE TITLE
StopModReposts

### ISSUE THREAD

**Issue by berrysauce** [nextdns/metadata#493]
Reposting is a big problem in the modding communities. That's we've united modders under the StopModReposts campaign. These fake modding sites are often malicious and can cause harm to the user's machine. More on that on our [homepage](https://stopmodreposts.org).

We already have browser extensions, but integrating our list(s) directly into a service like NextDNS would likely be more practical for a lot of people.

Link: https://github.com/StopModReposts/Illegal-Mod-Sites

Note: We have multiple lists for multiple games. If you'd like a complete one, we've got an API (https://github.com/StopModReposts/Illegal-Mod-Sites/wiki/API-access-and-formats).

**Comment by berrysauce** [comment]
Any updates @romaincointepas? Thanks!

**Comment by romaincointepas** [comment]
I don't feel like this fits in Security or Privacy, and could be confusing. But we will keep this in mind.
