### ISSUE TITLE
False positive - Threat Intelligence Feeds - covid19criticalcare.com

### ISSUE THREAD

**Issue by jrakz** [nextdns/metadata#494]
The website covid19criticalcare.com is included in the Threat Intelligence Feeds blocklist. This is a false positive. The website is legitimate and is the official website of the Frontline COVID-19 Critical Care Alliance (FLCCC). Please remove immediately.

**Comment by crssi** [comment]
It comes from upstream form one or more of the lists here https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json

**Comment by crssi** [comment]
Specifically here: https://kriskintel.com/feeds/ktip_covid_domains.txt

Report here: https://kriskintel.com/

**Comment by jrakz** [comment]
Thank you, unfortunately there's no apparent way to report it to them since the site lacks contact information. Any way to exclude their list completely? Seems they aren't doing sufficient due diligence.

**Comment by Snaxeko** [comment]
I agree, no way to contact them --> Their list should be removed from threat intelligence NextDNS list.

**Comment by romaincointepas** [comment]
Seems to have fixed itself, closing.
