### ISSUE TITLE
Feature requests : DoQ (dns over quic)

### ISSUE THREAD

**Issue by michaelb-ae** [nextdns/metadata#497]
hello i ask here since i don't have seen a repository for the "core" of your nextdns.
I want to know if its possible for you to implement the dnsproxy of adguard, who will permit you to provide us dns over quic, i know it's experimental but in some network and correct configuration it's better in speed than tls or https.

**Comment by timkgh** [comment]
I asked for the same here
https://github.com/nextdns/nextdns/issues/390

**Comment by michaelb-ae** [comment]
oh thanks i will close this since it's not it's place thanks @timkgh
