### ISSUE TITLE
DNS Rebinding Protection blocks localhost resolution

### ISSUE THREAD

**Issue by timkgh** [nextdns/metadata#498]
`localhost` should be allowed and should return `127.0.0.1` and `::1`, nothing good comes out of returning `0.0.0.0`

Normally these queries shouldn't end up on the DNS server, but buggy devices still send them.

**Comment by timkgh** [comment]
@romaincointepas

**Comment by beerisgood** [comment]
Can confirm this with my HP printer.

**Comment by timkgh** [comment]
I added `localhost` to the Allowlist for now. Or you can add it as a Rewrite in Settings.

**Comment by romaincointepas** [comment]
For those with this issue, please add it as a rewrite if needed, it doesn't feel right to return custom answers for edge cases like this one.

**Comment by timkgh** [comment]
@romaincointepas Not sure I understand your reply. The NextDNS servers return a valid answer for `localhost` without DRP enabled:
```
> dig @45.90.30.0 localhost

;; ANSWER SECTION:
localhost.		10800	IN	A	127.0.0.1
```

Maybe they should not resolve `localhost` at all?

**Comment by romaincointepas** [comment]
@rs should we return something for `localhost`?

**Comment by rs** [comment]
I guess we should not

**Comment by timkgh** [comment]
Just curious, anything bad about resolving localhost to 127.0.0.1 and ::1 ? The request already made it there, and it's pretty clear what it should return. Stub resolvers like dnsmasq and nextdns cli will resolve it too if they process /etc/hosts on whatever host they are running on.
