### ISSUE TITLE
Add Fanboy / EasyList Cookies List

### ISSUE THREAD

**Issue by aetha** [nextdns/metadata#502]
Hi, I'm very tired of all these cookie notices, and wanting to try a list to filter them. Wondering if you could add the one that Fanboy / EasyList provides?

https://secure.fanboy.co.nz/fanboy-cookiemonster.txt

**Comment by beerisgood** [comment]
First this list doesn't work with DNS as DNS can't hide website elements.

Second such list doesn't make sense at all as in worst case the site use all Cookies instead of your chosen one(s) which means you get worse privacy instead of better without blocking.

**Comment by romaincointepas** [comment]
@beerisgood is right, unfortunately this list can't be used at the DNS level.
