### ISSUE TITLE
Oisd Abuse

### ISSUE THREAD

**Issue by cloudyytechie** [nextdns/metadata#503]
The blocklist oisd is abusing the blocklist it’s blocking lots of domains that have nothing to do with tracking or malware 
https://cdn.discordapp.com/attachments/772904251348484156/792757181518446592/image0.png

**Comment by cloudyytechie** [comment]
I have reported it to the oisd team

**Comment by crssi** [comment]
The OISD team is aware of it and working on a solution now.
It will be sorted out soon as I understood.

Cheers

**Comment by cloudyytechie** [comment]
Thank you so much :)

**Comment by crssi** [comment]
I have been informed that it is fixed now.

Cheers
