### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ignoramous** [nextdns/metadata#504]
Hi Romain,

Apologies if this was discussed already, but I couldn't find it anywhere. We are users of these lists through NextDNS. We also want to be able to use this in our open-source projects, but the lack of license is worrying.

I see that you're not the only committer to the repository so you / NextDNS may not own all the copyrights and this makes (re-)licensing a bit difficult but nothing that can't be worked out. The later licensing decision is punted to the more complicated it is going to get.

As such, I implore you to consider releasing the content here-in under a permissive license of your choosing with approvals from the contributors to this repository. I'd say CC-0 or CC-by-SA are good enough, but you may have other ideas.

**Comment by PeterDaveHello** [comment]
#49 ?

**Comment by romaincointepas** [comment]
We are spliting this monorepo, new repos will have their own license.
