### ISSUE TITLE
False positive: Netguard.me blocked by Threat Intelligence Feeds

### ISSUE THREAD

**Issue by drewblasphemepatchwork** [nextdns/metadata#508]

**Comment by romaincointepas** [comment]
@stamparm is there a reason why `netguard.me` is listed in https://github.com/stamparm/aux/blob/master/maltrail-malware-domains.txt?

**Comment by stamparm** [comment]
@romaincointepas that's an ancient domain classified by https://malwared.malwaremustdie.org/ as `netguard`. I could research a bit on why it was blacklisted in the first place, but currently I have mixed feelings

**Comment by stamparm** [comment]
![1](https://user-images.githubusercontent.com/921555/103566776-ea82e180-4ec2-11eb-8603-f1900e7cce97.png)

Reference:
https://vimeo.com/97519113

**Comment by stamparm** [comment]
Ok. Decided to remove that ancient source completely as I had same urge to do it months ago. Anyhow, from this moment that same domain should not appear there anymore

**Comment by drewblasphemepatchwork** [comment]
Thanks. Closing this now

**Comment by romaincointepas** [comment]
@stamparm thanks for jumping in!
