### ISSUE TITLE
False positive: Visual Studio Code zip package download blocked

### ISSUE THREAD

**Issue by zmni** [nextdns/metadata#511]
`az764295.vo.msecnd.net` blocked by NextDNS Recommended Ads & Trackers Blocklist.

Full address: `https://az764295.vo.msecnd.net/stable/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/VSCode-win32-x64-1.52.1.zip`

Thank you.

**Comment by romaincointepas** [comment]
Seems to have fixed itself, can you confirm?

**Comment by zmni** [comment]
Yes, fixed. Thanks.
