### ISSUE TITLE
False Positive: download.sysinternals.com / az725175.vo.msecnd.net

### ISSUE THREAD

**Issue by beerisgood** [nextdns/metadata#512]
This is the official binary download domain from Microsoft's Sysinternals tools.

E.g.  `https://download.sysinternals.com/files/Autoruns.zip` from `https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns`

![image](https://user-images.githubusercontent.com/9625159/103439276-b3e76580-4c3b-11eb-8df6-b66038e7207b.png)

**Comment by romaincointepas** [comment]
Seems to have fixed itself, can you confirm?

**Comment by beerisgood** [comment]
Looks good so far!
