### ISSUE TITLE
SearX search engines should be added to "Safesearch-not-supported" list.

### ISSUE THREAD

**Issue by ACodingGenie** [nextdns/metadata#514]
I made a list of all the SearX engines which do not support Safesearch enforcement as far as I know. I got these straight from their GitHub repo and included only the domains. They also have some .onion domains which are not included below. Some of the endpoints also allow you to proxy the search results bypassing any DNS filters. 

List: [Searx.txt](https://github.com/nextdns/metadata/files/5759998/Searx.txt)

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/7471e05e03dc3a556efbdc5cff206eaff10aeed8, thanks!
