### ISSUE TITLE
NextDNS blocklist breaking amazon devices

### ISSUE THREAD

**Issue by alysson-silva** [nextdns/metadata#516]
Hi, two days ago all my echo devices stopped working. It seems the problem is with the `NextDNS Ads & Trackers Blocklist`? One way I found to fix the issue without disabling the whole blocklist was to add the `avs-alexa-14-eu.amazon.com` domain to the allow list.

![Untitled](https://user-images.githubusercontent.com/297559/103456381-5f9cbe00-4ced-11eb-860e-62191401a29e.png)

**Comment by romaincointepas** [comment]
Seems to have fixed itself, can you confirm?

**Comment by alysson-silva** [comment]
Yeah, the issue has been solved. Thank you.
