### ISSUE TITLE
False positive - myplate.gov and choosemyplate.gov blocked as porn

### ISSUE THREAD

**Issue by timothyhull** [nextdns/metadata#518]
Using only the **NextDNS Ads & Trackers Blocklist**, NextDNS blocks www.myplate.gov and www.choosemyplate.gov.  These are legitimate websites.

<img width="573" alt="Screen Shot 2021-01-04 at 12 41 03 PM" src="https://user-images.githubusercontent.com/22779364/103577762-39f8eb80-4e8a-11eb-9aff-df955994c911.png">

**Comment by crssi** [comment]
By the screenshot you provided it is blocked by Porn category, which might be wrong.
