### ISSUE TITLE
AdGuard Annoyances Filter - Mobile App Only

### ISSUE THREAD

**Issue by CB-wee** [nextdns/metadata#521]
This filter can be used to block banners of mobile apps for the sites, for example, Reddit's app banner on the mobile site.

I am not sure about if these banners can be blocked with DNS, please add support for this filter if possible.

https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/mobile-app.txt

https://github.com/AdguardTeam/AdguardFilters

**Comment by beerisgood** [comment]
Such filter doesn't work with DNS.
DNS can only handle domains and TLDs.
