### ISSUE TITLE
recategorize img1.wsimg.com (currently listed as porn)

### ISSUE THREAD

**Issue by XzeroR3** [nextdns/metadata#525]
When trying to sign into Godaddy @ https://sso.godaddy.com/?realm=idp&path=%2fproducts&app=account the site will not load due to img1.wsimg.com being marked as porn, once I whitelisted the domain, I could login into GoDaddy.  
![image](https://user-images.githubusercontent.com/49564480/103937310-d3700980-50e5-11eb-9d4b-099322f1045b.png)

**Comment by spirillen** [comment]
You should be good to go with a fresh version, I have removed the domain from the porn list. However you should be aware that this domain is used for serving adult ads / contents and therefor most likely will reappear at some point

You can find the log here: https://www.mypdns.org/T1404
