### ISSUE TITLE
False positive: cdn.iubenda.com

### ISSUE THREAD

**Issue by vin047** [nextdns/metadata#527]
`cdn.iubenda.com` is blocked, which prevents usage of their auto-updated privacy policy feature.

**Comment by scafroglia93** [comment]
The case of iubenda is particular in that if blocked it prevents spam inherent in the cookie selection screen.

The advice is to take advantage of the whitelist function

or

use this setting without Steven Black list ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

**Comment by romaincointepas** [comment]
Please report this directly to Steven Black at https://github.com/StevenBlack/hosts.
