### ISSUE TITLE
Blocklist Suggestion - Conspiracy Theories 

### ISSUE THREAD

**Issue by northmendo** [nextdns/metadata#533]
https://raw.githubusercontent.com/dnsblocklistnet/blocklists/master/conspiracy.list

**Comment by northmendo** [comment]
[https://raw.githubusercontent.com/dnsblocklistnet/blocklists/master/conspiracy.list](url)

**Comment by Cybo1927** [comment]
If I may pitch in, these lists seem problematic for something like NextDNS to add because of how political they are. Parler, Gab, Bitchute, and 8Kun are 4 entries that would most likely have to be whitelisted as they're free speech platforms and not specifically for the spreading of conspiracies.

**Comment by northmendo** [comment]
I see your point there. Being able to add custom lists would solve it. There are legit reasons for the list, I.E. workplaces.

**Comment by michaelb-ae** [comment]
since blocklist are facultative i'm for it !

**Comment by romaincointepas** [comment]
Blocklists should be privacy-related.

**Comment by Macqael** [comment]
So you tell us to add tousand of domain manually, if you start to filter witch list can or cannot be added and/or you don't let us the choice to add them manually i don't really think your services will be used by many.
Time to mount my own server i think.
