### ISSUE TITLE
textsecure-service.whispersystems.org blocked by DNS Rebinding

### ISSUE THREAD

**Issue by nishaddesilva** [nextdns/metadata#540]
textsecure-service.whispersystems.org domain is blocked by DNS Rebinding Protection. Is this a mistake or am I missing something?
![HYogMO](https://user-images.githubusercontent.com/74057395/104760235-15085080-5787-11eb-9313-7c13cd431c74.png)

**Comment by crssi** [comment]
You are missing something. ;)

![image](https://user-images.githubusercontent.com/17024151/104761043-3272f580-575a-11eb-85be-ce126fe7ddad.png)

**Comment by nishaddesilva** [comment]
> You are missing something. ;)
> 
> ![image](https://user-images.githubusercontent.com/17024151/104761043-3272f580-575a-11eb-85be-ce126fe7ddad.png)

Any idea why this is happening?

**Comment by crssi** [comment]
That is the question for site owner/dns admin.

**Comment by Cybo1927** [comment]
https://status.signal.org/

Signal has been down for some time now...

**Comment by crssi** [comment]
If you follow the news, the signal is overwhelmed ATM since a lot of WhatApp users are fleeing to signal, due to change of EULA from shitty FB.

And your question again has nothing to do with NextDNS it self. This is now at the edge of spamming. 😉

**Comment by romaincointepas** [comment]
The DNS Rebinding security feature blocks domain resolving to local IP, this is working as expected.
