### ISSUE TITLE
Add "Geoffrey Frogeye's block list of first-party trackers"

### ISSUE THREAD

**Issue by Youngblood50** [nextdns/metadata#545]
It is actually based on the NextDNS First-party blocklist. It is regularly updated. 
Website: https://hostfiles.frogeye.fr/
Blocklist (hosts file): https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
Blocklist (raw): https://hostfiles.frogeye.fr/firstparty-trackers.txt

**Comment by romaincointepas** [comment]
NextDNS is able to both wildcard-block and block at the CNAME level, so https://github.com/nextdns/cname-cloaking-blocklist is enough (and better).
