### ISSUE TITLE
thepiratebay.org (false alarm)

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#547]
![image](https://user-images.githubusercontent.com/19517680/105189169-4312d980-5b67-11eb-942f-a53f5a890a75.png)

**Comment by romaincointepas** [comment]
Could you please submit the removal request directly at the source at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi?

**Comment by 3xploiton3** [comment]
> Could you please submit the removal request directly at the source at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi?

done
