### ISSUE TITLE
Allow recreation time on denylist

### ISSUE THREAD

**Issue by thetimetraveler** [nextdns/metadata#549]
Currently services under parental control support recreation time feature however the feature is limited only for services available. I would like to propose that the recreation time feature be available on denylist tab as well so users are allowed to set recreation time for custom services. 

Furthermore, I would like to see a more advanced recreation time feature that allows custom configuration on a per host basis.

**Comment by romaincointepas** [comment]
Duly noted. Closing as this repo is not for feature request (https://help.nextdns.io/ is better for this).
