### ISSUE TITLE
False Positive in Simple Mode - Whitelist request

### ISSUE THREAD

**Issue by jd1ddy** [nextdns/metadata#55]
The popular UK Classified Site - Gumtree (owned by eBay) is blocked whilst using Simple Mode lists.

It is categorised as an Ad/Tracker domain.

Please globally whitelist: gumtree.com

Cheers!
![Screenshot (3)](https://user-images.githubusercontent.com/20308625/72687809-9805b500-3af9-11ea-894f-cc17f6451141.png)

**Comment by jd1ddy** [comment]
I've observed an additional issue with the Ad & Tracker list. The following Microsoft domains are essential to the operation of the Xbox One console:

v10.events.data.microsoft.com
settings-win.data.microsoft.com

Whilst these domians are blocked, error messages appear on the console. 
I'm aware these domains are associated with trackers from Microsoft, but these do seem to interfere with connectivity on the console (Specifically Game Save syncronisation and Achievements. 

Just a suggestion, but would it be possible for the user to have a whitelist option for instances such as Game Consoles?

You can read more on this specific issue here (Referencing a PiHole blocklist): [Reddit (r/pihole)](https://www.reddit.com/r/pihole/comments/c4bgjr/xbox_one_keep_getting_local_cache_is_full_cant/)

Cheers!

**Comment by romaincointepas** [comment]
`gumtree.com` is only blocked by https://github.com/jerryn70/GoodbyeAds. We do not interfere with blocklists, so feel free to discuss that on their repo directly.

Regarding the microsoft domains, we've whitelisted them for the NextDNS Recommended blocklist, but they are still blocked by (quite a few) blocklists. And again, we don't interfere with those.

We will think about that Game Consoles setting!
