### ISSUE TITLE
Please add gab.com ASAP to parental control. It is a QAnon safe-haven.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [nextdns/metadata#550]
`gab.com` is a QAnon safe haven that knowingly disseminates conspiracy theories aimed at toppling the U.S. government.

**Comment by quantumpacket** [comment]
> ...aimed at toppling the U.S. government.

Your profile status states you're an anarchist, but you're so worried about toppling a government. :man_facepalming: 

But back on-topic, let's aim to keep NextDNS like Switzerland, neutral and not becoming politicized. If someone wants to block platform _xyz.com_, then they have the ability to do so by adding the site anytime to the _Denylist_.

**Comment by romaincointepas** [comment]
Please use the Denylist for this.

**Comment by Voltairine-de-Cleyre** [comment]
... anarchist : yes, that's correct. I'll not bother to explain what anarchism is. I'm also antifascist. And most obviously anti-Nazism. Is that an issue as well? May I ask that parents' children not be exposed to QAnon? Have you an understanding of what it is? It's a cult. It behaves as a religion as a front for its propaganda. Don't let NextDNS become politicized? It has been since it's beta release. If I said QAnon is a "social network" would it then be okay to have it added to parental controls? Hitter 1923 failed coup; used the knowledge gathered from it to succeed "democratically" which is BS - it was a coup, a "soft" one if that term is preferable to sensitivities. As anarchist, I certainly don't want safe havens for Nazis by whatever name you want to apply to them. White Supremacist, White Nationalists, KKK, Neo-Nazis, QAnon : it's all the same message dressed up in different clothes & using various names. If NextDNS supports that message, then I can no longer support NextDNS with my $$$ nor will most. Talking about it watered down with terms like protest or riot, being okay with Nazis & moreover being okay living in the world that Nazis want is disgusting.But back on topic, Gab is a social network. Now can it be added to Parental Controls? On Mon, Jan 25, 2021 at 10:35, 0ri0n <notifications@github.com> wrote:  

...aimed at toppling the U.S. government.

Your profile status states you're an anarchist, but you're so worried about toppling a government. 🤦‍♂️
But back on-topic, let's aim to keep NextDNS like Switzerland, neutral and not becoming politicized. If someone wants to block platform xyz.com, then they have the ability to do so by adding the site anytime to the Denylist.

**Comment by Voltairine-de-Cleyre** [comment]
Edit: Hitler: 1923.

**Comment by romaincointepas** [comment]
@Voltairine-de-Cleyre Gab is not popular enough to make it to the individual service section. It should be in the Social Networks category though, if it's not feel free to suggest directly at the source at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi.

**Comment by Voltairine-de-Cleyre** [comment]
> @Voltairine-de-Cleyre Gab is not popular enough to make it to the individual service section. It should be in the Social Networks category though, if it's not feel free to suggest directly at the source at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi.

This is your company. It's not mine. I paid a full year but deleted my account due to you thinking gab has little influence. Gab is where most of Jan 6th was planned. I should know, after having helped the FBI track down the Nazis via Twitter. You'd put gab on NextDNS if you waded into the hell I did to find these scum.
