### ISSUE TITLE
Multiple wrong NRD blocks 

### ISSUE THREAD

**Issue by Kage1** [nextdns/metadata#552]
Hello,

I'm seeing a lot of blocks in my logs for NRD for domains that have been register for years. 

Some examples:
api.ambientweather.netA
Blocked by Newly Registered Domains (NRDs).

Whois info
Updated Date: 2020-08-02T04:39:15Z
   Creation Date: 2016-08-31T17:36:49Z

msedge.netDS
Blocked by Newly Registered Domains (NRDs).

Whois info
Updated Date: 2020-02-13T10:32:25Z
   Creation Date: 2012-03-16T16:15:02Z

I'm sure there are more, but the ambientweather.net caught my attention due to my weather station stopped reporting.

**Comment by Kage1** [comment]
One more:

omt.garmin.comAAAA
→ omt.garmin.com.cdn.cloudflare.net | Blocked by Newly Registered Domains (NRDs).

**Comment by crssi** [comment]
There must have been temporarily something wrong with the upstream source at the time, since I can't see any problems ATM from here.

Cheers

**Comment by beerisgood** [comment]
Related:
https://www.reddit.com/r/nextdns/comments/l4d5ch/nrd_list_error/

**Comment by romaincointepas** [comment]
See our response on https://help.nextdns.io/t/y4hzhj6/false-positives-on-nrds.
