### ISSUE TITLE
Porn site not blocked

### ISSUE THREAD

**Issue by atwr2d2** [nextdns/metadata#553]
nextdoorraw.com is not being blocked by the porn filter.

**Comment by 3xploiton3** [comment]
> nextdoorraw.com is not being blocked by the porn filter.

add in here
https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi

**Comment by spirillen** [comment]
added in https://www.mypdns.org/T3439 and will be released by next build of clefspare13/pornhost

**Comment by spirillen** [comment]
Should be in this release https://github.com/Clefspeare13/pornhosts/commit/0dfb6ae3322ac378664e395f6b6d69f789ae8459

**Comment by romaincointepas** [comment]
What @3xploiton3 said.
