### ISSUE TITLE
s.media-imdb.com [false alarm]

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#559]
![image](https://user-images.githubusercontent.com/19517680/106390739-6ae22700-641c-11eb-8a91-3e72a2a7cb71.png)
![image](https://user-images.githubusercontent.com/19517680/106390754-79c8d980-641c-11eb-8a15-5b46eebff0a5.png)

block images from imdb

**Comment by romaincointepas** [comment]
Could you please report this to Steven Black directly at https://github.com/StevenBlack/hosts?
