### ISSUE TITLE
False positive: files.slack.com

### ISSUE THREAD

**Issue by mu373** [nextdns/metadata#561]
`files.slack.com` is blocked by NextDNS Ads & Trackers Blocklist. Files (images) on Slack can not be loaded/uploaded.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/2176670/106429570-f35cd800-64ad-11eb-83e6-86479fb94973.png">

**Comment by carlylemiii** [comment]
I'd be interested in knowing how something like this got added. 🤔

**Comment by mu373** [comment]
Maybe related to this.

> @AdamSurak: If you see problems with files in @SlackHQ, that could be because https://osint.digitalside.it started to include "http://files.slack.com" on their IoC list. Slack files are starting to be used for malware distribution (saw it first hand last week). Tune your pihole accordingly
https://twitter.com/AdamSurak/status/1356152687289655297

**Comment by romaincointepas** [comment]
Fixed, whitelisted on our side.

It was falsely blocked by https://github.com/StevenBlack/hosts, one of the sources of the *NextDNS Ads & Trackers Blocklist*.

Always whitelisted from TI feeds.

**Comment by mu373** [comment]
@romaincointepas Thank you for the quick fix. Closing this issue as the problem has now been resolved.
