### ISSUE TITLE
Threat Intelligence -> Alphasoc Ryuk

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#562]
Source ->
https://alphasoc.com/

List ->
https://feeds.alphasoc.net/ryuk.txt

**Comment by scafroglia93** [comment]
Waiting for info

**Comment by scafroglia93** [comment]
@romaincointepas

**Comment by scafroglia93** [comment]
It's possible add this to Threat Intelligence Feeds sections ?

**Comment by scafroglia93** [comment]
Waiting for approval

**Comment by romaincointepas** [comment]
@scafroglia93 Sorry for coming down hard on you today, but we would really like to keep you here as we appreciate your help. But please do not add comment like this, it spams watchers of this repo and won't change a thing.

We are busy working hard on many other NextDNS things and we can't always react quickly, and we don't mind getting others input as well on things like this.
