### ISSUE TITLE
False Positive (Porn) - www.eonline.com

### ISSUE THREAD

**Issue by Nisten-netizen** [nextdns/metadata#564]
Entertainment Online (www.eonline.com) is a source of entertainment news, celebrities, celebrity news, and celebrity gossip; shouldn't be blocked as porn

![image](https://user-images.githubusercontent.com/76894165/106789606-17d4c380-6618-11eb-955e-3490170c2efa.png)

**Comment by bpjones** [comment]
Resolved upstream via this issue:  https://github.com/mhxion/pornaway/issues/17
