### ISSUE TITLE
[whitelist] oasjs.kataweb.it

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#566]
this domain is used by one of the most important Italian newspapers for the use of the videos on their site

Main site ->
https://www.repubblica.it/

It's the same issue related to the other domain: it was whitelisted but nextdns block this

**Comment by crssi** [comment]
With your list selection/nextdns config you will hit a lot of breakages.
Looking at your nextdns settings that is... see mine. 😉
Some of those are useless and some of those are already covered by OISD where breakages are excluded.

Cheers

**Comment by scafroglia93** [comment]
> 
> 
> With your list selection/nextdns config you will hit a lot of breakages.
> Looking at your nextdns settings that is... see mine. 😉
> Some of those are useless and some of those are already covered by OISD where breakages are excluded.
> 
> Cheers

It was updated, the problem was related to easylist and easylist italy where nextdns also includes excluded domains
