### ISSUE TITLE
[false positive] post.spmailtechno.com

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#568]
![image](https://user-images.githubusercontent.com/19517680/107144676-5697b000-696f-11eb-8305-2a82dc97da08.png)

break function email confirmation from codewars.com
![image](https://user-images.githubusercontent.com/19517680/107144698-7dee7d00-696f-11eb-8aeb-6ff388b6b960.png)

**Comment by StevenBlack** [comment]
Take note that in Issue https://github.com/StevenBlack/hosts/issues/1532 we decided to keep blocking domain `post.spmailtechno.com`.

**Comment by crssi** [comment]
@3xploiton3 that is exactly the reason to avoid default selection.
Go for 1Host (Lite) + OISD instead... you will get more coverage with much much less breakage.

It is just my humble opinion. 😉 

Cheers
