### ISSUE TITLE
porn.json (PR on it's way...)

### ISSUE THREAD

**Issue by spirillen** [nextdns/metadata#569]
Do to the [issue](https://github.com/Clefspeare13/pornhosts/issues/347) at Clefspeare13 pornhosts, I found this repo, which is using the lists as sources for adult content 

However I can see that the following domains, which you have added manually as addition seems to be covered by my adult-records lists. A few are missing, but I have made the issues at my board, so I can add them if they are confirmed.

  - [X] [awemdia.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L47) however, they are listed here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29awemdia.com>, Issue <https://www.mypdns.org/T1768>

  - [X] [babes.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L48) is added here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29babes.com>, Issue: <https://www.mypdns.org/T1415>

  - [X] [hotgaylist.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L49) is listed here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29hotgaylist.com>, Issue: <https://www.mypdns.org/T1422>

  - [x] [niceteentubes.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L50) is to be added by [this issue](https://www.mypdns.org/T3426)

  - [X] [peeperz.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L51) Is listed here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29peeperz.com>, Issue: <https://www.mypdns.org/T1424>

  - [X] [playboytv.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L52) Is added here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29playboytv.com>, Issue: <https://www.mypdns.org/T1430>

  - [X] [porniq.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L53) Is added here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29porniq.com>, Issue: <https://www.mypdns.org/T1444>

  - [ ] [pornlaser.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L54) Will be added with [this issue](https://www.mypdns.org/T3427) (if active)

  - [X] [sextube.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L55), is already added here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29sextube.com>, Issue: <https://www.mypdns.org/T1448>

  - [X] [skipthegames.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L56) Already added here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29skipthegames.com>, Issue: <https://www.mypdns.org/T1451>

  - [X] [sukebei.nyaa.net](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L57) Already added here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29nyaa.net>, Issue 1(master): <https://www.mypdns.org/T2811>, Issue 2 (doublet): <https://www.mypdns.org/T2987>

  - [x] [teen-xxx-videos.net](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L58) will be added with [this issue](https://www.mypdns.org/T3428) (if active)

  - [x] [teen18pussy.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L59) Will Be added with [this issue](https://www.mypdns.org/T3429) If Active)

  - [x] [teenafterteen.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L60) Will be added by [this issue](https://www.mypdns.org/T3430) (If Active)

  - [x] [teenfreshporn.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L61) Will be added with [this issue](https://www.mypdns.org/T3431) (If Active)

  - [x] [teenliketube.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L62) To be added by [this issue](https://www.mypdns.org/T3432) (IF confirmed)

  - [x] [teenlovestube.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L63) Will be added with [this issue](https://www.mypdns.org/T3433) (If confirmed)

  - [X] [viptube.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L64) Is already added: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29viptube.com>, Issue: <https://www.mypdns.org/T1449>

  - [X] [vptpsn.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L65) Already listed here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29vptpsn.com>, Issue: <https://www.mypdns.org/T1450>

  - [X] [whynotbi.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L66) Already listed here: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29whynotbi.com>, Issue: <https://www.mypdns.org/T1454>

  - [x] [xhcdn.com](https://github.com/spirillen/metadata/blob/874e9afd27d243cfeda5e0d8cb1fcbf67e64a4b3/parentalcontrol/categories/porn.json#L67) partly added, as it is not confirmed all records have been found: <https://www.mypdns.org/source/PornRecords/browse/master/?grep=%28%5E%7C%5C.%29xhcdn.com>, OPEN Issue: <https://www.mypdns.org/T2273>

**Comment by spirillen** [comment]
To follow up on this issue, I can confirm all existing records but one

`pornlaser.com` Does not have a NS record at the time of testing [T3427](https://www.mypdns.org/T3427)


This means, if anybody are able to obtain a NS record **AND** post screenshots within the issue mention previously, it will be added to the source. (You simply signup with your github account, that way I only have your nick and unfortunately your email :sob: ) A side note to this, when signed up, please go to your account settings and disable ALL email notifications or phabricator "spams" you with every changed bits like another Github/Gitlab

```console
drill -T pornlaser.com
.       518400  IN      NS      a.root-servers.net.
.       518400  IN      NS      b.root-servers.net.
.       518400  IN      NS      c.root-servers.net.
.       518400  IN      NS      d.root-servers.net.
.       518400  IN      NS      e.root-servers.net.
.       518400  IN      NS      f.root-servers.net.
.       518400  IN      NS      g.root-servers.net.
.       518400  IN      NS      h.root-servers.net.
.       518400  IN      NS      i.root-servers.net.
.       518400  IN      NS      j.root-servers.net.
.       518400  IN      NS      k.root-servers.net.
.       518400  IN      NS      l.root-servers.net.
.       518400  IN      NS      m.root-servers.net.
com.    172800  IN      NS      i.gtld-servers.net.
com.    172800  IN      NS      f.gtld-servers.net.
com.    172800  IN      NS      j.gtld-servers.net.
com.    172800  IN      NS      l.gtld-servers.net.
com.    172800  IN      NS      k.gtld-servers.net.
com.    172800  IN      NS      b.gtld-servers.net.
com.    172800  IN      NS      h.gtld-servers.net.
com.    172800  IN      NS      c.gtld-servers.net.
com.    172800  IN      NS      e.gtld-servers.net.
com.    172800  IN      NS      a.gtld-servers.net.
com.    172800  IN      NS      d.gtld-servers.net.
com.    172800  IN      NS      m.gtld-servers.net.
com.    172800  IN      NS      g.gtld-servers.net.
com.    900     IN      SOA     a.gtld-servers.net. nstld.verisign-grs.com. 1612808157 1800 900 604800 86400
```

**Comment by romaincointepas** [comment]
We will be handling our Porn category in-house very soon, closing as to not waste anyone's time.

**Comment by spirillen** [comment]
hey @romaincointepas 

How about we collected our resources and made a shared list/project for the topic in question, the reason is it is a huge field with a lot of sited, and a bigger demand for maintaining several forms of lists/zone types to just an equal big number of different software?

The most important must be to have only human verified records on an/the active lists for other to extract to meed there needs.

Are you and your fellowmen open minded for this suggestion?
