### ISSUE TITLE
Block lists should be sorted in alphabetical order?

### ISSUE THREAD

**Issue by le0mil** [nextdns/metadata#570]
Hello,

Sorting the lists would make the list easier to read and aloso easier to choose the lists you were looking for.

Another solution could be categorizing them in groups. Eg. All EasyList lists under one category, or all Malware-related lists under Security/Malware category etc..

**Comment by ClusterByte-x** [comment]
It should definitely be arranged with lists similar to each other (EasyList etc.). Also, I think the user could select specific TIF sources (all enabled by default).

**Comment by scafroglia93** [comment]
You can use this for alphabetical order ->
https://github.com/hjk789/NXEnhanced

**Comment by romaincointepas** [comment]
Right now it's ordered by popularity on NextDNS, we will improve the UI soon with filters, country-specific blocklists, etc.
