### ISSUE TITLE
Two sets of very effective lists which should be considered

### ISSUE THREAD

**Issue by le0mil** [nextdns/metadata#571]
Malicious domains:

https://raw.githubusercontent.com/stamparm/blackbook/master/blackbook.txt (This is probably already included in Maltrail list.)

**Comment by scafroglia93** [comment]
Most of this lists are already present inside nextdns feeds

**Comment by le0mil** [comment]
@scafroglia93 It seems to. Didn't know that they were at the threat intelligence feeds. :)

I have removed duplicate lists so @romaincointepas can have a look at the ones which are missing.

**Comment by le0mil** [comment]
I have removed the duplicated lists. Forgot to have a look at the Threat Intelligence Feeds before posting. Sorry!
