### ISSUE TITLE
[False Positive] Why is Urban Dictionary blocked by Dating category of Parental Control?

### ISSUE THREAD

**Issue by gracjankn** [nextdns/metadata#572]
I think, `urbandictionary.com` should be removed from the Dating category.

**Comment by lyrad87** [comment]
I believe this should be reported to [https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi](https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi) since NextDNS sources from there.

**Comment by crssi** [comment]
I have reported it at the source, here https://github.com/olbat/ut1-blacklists/issues/8

Cheers

**Comment by gracjankn** [comment]
> I have reported it at the source, see https://github.com/olbat/ut1-blacklists/issues/8
> 
> 
> 
> Cheers

Okay, thanks.

**Comment by gracjankn** [comment]
I checked my logs and it appears to be removed upstream. Closing the issue.
