### ISSUE TITLE
Privacy Lists Not Being Updated Or Calculated Correctly?

### ISSUE THREAD

**Issue by quantumpacket** [nextdns/metadata#573]
On the _Privacy_ page each list that you add has an _entries_ and _updated_ field. This tells us how many entries a list contains, and also when it was last updated. This helps us determine if the list is being maintained.

I submitted some additions to the [No Google](https://github.com/nickspaargaren/no-google) list, which got added today. I went to check to see if the list was updated on NextDNS and found it said the list contains _301 entries_ and was last _Updated 10 months ago_.

This clearly can't be right, as the list contains over 5,200 entries and has been updated many times within the past 10 months. Is the list not being updated correctly? Or is the stats on the list not being updated?

I did some tests with some newer domains and they were blocked, so I can _assume_ it's being updated correctly. But if NextDNS is calculating the entry count from the same updated list then it should match, otherwise I'd be worried something is afoot and it's perhaps losing part of the list?

Would love a confirmation that all is fine with the lists updating. :)

**Comment by crssi** [comment]
I think that the best would be if NextDNS would provide No-Google na No-Facebook lists from their own GAFAM list... see: https://github.com/nextdns/metadata/blob/master/analytics/gafam.json

Cheers

**Comment by quantumpacket** [comment]
> I think that the best would be if NextDNS would provide No-Google and No-Facebook lists from their own GAFAM list... see: [https://github.com/nextdns/metadata/blob/master/analytics/gafam.json](https://github.com/nextdns/metadata/blob/master/analytics/gafam.json?rgh-link-date=2021-02-10T10%3A42%3A36Z)

This looks like a more restrictive list than the _No Google_ list, which is very specific in using a ton of subdomains for a parent domain. Which we know is a big hit or miss as new subdomains are made all the time, which is why I had to submit some additions. So I'm totally for outright blocking the parent domains as _No Google_ should mean just that.

**Comment by crssi** [comment]
> However, the list definitely needs to be expanded on as it is missing a lot of domains that are owned by Google.

Fully agree and I think it would be in NextDNS interest to complete the list, otherwise the analytics is partly broken. @romaincointepas ?

**Comment by quantumpacket** [comment]
Related to above discussion: https://github.com/nextdns/metadata/issues/648

**Comment by romaincointepas** [comment]
We are using the wildcard list at https://raw.githubusercontent.com/nickspaargaren/no-google/master/wildcards-domains.

**Comment by quantumpacket** [comment]
@romaincointepas we currently have each list with a link to the project. Can we also have a link to the specific raw list for cases like this where the project has multiple lists? That way we know which list is being utilized for NextDNS.
