### ISSUE TITLE
AMP hosts support

### ISSUE THREAD

**Issue by RicoHeat** [nextdns/metadata#575]
https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt

**Comment by romaincointepas** [comment]
Blocking those will block the link completely, it will NOT suddenly start sending you to the original website. Are you aware of this limitation?

**Comment by beerisgood** [comment]
> Blocking those will block the link completely, it will NOT suddenly start sending you to the original website. Are you aware of this limitation?

But a redirect solution for all known AMP sites doesn't exists doesn't it?
Most users which are read about AMP, want blocking it at any cost anyway.

**Comment by romaincointepas** [comment]
@beerisgood yes, it's impossible to redirect AMP links at the DNS level.

I'm going to let this open, but I don't believe that's something we should offer, this will just break so many websites with no way of easily accessing them.

**Comment by beerisgood** [comment]
Fair enough!
