### ISSUE TITLE
Add ABL to the list of blocklists

### ISSUE THREAD

**Issue by jenabaivab** [nextdns/metadata#577]
Very good blocklist, lighter alternative to OISD

https://github.com/arapurayil/aBL

**Comment by AidanGee7** [comment]
I also think this would be a good one to add.

**Comment by beerisgood** [comment]
This uses some lists with high false positives.
OISD filter all false positives which is a lot better

**Comment by jenabaivab** [comment]
> This uses some lists with high false positives.
> OISD filter all false positives which is a lot better

Haven't had many problems with this, been using for more than a week now. This list also maintains the whitelist for false positives.

Either way, it's optional. Nobody has to use it if they don't want to. It's the matter of giving the option to use it.

**Comment by scafroglia93** [comment]
I don't like this kind of list who a script merged all without any rules

-1

**Comment by romaincointepas** [comment]
> This repository has been archived by the owner on Nov 19, 2022. It is now read-only.
