### ISSUE TITLE
False positive: notion.so 

### ISSUE THREAD

**Issue by faishalirwn** [nextdns/metadata#578]
`notion.so` is blocked by Threat Intelligence Feeds. It's a productivity app.

![image](https://user-images.githubusercontent.com/27213166/107782098-3c990b80-6d7b-11eb-974b-f6aa12dcfe60.png)

**Comment by lyrad87** [comment]
Hmm, that's definitely odd. I have TIF enabled as well but can access `notion.so` just fine. Is it maybe something specific within the website, like support, wiki, the app?

**Comment by faishalirwn** [comment]
> Hmm, that's definitely odd. I have TIF enabled as well but can access `notion.so` just fine. Is it maybe something specific within the website, like support, wiki, the app?

I'm not sure, maybe there were some minor issues in one of the source list before you replied and it has got resolved. It's working fine now. Gonna close this issue.
