### ISSUE TITLE
Blocking kaltura.com breaks Finnish TV broadcasting (YLE)

### ISSUE THREAD

**Issue by smoltron** [nextdns/metadata#579]
If cdnapisec.kaltura.com is blocked, videos are not shown in Firefox browser.

**Comment by scafroglia93** [comment]
https://github.com/StevenBlack/hosts/issues/1542

for the next time open an issue to the maintainer of the list you use (see it through the log); nextdns does not manage domains

**Comment by scafroglia93** [comment]
Reference 1 ->
https://github.com/StevenBlack/hosts/issues/1542

Reference 2 -> (real domain)
https://github.com/StevenBlack/hosts/issues/1548

Resolved; it will be unlocked as soon as the list is updated

**Comment by scafroglia93** [comment]
you can close this issue; it's ok (you have to wait the next release of stevenblack hosts)

**Comment by smoltron** [comment]
Thanks!
