### ISSUE TITLE
NextDNS block list false +

### ISSUE THREAD

**Issue by kpodman** [nextdns/metadata#582]
I'm unable to log into Schwab.com using a browser.  I have no problem when using the iOS app.  I'm using only the NextDNS block list and I put *Schwab.com in the allow list.  Looking at the blocked logs... there is no entry for Schwab.com.  So I have no idea what is actually block the site.  When I stop using Next DNS the browser has no problem loading the Schwab site.

**Comment by kpodman** [comment]
Never mind. It turned out to be Safari's "Prevent cross-site tracking" setting.

**Comment by beerisgood** [comment]
> Never mind. It turned out to be Safari's "Prevent cross-site tracking" setting.

You should report this then to Apple.
