### ISSUE TITLE
zapto.org blocked by NextDNS Ads & Trackers Blocklist

### ISSUE THREAD

**Issue by naturalpb** [nextdns/metadata#583]
I run a personal site as a subdomain of zapto.org (ex: test.zapto.org). *.zapto.org are subdomains provided by [No-Ip](https://www.noip.com/) for Dynamic DNS.

I noticed that zapto.org and all subdomains are being blocked by the NextDNS Ads & Trackers Blocklist. I understand that Dynamic DNS subdomains can be risky, but is the intention that they all be blocked? I know of other Dymanic DNS domans that are not blocked.

Can zapto.org (and *.zapto.org) be removed from the NextDNS Ads & Trackers Blocklist?

**Comment by romaincointepas** [comment]
It's being blocked by https://github.com/StevenBlack/hosts, one of the source of the NextDNS Ads & Trackers Blocklist. Could you report it there?
