### ISSUE TITLE
doh.dns.apple.com not blocked by Block Bypass Methods feature

### ISSUE THREAD

**Issue by Unksi** [nextdns/metadata#588]
I noticed that even while Block Bypass Methods is enabled, traffic to doh.dns.apple.com gets through.

**Comment by scafroglia93** [comment]
this domain is not present in the dedicated list

**Comment by romaincointepas** [comment]
Where/when is that DoH domain being used?

**Comment by Unksi** [comment]
Apple states in its documentation that it is used for DoH in iOS/tvOS 14 and macOS 11: https://support.apple.com/en-us/HT210060 (under "Domain Name System resolution" headline)

Since some time has passed, I do not know which device performed the request (there are multiple different kinds of Apple devices in the network, and it does not show up in currently available logs). I was not able to verify how to trigger the query.
