### ISSUE TITLE
Add custom block list - Current list of spy pixels named'n'shamed in HEY email service

### ISSUE THREAD

**Issue by johndlloyd** [nextdns/metadata#589]
Please consider adding the custom blocklist maintained by the HEY email service

https://gist.github.com/dhh/360f4dc7ddbce786f8e82b97cdad9d20

**Comment by quantumpacket** [comment]
That is not a DNS blocklist. Only a few items on the list can be blocked via DNS, the rest are blocked at the HTTP level.

**Comment by scafroglia93** [comment]
Sorry but this list is not for NextDNS

I suggest you to use my setting ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

Enjoy

**Comment by romaincointepas** [comment]
What @quantumpacket said.
