### ISSUE TITLE
Gaming Blacklist

### ISSUE THREAD

**Issue by lukerock7** [nextdns/metadata#590]
Hello,

My children play a lot of games that are off the blacklists that are currently available, which is why I am in need of a list that covers more of the gaming platforms.

I request that this list be implemented:

https://github.com/dupontjean/pihole-blocklist

It contains almost all of the major games and their platforms. I would really appreciate if this was implemented!

Thanks,
Luke

**Comment by romaincointepas** [comment]
This list doesn't seem very popular. We will be adding a Gaming category soon, we will revisit then.
