### ISSUE TITLE
Blocklist suggestion: BlockConvert

### ISSUE THREAD

**Issue by mkb2091** [nextdns/metadata#591]
It's another compilation list thats aims to block ads, tracking and malware. As well as compiling existing lists, it used regexes and IP lists to find more domains to block. Domains that are reported as false positives get added to an allowlist, which get ignored when generating the list

I'm not sure what format nextdns wants:
- https://mkb2091.github.io/blockconvert/output/adblock.txt which is in adblock plus style format and removes subdomains and includes ips, as of last commit is 1198651 domains, and 412389 ips
- https://mkb2091.github.io/blockconvert/output/domains.txt which is just list of domains, and as such includes subdomains, and as of the last commit is 2053178 domains

It's updated roughly once a day

**Comment by scafroglia93** [comment]
-1

Currently within nextdns there are already some compilation lists that work perfectly also, the use of IPs is useless as the block is done at the dns level

**Comment by scafroglia93** [comment]
@mkb2091 
Use my setting and enjoy the power of nextdns ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

**Comment by romaincointepas** [comment]
Not popular enough for a compilation blocklist at the moment, and I feel their approach is risky regarding false positives.
