### ISSUE TITLE
Add "Google" to list of Services

### ISSUE THREAD

**Issue by RejZoRSheep** [nextdns/metadata#60]
Would appreciate if there was also "Google" on the list of Services that would block everything Google (except Youtube which needs to remain its own selection). I've bought iPhone to get rid of creepy Google and stuff keeps connecting to Google services because apps are bundled with their junk. Not even Google made apps! I'm still unsure whether it should just outright block everything related to Google or should "Google APIs" be separate option which affects Google Fonts and SafeBrowsing among other things which will affect regular webpages too since they'll use default browser fonts as a result.

**Comment by romaincointepas** [comment]
The `No G` blocklist is a better fit for that, and you can manually whitelist the domains you want to fine-tune it.
