### ISSUE TITLE
Blocklist suggestion: CNAME-cloaked trackers

### ISSUE THREAD

**Issue by kdeldycke** [nextdns/metadata#601]
> Most complete auto-updating repository of actively used hidden trackers. The list is to be updated on a regular basis to add new hidden trackers as they’re detected.

Source repository: https://github.com/AdguardTeam/cname-trackers

**Comment by mojo333** [comment]
Definitely one to add to NextDNS. 6000+ entries compared to the 20+ entries in the NextDNS version https://github.com/nextdns/cname-cloaking-blocklist

**Comment by crssi** [comment]
I don't think this is applicable/valuable here.
The list in OP is used for Chrome, Chromium and Safari, which are not able to reveal CNAMEs.
But NextDNS does not suffer of this limitation and it can reveal CNAMEs.

But... let see what @romaincointepas have to say.

Cheers

**Comment by romaincointepas** [comment]
This is already handled by https://github.com/nextdns/cname-cloaking-blocklist, and appear as a specific separate feature in NextDNS.

The reason they advertise the *6000+* is that I'm assuming their system is not able to block at the CNAME level, so they do something less ideal of *scraping the web* to try to list all QNAMEs pointing to those few CNAMEs, and try to get this list as complete and up-to-date as they can.

**Comment by Yuki2718** [comment]
IDK where they advertised the 6,000 number but AGDNS has been blocking at the cname level. As clearly stated in README, the whole point in this project is to help those unprotected user regardless what blocker they use. In fact EasyList author was contacted soon after the creation of repo despite AG products don't use EasyPrivacy by default. Please read first and don't fall into which-is-better discussion.

**Comment by Yuki2718** [comment]
BTW looking at the your list, you may possibly be interested in adding these entities: https://github.com/AdguardTeam/cname-trackers/issues/1

**Comment by scafroglia93** [comment]
Added inside notracking list ->
https://github.com/notracking/hosts-blocklists/issues/517

I suggest you to use my setting ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

Enjoy the NextDNS Power

**Comment by romaincointepas** [comment]
Closing as NextDNS is able to block at the CNAME-level, which is much more efficient than keeping a huge list of QNAMEs for just a few CNAMEs.

If anyone feel like we should be supporting additionnal CNAMES, please open an issue at https://github.com/nextdns/cname-cloaking-blocklist.
