### ISSUE TITLE
Keyword blocking - Porn

### ISSUE THREAD

**Issue by northmendo** [nextdns/metadata#604]
Better pron blocking is needed. So many get through. What about adding keyword blocking or a least wilcards. e.g. *porn.com would catch many of them. Basically anything with porn in the url root domain name should be blocked.

**Comment by gracjankn** [comment]
> What about adding keyword blocking or a least wildcards

It's a great idea. The ability to set more advanced rules in Denylist and Allowlist would make blocking sites much easier, improve the effectiveness (fewer things would slip through) and help clean up the lists (I have over 300 domains in Denylist). Ideally, there would be a setting for the individual rule to use Regular Expression, wildcards or just a specific domain name like now. I hope for that, but at least the wildcards would be a massive improvement already.

**Comment by romaincointepas** [comment]
We are currently working on something pretty great related to this, stay put for the announcement.
