### ISSUE TITLE
cl.exct.net is not covered by the "allow affiliate and tracking links" setting, breaking email newsletters

### ISSUE THREAD

**Issue by jekis913** [nextdns/metadata#605]
I discovered this when attempting to click through to an article in a news alert email from the Memphis Commercial Appeal newspaper. I have turned on the option to allow affiliate and tracking links, but the domain is still blocked. I have disabled all of the third party blocklists listed in the block message, so it now reads as follows: 
cl.exct.net (→ akamai-san24.exacttarget.com.edgekey.net) is being blocked by NextDNS Ads & Trackers Blocklist.

**Comment by bpjones** [comment]
Exct.net seems to be Exact Target, a Salesforce.com marketing company.  It’s getting blocked for me because it’s misclassified as porn.
