### ISSUE TITLE
Blocklist suggestion: Newscorp and Rupert Murdoch

### ISSUE THREAD

**Issue by beardo01** [nextdns/metadata#606]
> News Corp’s partisan campaign coverage is harmful to democracy.
> 
> Fed up with the abysmal treatment by the Murdoch media during the Australian Bushfires I decided to make a blocklist so I never have to engage with Murdoch propaganda again.
> 
> Thus, this collection of URLs and blocklists for News Corp websites, to remove unpleasant surprises.

Repo: https://github.com/AshKyd/murdoch-block

I am also happy to fork this and keep it more up to date if NextDNS is interested (I can already see some links that are missing).

**Comment by beerisgood** [comment]
I don't think NextDNS want add content filter lists

**Comment by scafroglia93** [comment]
I believe it is not possible

**Comment by romaincointepas** [comment]
Too close to censorship for our taste unfortunately.
