### ISSUE TITLE
[Exclusion] Domain whoami.akamai.net

### ISSUE THREAD

**Issue by bigdargon** [nextdns/metadata#609]
The domain `whoami.akamai.net` is on the default nextdns block list (From the list https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts). 

This domain name is not advertised or tracked, details are here https://developer.akamai.com/blog/2018/05/10/introducing-new-whoami-tool-dns-resolver-information

**Comment by beerisgood** [comment]
better report it upstream to https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts dev

**Comment by bigdargon** [comment]
@beerisgood I will try! Thanks!

**Comment by scafroglia93** [comment]
You were right to report the problem; if it takes a long time I suggest you try my setting ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt
