### ISSUE TITLE
Blocklist suggestion: hufilter

### ISSUE THREAD

**Issue by asrob** [nextdns/metadata#611]
There is a hungarian filter list: https://github.com/hufilter/hufilter
It has a pi-hole (DNS) filter as well: https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-dns.txt

Can you add it?

**Comment by scafroglia93** [comment]
you cand find this list inside OISD ->
https://oisd.nl/?p=inc

**Comment by scafroglia93** [comment]
I suggest you to use my config ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

**Comment by asrob** [comment]
Hi @scafroglia93,

Ah.... I see. Thank you! :)
