### ISSUE TITLE
LG & Samsing Smart TV ad network block list

### ISSUE THREAD

**Issue by kdeldycke** [nextdns/metadata#613]
A couple of [domain names I found on a reddit thread](https://old.reddit.com/r/YouShouldKnow/comments/gn7fw5/ysk_if_you_own_a_samsung_smart_tv_that_has_ads/):

LG:
* `ngfts.lge.com`
* `us.ad.lgsmartad.com`
* `lgad.cjpowercast.com`
* `edgesuite.net`
* `us.info.lgsmartad.com`

Samsung:
* `samsungotn.net`
* `samsungrm.net`
* `samsung.net/ads`
* `ads.samsung.com`
*  `samsungadhub.com`

**Comment by scafroglia93** [comment]
In this case you must directly hear a maintainer of one of the many lists; I opened an issue on notracking

Use my setting if you want enjoy the power of nextdns ->
https://github.com/scafroglia93/nextdns-setting/blob/master/nextdns-setting.txt

**Comment by quantumpacket** [comment]
@scafroglia93 can you please stop spamming issues telling people to use your settings. You've hit around 10 issues within around 24hrs doing so. It's frankly very annoying for people who are watching this repo for activity and have to weed trough useless notifications.

**Comment by scafroglia93** [comment]
Most people open wrong issues by making the applicant wrong.
since I waste time opening the issues to the various maintainers, I ask you to replace me as I no longer intend to fix the requests of other users for free

The rest is caused by an incorrect configuration with out-of-date and incorrectly followed lists

**Comment by romaincointepas** [comment]
@scafroglia93 @quantumpacket is right, it's spam and it doesn't actually help anyone.

> since I waste time opening the issues to the various maintainers, I ask you to replace me as I no longer intend to fix the requests of other users for free

Either you do it for free (and we may send you a few subs your way), or you don't do it. Unfortunately you don't get to be annoyed by issues you don't like. Even we don't.

If you need to continue the conversation regarding this, create a post on https://help.nextdns.io, we don't want to spam watchers of this repository.

**Comment by romaincointepas** [comment]
@kdeldycke Sorry about all this 😄 

This would fall under our Native Protection feature, and we take this very seriously as those can't break anything. Some of those domains are already there, others block entire CDN (e.g. `edgesuite.net`).

Rest assured that those domains should probably already be included in popular blocklists.

**Comment by kdeldycke** [comment]
No worries @romaincointepas and thanks for the quick update.

And sorry for the raw dump, I did not double-checked the domains, some are obvious, others are indeed way too broad.

Anyway, thanks for NextDNS, I love your product and I'm a happy customer! :)
