### ISSUE TITLE
https://isc.sans.edu/feeds/suspiciousdomains_High.txt feed is dead, sans stopped supplying and updating it. It's blank.

### ISSUE THREAD

**Issue by RDLMP** [nextdns/metadata#616]
https://isc.sans.edu/feeds/suspiciousdomains_High.txt feed is blank, you might consider removing it, Sans quit updating it and it's blank.

**Comment by beerisgood** [comment]
In the file they also wrote:
> SERVICE SUSPENDED

**Comment by romaincointepas** [comment]
> Upon recently reviewing some of our sources for this service, we noticed how pretty much none of them are producing current data anymore (thanks to a reader for pointing this out to us). The lists will be empty until we find a way to resume this service.

From https://isc.sans.edu/suspicious_domains.html.

We will keep it there (it does no harm) until we are sure they won't come back.
