### ISSUE TITLE
False Positives/Negatives after update

### ISSUE THREAD

**Issue by IDKwhattoputhere** [nextdns/metadata#62]
Former advanced mode user here. I noticed that some filters changed with the new update.
I will use this issue to report any FPs/FNs I find if that is acceptable.
PS: You got a really great project going. Keep up the good work. :)

www.urbandictionary.com
Blocked by category:porn.
No porn to be seen here.

www.unhcr.org
Blocked by category:porn.
No porn here either.

www.teensource.org
Blocked by category:porn.
I would say sex education is very different from pornography.

www.ifrc.org
Blocked by category:porn.
Same as above.

www.agentprovocateur.com
Blocked by category:porn.
Do somewhat clothed people count as porn?

**Comment by romaincointepas** [comment]
Fixed, thanks for the report.

Those were false positives from the lists we use for the new Porn category:
https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/adult/domains
https://raw.githubusercontent.com/EnergizedProtection/block/master/porn/formats/domains.txt
https://raw.githubusercontent.com/cbuijs/shallalist/master/porn/domains

**Comment by IDKwhattoputhere** [comment]
Thanks for the quick fix. Here's more:

www.yourbrainonporn.com
Blocked by category:porn.
Quite the opposite I would say.

www.worldometers.info
Blocked by category:porn.
No porn to be found.

www.mail.com
Blocked by typosquatting.
Legitimate website. https://en.wikipedia.org/wiki/Mail.com

evo.shoryuken.com
Blocked by category:porn.
No porn as far as I can see.

`whynotbi.com`
**Not** blocked by category:porn.

**Comment by IDKwhattoputhere** [comment]
Another problem I've noticed is that the Enforce Safe Search option isn't able to separate search engines from YouTube's safe search.
YouTube Restricted Mode is very restrictive and having it enabled if you want to block adult content from search engines is a pain.

Example: https://www.youtube.com/channel/UCL7DDQWP6x7wy0O6L5ZIgxg
Realistically PG-13 but can't watch any video in Restricted Mode. For children that's fair but for teenagers and others it seems a little much.

**Comment by IDKwhattoputhere** [comment]
I really like that you integrated Safe Browsing by the way. :)
Have you seen this yet? https://www.reddit.com/r/oisd_blocklist/comments/eytflu/pornoisdnl_the_blocklist_to_block_adultnsfwporn/

Some more FPs:

www.siecus.org
Blocked by category:porn.
Sexuality Information and Education Council of the United States

anonym.to
Blocked by category:porn.
Used to hide the HTTP referer.
Example: https://www.nsanedown.com/?request=231660 (Click on any download links.)

www.venus.com
Blocked by category:porn.
Women's Fashion

sfsi.org
Blocked by category:porn.
San Francisco Sex Information

www.xenu.net
Blocked by category:porn.
Website critical of the Church of Scientology.

www.fark.com
Blocked by category:porn.
Sort of a news aggregator.

www.figleaves.com
Blocked by category:porn.
Lingerie/Swimwear for Women

www.scarleteen.com
Blocked by category:porn.
Sex education

www.okcupid.com
Blocked by category:porn.
Online dating

www.wluml.org
Blocked by category:porn.
Women's rights

epic.org
Blocked by category:porn.
Electronic Privacy Information Center

www.spark.com
Blocked by category:porn.
Online dating

www.sexedlibrary.org
Blocked by category:porn.
Sex education

sexetc.org
Blocked by category:porn.
Sex education

www.religioustolerance.org
Blocked by category:porn.
They try to objectively cover different religions and religious topics.

www.selectsmart.com
Blocked by category:porn.
Quizzes

**Comment by romaincointepas** [comment]
Thanks for those, whitelisted. That's a ton of false positives though, we will figure out a way to improve this.

Regarding YouTube Restricted Mode, we just added a separate setting for it (it's not tied with Safe Search).

**Comment by SeriousHoax** [comment]
Some torrent sites are being blocked by Porn category so, false positives. Here are some of them:

https://1337x.to
https://www.torrentfunk.com/
https://thepiratebay.org/

These sites should be blocked by the BitTorrent blocking module only. 
I think there are even more torrent sites that are being blocked. These are just the ones I found.

**Comment by SeriousHoax** [comment]
This two are currently being blocked by porn category as well. 
https://codecguide.com
https://findicons.com

**Comment by SeriousHoax** [comment]
Another: fastpic.ru

**Comment by MikeeI** [comment]
https://rpetri.ch

This is just a Cydia iOS Repository
![IMG_0426](https://user-images.githubusercontent.com/13944905/75121744-39eb6500-5697-11ea-897f-f973fc908e06.jpeg)

**Comment by IDKwhattoputhere** [comment]
category:**porn** should probably block these:
```
babes.com
playboytv.com
peeperz.com
sextube.com
porniq.com
seancody.com
gotgayporn.com
hotgaylist.com
sickjunk.com <- NSFL
```

**Comment by SeriousHoax** [comment]
Should be added to porn category

> anybunny.tv

**Comment by romaincointepas** [comment]
All the domains mentioned in this issue have been either excluded or added to the Porn category, thanks all!
