### ISSUE TITLE
Enabling "Allow Affiliate & Tracking Links" does not allow Google ads

### ISSUE THREAD

**Issue by jkpe** [nextdns/metadata#620]
Enabling "Allow Affiliate & Tracking Links" one would expect users to be able to click the results shown at the top of Google Search results.

I can see [here](https://github.com/nextdns/metadata/blob/a1856cc8475227dc3a86568354d2bca9255eafbd/privacy/affiliate-tracking-domains#L335) you attempt to whitelist them

Line 335
pagead.l.doubleclick.net # CNAME of www.googleadservices.com

However for me (perhaps geographically affected) adservice.google.co.uk is an alias for pagead46.l.doubleclick.net

Manually whitelisting *.l.doubleclick.net fixes the issue.

**Comment by romaincointepas** [comment]
It should now, please tell us if it still doesn't work.
