### ISSUE TITLE
Threat Intelligence Feeds blocks falsely http://s4.onweb.gr/

### ISSUE THREAD

**Issue by Devid-** [nextdns/metadata#623]
Blocking http://s4.onweb.gr/ is a false positive (I think). It should not be blocked. 

![Threat Intelligence Feeds](https://s3-us-west-2.amazonaws.com/media.forumbee.com/i/7cc435f1-2ecd-4e65-b33a-b9635bbde08f/h/547.png)

**Comment by scafroglia93** [comment]
it's work for me

**Comment by beerisgood** [comment]
Works here too.
Try without NextDNS block site

**Comment by romaincointepas** [comment]
Seems to have fixed itself, closing.
