### ISSUE TITLE
f000.backblazeb2.com too wide a target for blocking

### ISSUE THREAD

**Issue by rjp** [nextdns/metadata#624]
f000.backblazeb2.com is one of the hostnames for content stored on b2 and served up via HTTP - which a lot of people are using to host, e.g., blog content (like myself).  Since `f000` is a cluster name which is automatically assigned at account creation, it's not something that can be changed by hosters to work around this issue - (see https://www.reddit.com/r/backblaze/comments/gg7yrg/beginner_b2_question_will_all_my_files_have_the/)

Seems to have been added to the NextDNS Ads & Trackers Blocklist some time between 2021-03-23 and 2021-03-29 going off my logs.

Malwarebytes had a similar issue in February - https://forums.malwarebytes.com/topic/270156-f000backblazeb2com/ - which they've since reverted.

**Comment by romaincointepas** [comment]
Indeed, nice catch. Seems to have fixed itself, closing.
