### ISSUE TITLE
Please remove ipsnews.net from blocklist

### ISSUE THREAD

**Issue by anupshah** [nextdns/metadata#626]
Hello,

Inter Press Service, http://www.ipsnews.net is a legit global news organisation.

I notice it has been blocked the last couple of days from the nextdns ads & trackers blocklist.

Can it be removed?

Thanks!

**Comment by anupshah** [comment]
![image](https://user-images.githubusercontent.com/2446665/113051757-40071b80-919e-11eb-9006-9f4c1e875b8d.png)

Just attaching image as example (there's subdomains like cdn.ipsnews.net etc also)

**Comment by scafroglia93** [comment]
@stevenblack

**Comment by krystian3w** [comment]
`ipsnews.net/business/2021/03/18/bitcoin-era-opinie-czy-bot-to-oszustwo-2021/`

https://web.archive.org/web/20210320095109/ipsnews.net/business/2021/03/18/bitcoin-era-opinie-czy-bot-to-oszustwo-2021/

**Comment by anupshah** [comment]
@krystian3w 

Many thanks for clarifying. That is indeed surprising. In the 10+ years I have worked with Inter Press Service (and the 20+ years I have read their news) I have not actually seen the /business sub-site, and it doesn't (from what I can tell) appear to be linked from their main news site.

I wonder what is happening there. Would it be possible to block either just that story or ipsnews.net/business but not the entire domain?

I will reach out to ipsnews.net to try and figure out what is going on.

**Comment by romaincointepas** [comment]
Doesn't seem to be blocked by anything anymore, closing.
