### ISSUE TITLE
[whitelist] `nv-sdk.jumio.com`

### ISSUE THREAD

**Issue by andschwa** [nextdns/metadata#632]
This is required for identity verification in the Gig car share app, but is blocked by one of the lists incorporated into NextDNS’s list. Note that oisd already [excludes](https://oisd.nl/excludes.php?w=nv-sdk.jumio.com) it, and I don’t know how to check all your other lists. Also, `mobile-sdk-resources.jumio.com` was contacted too, and I don’t know if it needs to be unblocked.

**Comment by romaincointepas** [comment]
Could you report this directly to Steven Black at https://github.com/StevenBlack/hosts?
