### ISSUE TITLE
Fake Positive spot.im

### ISSUE THREAD

**Issue by technicgeek** [nextdns/metadata#633]
Hello,

The domain in question belongs to OpenWeb website that allows webmasters to embedd comment management element into their websites.

I am using "NextDNS Ads & Trackers Blocklist" and the domain in question was blocked until I allowed it which no longer caused comments element being blocked.

**Comment by Cybo1927** [comment]
Can confirm this breaks comments on `metro.co.uk`.

Whitelisting will also require adding `pix.spot.im`, `metrics-logger.spot.im`, `events-collector.spot.im`, `and direct-events-collector.spot.im` to the blacklist. Hope this change comes soon and fixes the problem!

**Comment by technicgeek** [comment]
@Cybo1927 Hello. I whitelisted entire domain. Why its aforementioned sub-domains must be blacklisted?

**Comment by Cybo1927** [comment]
> Why its aforementioned sub-domains must be blacklisted?

Sorry, that was mostly for a maintainer of the "NextDNS Ads & Trackers Blocklist". Those sub-domains are trackers and possibly the reason `spot.im` was blacklisted in the first place, so when `spot.im` is whitelisted those should be blocked for being trackers and it may help prevent the same false positive from happening again.

**Comment by romaincointepas** [comment]
This domain doesn't seem to be blocked by the NextDNS Ads & Trackers Blocklist anymore, closing.
