### ISSUE TITLE
[whitelist] ztm.waw.pl

### ISSUE THREAD

**Issue by gita6t5** [nextdns/metadata#634]
https://en.wikipedia.org/wiki/Zarz%C4%85d_Transportu_Miejskiego_w_Warszawie#External_links

**Comment by romaincointepas** [comment]
This is being blocked by https://www.usom.gov.tr (https://www.usom.gov.tr/url-list.txt).

If anyone turkish could report it to them that would be great.

**Comment by ClusterByte-x** [comment]
@gita6t5 - hello. I have requested to unblock this site now. Let's wait for the answer.

@romaincointepas - don't you think that the information that the page has been blocked by the TIF source is not too detailed? Wouldn't it better point that exactly? For example, the website "ztm.waw.pl" is blocked by "TIF: CERT.PL".

**Comment by ClusterByte-x** [comment]
@gita6t5 @romaincointepas **The site is no longer blocked**. Please close.
