### ISSUE TITLE
Please look at updated removed NSA Blocklist

### ISSUE THREAD

**Issue by gorillap** [nextdns/metadata#635]
Chef-Kochs account was removed from github but others have forked his NSA repo and split it into 2 options. 1 removes some of the excessive .gov URLs. I would suggest replacing the list with either this updated list or the one that removes the excessive .gov blocking.
https://github.com/Cauchon/NSABlocklist-pi-hole-edition

**Comment by beerisgood** [comment]
> Chef-Kochs account was removed from github but others have forked his NSA repo and split it into 2 options. 1 removes some of the excessive .gov URLs. I would suggest replacing the list with either this updated list or the one that removes the excessive .gov blocking.
> https://github.com/Cauchon/NSABlocklist-pi-hole-edition

This list is just nonsense. No matter if someone fork it or not

**Comment by quantumpacket** [comment]
One of the main reasons to not even provide these NSA lists is that the NSA is very likely not going to use these publicly known domains for surveillance. This provides users a false sense of security that if they use these blocklists that they are protected against them, which is far from the truth. There are much more effective methods of avoiding surveillance that don't involve DNS blocking.

**Comment by gorillap** [comment]
The lists clearly arent a be all/end all solution. You cant say to avoid putting any list together because some people are not educated. 
Any suggestions for other lists that block servers involved in state sponsored spying operations? You can obviously try to avoid them, but its nice to have something that will stop devices from checking in with them. Not everyone is going to have a home firewall with ids/ips capabilities.

**Comment by quantumpacket** [comment]
> The lists clearly arent a be all/end all solution.

It's no solution at all. An intelligence agency is not going to use domains that are publicly known to be associated with them or other agencies as their surveillance endpoints.

**Comment by pYFZOS5** [comment]
>This provides users a false sense of security that if they use these blocklists that they are protected against them.

I agree with that but,

> This list is just nonsense. No matter if someone fork it or not

>which is far from the truth. There are much more effective methods of avoiding surveillance that don't involve DNS blocking.

This is a DNS service so it offer what it can and more people don't know about that effective methods; according to your profile you're a security researcher then you know more about IT but i see it make sense when not connecting to them.

**Comment by quantumpacket** [comment]
@pYFZOS5  DNS is simply a convenient way for one IP to communicate to another IP where it assigns a hostname to an IP, and you then connect to that hostname. So even if the IP changes the hostname will work provided the DNS entry was updated.

That being said, once you remove that convenience layer it's still an IP going to an IP. So for example if you connect to `cisco.com` it will connect to `72.163.4.185`. You can block `cisco.com` on NextDNS and now it will no longer connect via hostname. But if you try to connect to `72.163.4.185` directly it will work. Your device can still access the IP just not by hostname.

So using this NSA blocklist you prevent connecting via hostname, but your devices can still connect to the supposed surveillance endpoint via IP. If your threat model includes surveillance agencies then relying on DNS blocking would be useless.

**Comment by romaincointepas** [comment]
We will remove this list soon.
