### ISSUE TITLE
Threat Intelligence Feeds - List provided by cert.pl

### ISSUE THREAD

**Issue by qbusi** [nextdns/metadata#642]
Can you include https://hole.cert.pl/domains/ hosted by cert.pl. It is consolidated list from CERT Poland and major Polish telecoms which includes domains used in phishing attacks.

Updated every 5 minutes, documentation: http://hole.cert.pl/schema/certpl_lista_ostrzezen_api_v1.pdf

List is available since March 2020
https://cert.pl/posts/2020/03/ostrzezenia_phishing/

**Comment by gita6t5** [comment]
https://github.com/nextdns/metadata/commit/1f3dff4a4073321a332fa665e8153df656056726#diff-4135ff190668c7547c08149ef0e9805998b01c8f4342f8b3caa58eb245ebe0b5

**Comment by ClusterByte-x** [comment]
@qbusi The list has long been included in NextDNS. 
- Check if you are protected by this list here: https://lista.cert.pl

**Comment by romaincointepas** [comment]
Already included in Threat Intelligence Feeds.
