### ISSUE TITLE
Android: passthrough DNS

### ISSUE THREAD

**Issue by aetha** [nextdns/metadata#643]
Feature request:

Hi, it'd be really useful for me to have DNS requests passed through to the system's own defined DNS server.

On iOS, I can combine Tailscale with a different private DNS service. I do this together with NextDNS. (Android doesn't have seperate services for this, but I can manually use my NextDNS config hostname.)

Would be even better if the Tailscale client could resolve my VPN hostnames first, then pass through after that.

**Comment by romaincointepas** [comment]
That would be up to Tailscale if I understand correctly.
