### ISSUE TITLE
It's possible add uBlock filter list?

### ISSUE THREAD

**Issue by peter9811** [nextdns/metadata#644]
https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/filters/filters.txt

I tried check it on https://adblock-tester.com/, but I don't get more that 60 points

And maybe this too, please

http://sbc.io/hosts/hosts
http://sysctl.org/cameleon/hosts
https://gnuzilla.gnu.org/filters/blacklist.txt
https://openphish.com/feed.txt
https://raw.githubusercontent.com/Lerist/Go-Hosts/master/hosts-ad
https://raw.githubusercontent.com/bjornstar/hosts/master/hosts
https://raw.githubusercontent.com/vokins/yhosts/master/hosts.txt
https://raw.githubusercontent.com/yous/YousList/master/hosts.txt
https://reddestdream.github.io/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts
https://v.firebog.net/hosts/static/w3kbl.txt

**Comment by mtverlee** [comment]
That uBlockOrigin list is not DNS blockable and is instead a list of elements on webpages that is intended to be used with a browser extension. It's unlikely it'll ever be added.

**Comment by beerisgood** [comment]
For your lists request, take a look at OISD list.

**Comment by romaincointepas** [comment]
What @mtverlee said.
