### ISSUE TITLE
Addition of Fakenews list

### ISSUE THREAD

**Issue by ryakel** [nextdns/metadata#645]
Please add StevenBlack's Fakenews List as a separate denylist option

https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews/readme.md
https://github.com/StevenBlack/hosts/blob/master/alternates/fakenews/hosts

**Comment by beerisgood** [comment]
Blocking content is never a good idea.

**Comment by ryakel** [comment]
> Blocking content is never a good idea.

This is the reason we have choices. I respect your position but disagree with your stance in this case. Taking it a step further, blocking content is technically already an option today by allowing admins for to force Google Safe Search. If one is using the tool to block any kind of site by classification, they are blocking content. 

StevenBlack’s lists are well respected in this space, so they can generally be assumed to have high fidelity. My ask is to make it an option for those who may want to integrate it, not force it upon anyone. This is in the same spirit as the current allow/deny list options.  

For anyone who may be using this list with other technologies (like a PiHole), this is simply providing an option to replicate that ability here. The alternative would be to enable the ability for people to import their own allow/deny lists into the platform.

**Comment by quantumpacket** [comment]
> StevenBlack’s lists are well respected in this space, and are generally be assumed to have high fidelity.

I have no political leanings, but even I can see after looking through this list it targets conservative sites or sites that offer different viewpoints contrary to mainstream narratives. That's not how content filtering works, that's how censorship works. NextDNS should not put itself into the position where it's in support of censorship.

I never understood why people are wanting such lists, when those who advocate for such lists can just leave such a website if they encounter it. However, for some reason want to push these lists on others. What happened to just being accountable for what sites you consume content from?

**Comment by ryakel** [comment]
For the sake of not starting a political discussion, I am withdrawing this request. I have no desire to put NextDNS or its community in a position that asserts any position other than neutral. I will solve my specific use case a different way.
