### ISSUE TITLE
False positive chtbl.com probably due to outdated upstream

### ISSUE THREAD

**Issue by yaotehsieh** [nextdns/metadata#647]
chtbl.com used to be blocked by StevenBlack which is one of the upstream for NextDNS’s own blocklist. Blocking chtbl.com will cause many podcast app (e.g. Overcast, Castro) failed to download many podcasts (e.g. Vergecast). This domain seems to have already been reported and removed from StevenBlack Host a month ago  https://github.com/StevenBlack/hosts/issues/1567 but both StevenBlack and NextDNS Ads & Trackers Blocklist currently live on NextDNS’ server still block this domain.

![5EAD3C2B-ABDC-46C7-B5CA-D3F64762F3CC](https://user-images.githubusercontent.com/53443113/115943399-51fc8580-a4e2-11eb-954a-8b5b77956cf9.jpeg)

**Comment by romaincointepas** [comment]
Seems fixed.
