### ISSUE TITLE
Dead List

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#65]
It's not update since 21 March 2019
https://github.com/bkrucarci/turk-adlist/commits/master

**Comment by scafroglia93** [comment]
@romaincointepas

**Comment by romaincointepas** [comment]
Any replacement for turkish ads and trackers?

**Comment by sakai135** [comment]
AdGuard maintains a Turkish filter. In fact, I would appreciate it if all the AdGuard language filters were available in NextDNS. 

https://kb.adguard.com/en/general/adguard-ad-filters#turkish

**Comment by scafroglia93** [comment]
@sakai135
You can find this inside -> AdGuard Simplified Domain Names filter

**Comment by sakai135** [comment]
@scafroglia93 The simplified domain names filter do not include all language filters. Even if they were included, I would appreciate separate lists for more granular control.

**Comment by scafroglia93** [comment]
@sakai135 
What you are saying is incorrect

1- https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
2- CTRL-F -> search "turksih"
3- Done

**Comment by scafroglia93** [comment]
@romaincointepas

**Comment by sbpir92i** [comment]
> Any replacement for turkish ads and trackers?

Hello
https://github.com/xorcan/hosts
Best regards

**Comment by lyrad87** [comment]
This should be included as it's one of the few good and up-to-date Turkish adblockers. It's been added as a blocklist suggestion via #138.

**Comment by Voltairine-de-Cleyre** [comment]
Not an ad-blocking list; however this hosts file is (100%) unique:

`https://gitlab.com/anarcho-copy/block-fake-pdf-sites.git`

`https://gitlab.com/anarcho-copy/block-fake-pdf-sites/-/raw/master/hosts`

**Comment by scafroglia93** [comment]
can you open a new issue with this list please
