### ISSUE TITLE
Does any one has database for online streaming sites

### ISSUE THREAD

**Issue by Blason** [nextdns/metadata#650]
Hi Team,

I am looking for online streaming platform domain database and wondering if this is a part for nextdns? like netflix or primvideo or any such.

**Comment by quantumpacket** [comment]
@Blason I presume you'd want to check out this directory: https://github.com/nextdns/metadata/tree/master/parentalcontrol/services, keep in mind it's not extensive as the blocking is really meant to block access to things like dashboards and apps. There are far too many additional domains those services connect out to.
