### ISSUE TITLE
nextdns new block list 

### ISSUE THREAD

**Issue by raymondjtoth32000** [nextdns/metadata#651]
hi i like to see add to block like malware here is link to it https://gitlab.com/curben/urlhaus-filter#urlhaus-malicious-url-blocklist and easy list https://forums.lanik.us/ and https://pgl.yoyo.org/adservers/ and https://github.com/gorhill/uBlock/wiki/Badware-risks would use these right a way thansk so much if can add these to nextdns so can use these thansk

**Comment by crssi** [comment]
Those are already in, or as the Blocklists in the Privacy section or as Threat Intelligence Feeds in the Security section.

**Comment by raymondjtoth32000** [comment]
How do i tirn them on?

**Comment by beerisgood** [comment]
> How do i tirn them on?

Threat Intelligence Feeds is already enabled by default.
Privacy lists can be configured in your account. I recommend using (and only this) OISD list.
