### ISSUE TITLE
Possible false positve listing via "Threat Intelligence Feeds" function

### ISSUE THREAD

**Issue by JanGrunowRecastIT** [nextdns/metadata#652]
The domain https://www.real-markt.de has been blacklisted by the "Threat Intelligence Feeds" function. We are hosting this website and are unsure why the domain has been blacklisted. Could you supply us with information (for example URLs, phishing mails) why the domain has been blacklisted?

If there is no valid data could you please delist the domain? It's the marketplace domain of the hypermarket real (https://en.wikipedia.org/wiki/Real_(hypermarket)).

**Comment by crssi** [comment]
All the sources for "Threat Intelligence Feeds" are here https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json

**Comment by lyrad87** [comment]
I can access the website just fine. May have been fixed upstream.

**Comment by romaincointepas** [comment]
Probably fixed upstream, closing.
