### ISSUE TITLE
Can you add this awesome AakList (Anti-Adblock Killer) to the blocklist?

### ISSUE THREAD

**Issue by BwntyHntr** [nextdns/metadata#653]
This is the blocklist file: https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt
The offical Website: https://reek.github.io/anti-adblock-killer/#filterlist

It's an amazing anti-Adblock warning and should be on the NextDNS list since we can't add a custom one.

Thanks.

**Comment by beerisgood** [comment]
This list doesn't work with NextDNS nor with DNS generally.

**Comment by romaincointepas** [comment]
As @beerisgood said, this is unfortunately not compatible with DNS blocking.
