### ISSUE TITLE
Add - New 1Host Filterlist - 1Host-Xtra

### ISSUE THREAD

**Issue by thomasmiddleton22** [nextdns/metadata#656]
1Host Xtra is a  new addition to the 1Host Family of mini, lite and pro.

you can find it here - https://github.com/badmojr/1Hosts/tree/master/Xtra

NextDNS already supports range of 1hosts filters, hope this new list can be added too.

**Comment by beerisgood** [comment]
All three lists are marked as experiments and aren't recommend for normal usage

**Comment by thomasmiddleton22** [comment]
> All three lists are marked as experiments and aren't recommend for normal usage

yes they are, but I didn't came across any page-breakage, I mostly used oisd, 1hosts(pro) and these addon lists for my previous setup, before switching to NextDNS, and since these will be optional for users do you think it will be unsafe to add these lists?

**Comment by beerisgood** [comment]
I use only OISD and in my opinion it's enough with also best in terms of false positives.

**Comment by badmojr** [comment]
Quick update:
They are no longer addons.
You can find them [here](https://github.com/badmojr/1Hosts/tree/master/Xtra) as new packs.
See: https://github.com/j-moriarti/pDNSf-Hosts-collection/pull/6

**Comment by thomasmiddleton22** [comment]
> They are no longer addons.
 Updated &
already using them, Thanks for your work.

**Comment by thomasmiddleton22** [comment]
> They are no longer addons.

Updated.
Using them already, thanks for your work.

**Comment by ReaLJohnBaker** [comment]
Example of ad/bad URL's which i found are blocked by nothing else other than 1Hosts (Xtra) (true as of 13 DEC 21)

https://blocklist-tools.developerdan.com/entries/search?q=bestgirls4fuck.com
https://blocklist-tools.developerdan.com/entries/search?q=today-trip.com
https://blocklist-tools.developerdan.com/entries/search?q=av-secure.me
https://blocklist-tools.developerdan.com/entries/search?q=findservice.xyz
https://blocklist-tools.developerdan.com/entries/search?q=ptypygrebu.com

And no doubt many more.. it might just be worth reconsidering.

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/5ed13aaca19a7f14b84c2c5cbc6ac6b9a580c3c3.
