### ISSUE TITLE
Taiwanese

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#658]
https://github.com/FutaGuard/FutaFilter

https://github.com/FutaGuard/FutaFilter/blob/master/hosts.txt

https://github.com/FutaGuard/FutaFilter/blob/master/nofarm_hosts.txt

**Comment by c2xusnpq6** [comment]
@tasi788

**Comment by tasi788** [comment]
ref: https://github.com/nextdns/metadata/issues/603

**Comment by c2xusnpq6** [comment]
> ref: #603

反正nextdns在中國也被污染 搞不懂他們為什麼不要futafilter 他們又不像adguard像中國還能用.....(adguard這個你懂的~~~吧?)

**Comment by romaincointepas** [comment]
Duplicate of https://github.com/nextdns/metadata/issues/603.
