### ISSUE TITLE
Daily feed of bad IPs

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#659]
> Daily feed of bad IPs (with blacklist hit scores)

> IPsum is a threat intelligence feed based on 30+ different publicly available lists of suspicious and/or malicious IP addresses. All lists are automatically retrieved and parsed on a daily (24h) basis and the final result is pushed to this repository. List is made of IP addresses together with a total number of (black)list occurrence (for each). Greater the number, lesser the chance of false positive detection and/or dropping in (inbound) monitored traffic. Also, list is sorted from most (problematic) to least occurent IP addresses.

https://github.com/stamparm/ipsum

https://github.com/stamparm/ipsum/tree/master/levels

https://github.com/stamparm/ipsum/blob/master/levels/4.txt
https://github.com/stamparm/ipsum/blob/master/levels/5.txt
https://github.com/stamparm/ipsum/blob/master/levels/6.txt

**Comment by mtverlee** [comment]
These are not something that can be blocked with DNS.

**Comment by c2xusnpq6** [comment]
> These are not something that can be blocked with DNS.

But you can block those domains that are linked to these IPs? @mtverlee

**Comment by mtverlee** [comment]
Sure, but that seems a little out of the scope of this project IMO. Could be wrong though. At the very least it's a good amount of work to implement, certainly not a quick addition.
