### ISSUE TITLE
New List

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#66]
It's occasionally updated but would be helpful
https://github.com/marktron/fakenews/commits/master

**Comment by scafroglia93** [comment]
https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts.txt

**Comment by romaincointepas** [comment]
URLHaus is already being used by the Threat Intelligence Feeds security feature.

Regarding fakenews, we decided to remove it. It has nothing to do with privacy, security or parental control and is so opinionated that manual blacklisting is a better fit for this.
