### ISSUE TITLE
chinese website whitelist

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#662]
https://github.com/privacy-protection-tools/anti-AD/blob/81df713b4dbbc98a581a4fe75e99ac8d31e41b81/scripts/lib/white_domain_list.php

yellow = why

in this case, this rule will break the app
https://github.com/privacy-protection-tools/anti-AD/blob/81df713b4dbbc98a581a4fe75e99ac8d31e41b81/scripts/lib/white_domain_list.php#L97
![image](https://user-images.githubusercontent.com/75058881/117764260-c95e4300-b25e-11eb-994a-d5efacf046b2.png)

![image](https://user-images.githubusercontent.com/75058881/117766110-a4b79a80-b261-11eb-8cef-50e9b22033ab.png)

**Comment by romaincointepas** [comment]
Could you please report this directly to https://github.com/jdlingyu/ad-wars?
