### ISSUE TITLE
Phishing Army

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#666]
Phishing Army | The Blocklist to filter Phishing! https://phishing.army/

Generated every 6 hours from PhishTank,
OpenPhish, Cert.pl and PhishFindR reports.
Each domain is analyzed to eliminate false positives,
through the Whitelist of Anudeep and the Alexa Rank.

https://phishing.army/download/phishing_army_blocklist.txt

https://phishing.army/download/phishing_army_blocklist_extended.txt

**Comment by crssi** [comment]
This is already included in **Threat Intelligence Feeds**

See https://github.com/nextdns/metadata/blob/master/security/threat-intelligence-feeds.json

**Comment by c2xusnpq6** [comment]
oh great~
