### ISSUE TITLE
False positive for Adobe licensing

### ISSUE THREAD

**Issue by aamck** [nextdns/metadata#670]
`lm.licenses.adobe.com` is blocked by the NextDNS Ads & Trackers Blocklist but is required for Adobe licence deployment, referenced in their endpoints [here](https://helpx.adobe.com/uk/enterprise/kb/network-endpoints.html).

I made an issue with the maintainer https://github.com/VeleSila/yhosts/issues/24 but looking at other issues they've not been responding much, so cross posted here.

**Comment by romaincointepas** [comment]
Should be fixed by https://github.com/nextdns/metadata/commit/d971d617e14a88482c80c8b49c95bded07fc6bc0.
