### ISSUE TITLE
YouTube Ads: blocklist suggestion

### ISSUE THREAD

**Issue by ghost** [nextdns/metadata#672]
I've had good luck with Evan Pratten's domain-based "YouTube Ad Blocklist", which is updated regularly:

https://raw.githubusercontent.com/Ewpratten/youtube_ad_blocklist/gh-pages/domains.txt

I've been importing it into my Deny list in one shot using the "Add a list of domains" feature of NX Enhanced. An occasional ad does slip thru, but rarely for me.  No YouTube breakage as far as I can tell.  Please note that I don't watch pop culture nonsense with billions of views, so perhaps YouTube is more aggressive with advertising in that content.

Simply bocking YouTube ads while watching on computer or phone is easy (hosts, uBlock Origin, ImprovedTube, NewPipe, etc...).  The real value of this domain blocklist is with Chromecast.  While casting YouTube content, Chromecast supplies ads separate from the device doing the casting. Of course a workaround is to cast the screen to get the ad blocking benefits of the source device, but that ruins the multitasking experience. 

Update:  I don't personally use the YouTube Roku app, but I just tested it.  Some ads are blocked, but not all.  Can't imagine wanting to use a Google-based Roku app anyways after Roku recently referred to them as "unchecked monopolists" involved in “predatory business practices”.

Worth a try.  If others have successful results, would love to see it as a Privacy Blocklist option.

**Comment by loopion** [comment]
Thanks for the tip about NX Enhanced and importing that list. It worked like a charm on my end network wise and on mobile with my iOS profile.

This blocklist should be added on the suggested list of NextDNS, but I understand why they don't add it: https://help.nextdns.io/t/q6hmva4/custom-blocklist-support

We'll see if they add it still...

**Comment by nicojan** [comment]
> I've had good luck with Evan Pratten's domain-based "YouTube Ad Blocklist", which is updated regularly:
> 
> https://raw.githubusercontent.com/Ewpratten/youtube_ad_blocklist/gh-pages/domains.txt
> 
> I've been importing it into my Deny list in one shot using the "Add a list of domains" feature of NX Enhanced. An occasional ad does slip thru, but rarely for me. No YouTube breakage as far as I can tell. Please note that I don't watch pop culture nonsense with billions of views, so perhaps YouTube is more aggressive with advertising in that content.
> 
> Simply bocking YouTube ads while watching on computer or phone is easy (hosts, uBlock Origin, ImprovedTube, NewPipe, etc...). The real value of this domain blocklist is with Chromecast. While casting YouTube content, Chromecast supplies ads separate from the device doing the casting. Of course a workaround is to cast the screen to get the ad blocking benefits of the source device, but that ruins the multitasking experience.
> 
> Update: I don't personally use the YouTube Roku app, but I just tested it. Some ads are blocked, but not all. Can't imagine wanting to use a Google-based Roku app anyways after Roku recently referred to them as "unchecked monopolists" involved in “predatory business practices”.
> 
> Worth a try. If others have successful results, would love to see it as a Privacy Blocklist option.

Thank you for your recommendation of NX Enhanced. By using the "Export this config" under the "Settings" tab and editing the JSON file to add [this](https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/black.list) list, you may be able to block significantly more YouTube ads.

**Comment by romaincointepas** [comment]
Youtube Ads can't be blocked at the DNS level because YouTube is serving the ads for the same domain as the videos.

This is either confirmation bias or sheer luck.
