### ISSUE TITLE
Add "semprot.com" and "semprotwow.com" inside Porn filter (Parental Control)

### ISSUE THREAD

**Issue by chigarow** [nextdns/metadata#673]
Hello guys, can you consider to add domain https://semprot.com and https://semprotwow.com inside your Porn Blocklist, because those site contains porn content.

Thankyou so much!

**Comment by romaincointepas** [comment]
Could you suggest this directly at https://dsi.ut-capitole.fr/cgi-bin/squidguard_modify.cgi?
