### ISSUE TITLE
bypass countries with low-strength privacy laws (2)

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#677]
I'm sorry, I didn't say it clearly...

Suppose a Chinese company has overseas business, because its website needs to serve Chinese and non-Chinese at the same time, so it needs to deploy multiple servers. It happens to have a Hong Kong user, and that user is very close to the Chinese server, so NextDNS will  Use a Chinese server to respond to his DNS request, but the Hong Kong user does not want to use a server located in China, and the company actually has servers in Taiwan and Singapore

Priority to use the IP address of a non-Chinese registered place to respond to DNS requests?

and... CNAME records preferentially use non-Chinese domain names (*.cn) to respond to the dns requests?

---

I hope that NextDNS can have a function of "trying to avoid countries with low-strength privacy laws such as China and Russia"

Because some websites(/apps) have servers in different locations, I think users will also want to connect to a more secure ip or server

**Comment by c2xusnpq6** [comment]
@ammnt @mtverlee @beerisgood

**Comment by c2xusnpq6** [comment]
I'm sorry I should use the better term "countries with low levels of human rights" instead of "countries with low levels of privacy laws"

**Comment by c2xusnpq6** [comment]
Totalitarian state? Totalitarianism? Which word do you think is more appropriate? Terrorist? Terrorism?

**Comment by beerisgood** [comment]
I don't think this makes any sense.

Specially china use a strict firewall. But even without, IPs can be changed so this would end in massive maintenance on NextDNS side and isn't worth it.

**Comment by mtverlee** [comment]
The solution to this isn't a function in NextDNS. If you really care this much, the solution is to use privacy-focused apps and software from the beginning.

**Comment by c2xusnpq6** [comment]
If you don't particularly want this feature, it doesn't mean that no one else wants it. And if maintenance is really troublesome and costly, it can be limited to paying users only?

**Comment by c2xusnpq6** [comment]
If you really think it is not feasible, then close this issue, thx!

**Comment by romaincointepas** [comment]
When using DNS-over-HTTPS/TLS (or the majority of the time with legacy DNS), NextDNS will keep you inside your country.

**Comment by c2xusnpq6** [comment]
> When using DNS-over-HTTPS/TLS (or the majority of the time with legacy DNS), NextDNS will keep you inside your country.

Great.

**Comment by c2xusnpq6** [comment]
Wait a minute... My question seems to have not been answered... Maybe I’m a little bit unclear...

What If I would rather have a poor browsing experience, but still want to avoid connecting to servers in high-risk areas?

Suppose I am in Japan now, and I would rather connect to a server in Europe that is farther away than to the server in China that is closest to me? and that website has no server in Japan?

THX!

**Comment by chirag127** [comment]
> the Hong Kong user does not want to use a server located in China,

I used to think that Hong Kong is a part of china.

**Comment by c2xusnpq6** [comment]
> > the Hong Kong user does not want to use a server located in China,
> 
> I used to think that Hong Kong is a part of china.

The reality is that Hong Kong is being controlled by the Chinese mainland government

But if you ask me do they want this? In fact, if you watch the Hong Kong news, you know that they are just like Ukraine... extremely pitiful...

(google translated~)

**Comment by c2xusnpq6** [comment]
> > the Hong Kong user does not want to use a server located in China,
> 
> I used to think that Hong Kong is a part of china.

Many Internet service providers will display mainland China and Hong Kong separately, because they are very different, and the Chinese mainland government is trying to reduce these differences...

**Comment by c2xusnpq6** [comment]
He deleted... ok........ fine....................🤔🤔😑
