### ISSUE TITLE
r3.o.lencr.org and sqgz.veloxity.net

### ISSUE THREAD

**Issue by baronexy** [nextdns/metadata#678]
random.veloxity.net E.G: sqgz.veloxity.net, dacs.veloxity.net  (VSKOR calculates credit score without using financial data for unbanked/underbanked individuals which make up more than 30% of adult population.) IS A TRACKER

r3.o.lencr.org (redirect virus, ads)

I've added them to my blacklist. It should be added to the NextDNS list.

**Comment by beerisgood** [comment]
you need posting these domains to upstream sources.
NextDNS only use sources instead of adding own domains.

**Comment by baronexy** [comment]
> you need posting these domains to upstream sources.
> NextDNS only use sources instead of adding own domains.

ohh sorry, thanks.
