### ISSUE TITLE
Blocking YouTube Ads

### ISSUE THREAD

**Issue by nicojan** [nextdns/metadata#679]
Adding [this updating list](https://github.com/kboghdady/youTube_ads_4_pi-hole/blob/master/black.list) in order to block YouTube ads.

**Comment by beerisgood** [comment]
Use search.

https://github.com/nextdns/metadata/issues/672

**Comment by nicojan** [comment]
> Use search.
> 
> #672

Thank you for linking me to that request; however, the list I've linked to blocks significantly more IPs. Am I missing something?

**Comment by quantumpacket** [comment]
@beerisgood the list @nicojan links to does not contain IPs, and is compatible with NextDNS. I would choose it over #672 as well since it does a much more extensive job at blocking.

**Comment by romaincointepas** [comment]
Youtube Ads can't be blocked at the DNS level because YouTube is serving the ads for the same domain as the videos.
