### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#682]
What if I want to configure different content blocking settings for different (Windows/Android/Mac) apps?

`https://firefox.dns.nextdns.io/` --> 
`https://firefox.dns.nextdns.io/app/{APP_ID}`
or
`https://firefox.dns.nextdns.io/app-{APP_ID}`

e.g. youtube android app `com.google.android.youtube`: 
`https://firefox.dns.nextdns.io/app/com.google.android.youtube`

or disable ads/trackers filtering on app like `shopback`?

**Comment by beerisgood** [comment]
Not possible. Apps would need support own DNS settings

**Comment by mtverlee** [comment]
@beerisgood is correct, this unfortunately isn't possible.

**Comment by c2xusnpq6** [comment]
> Not possible. Apps would need support own DNS settings

yes! adguard!

**Comment by c2xusnpq6** [comment]
Don't think so narrowly, use your imagination

It can also be divided into different settings in different scenarios
e.g. home mode, normal
working mode, for example, app developer, then disable some ads manage platform domain?


(google translated)

**Comment by c2xusnpq6** [comment]
I don’t understand why you keep vetoing my proposal. Those can obviously be applied to many many scenarios.

If that function is very easy to use, there will naturally be apps to adapt to that function

What's more, that function can also be entered manually, as I just said, that can be applied to multiple scenarios

**Comment by mtverlee** [comment]
I don't think you're understanding what we're saying. It's a great idea, just not possible as things are right now.

For example, with your YouTube app, that YouTube app itself would need to be able to have its own DNS settings, not to mention encrypted DNS support, both of which are currently unsupported and are unlikely to be supported. In addition, things like YouTube con Chromecast uses hardcore DNS addresses and that's  unlikely to change as well.

**Comment by c2xusnpq6** [comment]
> If that function is very easy to use, there will naturally be apps to adapt to that function

If the smart set-top box cannot change the dns setting, maybe you can start from the router side?

**Comment by beerisgood** [comment]
> > If that function is very easy to use, there will naturally be apps to adapt to that function
> 
> If the smart set-top box cannot change the dns setting, maybe you can start from the router side?
> 
> > What's more, that function can also be entered manually, as I just said, that can be applied to multiple scenarios

Just no. You should read how DNS works as it doesn't work like you think.

And no, apps like adguard doesn't help. Every app need to support own DNS resolver which would never happen as it doesn't make any sense.

So my recommendation is to close this issu

**Comment by c2xusnpq6** [comment]
or..... maybe.....

`https://dns.nextdns.io/ee95e7/mode/home` or `https://dns.nextdns.io/ee95e7/mode/working`

`https://dns.nextdns.io/ee95e7/device/my_android_phone` or `https://dns.nextdns.io/ee95e7/device/home_pc`

**Comment by c2xusnpq6** [comment]
just close it then.....
