### ISSUE TITLE
bypass countries with low-strength privacy laws (3)

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#695]
Wait a minute... My question seems to have not been answered... Maybe I’m a little bit unclear...

What If I would rather have a poor browsing experience, but still want to avoid connecting to servers in high-risk areas?

Suppose I am in Japan now, and I would rather connect to a server in Europe that is farther away than to the server in China that is closest to me? and that website has no server in Japan?

THX! @romaincointepas

https://github.com/nextdns/metadata/issues/677#issuecomment-859550820

**Comment by romaincointepas** [comment]
Please keep your response in the initial issue.

We don't offer this (or any other sort of tunneling out), it doesn't really make sense for DNS.
