### ISSUE TITLE
[Threat Intelligence] CyberSayan List

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#701]
CyberSayan is the largest italian whitehat community 

Source ->
https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE

**Comment by SohanRay** [comment]
> CyberSayan is the largest italian whitehat community
> 
> Source -> https://infosharing.cybersaiyan.it/feeds/CS-PIHOLE

The above link seems blank/empty. This issue can be closed I think.
