### ISSUE TITLE
Blocklist Suggestion

### ISSUE THREAD

**Issue by iaxat** [nextdns/metadata#702]
https://github.com/gorhill/uBlock

I am sure you might have received this blocklist name many many times.
It is my dearest and humblest request, please add this to the blocklist, I just joined your premium service today and I love it. If you just include the Ublock Origin, I am sure most of the people will not require any other blocklist and that will be so great for the users.

**Comment by mtverlee** [comment]
You didn't link to a list. Furthermore, as far as I know, UBlock blocks elements and tags, and thus is not DNS-compatible. Recommend closing this issue.

**Comment by beerisgood** [comment]
Not usable with NextDNS or DNS generally

**Comment by iaxat** [comment]
I am just looking for a blocklist that can help me remove ads just like ublockorigin does.

**Comment by iaxat** [comment]
Any Advice?

**Comment by mtverlee** [comment]
You're not going to find a DNS list that does what UBlock does because UBlock blocks elements of the page on load and DNS simply cannot do that. The best approach is a combination of UBlock and DNS blocking.

**Comment by iaxat** [comment]
> You're not going to find a DNS list that does what UBlock does because UBlock blocks elements of the page on load and DNS simply cannot do that. The best approach is a combination of UBlock and DNS blocking.

Trying to understand, so inside the settings, there are blocklists that say that they can block ads and trackers, are they not blocking ads?

**Comment by beerisgood** [comment]
> > You're not going to find a DNS list that does what UBlock does because UBlock blocks elements of the page on load and DNS simply cannot do that. The best approach is a combination of UBlock and DNS blocking.
> 
> Trying to understand, so inside the settings, there are blocklists that say that they can block ads and trackers, are they not blocking ads?

They do but as @mtverlee already wrote, website elements can't be blocked with DNS.
Only full domains like domain.com and sub domains like tracking.domain.com can blocked.
If the site itself include ads or tracking (like YouTube) you can't block it at DNS without breaking the whole site.

**Comment by crssi** [comment]
See https://github.com/nextdns/metadata/issues/683#issuecomment-853668764

Cheers

**Comment by iaxat** [comment]
thank you :)
