### ISSUE TITLE
Threat Intelligence 

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#71]
They could be perfect for inclusion in the group

filtri-dns.ga/filtri.txt
infosharing.cybersaiyan.it/feeds/CS-PIHOLE
osint.digitalside.it/Threat-Intel/lists/latestdomains.txt

**Comment by romaincointepas** [comment]
`filtri-dns.ga/filtri.txt`: seems to include trackers as well, so a no go.

The other 2 are not reputable enough to be included (and probably redundant as well).
