### ISSUE TITLE
px-conf.perimeterx.net

### ISSUE THREAD

**Issue by jawz101** [nextdns/metadata#721]
I tried looking for this entry on AdGuard's DNS blocklist but I do not see it in the AdGuard DNS github repo.  I'm going to reach out to EasyPrivacy as well, but I would think this would be a good one to exclude from blocking for what they do.  It looks like it's a fraud prevention mechanism for shopping sites and apps.  Personally, I'm all for fraud prevention.

(adaway list maintainer here)

**Comment by romaincointepas** [comment]
Seems to be blocked my many third-party blocklists.
