### ISSUE TITLE
Many NSFW  domain not blocked

### ISSUE THREAD

**Issue by chirag127** [nextdns/metadata#728]
1. https://hitbdsm.com/
2. https://privatehomeclips.com/
3. https://xhamster12.desi/
4. https://porntn.com/
5. https://adult.noodlemagazine.com/new-video
6. https://adultsearch.com/
7. https://www.porn00.tv/

The above domains / urls are not blocked by the nextdns Porn category in Parental controls .

**Comment by 3xploiton3** [comment]
> 1. https://hitbdsm.com/
> 2. https://privatehomeclips.com/
> 3. https://xhamster12.desi/
> 4. https://porntn.com/
> 5. https://adult.noodlemagazine.com/new-video
> 6. https://adultsearch.com/
> 7. https://www.porn00.tv/
> 
> The above domains / urls are not blocked by the nextdns Porn category in Parental controls .

submit to this site
https://cliqz.com/en/report-url#adult

**Comment by chirag127** [comment]
now added somewhere in the upstream. Thank you.
