### ISSUE TITLE
vox.com is blocked by the internal 'social network' list

### ISSUE THREAD

**Issue by 07416** [nextdns/metadata#733]
https://en.wikipedia.org/wiki/Vox_(website)

Vox isn't a social network website.

**Comment by chirag127** [comment]
reporting upstream can be more useful.

**Comment by 07416** [comment]
> reporting upstream can be more useful.

@chirag127 This is the "upstream" issue tracker:

>This repository contains the data behind our Security, Privacy and Parental Control features.

'social network' list falls under parent control:

![image](https://user-images.githubusercontent.com/14923168/126594244-1e85f33e-d6bf-40da-963c-606b29341d1a.png)

**Comment by lyrad87** [comment]
In this case though, upstream means "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/social_networks/domains", see https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/social-networks.json. It's usually better to mention it to the list maintainer or add it to the Allowlist yourself.

**Comment by chirag127** [comment]
> In this case though, upstream means "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/social_networks/domains", see

Ya, that's what upstream mean.

**Comment by 07416** [comment]
> In this case though, upstream means "https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/social_networks/domains", see https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/social-networks.json. It's usually better to mention it to the list maintainer or add it to the Allowlist yourself.

I fully understand no. **I wish that NextDNS would clarify in the web UI that the lists are created by third-parties**.

The repo is a read-only mirror in fact: https://github.com/olbat/ut1-blacklists/issues/8
