### ISSUE TITLE
Domains to block

### ISSUE THREAD

**Issue by us40123** [nextdns/metadata#735]
Adult:
ackinprivacy.com.br
hubgif.com
papersculpture.eu
denisenkov.org
phatgifs.com
liongif.com
gifsauce.com
datawav.club
scrolller.com
exgf.party
nsfw.myconfinedspace.com
phatgifs.com
nenyda.com
pillowfort.social

Download site:
freeomovie.to
maxmovies.club
katmoviehd.sx
123movieswatchonline.net
moviestube.co
tinyzonehd.net
movies123.studio
southfreak.bar
gomovies.agency
streaming247.nl
movies123.cam
123movies-org.com
www5.0123movies.net

dood.so
streamtape.com
evoload.io

**Comment by beerisgood** [comment]
report them to the filter list maintainer.
NextDNS only use those lists.

**Comment by drego85** [comment]
Hi @Clefspeare13, can you add this porn site in your blocklist? Thanks

**Comment by spirillen** [comment]
Hey @drego85 

@Clefspeare13 haven't been around for over a year, And I'm the one keeping his repo alive, but as [announced](https://github.com/Clefspeare13/pornhosts/blob/master/CONTRIBUTING.md#the-nearly-as-fast-commit-approach), I have started to migrate it into https://mypdns.org/my-privacy-dns/porn-records, however as it is a huge process (human verification of all records) this isn't done within the next month.

This said, I would be very happy to include them but bulk lists ain't doing well with my scripts, which means one domain = on issue, complete the guides, you are already on the side so easily a quickly done vs I have to revisit each side a spend about 20 to 25 minutes per domain to do what you can do in 2 to 3 minutes while you already on the sites.

Another thing is @romaincointepas has announced @nextdns would build yet another pornlist rather chan contribute or collaborate with existing lists: See https://github.com/nextdns/metadata/issues/569#issuecomment-860041895

PS: https://mypdns.org/my-privacy-dns/porn-records requires login to keep it off public as it contains adult material.

**Comment by drego85** [comment]
Thanks @spirillen for the clarifications! ;)

**Comment by spirillen** [comment]
Already dead domains on the list supplied:
```
ackinprivacy.com.br
```

Needs more information on why you think this should be added
```
movies123.studio
www5.0123movies.net
pillowfort.social
katmoviehd.sx
moviestube.co
tinyzonehd.net
southfreak.bar
gomovies.agency
streaming247.nl
movies123.cam
123movies-org.com

```

Following have been created at the given point and added to the source of https://mypdns.org/my-privacy-dns/porn-records

hubgif.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/143
papersculpture.eu => https://mypdns.org/my-privacy-dns/porn-records/-/issues/144
denisenkov.org => https://mypdns.org/my-privacy-dns/porn-records/-/issues/145
phatgifs.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/146
liongif.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/147
gifsauce.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/148
datawav.club => https://mypdns.org/my-privacy-dns/porn-records/-/issues/149
scrolller.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/16
exgf.party => https://mypdns.org/my-privacy-dns/porn-records/-/issues/150
nsfw.myconfinedspace.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/151
phatgifs.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/146
nenyda.com => https://mypdns.org/my-privacy-dns/porn-records/-/issues/153
pillowfort.social => https://mypdns.org/my-privacy-dns/porn-records/-/issues/154

freeomovie.to => https://mypdns.org/my-privacy-dns/porn-records/-/issues/155
maxmovies.club => https://mypdns.org/my-privacy-dns/porn-records/-/issues/156


dood.so => (Epic Head) `doodstream.com` which became no less than 7 domains that might need to be added into the [Strict](https://archive.mypdns.org/w/rpzlist/#strict-adult-mypdns-cloud) list. https://mypdns.org/my-privacy-dns/porn-records/-/issues/159
streamtape.com => https://mypdns.org/my-privacy-dns/issues/-/issues/2511 (https://archive.mypdns.org/T2511)
evoload.io => Only record I have of this domain is on `thecandidbay.com` https://mypdns.org/my-privacy-dns/porn-records/-/issues/168 , I would like to see more before adding them as I haven't noticed any place where `evoload.io` accepts adult contents
