### ISSUE TITLE
Query dns records directly with IP

### ISSUE THREAD

**Issue by c2xusnpq6** [nextdns/metadata#737]
Users with complex network environments may not be able to resolve "firefox.dns.nextdns.io"

Can I directly use ip to query dns records? Like Cloudflare? `https://1.1.1.1/dns-query`

**Comment by rs** [comment]
You need to use bootstrap IPs with clients having this capability or our [CLI](https://github.com/nextdns/nextdns) which will work out of the box in such context.

Please use https://help.nextdns.io for such questions in the future. This repository is only about metadata.
