### ISSUE TITLE
Custom blocklist

### ISSUE THREAD

**Issue by leventyalcin** [nextdns/metadata#738]
Hi, 

I've just started to create a custom list to block domain names in scam text that I get in the UK. I thought it could also be beneficial to people in UK as well. 

As far as I can see in the documentation, I have to open an issue in here in order to make my blocklist available to the community. 

Please consider to add this <https://github.com/leventyalcin/uk-scam-text-dns-block/blob/master/hosts> custom list into yours. 

Thanks, 
L.

**Comment by romaincointepas** [comment]
Could you recommend it to https://phishing.army?
