### ISSUE TITLE
New Filter List Suggestions

### ISSUE THREAD

**Issue by bslatyer** [nextdns/metadata#741]
Hi,

I was wondering if the following lists could be looked at to see if they can be added to NextDNS?

Thanks!

### AdGuard Annoyances filter
```https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt```

### Adblock Warning Removal List
```https://easylist-msie.adblockplus.org/antiadblockfilters.txt```

### I Don't Care About Cookies List
```https://www.i-dont-care-about-cookies.eu/abp/```

### Spam404 Filter List
```https://raw.githubusercontent.com/Spam404/lists/master/adblock-list.txt```

### NoCoin Filter List
```https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt```

### Online Malicious URL Blocklist
```https://curben.gitlab.io/malware-filter/urlhaus-filter.txt```

### Legitimate URL Shortener
```https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt```

**Comment by ClusterByte-x** [comment]
@bslatyer Some of these filters cannot benefit from the DNS level. NoCoin is included in the basic configuration, Spam404 is included in threat information sources.
