### ISSUE TITLE
Pls add clone profile feature

### ISSUE THREAD

**Issue by securewithsam** [nextdns/metadata#746]
Pls add clone profile , instead of creating a new profile everytime with all settings

**Comment by lyrad87** [comment]
That's not the right place to ask for this I assume since this is focused on metadata. You should probably mention it [here](https://help.nextdns.io/category/ideas) instead, but someone already did, see [here](https://help.nextdns.io/t/35htafy/ability-to-clone-an-existing-profile).

**Comment by romaincointepas** [comment]
What @lyrad87 said.
