### ISSUE TITLE
Add Google AMP blocklist

### ISSUE THREAD

**Issue by paulfarnell** [nextdns/metadata#748]
I see you host other blocklists maintained by the same author. Would be great to add his Google AMP list.

https://www.github.developerdan.com/hosts/lists/amp-hosts-extended.txt

Thanks 🙏

**Comment by quantumpacket** [comment]
That entire list can be simplified into this short list:

```
0.0.0.0 amp-assets.cinemablend.com
0.0.0.0 amp.akamaized.net
0.0.0.0 amp.businessinsider.com
0.0.0.0 amp.cinemablend.com
0.0.0.0 amp.cloudflare.com
0.0.0.0 amp.kirklands.com
0.0.0.0 amp.knoxnews.com
0.0.0.0 amp.newsobserver.com
0.0.0.0 amp.reddit.com
0.0.0.0 amp.si.com
0.0.0.0 amp.spot.im
0.0.0.0 amp.tennessean.com
0.0.0.0 amp.theguardian.com
0.0.0.0 amp.thestate.com
0.0.0.0 amp.thisisinsider.com
0.0.0.0 amp.usatoday.com
0.0.0.0 ampproject.net
0.0.0.0 ampproject.org
0.0.0.0 block-test-amp.developerdan.com
0.0.0.0 block-test.developerdan.com
0.0.0.0 cdn-social.janrain.com
0.0.0.0 www.amp.reddit.com
0.0.0.0 www.block-test.developerdan.com
```

**Comment by paulfarnell** [comment]
Thank you very much for the swift reply @quantumpacket, and the neat script you shared.

I now understand that _DNS-level blocking_ of AMP URLs will **not** be effective for redirecting users to canonical (non-AMP) URLs. I appreciate your comments and insight. Cheers!
