### ISSUE TITLE
[NOBUG] Thank you for your awesome work!

### ISSUE THREAD

**Issue by MikeeI** [nextdns/metadata#75]
I think you get way too less "thank yous" for your work. 

I'm just so grateful to use it and profit from your dedication.

DNS Blocking is now my passion.

Just a thank you. 😊

![200](https://user-images.githubusercontent.com/13944905/75364686-63390a80-58bc-11ea-8dc5-50a684ad23f2.gif)

**Comment by romaincointepas** [comment]
![](https://media.giphy.com/media/j0qSbeNFuzjhXKFVSP/giphy.gif)
