### ISSUE TITLE
Please add 'I don't care about cookies' script

### ISSUE THREAD

**Issue by nagalronnen** [nextdns/metadata#750]
Hi Olivier, 
On the cell-phone it's really annoying to press to accept cookies on every page. (specially in EU)
I don't case about cookies has few browser-extensions, as well as a script that can block most.
In their website: https://www.i-dont-care-about-cookies.eu/
Under 'Adblock Plus' there is an option to view the script ('download the list'), updated regularly, and well trusted.
I love nextdns, and I will love it even more with this script as an option. 

Thank you.

**Comment by beerisgood** [comment]
You can't block website elements with DNS

**Comment by nagalronnen** [comment]
I tried this script on Gas-Mask app on Mac and it works like a charm across all Mac apps ! 
(rss reader and such) 
So, why not on our beloved NextDNS ?

**Comment by beerisgood** [comment]
> I tried this script on Gas-Mask app on Mac and it works like a charm across all Mac apps !
> (rss reader and such)
> So, why not on our beloved NextDNS ?

You're confused. Using an App which can block elements isn't same as using basic DNS.
DNS can only handle domain names as the word already says: Domain Name System.

**Comment by crssi** [comment]
As @beerisgood said.

Out of a little more than 22300 rules 67 only are useful for DNS blocking.

You can add those to your Denylist and see if it solves some of your problems:
```
eurocookie.galilcloud.wixapps.net
cookie.consent.is
api.cookielaw.eu
api.cookielaw-script.it
cookies.innershed.co.uk
cookies.algo.at
cookielaw.emea.fcagroup.com
up-cookiemon.wavecdn.net
bs-cookie.staging.springbok.agency
flipdish-cookie-consent
cookieconsent.syreta.com
cookie-bar.salessquad.co.uk
cookiemon.atcom.gr
js.cookietagmanager.net
procookie.by.nf
jquery-eu-cookie-law-popup
cookies.ae-webdesign.com
consent-notice.magix.com
consent.theneweuropean.co.uk
cdn.appconsent.io
consent.23g.io
browser-consent-front.coco.s-cloud.fi
consent-manager.metomic.io
cmp.uniconsent.com
choices.consentframework.com
consentserve.mgr.consensu.org
analytics-consent-manager.azureedge.net
gdpr.internetbrands.com
gdpr-banner.awsmpsa.com
jssdk.privacy.pre.schibsted.com
privacy.schibsted.com
privacy-policy.u-lab.nl
app.eprivacy-keeper.eu
privacy.claytonhomes.com
cmp.dreamlab.pl
cmp.cdntrf.com
cmp.mediavine.com
cmp-loader.choice.faktor.io
cmp.osano.com
cmp.md-nx.com
cdn.opencmp.net
cdncmp.richaudience.com
cmp.cls.pm
cmp.optad360.io
gemius.mgr.consensu.org
sddan.mgr.consensu.org
digitrust.mgr.consensu.org
sharethis.mgr.consensu.org
webads.mgr.consensu.org
sibboventures.mgr.consensu.org
etarget.mgr.consensu.org
marfeel.mgr.consensu.org
shinystat.mgr.consensu.org
dan.mgr.consensu.org
ogury.mgr.consensu.org
inforpl.mgr.consensu.org
fundingchoices.google.com
cdn.userdatatrust.com
st.getsitecontrol.com
cdn.truendo.com
widgets.legalmonster.com
nexus.ensighten.com
privacidade.api.milvus.com.br
global.ketchcdn.com
connect.danone.es
notice.sp-prod.net
tag.goadopt.io
```

Let us know your observations... 😉 
Cheers

**Comment by beerisgood** [comment]
Remember that blocking any such domain will end in a non-customisation for Cookies on these sites/ sites which use these scripts.
In worst case, (Third-Party-)tracking is activated/ Opt-Out not enabled,

**Comment by nagalronnen** [comment]
> As @beerisgood said.
> 
> Out of a little more than 22300 rules, 67 only are useful for DNS blocking.
> 
> You can add those to your Denylist and see if it solves some of your problems:
> 
> ```
> eurocookie.galilcloud.wixapps.net
> cookie.consent.is
> api.cookielaw.eu
> api.cookielaw-script.it
> cookies.innershed.co.uk
> cookies.algo.at
> cookielaw.emea.fcagroup.com
> up-cookiemon.wavecdn.net
> bs-cookie.staging.springbok.agency
> flipdish-cookie-consent
> cookieconsent.syreta.com
> cookie-bar.salessquad.co.uk
> cookiemon.atcom.gr
> js.cookietagmanager.net
> procookie.by.nf
> jquery-eu-cookie-law-popup
> cookies.ae-webdesign.com
> consent-notice.magix.com
> consent.theneweuropean.co.uk
> cdn.appconsent.io
> consent.23g.io
> browser-consent-front.coco.s-cloud.fi
> consent-manager.metomic.io
> cmp.uniconsent.com
> choices.consentframework.com
> consentserve.mgr.consensu.org
> analytics-consent-manager.azureedge.net
> gdpr.internetbrands.com
> gdpr-banner.awsmpsa.com
> jssdk.privacy.pre.schibsted.com
> privacy.schibsted.com
> privacy-policy.u-lab.nl
> app.eprivacy-keeper.eu
> privacy.claytonhomes.com
> cmp.dreamlab.pl
> cmp.cdntrf.com
> cmp.mediavine.com
> cmp-loader.choice.faktor.io
> cmp.osano.com
> cmp.md-nx.com
> cdn.opencmp.net
> cdncmp.richaudience.com
> cmp.cls.pm
> cmp.optad360.io
> gemius.mgr.consensu.org
> sddan.mgr.consensu.org
> digitrust.mgr.consensu.org
> sharethis.mgr.consensu.org
> webads.mgr.consensu.org
> sibboventures.mgr.consensu.org
> etarget.mgr.consensu.org
> marfeel.mgr.consensu.org
> shinystat.mgr.consensu.org
> dan.mgr.consensu.org
> ogury.mgr.consensu.org
> inforpl.mgr.consensu.org
> fundingchoices.google.com
> cdn.userdatatrust.com
> st.getsitecontrol.com
> cdn.truendo.com
> widgets.legalmonster.com
> nexus.ensighten.com
> privacidade.api.milvus.com.br
> global.ketchcdn.com
> connect.danone.es
> notice.sp-prod.net
> tag.goadopt.io
> ```
> 
> Let us know your observations... 😉
> Cheers

Thank you, I’ll give it a try.  Thanks.

**Comment by nagalronnen** [comment]
Need to add hem one by one.

**Comment by crssi** [comment]
When I drilled down those 65...

60 are listed in OISD and a few also in 1Hosts Lite (also in Pro, obviously).
3 are listed in 1Hosts Lite (also in Pro, obviously).

And 2 are not listed in OISD or 1Hosts.

So, you can add OISD and 1Hosts Lite (or 1Hosts Pro) and add the following on the Denylist:
```
consent.theneweuropean.co.uk
digitrust.mgr.consensu.org
```

**Comment by crssi** [comment]
If you check my github profile, you will see that those two lists are the only I would suggest to anyone.
If you dare more, then you can go also with the !Hosts Pro instead of Lite... Pro is lately very good with almost no breakages, at least very little were spotted here.

Cheers

**Comment by nagalronnen** [comment]
> When I drilled down those 65...
> 
> 60 are listed in OISD and a few also in 1Hosts Lite (also in Pro, obviously).
> 3 are listed in 1Hosts Lite (also in Pro, obviously).
> 
> And 2 are not listed in OISD or 1Hosts.
> 
> So, you can add OISD and 1Hosts Lite (or 1Hosts Pro) and add the following on the Denylist:
> 
> ```
> consent.theneweuropean.co.uk
> digitrust.mgr.consensu.org
> ```
> 
> For the last two, that is the manual addidtion I wouldn't even bother.. if there will be a lot of it, then I am sure those two will get on mentioned lists very soon. 😉

Great! Thank you!!
