### ISSUE TITLE
Add CoinBlocker list :)

### ISSUE THREAD

**Issue by n3tlif3** [nextdns/metadata#754]
Hey dear NextDNS Team,

what about adding this list to yours? Would be a nice combination. :) Stay safe!
https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser

**Comment by crssi** [comment]
That is already included in Security -> Cryptojacking Protection.

Or better, over other privacy lists like 1Hosts Lite, 1 Hosts Pro or OISD.

**Comment by romaincointepas** [comment]
Already used by our Cryptojacking security feature.
