### ISSUE TITLE
Blocklists

### ISSUE THREAD

**Issue by denrusvrn** [nextdns/metadata#755]
Hello!If I'm not mistaken, then you need to slightly change the link to the Goodreads list, since the HOSTS format is currently used by reference https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt, and you need the ADBLOCK format at this link here https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt and I really hope that you have heard me and will correct this as far as possible, and there are also a lot of lists for correcting links to valid and correct formats for proper blocking by DNS and deleting those that are not valid or have not been updated for a long time, since you need to keep all this up to date.Thank you in advance and thank you for your understanding!!!

**Comment by quantumpacket** [comment]
@denrusvrn if I understand what you're saying you are asking to replace the 1st link with the 2nd?

If so, that will not work as the 2nd link is not meant for DNS and will not work with NextDNS.

**Comment by denrusvrn** [comment]
And why then is this intended https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt and it seems like the format of the list is the same, but that is not clear at all, well, okay, you know better.

**Comment by quantumpacket** [comment]
@denrusvrn DNS blocking via a plugin/addon/extension is not the same as blocking DNS at the network level, the latter being how NextDNS operates. Scroll all the way down on the list and you will see a lot of `@@` entries.

> it seems like the format of the list is the same

Seems, is not the same. One is a format for a DNS resolver, to parse and the other is for a browser/software to parse. The DNS entries NextDNS uses would be in the format `0.0.0.0 example.com`.

**Comment by crssi** [comment]
Most of those might be fine, but there are some that are not.

TL/DR:
For NextDNS there should be a FQDN entries that may or may be not wrapped around.
At the moment that there are specifics by path/file, protocol, parameter or using wilcard then this rule is not to be accepted.

That is a short explanation, but the things might get more complicated. 😉
