### ISSUE TITLE
audioboom.com being blocked by Ads and Trackers Blocklist

### ISSUE THREAD

**Issue by dracomjb** [nextdns/metadata#756]
audioboom.com is being blocked, requiring an explicit whitelist.  That site is for distributing podcasts, so I don't understand why the domain is being blocked.

**Comment by lyrad87** [comment]
Not blocked for me if you were referring to the NextDNS Ads & Trackers Blocklist. It may have been fixed upstream.

**Comment by dracomjb** [comment]
yes I was referring to that blocklist. It was blocked until I whitelisted it.

**Comment by romaincointepas** [comment]
Fixed
