### ISSUE TITLE
subdomains of quora.com have adult content

### ISSUE THREAD

**Issue by dooley74** [nextdns/metadata#759]
dirtyvideos.quora.com
pornpics.quora.com
pinkpussyy.quora.com
amateurpornographymodels.quora.com
pornxxx.quora.com
iam18.quora.com
nsfw2.quora.com
neilgrsse.quora.com

I'm sure there are more, it would be safer to just add the entire quora.com domain to the adult content block list.

**Comment by quantumpacket** [comment]
I'm sure the same can be said for any website that allows user content on subdomains. Blocking the entire domain seems a bit aggressive when the site has far more safer content than adult content, which would be a lot more useful than not.

Quora allows adult content per:
- https://help.quora.com/hc/en-us/articles/4405052142868-What-is-an-Adult-Space-on-Quora-
- https://help.quora.com/hc/en-us/articles/360000470683-What-is-Quora-s-Policy-on-Sex-Related-Content-

This limits what is shown to an (un)authenticated user. If an account is in violation of these policies and allows viewing by anyone then it should be reported to the platform.

**Comment by dooley74** [comment]
With respect, I don't give a flying fig what quora's policies are, and I dont see how even mentioning what quora policy is is even relevant in this particular instance. 
Their domain hosts porn.
I'm posting about that fact on a forum which explicitly deals with a service which can be used for the blocking of porn content.
If someone wants to block porn, and still be able to view quora.com content then they can add an allow rule exception.

**Comment by quantumpacket** [comment]
Twitter also hosts adult content, but you don't see it on the adult blocklist. There has to be a line between usability and coverage. NextDNS is not just used by home users, it's also used in business/organizational environments. So asking an admin to make an exclusion for every legitimate subdomain a user needs is not practical, when the safe content far exceeds the adult content.

**Comment by dooley74** [comment]
`The same can be said if someone wants to block adult content on quora.com, they can create a deny rule.`
More than happy to, can you share that list of urls with us please?

It's easier to block the porn category and add an allow for *.quora.com, than it is to ad god knows how many urls linking to porn pages on quora.com.

**Comment by quantumpacket** [comment]
Your original suggestion is to block the entire domain. So why would the deny rule that I suggest you use be any different? Block the entire domain and call it a day.

**Comment by dooley74** [comment]
I have blocked the entire domain, but I'm surprised that as it offers porn to unauthenticated users it's not on the porn blocking list.

**Comment by dooley74** [comment]
`Adding that rule will override ALL blocklists, so you basically accomplished nothing.`
That was in response to your "quora's too good to block because of porn" comment. 
If a person wanted to block porn, but still have access to quora, then it's easily done by adding an exception so that quora can be viewed while still having pornhub and the like blocked by the porn blocking list.

**Comment by spirillen** [comment]
Thanks G... third world war for a question about where and how to have sub-domains serving porn blacklisted :unamused: 

@dooley74 the answer is as simple as adding your findings to https://mypdns.org/my-privacy-dns/matrix/-/issues/2318 and we take them to the [Porn Records](https://mypdns.org/my-privacy-dns/porn-records) IF, however it is a significant amount of subdomains, then please upen up a new `quora.com` issue at Porn Records https://mypdns.org/my-privacy-dns/porn-records/-/issues/new?issuable_template=Adult_contents&issue[title]=quora.com

**Comment by romaincointepas** [comment]
We are moving to our internal Porn AI, those should be fixed soon.
