### ISSUE TITLE
Kindle's covers thumbnails being blocked

### ISSUE THREAD

**Issue by maddler** [nextdns/metadata#76]
kindle-store.images-amazon.com is being blocked by NextDNS Recommended Ads & Trackers Blocklist.

Steps to reproduce:
1. Enable "NextDNS Recommended Ads & Trackers Blocklist"
2. Open Kindle app or e-reader and download a new book

Expected behavior: books covers being shown in the book list.
Actual behavior: no cover thumbnails show

Workaround available: add kindle-store.images-amazon.com to whitelist

**Comment by romaincointepas** [comment]
Fixed, thanks!
