### ISSUE TITLE
NSABlocklist

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#763]
https://github.com/CHEF-KOCH/NSABlocklist is not available

change to 

https://github.com/shyamsantoki/nsablocklist

**Comment by beerisgood** [comment]
The whole blacklist doesn’t make sense
See https://github.com/nextdns/metadata/pull/507

**Comment by pYFZOS5** [comment]
https://github.com/nextdns/metadata/pull/507#issuecomment-932814279

**Comment by pYFZOS5** [comment]
@3xploiton3 who're owners of that? it get deleted from everywhere, including forks
https://github.com/shyamsantoki/nsablocklist (gone)

**Comment by romaincointepas** [comment]
We will be removing this blocklist soon.
