### ISSUE TITLE
Allow clickhouse.com 

### ISSUE THREAD

**Issue by manigandham** [nextdns/metadata#765]
Clickhouse is an open-source analytical data warehouse product. Originally at https://clickhouse.tech and now hosted at https://clickhouse.com

Clickhouse.com should not be blocked.

![image](https://user-images.githubusercontent.com/457226/134070709-3f413b8f-c713-4c85-bd01-2f4aa7a5953d.png)

**Comment by lyrad87** [comment]
Blocked by StevenBlack, so you should report it [upstream](https://github.com/StevenBlack/hosts/issues).

**Comment by manigandham** [comment]
@lyrad87 Got it. Looks like it's already reported there, and StevenBlack is just another aggregator list with more upstreams https://github.com/StevenBlack/hosts/issues/1765
