### ISSUE TITLE
Block autodiscover.{tld}

### ISSUE THREAD

**Issue by ThePowerOfDreams** [nextdns/metadata#769]
Rather than leaving this to third-party blocklists, I suggest that NextDNS immediately add `autodiscover.{tld}`, for all TLDs, to its own base security protection due to [this](https://www.guardicore.com/labs/autodiscovering-the-great-leak/).

**Comment by Rexadev** [comment]
> autodiscover

There is no TLD with that name according to the article these should be blocked -

Autodiscover.com.br – Brazil
Autodiscover.com.cn – China
Autodiscover.com.co – Columbia
Autodiscover.es – Spain
Autodiscover.fr – France
Autodiscover.in – India
Autodiscover.it – Italy
Autodiscover.sg – Singapore
Autodiscover.uk – United Kingdom
Autodiscover.xyz
Autodiscover.online
Autodiscover.cc
Autodiscover.studio
autodiscover.capital
autodiscover.club
autodiscover.company
autodiscover.jp       
autodiscover.me       
autodiscover.mx       
autodiscover.ventures

**Comment by rs** [comment]
Already done
