### ISSUE TITLE
zaobao.com.sg is labeled as porn site incorrectly

### ISSUE THREAD

**Issue by tsekityam** [nextdns/metadata#77]
zaobao.com.sg is a Singaporean newspaper website, however, it is listed in https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt.

**Comment by romaincointepas** [comment]
Fixed with https://github.com/nextdns/metadata/commit/bf5dfcb5223a80f1e7f904a6835ac06ae52dd233
