### ISSUE TITLE
CERT.PL phishing sites aimed at Polish users

### ISSUE THREAD

**Issue by pawelkoszalin** [nextdns/metadata#770]
[https://hole.cert.pl/domains/domains_hosts.txt](https://hole.cert.pl/domains/domains_hosts.txt)
Phishing sites aimed at Polish users, list hosted by cert.pl. It is consolidated list from CERT Poland and major Polish telecoms.

**Comment by ClusterByte-x** [comment]
This list is already included in NextDNS.
