### ISSUE TITLE
inwx.de/.com identified as Porn

### ISSUE THREAD

**Issue by jeifour** [nextdns/metadata#772]
When I try to visit the website of my domain registrar (INWX GmbH & Co. KG), which is just a regular ICANN-accredited domain registrar (IANA number 1420), it doesn't work. Apparently because of porn blocklist. I have tried to identify this entry in the blocklists of third parties but wasn't able to find it.

I also made a screenshot, sorry but it is in Japanese and I there's no language changer on the NextDNS website. It says "Blocked by Porn." when hovering over the "i" button.

![スクリーンショット 2021-09-28 22 47 57](https://user-images.githubusercontent.com/3247063/135163835-8935907c-0af2-41ba-b996-012f9d168a01.png)

**Comment by jeifour** [comment]
This is unfortunately still the case. Cannot access https://www.inwx.de

**Comment by quantumpacket** [comment]
I believe the domain is being blocked by [parentalcontrol/categories/porn.json#L8](https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/porn.json#L8). However, the associated GitHub [account](
https://github.com/Clefspeare13/pornhosts) for that list has been disabled. As far as I know NextDNS is caching the old copy as it's the only one available, even though it's no longer maintained.

For now just add `fry.inwx.net` to your allow list.

**Comment by romaincointepas** [comment]
Fixed
