### ISSUE TITLE
Allow affiliate link not working

### ISSUE THREAD

**Issue by Singhson13** [nextdns/metadata#775]
Hi
Sorry to bother you. I have enabled Allow Affiliate Link but these ones are all blocked

 This one is from a forum that doesn't work, it's blocked. Ironically it's all related to home Depot
https://the-home-depot-ca.pxf.io/c/341376/583694/9526?u=https://www.homedepot.ca/en/home/categories/all/collections/charged-up-event.html is unreachable.

Another one related to Canadian Tire email links for their promos
http://click.myctm.canadiantire.ca

This one for prime cables email link
https://click.icptrack.com/icp/relay.php?r=67605929&msgid=948492&act=Q1WX&c=345082&destination=https%3A%2F%2Fwww.primecables.ca

This one for Dell email deals
https://t.myvisualiq.net/click_pixel?et=c&ago=212&ao=871&aca=23491753&si=5761632&ci=125308808&pi=261713913&ad=457205120&sv1=[keyword_id]&advt=9683780&chnl=-7&vndr=115&sz=7577&u=&viq_did=&red=https://deals.dell.com/en-ca?

For Shippn.com
https://jtlsfghs.r.us-west-2.awstrack.me/L0/https:%2F%2Fwww.shippn.com

The above works if nextdns is disabled

Thank you

**Comment by ignoramous** [comment]
If you're blocking affiliate links, why do you want to allow affiliate links?

Add the ones you want exempted to the `allowlist` section on appropriate configuration at `my.nextdns.io` You could also post at `help.nextdns.io` if you need more help.

**Comment by mtverlee** [comment]
I think @Singhson13 is saying that when they set "Allow Affiliate Links" to on, these sites should not be blocked. 

In any case, you should whitelist the domains that are being blocked. This cannot be solved with a PR on this repo as far as I'm aware.

**Comment by Singhson13** [comment]
@ignoramous and @mtverlee  thank you for your reply. I posted here after reading posts like issue#199. 

Adding these to allow list will solve the issue for me however its not limited to me 

Under privacy with default filter "NextDNS Ads & Trackers Blocklist" these affiliate and trackers are blocked which is wonderful. However when you enable "Allow Affiliate & Tracking Links" then these shouldn't be blocked. But I'm not sure who is maintaining the "Allow Affiliate & Tracking Links " list so they can add these to it.

Hopefully this clears my issue a little bit more

Thanks

**Comment by rs** [comment]
Added except jtlsfghs.r.us-west-2.awstrack.me which we couldn't validate is a pure affiliate link.

Thanks for your contrib

**Comment by Singhson13** [comment]
@rs thank you so much. Really appreciate your help
In future if I come across any more email Affiliate links is there a template I should follow on how to post it here or anyone I should tag, eg like you? Particular keywords I should use in the issue title to make it easier for the team?
I won't create a issue for one or two links until I find few. I respect your guys time and don't want to waste it with one off issue.

Once again thank you

**Comment by rs** [comment]
Just post the URLs like you did in a new ticket and we will review them. Thank you.
