### ISSUE TITLE
contents*.00110.citi.com blocked - breaks citi.com pages

### ISSUE THREAD

**Issue by timkgh** [nextdns/metadata#780]
I use only the AdGuardSDNSFilter in NextDNS. I reported the problem to AdGuard and they fixed it:
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/781

https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/c5e3898c59aeb39dc5f85a0a4666b528583ac850

The filter list seems to be refreshed by NextDNS, but NextDNS still blocks it:

NextDNS query:
```
> dig contents1.00110.citi.com

;; ANSWER SECTION:
contents1.00110.citi.com. 3580	IN	CNAME	log-edc5180c.us.v2.we-stats.com.
log-edc5180c.us.v2.we-stats.com. 280 IN	A	0.0.0.0
```

AdGuard DNS query:
```
> dig contents1.00110.citi.com @94.140.14.14

;; ANSWER SECTION:
contents1.00110.citi.com. 788	IN	CNAME	log-edc5180c.us.v2.we-stats.com.
log-edc5180c.us.v2.we-stats.com. 444 IN	A	13.89.105.232
```

Maybe you are not processing the AdGuardSDNSFilter `exceptions.txt` and `exclusions.txt` correctly?
https://github.com/AdguardTeam/AdGuardSDNSFilter/tree/master/Filters

**Comment by romaincointepas** [comment]
It's `log-edc5180c.us.v2.we-stats.com` that is blocked?
