### ISSUE TITLE
Typosquatting False Positive: github.co

### ISSUE THREAD

**Issue by ZackBoe** [nextdns/metadata#79]
`github.co` is a branded Bitly domain [used by GitHub](https://twitter.com/github/status/1233476467209785345) and is blocked under the typosquatting category. Didn't immediately see it in this repo to make a PR for, nor any reference to an external list used for typosquatting.

![firefox_2020-02-29_02-43-14](https://user-images.githubusercontent.com/904055/75603538-41e34480-5a9d-11ea-9248-b74636aab837.png)

**Comment by JoergBastian** [comment]
Is there a blocklist anywhere for typosquatting where PRs can be opened, or what is the data source for nextdns's typosquatting protection? I also encountered some false positives.

**Comment by romaincointepas** [comment]
Whitelisted, thanks.

@JoergBastian right now we are using https://raw.githubusercontent.com/hl2guide/DNS-Sinkhole-Lists-A2/master/typosquatting_blocklist.txt, we will make our own thing very soon though as this list has quite a few false positives.
