### ISSUE TITLE
[NextDNS] Parental control services issue

### ISSUE THREAD

**Issue by NetE1** [nextdns/metadata#80]
Regarding parental control services

- Telegram(especially), Disney+
   * We may need to avoid add sole privacy friendly services similar telegram, signal, matrix(riot) etc that people necessary to use (or learn to use) for daily communication.
   * Platforms similar Disney+ are not risky like youtube that stream any kind of videos and it seems not aimed for adult https://www.reddit.com/r/DisneyPlus/comments/cv66pn/adult_shows/
https://www.theverge.com/2020/2/5/21123232/disney-plus-mandalorian-tv-shows-marvel-wandavision-falcon-winter-soldier-netflix-earnings
(People want Disney+ to match Netflix’s output, but Disney doesn’t care Feb 5, 2020)

Usually parental control use for kids, teenagers (maybe for house or workplace members) so this feature must have a limit and perfect goal, something like practice kids or people to use good and right things; not just let options to restrict everything (due popular, waste time or someone's request) 
I also feel bit unhappy about block lot of games however that may leads to this facility useless, even parents have some expectation but nowdays most teenagers often pick such thing for spend their free or alone time. If offer built-in lockdown facility for so many type of services then children break that restriction and next they pick *social media, *adult sites or else; somehow not the game
Furthermore, these common services able to block using nextdns blacklist feature based on user requirement or it's possible to offer new feature for add custom services through web interface after sign up for an account.

- Yandex https://github.com/nextdns/metadata/pull/54

It's worth to consider twice about proper way to block google, yandex, microsoft tech giants. they have operating systems, app stores, web browsers, email clients and many other softwares that NextDNS have no way to prevent use. subscribers may have various reason to block them however device users or owners may still use vulnerable softwares without updates for years and they cant even reach company websites to see security advisories or any other critical issue notice.
There is a way for reduce attraction for any company by blocking their products download links, sign in, sign up subdomains, cloud services (also maybe home page exclude sub paths) and leave the rest accessible.
(In this cause, add explanation note about the reason for place limited restriction or advice account administrator to remove all softwares belong to certain company before block access but keep in mind that internet users still possible download them through third party sites.)

**Comment by romaincointepas** [comment]
Services are there for Parental Control, so it has nothing to do with privacy and everything to do with controlling access to certain services (like Disney+) for your kids or whomever you have authority over. It's up to whom has authority to decide what they want to block, not us.

For privacy invading services that you may want to block, this is/will be in Privacy -> Blocklists (we already have *No Google*).

Not sure I understand your point though, so please reopen if I didn't.
