### ISSUE TITLE
Add a Spanish block list like AdGuard Spanish/Portuguese

### ISSUE THREAD

**Issue by sdgrs546547Q** [nextdns/metadata#801]
There is no block list for Spanish content, so one is required. Some good recommendation would be those of AdGuard Spanish / Portuguese (https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_9_Spanish/filter.txt ) 

Thanks!

**Comment by romaincointepas** [comment]
Duplicate of https://github.com/nextdns/blocklists/issues/18
