### ISSUE TITLE
False positive s.click.aliexpress.com

### ISSUE THREAD

**Issue by nishaddesilva** [nextdns/metadata#804]
nextdns-recommended list is blocking the domain s.click.aliexpress.com. This domain is used for items listed on Aliexpress website.

**Comment by quantumpacket** [comment]
It's blocked by more than just the recommended list. It's blocked also by AdAway, anti-AD, Anudeep's Blacklist, CertyficateIT, Energized Xtreme Extension, AdAway Blocking Hosts File for Japan, Steven Black.

What functionality on AliExpress is it breaking? I can visit the website, browse items, add to cart, checkout, etc while this domain is being blocked.

**Comment by nishaddesilva** [comment]
On most third party websites/YouTube videos the links to items on Aliexpress start with this domain. So it won't load anything at all when the link is clicked.

**Comment by quantumpacket** [comment]
From what you are saying the link sounds like it's being used on advertisements for click tracking? In that case, I don't see this as a false positive. Add it to your allow list if you need such functionality.

**Comment by spirillen** [comment]
That is used for tracking...

`s.click.aliexpress.com   CNAME . ; Tracking`

Issue: https://mypdns.org/my-privacy-dns/matrix/-/issues/1401

**Comment by romaincointepas** [comment]
Included in our `Privacy -> Allow Affiliate & Tracking Links` feature
