### ISSUE TITLE
Add Blocklist - 1Hosts (Xtra) 

### ISSUE THREAD

**Issue by leonicholasthe3** [nextdns/metadata#807]
can it be taken into consideration to include this blocklist in the blocklist list?
https://o0.pages.dev/Xtra/domains.txt

**Comment by quantumpacket** [comment]
Upstream's description for that list is _"Xtra - Level 4: extremly aggressive & restrictive. Do not use unless you know what you're doing!"_, which may be why NextDNS has not added it.

**Comment by ReaLJohnBaker** [comment]
@quantumpacket 

Example of ad/bad URL's which i found are blocked by nothing else other than 1Hosts (Xtra)

https://blocklist-tools.developerdan.com/entries/search?q=bestgirls4fuck.com
https://blocklist-tools.developerdan.com/entries/search?q=today-trip.com
https://blocklist-tools.developerdan.com/entries/search?q=av-secure.me
https://blocklist-tools.developerdan.com/entries/search?q=findservice.xyz
https://blocklist-tools.developerdan.com/entries/search?q=ptypygrebu.com

And no doubt many more.. it might just be worth reconsidering.

**Comment by quantumpacket** [comment]
That may be the case, but NextDNS has a policy on not adding lists that may break sites. It likely will not be approved with such a strong warning from upstream. Anyway, this issue needs to be closed as it's a duplicate and all discussions should be on the original issue thread at #656.

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/5ed13aaca19a7f14b84c2c5cbc6ac6b9a580c3c3.
