### ISSUE TITLE
Add religious extremism, conspiracy theory, terrorism, pseudoscience, voodoo categories

### ISSUE THREAD

**Issue by Rexadev** [nextdns/metadata#808]

**Comment by Cybo1927** [comment]
I recommend checking out #423 as adding lists like this have been talked about before and would generally not be considered a good idea.

**Comment by Rexadev** [comment]
> I recommend checking out #423 as adding lists like this have been talked about before and would generally not be considered a good idea.

Blocklist will controversial but good for home, work, school.

**Comment by Cybo1927** [comment]
> Blocklist will be controversial but good for home, work, school.

It being controversial is what we're trying to avoid. It would be a bad business decision on NextDNS's end.

**Comment by Rexadev** [comment]
> > Blocklist will be controversial but good for home, work, school.
> 
> It being controversial is what we're trying to avoid. It would be a bad business decision on NextDNS's end.

Make a user contributed raking based on voting list that way there is no mod

**Comment by Cybo1927** [comment]
> Make a user contributed raking based on voting list that way there is no mod

It would be best to just have the issue dedicated to allowing people to import custom blacklists or something like that. https://github.com/nextdns/metadata/issues/423#issuecomment-720527354
