### ISSUE TITLE
Components modification request

### ISSUE THREAD

**Issue by ZExplore** [nextdns/metadata#81]
We request you to merge below items into a one as 'Adult Contents' or please use more polite identification
 
>**'Child Safety'**
(Block domains related inappropriate contents and material for children. It includes websites, apps and other internet services)

Security - Block Child Sexual Abuse Material (CSAM)
Categories - Porn
Categories - Dating
_(this doesn't make any sense by categorize them and those sites outcomes are more greater for adults as well although if someone has known site and required to use then easy to whitelist it)_

It's disgusting to see that accidentally because this services also use by many children around the world include ours so we thought to open an issue here. Kindly do not ignore the request.

**Comment by romaincointepas** [comment]
We may add a "shortcut" that automatically select everything that should be blocked for kids in the future, but right now it's not that complicated to go through all settings and turn on the ones that are needed.
