### ISSUE TITLE
NSA Blocklist

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#82]
https://github.com/nextdns/metadata/blob/master/privacy/blocklists/nsa-blocklist.json

this is dead, you can remove without any issue

**Comment by scafroglia93** [comment]
@romaincointepas romaincointepas

**Comment by crssi** [comment]
And any other of CF.

https://github.com/ghacksuserjs/ghacks-user.js/issues/323

Cheers

**Comment by scafroglia93** [comment]
+1 for remove

**Comment by scafroglia93** [comment]
The list contains the info released by Snowden which is now useless so I think it can be safely removed

**Comment by beerisgood** [comment]
As already said, all list from Chef-Koch can be delisted as they only stealed work and he doesn't have any knowledge about maintaining such by himself

**Comment by scafroglia93** [comment]
+1 for removing

**Comment by romaincointepas** [comment]
Lots of people seem to like it and use it, keeping it for now.

**Comment by scafroglia93** [comment]
ok
