### ISSUE TITLE
[threat intelligence] amnenstytech

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#821]
Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-amnenstytech.txt

the list contains all the aggregate indicators of amnestytech (1: 1)

**Comment by scafroglia93** [comment]
added now inside my blocklist ->
https://github.com/AmnestyTech/investigations/tree/master/2021-12-16_cytrox

**Comment by romaincointepas** [comment]
Noted. We won't be adding it permanently to TI feeds though, as those lists are usually built once and never get updated.

Also, @scafroglia93 could you please stop linking to sources inside your own repo? We only use original sources.
