### ISSUE TITLE
Suggested Blocklist: YouTube Ads

### ISSUE THREAD

**Issue by the-solipsist** [nextdns/metadata#824]
Hi, this project seeks to have an updated DNS blocklist of YouTube ad servers:
https://github.com/Ewpratten/youtube_ad_blocklist/

It might be useful to add that as a NextDNS blocklist.

**Comment by the-solipsist** [comment]
Actually, this seems far more comprehensive:
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt

That's requested already in https://github.com/nextdns/metadata/issues/790, as part of GoodbyeAds Extensions.

**Comment by romaincointepas** [comment]
Youtube ads can't be blocked this way, see https://help.nextdns.io/t/g9hmvcq/why-cant-youtube-ads-be-blocked.
