### ISSUE TITLE
[Blocklist Request] Mixed Content Blocklist like AdGuard has.

### ISSUE THREAD

**Issue by Rexadev** [nextdns/metadata#832]
Sites like reddit, twitter, Facebook, tiktok

**Comment by rs** [comment]
Doesn't work at DNS level.

**Comment by Rexadev** [comment]
> Doesn't work at DNS level.

No I am saying to block sites that are not adult but have adult content and not have a safe version.
Those can be blocked for making it child safe like reddit twitter....
