### ISSUE TITLE
[Feature Request]Option to block IPs for a location or Malicious IPs. 

### ISSUE THREAD

**Issue by Rexadev** [nextdns/metadata#838]
Ex- If website registered is .com but server is in China.
It will create problems with CDN but blocking countries like Afghanistan will be good for security.
If domain using a IP is malicious then block all domains using that IP

**Comment by beerisgood** [comment]
Not possible with DNS.

**Comment by Rexadev** [comment]
> Not possible with DNS.

ControlD does this

**Comment by ignoramous** [comment]
> Not possible with DNS.

It is but just like CNAME uncloaking, this would require post-processing on the server to block IPs geo-located in China. That said, geo-locating is itself a hairy beast with IPs recycled all the time among various servers that may run anywhere in the world.

**Comment by Rexadev** [comment]
> > Not possible with DNS.
> 
> It is but just like CNAME uncloaking, this would require post-processing on the server to block IPs geo-located in China. That said, geo-locating is itself a hairy beast with IPs recycled all the time among various servers that may run anywhere in the world.

What about malicious IPs

**Comment by ignoramous** [comment]
> What about malicious IPs

Same thing. DNS can block those requests if the malware/spyware/ransomware/adware makes a DNS request first to contact that particular IP. If not, you're better off with using a network-wide / os-wide firewalls.

**Comment by Rexadev** [comment]
> > What about malicious IPs
> 
> Same thing. DNS can block those requests if the malware/spyware/ransomware/adware makes a DNS request first to contact that particular IP. If not, you're better off with using network-wide / os-wide firewalls.

Guide for Windows, MacOS, Linux, Android IP Blocklist Software that automatically updates?

**Comment by ignoramous** [comment]
> Guide for Windows, MacOS, Linux, Android IP Blocklist Software that automatically updates?

This isn't the right place, but search for
macOS: LittleSnitch, LuLu Firewall
Linux: OpenSnitch
Windows: Glasswire
Android: AfWall+ (root)

**Comment by romaincointepas** [comment]
Non-residential geo-ip DBs are not that accurate, there would be too many false positives. It's also not that hard to get a US IP nowadays with any self-serve VPS provider.
