### ISSUE TITLE
Gmail blocked by NextDNS-Recommanded blocklist

### ISSUE THREAD

**Issue by fma16** [nextdns/metadata#84]
Hi,

During the last update of your NextDNS Recommended Ads & Trackers Blocklist, the domain mail.google.com was blocked, making Gmail unavailable.

Could you remove this domain from the list?

Thanks in advance
![image](https://user-images.githubusercontent.com/1146233/76335713-3a216c80-62f5-11ea-94a7-8bf2ecfb9a27.png)

**Comment by joeferraro** [comment]
reddit.com, www.reddit.com, and twitter.com were also blocked. Is this by design?

**Comment by M0UL** [comment]
probably one of the list they use got it included for some reason. i think it is the adguard filters

**Comment by FernandoMiguel** [comment]
![image](https://user-images.githubusercontent.com/168366/76336897-8fa64b00-62ee-11ea-8c3d-6ba860e0f97b.png)
can't see it blocked on mine

![image](https://user-images.githubusercontent.com/168366/76336939-9fbe2a80-62ee-11ea-8e47-a6b9c5d26fb5.png)
list update was less than 10 min

**Comment by scafroglia93** [comment]
Updated a few second ago

**Comment by fma16** [comment]
Can confirm it is indeed working.

Thanks for the quick resolution.

**Comment by rs** [comment]
For the context: https://www.reddit.com/r/nextdns/comments/fgh21w/blocklist_bug/

**Comment by joeferraro** [comment]
Thanks for the transparency and quick action
