### ISSUE TITLE
parentalcontrol/safesearch-not-supported doesn't makes sense.

### ISSUE THREAD

**Issue by Rexadev** [nextdns/metadata#842]
Only google is somewhat adult-free in safemode and even it on 2 page have weird domains.
For example duckduckgo.com even on safemode to highest shows porn as top result even when searching for normal stuff.
Only alternative is Qwant but it is not available everywhere

So using "parentalcontrol/safesearch-not-supported" is like only allow google. That's good for home but in school/office environment it is a controversial business practice

Better add all search engine and leave it on user to only allow certain.

**Comment by spirillen** [comment]
You can ie take this SafeSearch lists and include.... I know they are incomplete but the privacy search engine [duckduckgo.com](https://mypdns.org/my-privacy-dns/matrix/-/blob/master/safesearch/safesearch.hosts#L9-11) is represented in safe mode

https://mypdns.org/my-privacy-dns/matrix/-/tree/master/safesearch
