### ISSUE TITLE
simplyhired.com [false alarm]

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#846]
![image](https://user-images.githubusercontent.com/19517680/144770458-01e2a544-d3ef-4dcf-b58d-206eab5aab15.png)

its regular site  for remote job

![image](https://user-images.githubusercontent.com/19517680/144770483-5319e2de-99ed-4700-95e2-243f15824c12.png)

**Comment by fdhfgbsjedfg-775** [comment]
This type of issue is supposed to be submitted to the upstream blocklist, so far, only anti ad is blocking it, you should submit this issue to anti ad.
