### ISSUE TITLE
Add GoodbyeAds YouTube Adblock

### ISSUE THREAD

**Issue by GEYSERBUG** [nextdns/metadata#847]
Hi, would it be possible to consider adding the GoodbyeAds YouTube Adblock list in the future https://github.com/jerryn70/GoodbyeAds

I've got a Smart TV i'd like to block youtube ads on if possible.

It's the only thing i'm struggling to block at present without any applicable lists.

**Comment by beerisgood** [comment]
YouTube ads cannot be blocked with DNS.

**Comment by GEYSERBUG** [comment]
But here are a Lot of YouTube ad links,
