### ISSUE TITLE
commonly white listed domains for Pi-Hole

### ISSUE THREAD

**Issue by virtualspin** [nextdns/metadata#849]
commonly white listed domains for Pi-Hole

https://github.com/anudeepND/whitelist
https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/referral-sites.txt
https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/optional-list.txt

Can you the domain white list

**Comment by romaincointepas** [comment]
We do not offer this feature. You could suggest those to be excluded from your favorite blocklist.
