### ISSUE TITLE
Please add the domain to the blocklist

### ISSUE THREAD

**Issue by Olizja** [nextdns/metadata#853]
This - huq.io

https://blog.appcensus.io/2021/10/25/what-the-huq/
https://www.vice.com/en/article/5dgmqz/huq-location-data-opt-out-no-consent
https://www.bbc.com/news/technology-59346063

**Comment by crssi** [comment]
Do you have some real site/service as a sample where huq.io is used?

Asking just because that the whole household and family all around here, computers and mobiles are covered and for the last two years there is no single entry of making DNS request for `huq.io` in the logs.

**Comment by Olizja** [comment]
> Do you have some real site/service as a sample where huq.io is used?
> 
> Asking just because that the whole household and family all around here, computers and mobiles are covered and for the last two years there is no single entry of making DNS request for `huq.io` in the logs.

UDP: https://github.com/AdAway/adaway.github.io/issues/297#issuecomment-993722867

**Comment by crssi** [comment]
The `huq.io` is listed in both only lists that I would recommend to use (see my profile), that it `OISD` and `1Hosts Lite` or `1Hosts Pro`.

Cheers
