### ISSUE TITLE
YouTube Blocklist

### ISSUE THREAD

**Issue by GrandWasTaken** [nextdns/metadata#856]
### YouTube Blocklist to Block YouTube Ads. 

https://github.com/Ewpratten/youtube_ad_blocklist

By, @Ewpratten
Hopefully this blocklist can be added soon.

**Comment by rs** [comment]
Those lists won’t work. You can’t block youtube ads this way.

**Comment by Ewpratten** [comment]
As the maintainer of this list, I agree @rs 😆

Somehow, a few hundred people actively use it and seem to get some use out of it, so the project continues
