### ISSUE TITLE
Request to block domains

### ISSUE THREAD

**Issue by jinksy31337** [nextdns/metadata#860]
These domains all link to a google chrome extension that hijacks the browser:

download.fromdoctopdf[.]com
hp.myway[.]com
www.fromdoctopdf[.]com
www.pdfconverterhq[.]com
www.actionclassicgames[.]com
www.radiorage[.]com
www.instantradioplay[.]com
www.gifsgalore[.]com
www.mytransitguide[.]com
www.pdfconverttools[.]com
free.mysocialshortcut[.]com
www.mysocialshortcut[.]com
download.webmailworld[.]com
free.mymapsexpress[.]com
download.myfileconvert[.]com
free.dailyrecipeguide[.]com
free.videodownloadconverter[.]com
free.flightsearchapp[.]com
download.televisionfanatic[.]com
free.mytransitguide[.]com
download.propdfconverter[.]com
mywaynotes.dl.myway[.]com
download.calendarspark[.]com
www.mapsgalaxy[.]com
propdfconverter.dl.myway[.]com
www.utilitychest[.]com
download.smsfrombrowser[.]com
www.totalrecipesearch[.]com
download.mysocialshortcut[.]com
download.testonlinespeed[.]com
download.easypackagetracker[.]com
www.productmanualsguide[.]com
download.instantradioplay[.]com
download.howtosuite[.]com
download.mapsgalaxy[.]com
download.formfinderfree[.]com
www.propdfconverter[.]com
www.freetemplatefinder[.]com
www.packagetracer[.]com
free.propdfconverter[.]com
www.freedirectionsonline[.]com
free.internetspeedtracker[.]com
free.atozmanuals[.]com
download.allinonedocs[.]com
formfinderfree.dl.myway[.]com
download.filesendsuite[.]com
free.yourtemplatefinder[.]com
download.easydocmerge[.]com
download.myradioaccess[.]com
download.howtosimplified[.]com
www.howtosimplified[.]com
download.easypdfcombine[.]com
download.getformsonline[.]com
www.liveradiosweeper[.]com
www.weatherblink[.]com
download.mytransitguide[.]com
www.howtosuite[.]com
download.findyourmaps[.]com
www.100sofrecipes[.]com
www.convertpdfsnow[.]com
www.onlineworksuite[.]com
www.audiotoaudio[.]com
fromdoctopdf.dl.myway[.]com
www.everydaymanuals[.]com
www.televisionfanatic[.]com
www.onlineformfinder[.]com
free.onlinemapsearch[.]com
www.mergedocsonline[.]com
free.gifsgalore[.]com
download.atozmanuals[.]com
free.getformsonline[.]com
download.dailylocalguide[.]com
free.puzzlegamesdaily[.]com
atozmanuals.dl.myway[.]com
download.easyfileconvert[.]com
www.mapmywayfree[.]com
download.pdfconverttools[.]com
www.smsfrombrowser[.]com
download.freemanualsindex[.]com
www.recipekart[.]com
free.pdfconverterhq[.]com
download.weatherblink[.]com
download.marineaquariumfree[.]com
download.audiotoaudio[.]com
download.onlinemapfinder[.]com
download.freelocalweather[.]com
free.webmailworld[.]com
free.fromdoctopdf[.]com
free.everydaylookup[.]com
download.videodownloadconverter[.]com
www.pconverter[.]com
www.directionsbuilder[.]com
www.myformsfinder[.]com
download.myscrapnook[.]com
freetemplatefinder.dl.myway[.]com
www.fileconvertonline[.]com
download.productivityboss[.]com
formfetcherpro.dl.myway[.]comformfetcherpro.dl.myway[.]com
www.productivityboss[.]com
download.filesharefanatic[.]com
download.quicktemplatefinder[.]com
www.formfinderfree[.]com
www.mergedocsnow[.]com
www.easyemailsuite[.]com
free.easydocmerge[.]com
www.everydaylookup[.]com
www.freemanualsindex[.]com
free.findmefreebies[.]com
www.onlineroutefinder[.]com
free.mynewsguide[.]com
free.searchformsonline[.]com
free.mapsgalaxy[.]com
download.getformsfree[.]com
www.onlinemapfinder[.]com
download.downloadmanagernow[.]com
free.mydigitalcalendar[.]com
everydaylookup.dl.myway[.]com
free.easypdfcombine[.]com
download.onlineformfinder[.]com
www.newnotecenter[.]com
free.downloadinboxnow[.]com
download.totalrecipesearch[.]com
download.liveradiosweeper[.]com
www.headlinealley[.]com
free.onlineformfinder[.]com
free.internetspeedutility.net
www.webmailworld[.]com
free.myscrapnook[.]com
download.directionsace[.]com
fromdoctopdf.dl.tb.ask[.]com
www.easypackagetracker[.]com
www.quicktemplatefinder[.]com
www.videoconverterhd[.]com
download.headlinealley[.]com
free.packagetracer[.]com
www.filesharefanatic[.]com
myimageconverter.dl.myway[.]com
www.downloadmanagernow[.]com
www.getseniorresources[.]com
download.easyweatheralert[.]com
www.easyweatheralert[.]com
download.onlineworksuite[.]com
www.productmanualspro[.]com
download.bettercareersearch[.]com
free.ontargetyoga[.]com
free.pdfconverttools[.]com
free.trackapackage.net
www.mydiygenie[.]com
www.anytimeastrology[.]com
www.bettercareersearch[.]com
www.myeasylotto[.]com
free.convertersnow[.]com
free.howtosuite[.]com
free.downloadrecipesearch[.]com
free.productmanualsfinder[.]com
www.filesendsuite[.]com
download.biggamecountdown[.]com
download.filmfanatic[.]com
www.quickweathertracker[.]com
www.findyourmaps[.]com
www.filmfanatic[.]com
download.mywebface[.]com
download.fileconvertonline[.]com
download.puzzlegamesdaily[.]com
download.download-freemaps[.]com
free.mytransitplanner[.]com
www.searchformsonline[.]com
www.simplepackagefinder[.]com
download.pdfconverterhq[.]com
download.mergedocsnow[.]com
download.packagetracer[.]com
www.funpopulargames[.]com
download.gamingwonderland[.]com
download.searchformsonline[.]com
download.packagetracking.net
download.trackapackage.net
free.convertdocsonline[.]com
download.onlinemapsearch[.]com
download.smarteasymaps[.]com
www.onlinemapsearch[.]com
productivityboss.dl.myway[.]com
download.dailyproductivitytools[.]com
download.freeshoppingtool[.]com
www.myimageconverter[.]com
www.freeshoppingtool[.]com
free.myformsfinder[.]com
free.findyourmaps[.]com

**Comment by beerisgood** [comment]
Better ask filterlist dev(s).

**Comment by spirillen** [comment]
Hmm

`free.myformsfinder.com` Is only flagged by CRDF an nobody else https://www.virustotal.com/gui/url/e92ebfb2ab73b2d68439dffd4d7a9069e0f5d86d723e69c26ba520d4dbe87f4b?nocache=1

Where do you have these information's from @jinksy31337 ?

**Comment by jinksy31337** [comment]
@spirillen 

I used the "Google Chrome Cloud Platform Manager" to manage a large number of workstations for as part of my job, the platform is able to report on extensions that users have installed, I investigated a number of extensions that had been sideloaded/ not installed from the store and noticed that a lot of extensions had the above domain as part of their "permission" when opening the fqdn in a browser such as Firefox i was then prompted to download the nuisance extension.  I then ran the FQDN through urlscan.io to find other similar websites which is the list you see above, they are all managed by "myway[.]com" 

https://malwaretips.com/blogs/search-myway-com-removal/

"Search.myway.com is a search engine, similar to Google or Bing, however, in most cases, people are redirected to this site by a browser hijacker. This browser redirect happens because a malicious browser extension or program is installed on your computer."

**Comment by spirillen** [comment]
Would you be open minded for adding the active ones one by one to mypdns? (There is a API you can use)you just link to this topic.

```
https://mypdns.org/my-privacy-dns/matrix/-/issues/new?issuable_template=Malicious%20MalWare
```

```
## Relevant External sources
- `https://github.com/nextdns/metadata/issues/860`
```

**Comment by romaincointepas** [comment]
Noted, thanks. Feel free to also report those to any of the TI feeds vendors we use.
