### ISSUE TITLE
NextDNS blocks WeChat login page

### ISSUE THREAD

**Issue by maXity** [nextdns/metadata#868]
Hello,

I cannot open the WeChat login verification page while my iPhone is set to NextDNS.

The blocked domains appear to be minorshort.weixin.qq.com and shminorshort.weixin.qq.com (see below).

![image](https://user-images.githubusercontent.com/23332112/147408061-b1246862-3575-498d-a97c-9d7a989347c9.png)

I know how to whitelist them, but I would argue this should not be blocked in the first place.

**Comment by MikeyTadd** [comment]
NextDNS is not blocking these, one of the blocklists you have enabled has blocked those sites. NextDNS uses 3rd party blocklists for most of the blocks. Check what block list, can see It in the interface if you hover over the Red I and possibly disable that list. 

NextDNS with no blocklists does not block anything, and its not being blocked by the NextDNS starter list so can't do anything on this site from NextDNS.

**Comment by maXity** [comment]
Thank you for your response. Your assumption is incorrect though, unless something has changed since my original post - the only liste I have activated is the deafult 'recommended starter blocklist', and you see in my screenshot above that the domains in question are being blocked.

Like I said, I am well aware how to whitelist false positives myself, but surely a lot of other users aren't, so I'm posting here to avoid frustration and help make NextDNS a better product.

**Comment by MikeyTadd** [comment]
Might want to double check your configuration as I tested the domains on my machine and it doesn't block for me. I am using the NextDNS starter configuration as well as the oisd and a few of the AdGuard ones and it doesn't block. 

What does it say when checking the source as I said in the previous post? I'm not seeing the block when I try

**Comment by romaincointepas** [comment]
Fixed.
