### ISSUE TITLE
Request to add a new adblock list

### ISSUE THREAD

**Issue by TechComputerServiceDunkerque** [nextdns/metadata#872]
Popup Scam Filter: 

- 
https://raw.githubusercontent.com/infinitytec/blocklists/master/scams-and-phishing.txt

- https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt

Filter ublock hosts: 

- https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt

- https://raw.githubusercontent.com/ReddestDream/reddestdream.github.io/master/Projects/MinimalHosts/etc/MinimalHostsBlocker/minimalhosts

Filter host mobile: 

- https://hostsmobile.oisd.nl/

Blah DNS: 

- https://oooo.b-cdn.net/blahdns/blahdns_rpz.txt

DNS WARDEN: 

Domains
- https://raw.githubusercontent.com/dnswarden/blocklist/master/blacklist-formats/hostnames

Adblock

- https://raw.githubusercontent.com/dnswarden/blocklist/master/blacklist-formats/hosts

Fishing filter: 

- https://curben.gitlab.io/malware-filter/phishing-filter-dnscrypt-blocked-ips.txt

Other: 

- https://gitlab.com/curben/urlhaus-filter/raw/master/urlhaus-filter-hosts-online.txt

- http://sbc.io/hosts/hosts

Thank you

**Comment by krystian3w** [comment]
How many added in year?
