### ISSUE TITLE
koyu.space is blocked

### ISSUE THREAD

**Issue by koyuawsmbrtn** [nextdns/metadata#878]
My domain is getting blocked by default. It is a Mastodon instance like any other. Below is a screenshot of the false positive:

![grafik](https://user-images.githubusercontent.com/40538332/147840045-98d38273-c0e8-4bc2-b719-f8293b61e097.png)

**Comment by kotx** [comment]
Still an issue.

**Comment by austinhuang0131** [comment]
should be resolved now

for reference, the two affecting blacklists are maltrail and [Blacklists UT1](https://dsi.ut-capitole.fr/blacklists/)

**Comment by koyuawsmbrtn** [comment]
Looks good.
