### ISSUE TITLE
"dessaly.com" suspicious link in my log

### ISSUE THREAD

**Issue by Rexadev** [nextdns/metadata#883]
website is blank. 
https://www.whois.com/whois/dessaly.com
from google search looks like its a spyware

Possibly it is used by [play.google.com/store/apps/details?id=com.downlood.sav.whmedia](url). But it is a offline app.

**Comment by scafroglia93** [comment]
https://www.virustotal.com/gui/url/650294f6862e56db216272e8004cc52a26f6141c1cd980718470ade51abcae85/detection
