### ISSUE TITLE
Include the NSFW list of OISD in the porn category?

### ISSUE THREAD

**Issue by cbuijs** [nextdns/metadata#885]
... Or even in the "BlockLists" sections?

URL = https://dblw.oisd.nl/nsfw/

There is also an "Extra" list:

URL = https://dblw.oisd.nl/extra/

More info: https://oisd.nl/downloadsXtra

**Comment by mingaldrichgan** [comment]
+1 for the ability to select individual blocklists for porn including OISD's NSFW list.

**Comment by romaincointepas** [comment]
We have moved to using our internal Porn AI.

**Comment by travisboss** [comment]
> 

Could I ask.  What does that mean?  Is this just using something similar to your threat intelligence feed AI?
