### ISSUE TITLE
(whitelist) http://da.gd/

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#89]
source:
http://da.gd/9

Oh no, da.gd is blocked 😔
The website you are trying to access is being blocked by whoever is in charge of the network you are connected to.
da.gd is being blocked by threat-intelligence-feeds.

**Comment by romaincointepas** [comment]
Nice catch, whitelisted. Sometimes link shorteners domains get caught and appear on some security blocklists.
