### ISSUE TITLE
https://gitlab.com/CHEF-KOCH/cks-filterlist (GONE)

### ISSUE THREAD

**Issue by 3xploiton3** [nextdns/metadata#898]
![image](https://user-images.githubusercontent.com/19517680/149962950-33eca32a-ba8b-4422-a623-c5c91be685da.png)

**Comment by beerisgood** [comment]
See comments in https://github.com/nextdns/metadata/issues/340

**Comment by romaincointepas** [comment]
We will remove it soon as there is no available maintained source anymore.
