### ISSUE TITLE
Whitelist justt.me - it is NOT porn - thank you!

### ISSUE THREAD

**Issue by yann-justt-me** [nextdns/metadata#899]
![image](https://user-images.githubusercontent.com/71407303/150033549-d2ea7c63-5b95-49d4-9ff2-25273428dff7.png)

**Comment by lyrad87** [comment]
I've enabled the Porn category and the site was loading just fine. It was most likely fixed upstream.

**Comment by romaincointepas** [comment]
Should be fixed soon, we have moved to our internal Porn AI.
