### ISSUE TITLE
Suggested blacklist: Nordic countries

### ISSUE THREAD

**Issue by morten-b** [nextdns/metadata#90]
Would you please consider adding the following list for the Nordic counties: https://github.com/DandelionSprout/adfilt

Direct link: https://github.com/DandelionSprout/adfilt/blob/master/NorwegianList.txt

**Comment by scafroglia93** [comment]
You can find this list inside -> notracking
https://github.com/notracking/hosts-blocklists/blob/master/SOURCES.md

you can close it ;)

**Comment by morten-b** [comment]
Excellent. Thanks!
