### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by ietermago** [nextdns/metadata#900]
Both the _NextDNS Ads & Trackers Blocklist_ and the _Steven Black_ lists block downloads from Dropbox with an error "There was an error downloading your file.". Everything else, like deleting files, seems to work.

**Comment by Belphemur** [comment]
I've reported to Steven Black: https://github.com/StevenBlack/hosts/issues/1868#issuecomment-1016604639

Newest release of that blocklist doesn't contains `dl.dropboxusercontent.com` anymore.

NextDNS should pull again the blocklist.
