### ISSUE TITLE
Add threat Intelligence feeds

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#901]
Nextdns should utilize open source threat intelligence feeds from AlienVault OTX, IBM X-Force , CrowdSec, MISP-project, Anomali, ThreatConnect (Free Version),
Barracuda

**Comment by romaincointepas** [comment]
Free doesn't always mean that it can be used for commercial use. We are however discussing with popular vendors, the feeds just won't be seen/listed in this repo.

**Comment by SohanRay** [comment]
> Free doesn't always mean that it can be used for commercial use. We are however discussing with popular vendors, the feeds just won't be seen/listed in this repo.

Ok. Thanks.

**Comment by SohanRay** [comment]
> Free doesn't always mean that it can be used for commercial use. We are however discussing with popular vendors, the feeds just won't be seen/listed in this repo.

Have the feeds from popular vendors been added?
