### ISSUE TITLE
Dead/unavailable threat feeds

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#903]
https://managedsentinel.com/downloads

https://infosec.cert-pa.it/analyze

https://mirror.cedia.org.ec/malwaredomains

These lists aren't present/updated anymore or have 0 entries.

**Comment by romaincointepas** [comment]
Done in https://github.com/nextdns/metadata/commit/d7343f9b991b0feb6cdde3337cc168a8305473c6.
