### ISSUE TITLE
Add these Intelligence feeds

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#904]
https://cinsscore.com/list/ci-badguys.txt

https://www.blocklist.de/downloads/urls/95.211.0.112-only-domains.txt

https://reputation.alienvault.com/reputation.data

https://reputation.alienvault.com/reputation.generic

http://lists.blocklist.de/lists/all.txt

http://danger.rulez.sk/projects/bruteforceblocker/blist.php

https://sslbl.abuse.ch/blacklist/sslblacklist.csv

**Comment by romaincointepas** [comment]
Those are either IP lists or very old domain lists.

**Comment by SohanRay** [comment]
> Those are either IP lists or very old domain lists.

So, Nextdns doesn't block malicious IPs?

**Comment by beerisgood** [comment]
> So, Nextdns doesn't block malicious IPs?
>

NextDNS is a DNS resolver.

**Comment by SohanRay** [comment]
> > So, Nextdns doesn't block malicious IPs?
> 
> NextDNS is a DNS resolver.

Ok, but blocklist.de has been updated like 11hrs ago... So its not old and I have provided its domain list

**Comment by beerisgood** [comment]
> Ok, but blocklist.de has been updated like 11hrs ago... So its not old and I have provided its domain list
>

This list provide IPs only too. Nothing to do for a DNS resolver.
Read https://en.wikipedia.org/wiki/Domain_Name_System

**Comment by SohanRay** [comment]
> > Ok, but blocklist.de has been updated like 11hrs ago... So its not old and I have provided its domain list
> 
> This list provide IPs only too. Nothing to do for a DNS resolver. Read https://en.wikipedia.org/wiki/Domain_Name_System

Check this one - >https://www.blocklist.de/downloads/urls/95.211.0.112-only-domains.txt

**Comment by romaincointepas** [comment]
@SohanRay It was last modified in 2012.
