### ISSUE TITLE
#904 (Request)Add these feeds

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#905]
https://www.blocklist.de/downloads/urls/95.211.0.112-only-domains.txt

https://api.cybercure.ai/feed/get_url?type=csv

https://cybercrime-tracker.net/all.php

**Comment by romaincointepas** [comment]
> https://www.blocklist.de/downloads/urls/95.211.0.112-only-domains.txt

Last updated in 2012.

> https://api.cybercure.ai/feed/get_url?type=csv

Not really worth it, mostly the `myfrance.xyz` domain?

> https://cybercrime-tracker.net/all.php

Not vetted enough?
