### ISSUE TITLE
Adblock

### ISSUE THREAD

**Issue by TeaqariaWTF** [nextdns/metadata#909]
some websites detect ad blocking can you add this repository to bypass it

https://github.com/bogachenko/fuckfuckadblock

**Comment by quantumpacket** [comment]
@TeaqariaWTF that list is not meant for DNS. It will not work with NextDNS.

**Comment by beerisgood** [comment]
Also badness enumeration can always be detected. No matter which list you use trying to circumstances it.

**Comment by romaincointepas** [comment]
What @quantumpacket said.

**Comment by krystian3w** [comment]
Few can by banned as long allowed translate `$third-party` to "block everywhere":

```adb
||exdynsrv.com^$third-party,important
||exoclick.com^$third-party,important
||exosrv.com^$third-party,important
||o333o.com^$third-party,important
||popads.net^$third-party,important
||popcash.net^$third-party,important
||realsrv.com^$third-party,important
||wpnsrv.com^$third-party,important
||popunderstar.com^$important,third-party
||0i0i0i0.com^$important,third-party
||jads.co^$third-party,important
```
