### ISSUE TITLE
Domain blacklist: ads-bi.zenkube.com and a few others

### ISSUE THREAD

**Issue by CyanoTex** [nextdns/metadata#91]
Hello! 👋 

Could you add the following domains to the `NextDNS Recommended Ads & Trackers Blocklist`? Or are some of these already in the list?

`ads-bi.zenkube.com`
`services.insurads.com`
`cdn.insurads.com`
`msg-0209861dced41c7ef.insurads.com`
`messaging.insurads.com`
`adsaccount.appcpi.net`
`analytics.xl.pt`
`adservice.google.be`

**Comment by scafroglia93** [comment]
it's all blocked under -> dbl.oisd.nl

except -> ads-bi.zenkube.com

**Comment by CyanoTex** [comment]
I see. Well, I'll open an issue on the GitHub for that one.

**Comment by romaincointepas** [comment]
@CyanoTex Suggesting it to https://github.com/StevenBlack/hosts would be even better, as we use that list (among a few others) to build our recommended list.
