### ISSUE TITLE
f-log-*.grammarly.io

### ISSUE THREAD

**Issue by SeriousHoax** [nextdns/metadata#912]
The rule "f-log-*.grammarly.io" is present in Adguard DNS filter list and I'm using AdGuard DNS filter on NextDNS. But the domain "f-log-mobile.grammarly.io" which is accessed by Grammarly keyboard on Android is not being blocked by NextDNS. 
It should've been blocked. Is this a bug?
AdGuard DNS filter link: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

**Comment by romaincointepas** [comment]
We would need a specific non-wildcard list of domains, feel free to suggest this to any other popular blocklist that releases an hosts file.
