### ISSUE TITLE
False positive cloom.com

### ISSUE THREAD

**Issue by totalimmersion** [nextdns/metadata#913]
Could you please remove the cloom.com domain from the blocklist, because it is a false positive.
![cloom](https://user-images.githubusercontent.com/1247198/151762040-1406cddc-4135-423b-8b86-a361383b4492.jpg)

**Comment by lyrad87** [comment]
As far as I can tell, it's blocked by the `Threat Intelligence Feeds` and `oisd`. It would be helpful to share which blocklists you use. But as for `oisd`, you should report it [upstream](https://oisd.nl/reportfalsepositive).

**Comment by romaincointepas** [comment]
Seems fixed
