### ISSUE TITLE
False positive: vms.bluebillywig.com / omroepzeeland.bbvms.com 

### ISSUE THREAD

**Issue by SanderGit** [nextdns/metadata#914]
omroepzeeland.bbvms.com is a video player embedded in news articles on the site omroepzeeland.nl 

It is being blocked by the NextDNS Ads & Trackers blocklist because it is a CNAME for vms.bluebillywig.com - resulting in the video player being unavailable.

**Comment by lyrad87** [comment]
You should report it upstream as it's blocked by [Steven Black's blocklist](https://github.com/StevenBlack/hosts).

**Comment by romaincointepas** [comment]
What @lyrad87 said.
