### ISSUE TITLE
Video breakage due to wrong classification

### ISSUE THREAD

**Issue by crssi** [nextdns/metadata#92]
Open `https://siol.net/novice/slovenija/mocan-potres-stresel-zagreb-cutili-smo-ga-tudi-v-sloveniji-521448` and see video is not playing due to wrong classification of `p.jwpcdn.com` in `https://raw.githubusercontent.com/Clefspeare13/pornhosts/master/0.0.0.0/hosts` as category `porn`.

I have also report the issue at source list, see https://github.com/Clefspeare13/pornhosts/issues/85#issue-585683103

Next thing I do not understand... see picture:
![wrong category](https://user-images.githubusercontent.com/17024151/77247112-cbfa7500-6c25-11ea-9eec-4eb6ec65e38f.PNG)

On the picture you can see that the `jwpcdn.com` is blocked by the `porn` category, but if you check all thge source at `https://github.com/nextdns/metadata/blob/master/parentalcontrol/categories/porn.json` the `jwpcdn.com` is not to be found, but there is `p.jwpcdn.com`.

Shouldn't be `ssl.` in the gray color and the `p.jwpcdn.com` in black on the picture... and NOT as `ssl.p.` in gray and `jwpcdn.com` in black.

Cheers

**Comment by romaincointepas** [comment]
Fixed with https://github.com/nextdns/metadata/commit/ee7ba03ebd004b01622252449d517b9d3cbd1c00, thanks for the report!

And the slightly darker part of the domain is the root domain, not what was blocked.
