### ISSUE TITLE
Malicious urls passing through?

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#923]
Malicious urls from :
https://urlhaus.abuse.ch/downloads/text
present in threat intelligence feeds, seem to pass through the filtering of NextDns. The Urls seem to load on the browser whereas there should have been a like 'unable to reach' kinda message.

**Comment by SohanRay** [comment]
> This list doesn’t work with DNS.

Well if it doesn't and NextDns isn't blocking these , why is it mentioned in the threat intelligence feeds??

**Comment by quantumpacket** [comment]
NextDNS supports parsing some non-DNS lists, hence the _[format](https://github.com/nextdns/metadata/blob/d7343f9b991b0feb6cdde3337cc168a8305473c6/security/threat-intelligence-feeds.json#L129)_ value for each threat feed.

I've noticed that if you have HTTPS-only enabled in the browser it will ask to load the HTTPS version of the site and prompt to download the page if you proceed to HTTPS. If you have HTTPS-only off it will be blocked by NextDNS as intended.

As to why that is happening I have not investigated. :eyes:

**Comment by SohanRay** [comment]
> This list doesn’t work with DNS.

please refer to post #939
