### ISSUE TITLE
Adding GoodbyeAds YouTube Adblock List

### ISSUE THREAD

**Issue by arjunr** [nextdns/metadata#924]
Hello,

Please add support for GoodbyeAds YouTube Adblock List. This would allow Youtube ads to be blocked. The list can be found here: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt

**Comment by beerisgood** [comment]
Doesn’t work with DNS.

**Comment by SohanRay** [comment]
Youtube Ads can never be blocked by any DNS filtering. You'll need an ad-on for that. And for android and IOS you can use the vanced youtube clients.

**Comment by mouryaaman** [comment]
Vanced YouTube is dead, also it not available for IOS

**Comment by mouryaaman** [comment]
> Hello,
> 
> Please add support for GoodbyeAds YouTube Adblock List. This would allow Youtube ads to be blocked. The list can be found here: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt

Hi, I tired this list with dns and it not working with dns. We need to find another solution for this.

**Comment by beerisgood** [comment]
> 
> Hi, I tired this list with dns and it not working with dns. We need to find another solution for this.

The solution is easy and exist already for years:
YouTube Premium

**Comment by mouryaaman** [comment]
> > Hi, I tired this list with dns and it not working with dns. We need to find another solution for this.
> 
> The solution is easy and exist already for years: YouTube Premium

If we are ready to buy premium of each app, then no need of custom dns

**Comment by beerisgood** [comment]
> 
> If we are ready to buy premium of each app, then no need of custom dns

A lot of people doesn’t know this solution but it’s always the same. Pay with money or get ads and also pay with your data. 

So as you now read a lot of times, DNS doesn’t help.

**Comment by romaincointepas** [comment]
Youtube ads can't be blocked at the DNS level.

**Comment by krystian3w** [comment]
But this is like HOSTS syntax:
```adb
||r9sn-vgqsrn7d.googlevideo.com^
```

Possible simple translated into:

```
0.0.0.0 r9sn-vgqsrn7d.googlevideo.com
````
