### ISSUE TITLE
NextDns's reliability for protection against threats

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#926]
I wanted to know to answer to a particular argument. Which is:
Dns services like Quad9 uses sources which are leading cybersecurity companies which uses web crawlers like Google to find domains and use their scanning engines to detect the malicious ones. And if the domains are only suspected then they are tested by employees in the companies to determine if they are malicious in daily, real time basis. 

NextDns on the other hand, uses lists that are open source, and maintained by some individuals. I really doubt they have crawler systems or scanning engines in their arsenal to find and detect malicious domains on the Internet on a daily basis. I wonder how they keep up to date their list of latest malicious domains. All I have seen is that they try and combine other blocklists from different sources which in turn updates by finding malicious domains in who knows, what way.
So how does NextDns ensure protection to its users in a reliable manner?

**Comment by quantumpacket** [comment]
Have you asked to the upstream maintainers of those lists?

**Comment by SohanRay** [comment]
> Have you asked the upstream maintainers of those lists?

No, the sources use other sources and they probably in turn use others. It would be tedious to reach the root source. But since NextDns uses those sources specifically after research, I suppose they should have a proper idea. In the end the sources are probably dependent on user feedbacks I think.
