### ISSUE TITLE
Youtube Block List

### ISSUE THREAD

**Issue by jesse9212** [nextdns/metadata#927]
Please add this block list:

https://raw.githubusercontent.com/Ewpratten/youtube_ad_blocklist/master/blocklist.txt

**Comment by quantumpacket** [comment]
There are multiple [issues](https://github.com/nextdns/metadata/issues?q=youtube) already open/closed about YouTube blocking, some even with the exact same list you are suggesting. Please check before opening a duplicate issue.

https://help.nextdns.io/t/g9hmvcq/why-cant-youtube-ads-be-blocked

**Comment by jesse9212** [comment]
Accidently used the default search with is:open included, my b.
