### ISSUE TITLE
untangle.com domains - false positive

### ISSUE THREAD

**Issue by jondagle** [nextdns/metadata#929]
NextDNS Ads & Trackers Blocklist includes these domains of the networking hardware company Untangle.
- www5.untangle.com = used for company website
- get.untangle.com = used for product info downloads

They are also blocked in list "notracking" and will be reported there.

**Comment by romaincointepas** [comment]
Could you also report this to https://github.com/StevenBlack/hosts? Our blocklist feeds from it.
