### ISSUE TITLE
Add Kees1958 / W3C_annual_most_used_survey_blocklist

### ISSUE THREAD

**Issue by SeriousHoax** [nextdns/metadata#930]
Here it is: https://github.com/Kees1958/W3C_annual_most_used_survey_blocklist

List name: EU_US+most_used_ad_and_tracking_networks

**Comment by beerisgood** [comment]
Too much false positives. 

See also https://github.com/nextdns/metadata/issues/128 & https://github.com/nextdns/metadata/issues/382

**Comment by SeriousHoax** [comment]
> Too much false positives. 
> 
> See also https://github.com/nextdns/metadata/issues/128 & https://github.com/nextdns/metadata/issues/382

Are those points still valid?

**Comment by beerisgood** [comment]
This list is also built for browser extension and not useful for DNS.

**Comment by SeriousHoax** [comment]
> This list is also built for browser extension and not useful for DNS.

Oh, alright. Guess I should close the issue then.
