### ISSUE TITLE
New List -> Orange Cyber IOC Ukraine - Russia

### ISSUE THREAD

**Issue by scafroglia93** [nextdns/metadata#934]
Original ->
https://github.com/Orange-Cyberdefense/russia-ukraine_IOCs/blob/main/OCD-Datalake-russia-ukraine_IOCs-ALL.csv

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-orangecyber.txt

**Comment by romaincointepas** [comment]
We will check this out, thanks.
