### ISSUE TITLE
Have Threat intelligence feeds from popular vendors been added yet?

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#937]
referring to #901
@romaincointepas  have the feeds from private/premium popular vendors been added yet? I know it won't be visible in this repo but just wanted to know if they have been added ......

**Comment by SohanRay** [comment]
> Free doesn't always mean that it can be used for commercial use. We are however discussing with popular vendors, the feeds just won't be seen/listed in this repo.
> 
> _Originally posted by @romaincointepas in [#901 (comment)](https://github.com/nextdns/metadata/issues/901#issuecomment-1019384914)_

Have the feeds from popular vendors been added?

**Comment by PeterDaveHello** [comment]
As a paid user I'm also curious about this issue ;)

**Comment by romaincointepas** [comment]
We do use private feeds, and we may disclose some of them in the future.

**Comment by SohanRay** [comment]
Can it be disclosed that around how many such private threat intelligence feeds are used?
