### ISSUE TITLE
Change/update-> Threat Intelligence Feed from Abuse Ch

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#939]
Change
 https://urlhaus.abuse.ch/downloads/text

To
https://urlhaus.abuse.ch/downloads/hostfile/

Should be more compatible with DNS.

**Comment by scafroglia93** [comment]
@romaincointepas

**Comment by romaincointepas** [comment]
We support parsing URLs feed, we would rather do the whitelisting ourselves (`bit.ly` and the likes).
