### ISSUE TITLE
Important Internal system feature request

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#940]
I am not aware if this system feature is already present, but if not I sincerely think it should be added.

**Feature function:** It should run a daily check on the comlete list of Threat Intelligence feed sources, to determine which of them 
                            have ceased to exist or isn't being updated anymore. Then it should give an immediate heads up or 
                            notification about the ceased/deprecated ones to the NextDns team so that they could take action as soon as 
                            possible. 

I believe this would be a handy and important internal system feature that would keep the firewall up to date. Last time , when I had found such dead/deprecated Threat Intelligence feeds, they had been that way for quite some time, until the day when I reported here in Github and they were fixed on the same day in this commit->https://github.com/nextdns/metadata/commit/d7343f9b991b0feb6cdde3337cc168a8305473c6
Having the above internal feature should avoid all such delays and also NextDns team won't have to rely on human intervention for reporting/discovering any such deprecated threat intelligence feeds.

**Comment by 0ABDL0** [comment]
I also think that this could be useful since there would be no need for human interaction to find depreciated filters. Should help with automation and generally make it easier.
