### ISSUE TITLE
Please add 1hosts new adblock list https://github.com/badmojr/1Hosts#1hosts-xtra

### ISSUE THREAD

**Issue by dalda123** [nextdns/metadata#942]
There is a new Adblock filter list [1Hosts (Xtra)](https://github.com/badmojr/1Hosts#1hosts-xtra) released by [badmojr](https://github.com/badmojr). So please add this new block list.

**Comment by SohanRay** [comment]
1hosts pro itself has noticeable false positives usually. Extra would have even more. The dev himself suggests users to use the lite version.

**Comment by dalda123** [comment]
False positive is okay if it blocks fully. At least give this Blocklist as an optional. I have tried many blocklists for the last 5 years but not a single list (except 1hosts) can block Microsoft tracking properly. For example 1hosts pro blocks "fp.msedge.net" which is used to send data about almost every click in Windows OS.
So please I am requesting to give 1hosts extra as an optional blocklist (or provide a warning of false positives in the description)

**Comment by dalda123** [comment]
> 1hosts pro itself has noticeable false positives usually. Extra would have even more. The dev himself suggests users to use the lite version.

![Screenshot_2022-03-06-21-11-25-915_idm internet download manager plus](https://user-images.githubusercontent.com/37587853/156930510-bb301e56-7789-41fe-af20-426234236815.png)
This is an example how 1hosts pro blocks more tracking than energized ultimate which has 100k more domains.

**Comment by beerisgood** [comment]
> False positive is okay
>
No. They should be avoided at all costs.

> I have tried many blocklists for the last 5 years but not a single list (except 1hosts) can block Microsoft tracking properly. For example 1hosts pro blocks "fp.msedge.net" which is used to send data about almost every click in Windows OS.
>
Stop posting misinformation. It don't exist such a thing.
This domain is used for:
> The following endpoints are related to Cortana and Live Tiles. If you turn off traffic for this endpoint, you will block updates to Cortana greetings, tips, and Live Tiles.
https://docs.microsoft.com/en-us/windows/privacy/manage-windows-1903-endpoints

You should research before posting such nonsense. Telemetry can also be configured in Windows.

**Comment by badmojr** [comment]
+1

**Comment by badmojr** [comment]
> There is a new Adblock filter list [1Hosts (Xtra)](https://github.com/badmojr/1Hosts#1hosts-xtra) released by [badmojr](https://github.com/badmojr). So please add this new block list.

+1

**Comment by romaincointepas** [comment]
Added in https://github.com/nextdns/metadata/commit/5ed13aaca19a7f14b84c2c5cbc6ac6b9a580c3c3.
