### ISSUE TITLE
Support for Yggdrasil, Namecoin, Emercoin and OpenNIC TLDs

### ISSUE THREAD

**Issue by ammnt** [nextdns/metadata#95]
Hello, Dear Team!

I just want to say thank you for a great job! And suggest adding support for the following unofficial TLDs:
1. Yggdrasil: https://yggdrasil-network.github.io
2. Namecoin: https://www.namecoin.org/dot-bit/
3. Emercoin: https://emercoin.com/en/documentation/blockchain-services/emerdns/emerdns-introduction
4. OpenNIC: https://wiki.opennic.org/start

It may make sense to also offer support for the Tor network, but I 'm not sure about that... Something like this:
https://blog.cloudflare.com/welcome-hidden-resolver/

Cheers!

**Comment by romaincointepas** [comment]
Those unofficial TLDs, as far as we know, lost in popularity or never took off and we're having a hard time finding enough cool sites using those. Closing, feel free to open a discussion on our subreddit /r/nextdns, more fitted for feature suggestions.
