### ISSUE TITLE
[Blocklist Requests] YouTube ADs 

### ISSUE THREAD

**Issue by spinfal** [nextdns/metadata#953]
I've found a few blocklists that block all, if not most, YouTube video ADs. Blocklists can be found below:

1. https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-YouTube-AdBlock-Filter.txt
2. https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
3. https://raw.githubusercontent.com/Ewpratten/youtube_ad_blocklist/master/blocklist.txt

Adding one or all of these would allow users to block YouTube ADs, which would be very useful for devices that do not support extensions or things of the such; such as PSX, Xbox, Nintendo Switches, etc.

I have created a pull request to add the 2nd link: https://github.com/nextdns/metadata/pull/954

**Comment by quantumpacket** [comment]
There are multiple [issues](https://github.com/nextdns/metadata/issues?q=youtube+sort%3Aupdated-desc) already open/closed about YouTube blocking. Please check before opening a PR.

[help.nextdns.io/t/g9hmvcq/why-cant-youtube-ads-be-blocked](https://help.nextdns.io/t/g9hmvcq/why-cant-youtube-ads-be-blocked)

**Comment by mouryaaman** [comment]
Hi, I suggest switch to Adguard dns, beta version support custom list user has ability to add there own list, also they are not rude like nextdns guys
