### ISSUE TITLE
Add security feature

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#958]
Add a security feature which when enabled will block all kinds of illegal content.

**Comment by quantumpacket** [comment]
That would be impossible to implement. Each country, state, province, city, etc. has different laws. What is legal in one can be illegal in another and vice versa. These laws are also frequently amended, repealed, etc. You can't expect any service to be able to keep track of all of this.

**Comment by SohanRay** [comment]
> That would be impossible to implement. Each country, state, province, city, etc. has different laws. What is legal in one can be illegal in another and vice versa. These laws are also frequently amended, repealed, etc. You can't expect any service to be able to keep track of all of this, let alone determine which laws apply to what users and when. Also, this is less of a "_security_" feature and more of a parental feature.

illegal drugs, dark web, illegal distribution of weapons etc, abuse of any entity should be illegal in all countries .

**Comment by romaincointepas** [comment]
What @quantumpacket said (but we may add more Parental Control categories in the future).
