### ISSUE TITLE
Update/replace Threat Intelligence feeds not updated since very long

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#959]
https://malc0de.com/bl/ZONES
--hasn't been updated since december 2019

https://rescure.me/rescure_domain_blacklist.txt
--hasn't been updated since 2 months eventhough it says feed update frequency is 24 Hrs.

https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
--last updated a month ago

https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
--last updated 4 months ago

https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts
--last updated 11 months ago

https://raw.githubusercontent.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites/master/hosts
--last updated 4 months ago

https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/malware/domains
--Last updated more than a month ago

https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/phishing/domains
--Last updated more than a month ago

https://raw.githubusercontent.com/cbuijs/shallalist/master/spyware/domains.original
--last updated 2 months ago

https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-10-07_donot/domains.txt
--last updated 6 months ago

https://raw.githubusercontent.com/AmnestyTech/investigations/master/2021-12-16_cytrox/domains.txt
--last updated 3 months ago

https://raw.githubusercontent.com/guardicore/labs_campaigns/master/Autodiscover/autodiscover-tlds.txt
--last updated 6 months ago

https://raw.githubusercontent.com/MetaMask/eth-phishing-detect/master/src/hosts.txt
--last updated 2 months ago

https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
--last updated 8 months ago

parked domains
--last updated 2 years ago

typosquatting
--last updated 2 months ago

**Comment by Sduibek** [comment]
NextDNS has unfortunately gone out of their way to support old/outdated/dangerous data without good reasons why. 

For example the multiple block lists in the Privacy tab that are 2+ years old, that really no one should use any more, that people keep asking to get removed - and NextDNS flat out refuses. 

They just don't care.

**Comment by SohanRay** [comment]
> NextDNS has unfortunately gone out of their way to support old/outdated/dangerous data without good reasons why.
> 
> For example the multiple block lists in the Privacy tab that are 2+ years old, that really no one should use any more, that people keep asking to get removed - and NextDNS flat out refuses.

Nextdns core service is to provide security, and good quality threat intelligence feeds that updates in time and has most percentage of malicious domains in its list , is of the most importance. And that is where Nextdns fails to deliver. I have long switched to ControlD for this reason. They use premium paid threat intelligence feeds , alongside open source ones and keep updating their sources to ensure the quality. Also, their plans cost the same or more when you wanna use their proxy features.

**Comment by Sduibek** [comment]
Thanks, I'll check that out! 

I like a lot of things about NextDNS, and i do think it's a very good service overall, but their aggressively flippant reaction to valid community concerns have prevented me from ever being a truly longterm user. It's just not possible to trust a company that treats its customers that way.
