### ISSUE TITLE
Security : Add Virustotal API

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#960]
Like Google safe browsing API, Virustotal API should also be added for security.

**Comment by Te-k** [comment]
afaik there is no way to query virustotal with a large number of domains in a way that can be integrated in a platform like nextdns

**Comment by quantumpacket** [comment]
I agree with @Te-k. Without the ability to download and cache all domains that VirusTotal has marked as unsafe it would require the API to be requested every time a DNS query is made. This would not only slow down the round-trip time for the client's DNS query, but it also adds a point of failure in the event there are issues with the VirusTotal API service

This is something best implemented at the browser level, which VirusTotal already happens to offer here: https://support.virustotal.com/hc/en-us/articles/115002700745-Browser-Extensions
