### ISSUE TITLE
Add these domains to typosquatting protection

### ISSUE THREAD

**Issue by SohanRay** [nextdns/metadata#966]
https://www.hdfcbank.com/

https://netbanking.hdfcbank.com/

https://www.onlinesbi.com/

https://sbi.co.in/

https://licindia.in/

https://www.lichousing.com/

https://www.bankofindia.co.in/

https://starconnectcbs.bankofindia.com/

https://www.unionbankofindia.co.in

https://www.bankofbaroda.in/

https://www.bankofbarodauk.com/

https://www.axisbank.com/

https://retail.axisbank.co.in/

https://bandhanbank.com/

https://www.idbibank.in/

https://inet.idbibank.co.in/

https://www.indusind.com/

https://www.kotak.com/

https://netbanking.kotak.com/

https://www.yesbank.in/

https://drive.google.com/

**Comment by romaincointepas** [comment]
We will check this out.
