### ISSUE TITLE
Add Energized Unified

### ISSUE THREAD

**Issue by Blobbie01** [nextdns/metadata#968]
Hello.

NextDNS supports a lot of Energized block lists, however the Energized Unified isn’t supported yet.

Could you add this block list to NextDNS?

Thanks in advance :)

**Comment by quantumpacket** [comment]
@Blobbie01 please check existing open/closed issues before opening a new one.

See https://github.com/nextdns/metadata/issues/688#issuecomment-859513187 in regards to Energized Unified.

**Comment by romaincointepas** [comment]
We only add privacy-focused blocklists, we have separate features for Parental Control.
