### ISSUE TITLE
Suggested Blocklist OTA Block list IOS 

### ISSUE THREAD

**Issue by sbpir92i** [nextdns/metadata#97]
ocsp.apple.com
world-gen.g.aaplimg.com
mesu.apple.com
gdmf.apple.com

Source here 
https://www.reddit.com/r/jailbreak/comments/f0k16i/tutorial_block_ios_update_for_unjailbroken_device/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

**Comment by scafroglia93** [comment]
-1 

You can apply yourself with blacklist features

**Comment by agottardo** [comment]
Additionally, blacklisting `ocsp.apple.com` is a very bad idea and will break all sorts of things, not just software updates. It's used for certificate validation for all certificates issued by Apple.

**Comment by romaincointepas** [comment]
Agreeing with @scafroglia93 and @agottardo here, those few highly opinionated blocks can be managed with the Blacklist feature.
