### ISSUE TITLE
Custom blocklist support: antispam-it

### ISSUE THREAD

**Issue by marco-acorte** [nextdns/metadata#970]
it could be possible to include this one?

https://github.com/marco-acorte/antispam-it

This list manually verified, and is updated regularly. Strictly blocks advertisements networks, malwares, spams, statistics & trackers included in phishing/malware/spam campaign harassing poor italian (domain.it) mailboxes.

raw: https://raw.githubusercontent.com/marco-acorte/antispam-it/main/antispam-it.txt

**Comment by romaincointepas** [comment]
This would fit our Threat Intelligence Feeds feature, we will check this out.
