### ISSUE TITLE
[Please Verify] False Positive(?)

### ISSUE THREAD

**Issue by TheRayJohnson** [nextdns/metadata#972]
Hi,

Any ideas why [Pick My Postcode](https://pickmypostcode.com) (formerly known as Free Postcode Lottery) is blocked? Using the `NextDNS Ads & Trackers Blocklist` blocklist breaks the website (from loading). Should I add this domain to the `Allowlist`?

Site works fine with it removed.

Thanks.

**Comment by beerisgood** [comment]
The default list have a lot of false positives. 
Try OISD only.

**Comment by TheRayJohnson** [comment]
> The default list have a lot of false positives. Try OISD only.

Thanks for the suggestion! I will try that.

**Comment by crssi** [comment]
If you want more beside OISD then add 1Hosts Lite. So OISD + 1Hosts Lite.
Or even more with combo OISD + 1Hosts Pro... this one will bring rare breakage, but 1Hosts maintainer is very prompt to resolve the issue, if you report. And so is OISD maintainer.
Kudos to both.

**Comment by lyrad87** [comment]
The site is not blocked for me and I use the mentioned blocklist. May have been fixed upstream.

**Comment by TheRayJohnson** [comment]
> The site is not blocked for me and I use the mentioned blocklist. May have been fixed upstream.

Thanks for the response. The only way I can get the site to render/load was to add `*.gdpr-wrapper.privacymanager.io` into the AllowList tab of the NextDNS dashboard.

Soon as I disable that the site doesn't load (logged in) fine logged out (visitors).

**Comment by romaincointepas** [comment]
Should be fixed.

**Comment by TheRayJohnson** [comment]
> Should be fixed.

Working now, but because I use Goodbye Ads it's now that filter breaking the website. I'll post on [jerryn70's page](https://github.com/jerryn70/GoodbyeAds/issues).
