### ISSUE TITLE
Alternative to Blocklists?

### ISSUE THREAD

**Issue by PatrickHeneise** [nextdns/metadata#974]
I'm working on a list to block only cookie consent scripts. This small list largely reduces the amount of annoying cookie popups/banners:

https://github.com/PatrickHeneise/cookie-consent-blocklist

**update**

Different countries / languages / professions / people want/need different deny/allow lists. As there are a lot of "add this / remove that" tickets, I wonder if there could be a better way of managing hosts in NextDNS. Adding/removing individual hosts in the UI is not user friendly, time consuming and unmaintainable.

**Comment by beerisgood** [comment]
nonsense which ends in worse privacy.

**Comment by quantumpacket** [comment]
@PatrickHeneise  Why is `s.yimg.com` on there? That's part of Yahoo's CDN, which would break a lot of sites.

**Comment by crssi** [comment]
Most of cookie consent mechanics cannot be safely remediated with DNS blocking.
For that you need browser extension... and even then there will be breakages.

**Comment by PatrickHeneise** [comment]
> Most of cookie consent mechanics cannot be safely remediated with DNS blocking.
> For that you need browser extension... and even then there will be breakages.

Correct. But the ones that can be blocked are on the list (or will be added). With a few blocked domains I see _a lot_ less popups.

As for privacy, I don't really see a difference between ignoring / blindly approving them or not showing the popup at all? Especially if all trackers/cookies are blocked anyway.

**Comment by beerisgood** [comment]
> 
> Correct. But the ones that can be blocked are on the list (or will be added). With a few blocked domains I see _a lot_ less popups.
> 
> As for privacy, I don't really see a difference between ignoring / blindly approving them or not showing the popup at all? Especially if all trackers/cookies are blocked anyway.

You don’t know what you’re talking about and that’s the problem with your and other similar  lists.
You break whole Cookie management and even site functionality.
On cookie sites you get worse privacy than without using your list as you block OptOut options and some sites still use OptOut instead of OptIn. Even without that fact you break user preferred site behaviour. 
I highly recommend stopping your project and start researching first instead of providing false sense of privacy to other people.

**Comment by PatrickHeneise** [comment]
As you correctly point out, it's "user preferred site behavior". I have these hosts blocked for a while now and enjoy my browsing experience without consent screens and cookies. If you enjoy searching for "save my preference" buttons, that's up to you. I'm not claiming that this is a privacy enhancing block list.

If there's no intention to add new lists / remove completely outdates and useless ones (disconnect me etc.) maybe the concept should be updated in the product. Adding one single domain at a time in the Allow/Deny lists is time consuming and unmaintainable.

**Comment by PatrickHeneise** [comment]
Just saw the amount of threads on that particular topic on reddit, so there's no need for this here and I hope there's a fix to the UI soon.
