### ISSUE TITLE
 cliqz.com is labeled as porn site incorrectly #77 

### ISSUE THREAD

**Issue by tsekityam** [nextdns/metadata#98]
cliqz.com is not a porn site, however, it is listed in https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt incorrectly.

**Comment by romaincointepas** [comment]
Fixed with https://github.com/nextdns/metadata/commit/bcd759ac993f269acc7d1a03b1189cbee6122cb3
