### ISSUE TITLE
Anti Anti adblock?

### ISSUE THREAD

**Issue by CookerBower** [nextdns/metadata#982]
are there any filters for anti-adblock?
if not can one of these be added?

**Comment by CookerBower** [comment]
https://github.com/reek/anti-adblock-killer/

https://github.com/bogachenko/fuckfuckadblock

**Comment by crssi** [comment]
Those lists does not work on DNS level.
On DNS level you can block only by host part of URL and not by path or parameters or schema or web part.

**Comment by quantumpacket** [comment]
Those will not work for DNS. Those block specific elements via a browser addon.

**Comment by bogachenko** [comment]
@CookerBower DNS blocking is the last century, it should be used only where detailed blocking is not possible, for example, on Game/TV consoles. It is impossible to remove anti-adblock using DNS, you will always have false positives.

As mentioned above, get acquainted with the uBO extension or with the extension (but better with the program) Adguard, and use NextDNS on those systems where these 2 packages do not work.

**Comment by romaincointepas** [comment]
What @crssi said, closing.

**Comment by krystian3w** [comment]
https://github.com/nextdns/blocklists/issues/27
