### ISSUE TITLE
Add a new list

### ISSUE THREAD

**Issue by prajwal-koirala-0000** [nextdns/metadata#984]
Hello,
Can you please add this list on your platform, it's mostly ad blocking for iphone and Android. 

https://github.com/complexorganizations/content-blocker

**Comment by scafroglia93** [comment]
have you tried to hear the maintainer of oisd to evaluate the inclusion in his list ?

**Comment by prajwal-koirala-0000** [comment]
`oisd` list is too long and instead of blocking domains globally they block each sub-domain.
