### ISSUE TITLE
False positive: peekyou.com as Porn

### ISSUE THREAD

**Issue by Sduibek** [nextdns/metadata#986]
This is an aggregate people-searcher and data-broker-info site.

Regardless of how one personally feels about the data broker industry (I find it repugnant and indefensible), this is not a pornographic site to the best of my knowledge.

**Comment by lyrad87** [comment]
This is blocked upstream, see https://raw.githubusercontent.com/mhxion/pornaway/master/hosts/porn_sites.txt. I'd recommend reporting it there but the list doesn't seem actively maintained (the last update is from February 2021). It's probably easier if @romaincointepas adds it manually to the exclusion list.

**Comment by Sduibek** [comment]
Appreciate the info and insight!

**Comment by romaincointepas** [comment]
Fixed
