### ISSUE TITLE
Subdomains are being blocked via a hosts-format list

### ISSUE THREAD

**Issue by chr-lei** [nextdns/metadata#992]
The Lightswitch05 ads & tracking list is a hosts format list that includes the entry:
0.0.0.0 activity.windows.com
...along with entries for certain subdomains.

The list maintainer has excluded some domains that break applications from this domain list, including edge.activity.windows.com. However, when this list is enabled in NextDNS, it appears that all subdomains (even nonexistent ones, like _madeupname15213462.activity.windows.com_) are blocked as well. 

The net result is that this domain needs to be manually allowed in NextDNS despite having already been removed from the list by the maintainer. For hosts-format lists, it may make sense to not automatically block subdomains as it effectively undoes these exclusions that the maintainers have implemented.

**Comment by romaincointepas** [comment]
We may do this at some point, but those being very edge cases this is not a sure thing.
