### ISSUE TITLE
False Positive: unece.org classified as Porn

### ISSUE THREAD

**Issue by 3rdman** [nextdns/metadata#997]
I'm not sure the history behind this but the United Nations Economics Commission for Europe is classified as Porn

![Screen Shot 2022-06-04 at 12 22 50](https://user-images.githubusercontent.com/36356/172022666-d6455e66-3175-4d2f-b02b-71bcbc8da906.png)
.

**Comment by quantumpacket** [comment]
My guess is somewhere on this domain a web application or unsecured comment form was allowing spammers to post links to porn sites, which resulted in them being added to one of these porn lists?

Or our governments are up to more than their usual shady business. :laughing:

**Comment by 3rdman** [comment]
Ooo.. that’s what “economic development” means…

**Comment by romaincointepas** [comment]
Fixed
