### ISSUE TITLE
False positive: barbadostoday.bb is blocked

### ISSUE THREAD

**Issue by d-alleyne** [nextdns/metadata#998]
The barbadostoday.bb website, which is a popular news website, was working 12 hours ago and now it isn't. Enabling the block page shows the following message:

**barbadostoday.bb** is being blocked by **Threat Intelligence Feeds**.

**Comment by romaincointepas** [comment]
It's being blocked by https://github.com/mitchellkrogza/The-Big-List-of-Hacked-Malware-Web-Sites, could you report it to them?

**Comment by d-alleyne** [comment]
@romaincointepas This is happening again.
