### ISSUE TITLE
False Positive: transitapp.com

### ISSUE THREAD

**Issue by s-crypt** [nextdns/metadata#999]
`transitapp.com` (a public transit navigation app/service) is marked as a false positive under threat intelligence feeds at time of writing.
![image](https://user-images.githubusercontent.com/41712656/172256112-8ac08015-f302-432c-ab92-c5507d1d1b84.png)
[URLVoid](https://www.urlvoid.com/scan/transitapp.com/) Says that CRDF had flagged the domain as malware. A false positive request was submitted and the domain was removed from the database.

Does NextDNS use CRDF as part of threat intelligence feeds? I do not see any indication on the list.
If not, could `transitapp.com` be added as an exclusion as I do not know what list is causing the block.

Is there a way to query threat intelligence feeds to see what list is blocking a domain?

**Comment by s-crypt** [comment]
It looks as though the domain has been removed from threat intelligence feeds. 
I still have two questions:

Does NextDNS use CRDF as part of threat intelligence feeds?
Is there a way to query threat intelligence feeds to see what list is blocking a domain?

**Comment by romaincointepas** [comment]
We don't use CRDF (yet, we planned to reach out to them).

We greatly improved our sanitization (false positive removal) logic today for TI feeds, and we had a bug for a few minutes making this softer than before, letting this domain and a few others pass through.

For reference, this was in the phishtank URL list:
```
"2022-05-13 21:19:52","2.10","https://transitapp.com/redirect.html?url=https://jep356.codes%E2%81%A0and%E2%81%A0box%E2%81%A0.%E2%81%A0io/?dg=YWx0YS5oYW1vdWlAemdmLmNvbQ==","2606:4700::6812:b73"
```

URL lists are a better source for threats, but they are much harder to clean/deal with.
